### ISSUE TITLE
页面滚动显示bug

### ISSUE THREAD

**Issue by PearlEast** [ghosert/cmd-editor#10]
处于编辑状态时，我往下滚动页面，到达一定深度后，网页上方的菜单工具栏消失了；
这时，我缓慢由底部往上滚动页面，工具栏依然不出现，直到文章标题能显示时，工具栏才出现。
![image](https://f.cloud.github.com/assets/5668955/1408216/09b35444-3d7e-11e3-89bb-b5906ba2c1fb.png)

![image](https://f.cloud.github.com/assets/5668955/1408220/0e4984c4-3d7e-11e3-9ffd-77e2f103f6d9.png)

**Comment by PearlEast** [comment]
第一个截图是消失了的工具栏，第二个是正常显示状态下的工具栏，请检查下，谢谢大牛。

**Comment by ghosert** [comment]
浏览器版本，操作系统版本提供一下，另外如果可以，把 Markdown 内容贴给我邮箱？ support@zybuluo.com

**Comment by PearlEast** [comment]
Chrome, Win7 32Bit.

**Comment by ghosert** [comment]
你发布一下吧，否则我看不到

**Comment by PearlEast** [comment]
done
于 10/25/2013 7:13 AM, Jay Zhang 写道:

**Comment by ghosert** [comment]
你的chrome啥版本，我下了最新的 30.0 没问题噢。。。

**Comment by PearlEast** [comment]
Version 30.0.1599.69 m

**Comment by PearlEast** [comment]
那我回头再看看，谢谢。

**Comment by ghosert** [comment]
要是有空的时候，可以换台机器，或者换个浏览器试试，有没有类似的问题，IE9+ FireFox ，有消息再报过来。

**Comment by ghosert** [comment]
还有不妨多公开文章噢

**Comment by PearlEast** [comment]
恩，有的不成熟，不好意思拿出来:)

于 10/25/2013 7:51 AM, Jay Zhang 写道:

**Comment by PearlEast** [comment]
Firefox确实没问题，Linux下我估计问题也不大，我再多试试看。

**Comment by ghosert** [comment]
暂时先关一下，如果有人能重现，给出步骤和必要信息再重开。
