### ISSUE TITLE
【导出到印象笔记】同步到印象笔记的代码格式拷贝时会连行号一起拷贝，拷贝时缩进也不能保留

### ISSUE THREAD

**Issue by nibocn** [ghosert/cmd-editor#1001]
![image](https://cloud.githubusercontent.com/assets/10879287/11705218/45c66ae8-9f29-11e5-9a17-868bf45394b3.png)

拷贝后的代码效果：

![image](https://cloud.githubusercontent.com/assets/10879287/11705230/5e172538-9f29-11e5-9f54-8ad7c4a44d69.png)

**Comment by ghosert** [comment]
这个用火狐浏览器好像就好了，而且是浏览器的行为，并不属于这里的问题。

**Comment by nibocn** [comment]
嗯，浏览器我在chrome里面也试了下是可以的，只是印象笔记的客户端复制时就有这种现象。
