### ISSUE TITLE
【导出到印象笔记】在印象笔记中查看内容时注脚不能跳转

### ISSUE THREAD

**Issue by nibocn** [ghosert/cmd-editor#1002]

**Comment by dongbingliu** [comment]
目录也不能跳转

**Comment by dongbingliu** [comment]
@ghosert 导出印象笔记，[TOC]目录也不能跳转

移动CmdMarkDown导出到印象笔记文章，到其他目录，在新目录中就不能编辑与保存了！！！

**Comment by nibocn** [comment]
内容是不能编辑的，可以添加标签。我记得马克飞象也是这样的，其实也好理解，这种通过第三方app同步生成的html页面在印象里面直接编辑效果体验也不佳吧

**Comment by ghosert** [comment]
@JerrryLiu 之前印象笔记给的权限不够，为了移动到其它笔记本也可以操作，你可以这样操作：

先前往 https://app.yinxiang.com/AuthorizedServices.action 把印象笔记对 Cmd Markdown 的授权撤销，然后回到 Cmd Markdown 重新导出到印象笔记，这个时候会重新让你授权 Cmd Markdown 访问 印象笔记，此后就不再有此限制了。

**Comment by dongbingliu** [comment]
@ghosert 按照你的方法，解决了移动文章后不能在移动后目录编辑导出。非常感谢！！！

因需要使用代码高亮，支持MarkDown语言，以前使用的是为知笔记
因之前购买了CmdMarkDown会员，现在其支持导出到印象笔记，果断购买了一年的印象笔记高级会员。

[TOC]目录与标签不能跳转的问题什么时候能修复？

**Comment by ghosert** [comment]
这个会修的，时间暂时不好说，一两礼拜吧。

**Comment by dongbingliu** [comment]
@ghosert 期待更新

**Comment by ghosert** [comment]
查阅了印象笔记的文档，页内的链接跳转是他们那边不支持，所以做不到了。

**Comment by dongbingliu** [comment]
@ghosert 刚使用马克飞象测试，保存到印象笔记中的[TOC]目录支持页内跳转，意味着印象笔记可以支持，技术上是可以行的通。

**Comment by ghosert** [comment]
好的，我再 reopen 出来，看看。那应该可以做得到。

**Comment by ghosert** [comment]
@JerrryLiu 你说的可以跳转是不是说在分享了印象笔记以后的页面上可以跳转？而不是说在未分享的三栏模式下可以分享？

我看到能跳转的就是这个页面：

https://app.yinxiang.com/shard/s4/nl/13540550/ee35cf0b-7ee5-43c8-9020-79c10cefc0b2

而且点上去以后会再开一个页面然后完成跳转？你是要这个效果吗？

**Comment by nibocn** [comment]
@JerrryLiu @ghosert  我试了下用马克飞象同步了一篇他官方的说明文档，用windows客户端的印象笔记点击注脚是可以跳转的，但网页版浏览时点击注脚也会跳转到其它页面。
PC客户端效果：
![image](https://cloud.githubusercontent.com/assets/10879287/12091370/93264c2e-b331-11e5-96cc-f3de612a4020.png)

网页浏览：
跳转的URL明显不对，目录
![image](https://cloud.githubusercontent.com/assets/10879287/12091452/3678e21a-b332-11e5-9b33-3596b71cf667.png)

注脚：
![image](https://cloud.githubusercontent.com/assets/10879287/12091474/582a4a5c-b332-11e5-9cf8-49079807dbb7.png)

不过PC端确实可以很奇葩，我用的浏览器是chrome 47.0.2526.106 m (64-bit)，另 @JerrryLiu 说的[TOC]目录指的应该是，马克飞象的一个标记
![image](https://cloud.githubusercontent.com/assets/10879287/12091702/8f6c46a4-b333-11e5-9de4-56e09c5a5979.png)

类似cmd-editor的
![image](https://cloud.githubusercontent.com/assets/10879287/12091720/a0f48170-b333-11e5-84f4-a251ce474da7.png)

**Comment by ghosert** [comment]
@niboxy 感谢翔实的分析，那我也按此实现即可。保证注脚和TOC可在印象笔记客户端和已分享笔记的网页端印象笔记中跳转。

**Comment by nibocn** [comment]
:+1:

**Comment by dongbingliu** [comment]
@niboxy 写的很详细，cmd作者看了一目了然；
@ghosert  [TOC]自动生成的目录可以在印象笔记客户端文章内实现跳转功能；

**Comment by ghosert** [comment]
这个在测试环境已经修好了。今明两天就发出来。

**Comment by nibocn** [comment]
:+1:

**Comment by ghosert** [comment]
修好了，这个关了。

**Comment by dongbingliu** [comment]
@ghosert 刚测试了ok，非常感谢！！！
@niboxy
