### ISSUE TITLE
导出到印象笔记时不能选择导出的笔记本吗？

### ISSUE THREAD

**Issue by NSFish** [ghosert/cmd-editor#1008]
您好，我在使用样稿的时候，在web端是可以选择导出到指定笔记本的。
付费之后使用Mac客户端时，绑定印象笔记账号的时候却只能绑定一个笔记本。

**Comment by ghosert** [comment]
印象笔记那边给我们的权限不够，已经发信和他们沟通了。 发自网易邮箱大师 在2015年12月11日 00:41 ，乐星宇写道： 您好，我在使用样稿的时候，在web端是可以选择导出到指定笔记本的。 付费之后使用Mac客户端时，绑定印象笔记账号的时候却只能绑定一个笔记本。 — Reply to this email directly or view it on GitHub.

**Comment by NSFish** [comment]
那为什么样稿是可以选择导出的笔记本的呢？是因为evernote的接口权限与印象笔记的不同吗？
![2015-12-11 4 05 50](https://cloud.githubusercontent.com/assets/3808102/11738859/66339a64-a021-11e5-86dd-e4f33485985a.png)

**Comment by ghosert** [comment]
样稿是已经生成共享的文稿，这篇文稿的作者应该是我，不太明白为什么你可以操作我的文稿，进行选择笔记本的操作。至于绑定印象笔记时只能选单个笔记本确实是他们的权限没给够，正在沟通。 发自网易邮箱大师 在2015年12月11日 16:08 ，乐星宇写道： 那为什么样稿是可以选择导出的笔记本的呢？是因为evernote的接口权限与印象笔记的不同吗？ — Reply to this email directly or view it on GitHub.

**Comment by ghosert** [comment]
已解决，对方已给了足够的权限，请先前往这里把印象笔记对 Cmd Markdown 的授权撤销，然后回到 Cmd Markdown 重新导出到印象笔记，这个时候会重新让你授权 Cmd Markdown 访问 印象笔记，此后就不再有此限制了。

**Comment by NSFish** [comment]
重新授权之后，授权页面上的确可以看到权限是满足的
![2015-12-17 10 14 18](https://cloud.githubusercontent.com/assets/3808102/11859675/1ce87a7e-a4a8-11e5-997d-f78c5dd942df.png)
但是在执行导出笔记的时候，没有选择笔记本这一步骤：
![2015-12-17 10 13 31](https://cloud.githubusercontent.com/assets/3808102/11859669/12fdcb04-a4a8-11e5-8144-002849270892.png)
![2015-12-17 10 13 39](https://cloud.githubusercontent.com/assets/3808102/11859670/188a377e-a4a8-11e5-9c18-a1d9c7727dc6.png)

**Comment by ghosert** [comment]
笔记本和标签的更改在印象笔记那边做吧。
