### ISSUE TITLE
登录又提示未验证邮箱

### ISSUE THREAD

**Issue by baoxiehao** [ghosert/cmd-editor#1009]
去年用qq邮箱注册，没有收到验证邮件；刚才用gmail重新注册了，收到验证邮件了，点击验证链接后登录的时候又提示邮箱未验证，一年多了，还是没法用啊。。。

备注：我的邮箱是baoxiehao@gmail.com

**Comment by ghosert** [comment]
不用来点链接的那个浏览器，先用你的用户名登录一下，然后再去点这个链接。 发自网易邮箱大师 在2015年12月11日 10:36 ，baoxiehao写道： 去年用qq邮箱注册，没有收到验证邮件；刚才用gmail重新注册了，收到验证邮件了，点击验证链接后登录的时候又提示邮箱未验证，一年多了，还是没法用啊。。。 — Reply to this email directly or view it on GitHub.
