### ISSUE TITLE
增加过多图片后，左右栏不对应的问题

### ISSUE THREAD

**Issue by BrambleXu** [ghosert/cmd-editor#1013]
文件里添加的图片比较多，在左栏文档的最后全是图片链接，右栏对应的是最后的文本。而我想标记左栏的文本时，右栏对应的位置并不是左栏目前编辑的位置。

![screenshot from 2015-12-12 13 57 05](https://cloud.githubusercontent.com/assets/10768193/11760260/4209c4c6-a0d8-11e5-8144-31b30aeb5479.png)

**Comment by ghosert** [comment]
图片的高度比链接高很多，没有其它办法对齐，算法上已经最大程度对齐了。 发自网易邮箱大师 在2015年12月12日 12:57 ，Bramble写道： 文件里添加的图片比较多，在左栏文档的最后全是图片链接，右栏对应的是最后的文本。而我想标记左栏的文本时，右栏对应的位置并不是左栏目前编辑的位置。 — Reply to this email directly or view it on GitHub.

**Comment by simonkuang** [comment]
这个问题在加了 `[TOC]` 并且目录比较长的时候也会出现。特别是编辑 `[TOC]` 下方的文字时，经常看不到预览效果，只能先盲打，然后一起看。

这事儿的确是个难题。

**Comment by ghosert** [comment]
暂时先关了。。。

**Comment by BrambleXu** [comment]
嗯，好的
