### ISSUE TITLE
自从作业部落发布第十三次更新后输入变的卡顿了

### ISSUE THREAD

**Issue by boathit** [ghosert/cmd-editor#1015]
使用的系统是 OS X 10.11.2 浏览器 safari 编辑， 之前的输入体验非常好，自从第十三次更新发布后，现在每输入若干个字符之后都会卡顿一下（反复测试了几次，主要是输入空格时会卡），删除字符也是，每删除若干个字符都会卡顿一下，体验超差：（

**Comment by boathit** [comment]
不过在 chrome 浏览器中好像没这个问题，现在也分不清到底是 safari 的问题，还是作业部落更新的问题

**Comment by ghosert** [comment]
作业部落本次的更新没有涉及编辑器部分，不会引起这个问题，优先推荐谷歌浏览器。OS X 10.10.5 safari 9.0.1 没有这个问题。我看看能不能更新一下 OS X 10.11.2，然后再试一下。

**Comment by boathit** [comment]
@ghosert  反复测试了几遍 chrome firefox 都正常，只有 Safari 有这个问题，而且在 Safari 中使用系统自带中文输入法时 emacs 模式有些快捷键也不正常，不过以前没有这些问题，所以这个应该是系统升级了 Safari 造成的。

**Comment by ghosert** [comment]
我把自己的系统更新到 10.11.2 并没有这个问题，暂时先关了。
