### ISSUE TITLE
使用html设置颜色和字体无效

### ISSUE THREAD

**Issue by moverzp** [ghosert/cmd-editor#1016]
比如
<font color=red>sad</font>
颜色并木有改变，在别的支持markdown语法的编辑器里面有效。

**Comment by ghosert** [comment]
是设置了白名单不是所有  HTML 标签都支持属性，譬如你这个 SAD 是标签？还是属性？常见的标签和属性是支持的。

**Comment by moverzp** [comment]
抱歉，显示的有问题。我想设置的是文字的颜色，使用font color设置，我把尖括号写成圆括号贴出来吧：（font color=red）sad（/font）。在cmd中是黑色的sad，在某款软件中显示的是红色的sad。

**Comment by ghosert** [comment]
FONT 是一种 HTML 不推荐使用的标签，我们这边是支持使用标准的内嵌属性，因此你的需求可以改写成： 

```
<span style="color:red;">sad</span>
```

**Comment by moverzp** [comment]
好的，十分感谢~

**Comment by LittleWhite-Hai** [comment]
感谢！
