### ISSUE TITLE
导出印象笔记失败

### ISSUE THREAD

**Issue by Jack2code** [ghosert/cmd-editor#1018]
> 导出当前文稿出错，请重试或联系我们，错误详情：Element or attribute do not match QName production: QName::=(NCName':')?NCName.

导出文章到印象笔记时发生如上错误，在离线版和网页版都是一样的错误。还没成功导出过。

印象笔记 和 evernote 均无法导出。

PS： evernote可以选择导出到哪个笔记本或新建笔记本，但印象笔记不行。

**Comment by williamtang** [comment]
遇到同样的问题！

**Comment by ghosert** [comment]
我和印象笔记沟通一下，我看下来都是间歇性的错误，过一会就好了，感觉不像是这边的问题。

**Comment by wafer-li** [comment]
@ghosert  我这边客户端不行，但是 chrome 可以。并不知道这是为什么。

**Comment by ghosert** [comment]
把文稿背景调成白色然后刷新下页面或者重启下客户端就好了。这个问题在修了。 发自网易邮箱大师 在2015年12月29日 15:31 ，Donglin Li写道： @ghosert 我这边客户端不行，但是 chrome 可以。并不知道这是为什么。 — Reply to this email directly or view it on GitHub.

**Comment by wafer-li** [comment]
Update

有可能是某些文档本身的问题，我尝试着发一份给你看看？

---

@ghosert 
之前几分钟可以，但是现在改成白色之后开始报另外一个错误了。
`Element type "nobr" must be declared.`

目前网页和客户端都出现了这一问题。

**Comment by ghosert** [comment]
你是不是写了自定义的标签？印象笔记不是所有自定义标签都支持。 发自网易邮箱大师 在2015年12月29日 15:57 ，Donglin Li写道： @ghosert 之前几分钟可以，但是现在改成白色之后开始报另外一个错误了。 Element type "nobr" must be declared. 目前网页和客户端都出现了这一问题。 — Reply to this email directly or view it on GitHub.

**Comment by wafer-li** [comment]
如果 “自定义标签” 指的是 HTML 标签，我刚才发过去的那个文档并没有使用 HTML 标签。

我觉得比较可能的应该是我用了一些比较复杂的数学公式。

除此之外好像并没有一些什么有毒的东西……？

在 2015年12月29日 下午5:31，Jay Zhang notifications@github.com写道：

**Comment by ghosert** [comment]
markdown原文发来。 发自网易邮箱大师 在2015年12月29日 16:42 ，Donglin Li写道： 如果 “自定义标签” 指的是 HTML 标签，我刚才发过去的那个文档并没有使用 HTML 标签。 我觉得比较可能的应该是我用了一些比较复杂的数学公式。 除此之外好像并没有一些什么有毒的东西……？ 在 2015年12月29日 下午5:31，Jay Zhang notifications@github.com写道： > 你是不是写了自定义的标签？印象笔记不是所有自定义标签都支持。 发自网易邮箱大师 在2015年12月29日 15:57 ，Donglin Li写道： > @ghosert 之前几分钟可以，但是现在改成白色之后开始报另外一个错误了。 Element type "nobr" must be > declared. 目前网页和客户端都出现了这一问题。 — Reply to this email directly or view it on > GitHub. > > — > Reply to this email directly or view it on GitHub > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167744563 > . > — Reply to this email directly or view it on GitHub.

**Comment by wafer-li** [comment]
已经发到 ghosert@gmail.com 了

如果没有收到，请指示另一个邮箱。

在 2015年12月29日 下午5:47，Jay Zhang notifications@github.com写道：

**Comment by ghosert** [comment]
是算法的那个附件吗？你两边名字对不上。 发自网易邮箱大师 在2015年12月29日 16:49 ，Donglin Li写道： 已经发到 ghosert@gmail.com 了 如果没有收到，请指示另一个邮箱。 在 2015年12月29日 下午5:47，Jay Zhang notifications@github.com写道： > markdown原文发来。 发自网易邮箱大师 在2015年12月29日 16:42 ，Donglin Li写道： 如果 “自定义标签” 指的是 > HTML 标签，我刚才发过去的那个文档并没有使用 HTML 标签。 我觉得比较可能的应该是我用了一些比较复杂的数学公式。 > 除此之外好像并没有一些什么有毒的东西……？ 在 2015年12月29日 下午5:31，Jay Zhang < > notifications@github.com>写道： > 你是不是写了自定义的标签？印象笔记不是所有自定义标签都支持。 发自网易邮箱大师 > 在2015年12月29日 15:57 ，Donglin Li写道： > @ghosert 之前几分钟可以，但是现在改成白色之后开始报另外一个错误了。 > Element type "nobr" must be > declared. 目前网页和客户端都出现了这一问题。 — Reply to this > email directly or view it on > GitHub. > > — > Reply to this email directly > or view it on GitHub > < > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167744563> > > . > — Reply to this email directly or view it on GitHub. > > — > Reply to this email directly or view it on GitHub > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167748818 > . > — Reply to this email directly or view it on GitHub.

**Comment by wafer-li** [comment]
是的😅

在 2015年12月29日 下午5:51，Jay Zhang notifications@github.com写道：

**Comment by ghosert** [comment]
可是我这边完美导出了啊，是不是在白色主题下重启客户端或者浏览器，然后再试下？我在 chrome 浏览器里试出來的。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2015年12月29日 下午4:53，Donglin Li notifications@github.com写道：

**Comment by wafer-li** [comment]
😰

我发现我导出的是 Evernote International

Chrome  版本是 47.0.2526.106 m

估计是国际版有毒性了。
​

在 2015年12月29日 下午5:55，Jay Zhang notifications@github.com写道：

**Comment by ghosert** [comment]
Evernote 我这边一样完美导出了。不过我用的 chrome 是 44，不过感觉和浏览器版本关系不大，客户端行吗？
https://www.zybuluo.com/cmd

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2015年12月29日 下午5:02，Donglin Li notifications@github.com写道：

**Comment by ghosert** [comment]
记得一定要在白色背景下重启客户端或者浏览器，然后别切黑色背景。否则导出会失败，在修。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2015年12月29日 下午5:05，Zhang Jiawei ghosert@gmail.com写道：

**Comment by wafer-li** [comment]
客户端刚下的。并不行，同样的错误。

Windows 10 Pro x64

可能是我刚装过马克飞象，然后它写了点注册表进去。有无可能是这个的原因？

在 2015年12月29日 下午6:06，Jay Zhang notifications@github.com写道：

**Comment by ghosert** [comment]
你新建一篇简单的文稿，看看是不是可以，如果可以说明导出功能本身没问题，然后把你的文稿一段一段删直到能够成功导出说明上次删掉的内容里有问题，再找到底是哪里的问题。 发自网易邮箱大师 在2015年12月29日 17:14 ，Donglin Li写道： 客户端刚下的。并不行，同样的错误。 Windows 10 Pro x64 可能是我刚装过马克飞象，然后它写了点注册表进去。有无可能是这个的原因？ 在 2015年12月29日 下午6:06，Jay Zhang notifications@github.com写道： > 记得一定要在白色背景下重启客户端或者浏览器，然后别切黑色背景。否则导出会失败，在修。 > > > > > > > > > > > _键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com > http://www.zybuluo.com个人博客：http://ghosertblog.github.com > http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert > http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert > http://book.douban.com/people/ghosert/_ > > 在 2015年12月29日 下午5:05，Zhang Jiawei ghosert@gmail.com写道： > > > Evernote 我这边一样完美导出了。不过我用的 chrome 是 44，不过感觉和浏览器版本关系不大，客户端行吗？ > > https://www.zybuluo.com/cmd > > > > > > > > > > > > > > > > > > > > > > _键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com > > http://www.zybuluo.com个人博客：http://ghosertblog.github.com > > http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert > > http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert > > http://book.douban.com/people/ghosert/_ > > > > 在 2015年12月29日 下午5:02，Donglin Li notifications@github.com写道： > > > >> 😰 > >> > >> 我发现我导出的是 Evernote International > >> > >> Chrome 版本是 47.0.2526.106 m > >> > >> 估计是国际版有毒性了。 > >> ​ > >> > >> 在 2015年12月29日 下午5:55，Jay Zhang notifications@github.com写道： > >> > >> > 可是我这边完美导出了啊，是不是在白色主题下重启客户端或者浏览器，然后再试下？我在 chrome 浏览器里试出來的。 > >> > > >> > > >> > > >> > > >> > > >> > > >> > > >> > > >> > > >> > > >> > _键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com > >> > http://www.zybuluo.com个人博客：http://ghosertblog.github.com > >> > http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert > >> > http://www.weibo.com/ghosert豆瓣社区： > >> http://book.douban.com/people/ghosert > >> > http://book.douban.com/people/ghosert/_ > >> > > >> > 在 2015年12月29日 下午4:53，Donglin Li notifications@github.com写道： > >> > > >> > > 是的😅 > >> > > > >> > > 在 2015年12月29日 下午5:51，Jay Zhang notifications@github.com写道： > >> > > > >> > > > 是算法的那个附件吗？你两边名字对不上。 发自网易邮箱大师 在2015年12月29日 16:49 ，Donglin Li写道： > 已经发到 > >> > > > ghosert@gmail.com 了 如果没有收到，请指示另一个邮箱。 在 2015年12月29日 下午5:47，Jay > >> Zhang < > >> > > > notifications@github.com>写道： > markdown原文发来。 发自网易邮箱大师 > 在2015年12月29日 > >> > > 16:42 > >> > > > ，Donglin Li写道： 如果 “自定义标签” 指的是 > HTML 标签，我刚才发过去的那个文档并没有使用 HTML 标签。 > >> > > > 我觉得比较可能的应该是我用了一些比较复杂的数学公式。 > 除此之外好像并没有一些什么有毒的东西……？ 在 2015年12月29日 > >> > > 下午5:31，Jay > >> > > > Zhang < > notifications@github.com>写道： > > >> > 你是不是写了自定义的标签？印象笔记不是所有自定义标签都支持。 > >> > > > 发自网易邮箱大师 > 在2015年12月29日 15:57 ，Donglin Li写道： > @ghosert > >> > > > 之前几分钟可以，但是现在改成白色之后开始报另外一个错误了。 > Element type "nobr" must be > > >> > declared. > >> > > > 目前网页和客户端都出现了这一问题。 — Reply to this > email directly or view it on > > > >> > > GitHub. > >> > > > > > — > Reply to this email directly > or view it on GitHub > < > > >> > > > > >> > > >> > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167744563> > >> > >> > > > >> > > > > > . > — Reply to this email directly or view it on GitHub. > > > — > >> > > >> > > Reply > >> > > > to this email directly or view it on GitHub > < > >> > > > > >> > > >> > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167748818> > >> > >> > > > >> > > > > . > — Reply to this email directly or view it on GitHub. > >> > > > > >> > > > — > >> > > > Reply to this email directly or view it on GitHub > >> > > > < > >> > > > >> > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167749890> > >> > >> > > >> > > > . > >> > > > > >> > > > >> > > — > >> > > Reply to this email directly or view it on GitHub > >> > > < > >> > > >> > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167750002> > >> > >> > > . > >> > > > >> > > >> > — > >> > Reply to this email directly or view it on GitHub > >> > < > >> > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167750225> > >> > >> > . > >> > > >> > >> — > >> Reply to this email directly or view it on GitHub > >> < > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167751428> > >> . > >> > > > > > > — > Reply to this email directly or view it on GitHub > https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167752816 > . > — Reply to this email directly or view it on GitHub.

**Comment by wafer-li** [comment]
好的，我先鼓捣鼓捣。

在 2015年12月29日 下午6:31，Jay Zhang notifications@github.com写道：

**Comment by wafer-li** [comment]
大概找到问题了。

我客户端和网页均采用 HTML-CSS 形式来 Render MathJax, 估计是这个的问题，我换成 SVG  来 Render 就没问题了。

建议以后在转换的时候直接忽略用户的个人设定，直接强制全部用 SVG 来 Render。

在 2015年12月29日 下午6:33，omysho mulakami omyshokami@gmail.com写道：

**Comment by wafer-li** [comment]
补充一下：应该是导出到印象笔记的时候全部强制使用 SVG Render。

当时就是觉得预览窗口 SVG 比较糊，没有 HTML-CSS 好看，才改成 HTML-CSS render 的。

当然如果有另一个更好的办法能解决这个问题也再好不过了。

在 2015年12月29日 下午6:42，omysho mulakami omyshokami@gmail.com写道：

**Comment by ghosert** [comment]
印象笔记既不支持svg也不支持htmlcss的公式渲染。但是svg可以被转换为图像然后嵌到印象笔记，所以当时把html css 改成了svg。 发自网易邮箱大师 在2015年12月29日 17:45 ，Donglin Li写道： 补充一下：应该是导出到印象笔记的时候全部强制使用 SVG Render。 当时就是觉得预览窗口 SVG 比较糊，没有 HTML-CSS 好看，才改成 HTML-CSS render 的。 当然如果有另一个更好的办法能解决这个问题也再好不过了。 在 2015年12月29日 下午6:42，omysho mulakami omyshokami@gmail.com写道： > 大概找到问题了。 > > 我客户端和网页均采用 HTML-CSS 形式来 Render MathJax, 估计是这个的问题，我换成 SVG 来 Render 就没问题了。 > > 建议以后在转换的时候直接忽略用户的个人设定，直接强制全部用 SVG 来 Render。 > > 在 2015年12月29日 下午6:33，omysho mulakami omyshokami@gmail.com写道： > >> 好的，我先鼓捣鼓捣。 >> >> 在 2015年12月29日 下午6:31，Jay Zhang notifications@github.com写道： >> >>> 你新建一篇简单的文稿，看看是不是可以，如果可以说明导出功能本身没问题，然后把你的文稿一段一段删直到能够成功导出说明上次删掉的内容里有问题，再找到底是哪里的问题。 >>> 发自网易邮箱大师 在2015年12月29日 17:14 ，Donglin Li写道： 客户端刚下的。并不行，同样的错误。 Windows 10 Pro >>> x64 可能是我刚装过马克飞象，然后它写了点注册表进去。有无可能是这个的原因？ 在 2015年12月29日 下午6:06，Jay Zhang < >>> notifications@github.com>写道： > >>> 记得一定要在白色背景下重启客户端或者浏览器，然后别切黑色背景。否则导出会失败，在修。 > > > > > > > > > > > >>> _键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com > <http://www.zybuluo.com >>> >个人博客：http://ghosertblog.github.com > <http://ghosertblog.github.com >>> >新浪微博：http://www.weibo.com/ghosert > http://www.weibo.com/ghosert豆瓣社区： >>> http://book.douban.com/people/ghosert > < >>> http://book.douban.com/people/ghosert/>_ > > 在 2015年12月29日 下午5:05，Zhang >>> Jiawei ghosert@gmail.com写道： > > > Evernote 我这边一样完美导出了。不过我用的 chrome 是 >>> 44，不过感觉和浏览器版本关系不大，客户端行吗？ > > https://www.zybuluo.com/cmd > > > > > > > >>> > > > > > > > > > > > > > > > _键盘狂热爱好者神经衰弱，强迫症患者作业部落： >>> http://www.zybuluo.com > > http://www.zybuluo.com个人博客： >>> http://ghosertblog.github.com > > http://ghosertblog.github.com新浪微博： >>> http://www.weibo.com/ghosert > > http://www.weibo.com/ghosert豆瓣社区： >>> http://book.douban.com/people/ghosert > > < >>> http://book.douban.com/people/ghosert/>_ > > > > 在 2015年12月29日 >>> 下午5:02，Donglin Li notifications@github.com写道： > > > >> 😰 > >> > >> >>> 我发现我导出的是 Evernote International > >> > >> Chrome 版本是 47.0.2526.106 m > >> > >>> >> 估计是国际版有毒性了。 > >> ​ > >> > >> 在 2015年12月29日 下午5:55，Jay Zhang < >>> notifications@github.com>写道： > >> > >> > >>> 可是我这边完美导出了啊，是不是在白色主题下重启客户端或者浏览器，然后再试下？我在 chrome 浏览器里试出來的。 > >> > > >> > > >>> >> > > >> > > >> > > >> > > >> > > >> > > >> > > >> > > >> > >>> _键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com > >> > < >>> http://www.zybuluo.com>个人博客：http://ghosertblog.github.com > >> > < >>> http://ghosertblog.github.com>新浪微博：http://www.weibo.com/ghosert > >> > < >>> http://www.weibo.com/ghosert>豆瓣社区： > >> >>> http://book.douban.com/people/ghosert > >> > < >>> http://book.douban.com/people/ghosert/>_ > >> > > >> > 在 2015年12月29日 >>> 下午4:53，Donglin Li notifications@github.com写道： > >> > > >> > > 是的😅 > >>> >> > > > >> > > 在 2015年12月29日 下午5:51，Jay Zhang notifications@github.com写道： >>> > >> > > > >> > > > 是算法的那个附件吗？你两边名字对不上。 发自网易邮箱大师 在2015年12月29日 16:49 >>> ，Donglin Li写道： > 已经发到 > >> > > > ghosert@gmail.com 了 如果没有收到，请指示另一个邮箱。 在 >>> 2015年12月29日 下午5:47，Jay > >> Zhang < > >> > > > notifications@github.com>写道： >>> > markdown原文发来。 发自网易邮箱大师 > 在2015年12月29日 > >> > > 16:42 > >> > > > ，Donglin >>> Li写道： 如果 “自定义标签” 指的是 > HTML 标签，我刚才发过去的那个文档并没有使用 HTML 标签。 > >> > > > >>> 我觉得比较可能的应该是我用了一些比较复杂的数学公式。 > 除此之外好像并没有一些什么有毒的东西……？ 在 2015年12月29日 > >> > > >>> 下午5:31，Jay > >> > > > Zhang < > notifications@github.com>写道： > > >> > >>> 你是不是写了自定义的标签？印象笔记不是所有自定义标签都支持。 > >> > > > 发自网易邮箱大师 > 在2015年12月29日 15:57 >>> ，Donglin Li写道： > @ghosert > >> > > > 之前几分钟可以，但是现在改成白色之后开始报另外一个错误了。 > >>> Element type "nobr" must be > > >> > declared. > >> > > > 目前网页和客户端都出现了这一问题。 >>> — Reply to this > email directly or view it on > > > >> > > GitHub. > >> > >>> > > > > — > Reply to this email directly > or view it on GitHub > < > > >> >>> > > > > >> > > >> > >>> https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167744563> >>> > >> > >> > > > >> > > > > > . > — Reply to this email directly or view it >>> on GitHub. > > > — > >> > > >> > > Reply > >> > > > to this email directly >>> or view it on GitHub > < > >> > > > > >> > > >> > >>> https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167748818> >>> > >> > >> > > > >> > > > > . > — Reply to this email directly or view it on >>> GitHub. > >> > > > > >> > > > — > >> > > > Reply to this email directly or >>> view it on GitHub > >> > > > < > >> > > > >> > >>> https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167749890> >>> > >> > >> > > >> > > > . > >> > > > > >> > > > >> > > — > >> > > Reply to >>> this email directly or view it on GitHub > >> > > < > >> > > >> > >>> https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167750002> >>> > >> > >> > > . > >> > > > >> > > >> > — > >> > Reply to this email >>> directly or view it on GitHub > >> > < > >> > >>> https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167750225> >>> > >> > >> > . > >> > > >> > >> — > >> Reply to this email directly or view >>> it on GitHub > >> < > >>> https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167751428> >>> > >> . > >> > > > > > > — > Reply to this email directly or view it on >>> GitHub > < >>> https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167752816> >>> > . > — Reply to this email directly or view it on GitHub. >>> >>> — >>> Reply to this email directly or view it on GitHub >>> https://github.com/ghosert/cmd-editor/issues/1018#issuecomment-167755840 >>> . >>> >> >> > — Reply to this email directly or view it on GitHub.

**Comment by wafer-li** [comment]
大概明白了，不过还是希望在导出到印象笔记的时候能在后台转换成使用 SVG 渲染之后再导出。

毕竟…… 那个 SVG 真的，很糊。。。。

不过如果对服务器负担大的话，我自己动手临时改一改也没什么问题。

在 2015年12月29日 下午6:58，Jay Zhang notifications@github.com写道：
