### ISSUE TITLE
mac客户端经常莫名其妙进入离线模式

### ISSUE THREAD

**Issue by zhengbuqian** [ghosert/cmd-editor#1022]
电脑明明可以上网的，但是却显示离线模式，也不能发布更新什么的
11年中的macbook air，系统是el capitan

**Comment by ghosert** [comment]
人在哪里？网络稳定吗？一般显示这个是由于连接网站的网络不稳定，别有代理，注意办公室或者学校里是否有防火墙。

**Comment by JackieMium** [comment]
@ghosert 我的Linux 64位出现同样问题，用的是最新版客户端。点击“立即同步”右下角后出现：

> 离线状态下无法同步数据，但可以离线编辑，请连接网络后重试。

环境：`Gentoo x86_64  with Kernel 4.1.12-gentoo
