### ISSUE TITLE
[Bug] 在firefox浏览器直接卡死

### ISSUE THREAD

**Issue by goreliu** [ghosert/cmd-editor#1027]
在firefox里打开示例页面直接卡死，登陆后编辑文档也非常缓慢，无法正常使用。

环境：win 10，firefox 42.0/43.0。

**Comment by ghosert** [comment]
先试试 CHROME 或者客户端，和操作环境，内存，硬盘都有关系。CHROME客户端性能最好。

**Comment by goreliu** [comment]
抱歉，我不会因为一个cmd-editor更换默认浏览器。而且如此严重的bug直接无视让人非常意外。

**Comment by ghosert** [comment]
和个人的软硬情况确实有很大关系，并非说一定要换浏览器，而是说可以先看下CHROME里是否有类似的状况以便确定首先是浏览器的问题，如果CHROME是没有问题的话。否则再继续考察是否是硬件配置，操作系统的问题。如果觉得还是有问题，可以再次 REOPEN。

**Comment by goreliu** [comment]
用Edge和IE11打开没有任何问题。Firefox打开一个文档稍微滚动一些立即整个浏览器卡死，标题栏显示“未响应”，无法立即关闭，带着系统一起卡，看任务管理器CPU、内存、硬盘占用都正常。使用空的profile也是一样，版本从42.0到43.0.4一直这样。如果设置成启动后打开上次关闭的页面，那么重新打开后没来得及关闭页面就立即卡死，刚才为了再验证一次卡得死去活来的，反复关了打开多次才缓过来。
