### ISSUE TITLE
Vim模式下能增加中文分词的支持么？

### ISSUE THREAD

**Issue by spacewander** [ghosert/cmd-editor#103]
虽然平常编程都是用Vim，但是在写文章的时候都不会用Vim，原因是Vim里面的“word”在中文里变成了一个分句，结果导致操作起来比较折磨人……
所以我想问一下，之后能不能添加中文分词的支持呢？比如在这一句的句头使用`w`的时候，会跳到`在`这个字，而不是`会`。这样就可以开心地使用Vim模式了。

**Comment by ghosert** [comment]
其实在本尊 gvim 里也是现在这样处理的暂时目测只能通过 ^ $ 到行首行末，hjkl 前后左右移动，或者 5 h 10 l 这样妥协一下。习惯以后还好，至少比普通模式强很多了。

**Comment by spacewander** [comment]
呃……我就是有点不爽本尊对中文的处理。就是不能像打英文那么流畅嘛。只不过如果能把“word”还原成中文里的“词”那就再好不过了。

**Comment by ghosert** [comment]
暂时先无暇顾及了，毕竟是个小众需求。
