### ISSUE TITLE
序列图BUG

### ISSUE THREAD

**Issue by mritd** [ghosert/cmd-editor#1030]
序列图大了右侧不显示，也无法拖动，求速度修复

**Comment by mritd** [comment]
序列图、流程图 太大了以后 右面的 无法看到

**Comment by ghosert** [comment]
我还准备修呢，别关。

**Comment by mritd** [comment]
额。。。我错了。。。  其实感觉 OSC 的 git 配合 Team 挺不错的组合

**Comment by ghosert** [comment]
这个到时通过点击序列图，流程图显示完整图的方式来解决。

**Comment by asterisk622** [comment]
请问啥时候能fix啊

**Comment by ghosert** [comment]
现在修。

**Comment by ghosert** [comment]
暂时没那么快修好，再稍微等等。

**Comment by ghosert** [comment]
暂时可以先试试把文稿导出到印象笔记，然后右键点击序列图保存图片，这样应该可以看到完整的图片。在印象笔记里是保存成图片格式的。

**Comment by asterisk622** [comment]
看到今天的更新，鸡冻了一把，还以为能包含此BUG修复。
加油 @ghosert  赞

**Comment by ghosert** [comment]
昨天尝试了一把，没时间更新在这次，只能先发布了。

**Comment by mritd** [comment]
求快更新。。。等得我花都谢了。。。 我还准备导出 给别人看呢。。。

**Comment by mritd** [comment]
我擦。。点错了

**Comment by mritd** [comment]
@ghosert 请问这个bug 什么时候可以修复，这可是年前的 BUG 啊。。。拖了3个月了。。。

**Comment by ghosert** [comment]
憋着急，前段时间在旅游。回来了。

**Comment by ghosert** [comment]
开发环境下已经改完了，上线以后会关闭这个问题。

**Comment by ghosert** [comment]
这个已经有了：fhttps://www.zybuluo.com/ghosert/note/378553
