### ISSUE TITLE
行内代码、序列图、流程图 BUG

### ISSUE THREAD

**Issue by mritd** [ghosert/cmd-editor#1036]
目前发现三者任意一个只要太大了，超出屏幕边界，在阅读时就无法显示多余的部分，即使导出成html因为无法显示，直接右半部分看不到了

**Comment by ghosert** [comment]
了解了，会改进。

**Comment by mritd** [comment]
这次更新好像 流程等大了就看不到的 bug还没修复。。。。

**Comment by ghosert** [comment]
一个一个来。。。

**Comment by ghosert** [comment]
这个到时通过点击序列图，流程图显示完整图的方式来解决。

**Comment by ghosert** [comment]
开发环境下已经改完了，上线以后会关闭这个问题。

**Comment by ghosert** [comment]
已经更新修复了。

**Comment by ghosert** [comment]
这个已经有了：fhttps://www.zybuluo.com/ghosert/note/378553
