### ISSUE TITLE
Windows客户端黑暗主题 公式颜色

### ISSUE THREAD

**Issue by kokobd** [ghosert/cmd-editor#1043]
![截图](http://jianguoyun.com/p/DcH9-iQQlpnmBRje_w8)
普通文字颜色会随主题切换成浅色，但公式依然是深色。

**Comment by kokobd** [comment]
![cmdmarkdownformula](https://cloud.githubusercontent.com/assets/16440269/12004717/13534222-abac-11e5-87fd-e4465a487a05.png)

**Comment by ghosert** [comment]
多谢提醒，疏忽了。

**Comment by MtZero** [comment]
把公式的渲染模式调为 SVG 的时候也是这样，公式颜色不随主题变化。

**Comment by ghosert** [comment]
已经修了，下周发布出来。

**Comment by ghosert** [comment]
已修复并上线。
