### ISSUE TITLE
建议提供查找替换功能

### ISSUE THREAD

**Issue by Jack-Lo** [ghosert/cmd-editor#1044]
编辑的时候经常需要快速定位，或者说批量替换文本，希望编辑器能够提供这样的功能。

**Comment by ghosert** [comment]
这个功能有啊，见编辑区右上角的查找图标。 发自网易邮箱大师 在2015年12月26日 10:07 ，jack写道： 编辑的时候经常需要快速定位，或者说批量替换文本，希望编辑器能够提供这样的功能。 — Reply to this email directly or view it on GitHub.

**Comment by bozh** [comment]
开发君，我在用替换的时候遇到了一个问题。
具体是这样的：

需要替换的字符是`$<公式>$`里的`$`, 我想把它替换成`$$`, 使整体变成`$$<公式>$$`;
但是发现无法替换。
如果改成`$`->`$￥`, 却又可以替换了:joy::octocat:
