### ISSUE TITLE
【Suggestion】缩小编辑模式的视图

### ISSUE THREAD

**Issue by HunterYIboHu** [ghosert/cmd-editor#1045]
**windos7**平台上的客户端的**编辑模式**会占据半个多屏幕，如果同时打开其他窗口（用来记笔记），比较麻烦。可以允许其缩小到半个屏幕吗？

**Comment by ghosert** [comment]
了解了，会改下。

**Comment by mritd** [comment]
15.3 寸笔记本表示上下间距无法调整，下部已进入底部开始栏里

**Comment by ghosert** [comment]
重新下载一下客户端，应该解决了。https://www.zybuluo.com/cmd
