### ISSUE TITLE
UI太差

### ISSUE THREAD

**Issue by kunlive** [ghosert/cmd-editor#105]
可以考虑借鉴的布局，做好一个主题
http://maxiang.info/

或者是发布页面可以做得更好些。
产品很好，功能也够全了。。UI让人喜欢就会让作业部落，价值更大。

另外可以思考考虑改下域名，

**Comment by ghosert** [comment]
我不知道你说的差是指皮肤不够绚丽还是功能布局有问题？可以详细说说。我反而觉得马克飞象太花了，文字工作者其实需要的是一个朴素的界面而不是够炫的皮肤。时间长了眼睛很花。

域名的问题，好的域名需要钱，目前都是免费在做。

**Comment by kunlive** [comment]
sorry,ui太差不太准确。背景我认为可以更好，没有必要绚丽，简书也不是绚丽，但感觉较好。发布后的页面可以考虑白色为背景，日期可以考虑几天前，7月2日似的表达。印象笔记，发布后是灰蓝背景吧，用白色一页显示markdown笔记内容。可能我比较喜欢这样。域名的话，设计到网站定位问题。.com域名不行可以考虑用.io .me ,xiexie.io 499元/年,看起来贵，但跟你个人开发的时间比起来可能也能接受。

**Comment by kunlive** [comment]
现在我觉得编辑器已经很好了，但涉及到社交，就要仔细想好了。我个人是不喜欢用简书的，我主要用来写给朋友，但是在简书在发布后好像所有人都能看到，我就找到淳朴的作业部落。

**Comment by ghosert** [comment]
这个怎么说呢，作为一个写作平台，实际上就是希望用户多来写，多发布，如果编辑器不收费，用户也不想公开文稿，如果人人都这样，作为作者真的很为难，实现上，或许可以为这一类需求提供设置文稿密码的功能，我在仔细想想。

**Comment by lanxinyuchs** [comment]
我挺喜欢这个UI的，除了“发布””新文稿“还有文本列表里面的那些蓝幽幽的字，感觉与整体风格有些不搭。整体而言，有极简主义风格，细节设计的很精致（比如搜索框），虽说前几次使用时有些功能有些难找

**Comment by ghosert** [comment]
@lanxinyuchs 感谢支持，其实极简也是无奈，因为没有美工，^_^。

**Comment by ghosert** [comment]
如果有好的美工能义务帮忙最好了。
