### ISSUE TITLE
使用注脚后鼠标会乱跳

### ISSUE THREAD

**Issue by weizhang93** [ghosert/cmd-editor#1053]

**Comment by ghosert** [comment]
能详细描述下吗？是，鼠标跳还是页面滚动？markdown原文，具体重现的步骤说下。操作系统浏览器版本说下。 发自网易邮箱大师 在2015年12月31日 14:26 ，weizhang写道： — Reply to this email directly or view it on GitHub.

**Comment by weizhang93** [comment]
https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown
这个页面为例，点击阅读栏的注脚后，到左边的编辑栏使用鼠标滑轮上下滚动后，点击鼠标左键，不管滚动多少，点击哪里，页面都会跳到注脚的地方。不知道我这样描述你理解了没有。
浏览器版本  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by ghosert** [comment]
我在chrome浏览器下试了试并没有发现这个问题。

**Comment by ghosert** [comment]
win7, chrome

**Comment by weizhang93** [comment]
我使用的是win10 ==''

**Comment by mdjsjdqe** [comment]
我的Win 10 版本一切正常，edge chrome firefox兼容性正常

**Comment by weizhang93** [comment]
换了一台电脑后使用正常
