### ISSUE TITLE
导出PDF失败了

### ISSUE THREAD

**Issue by BrambleXu** [ghosert/cmd-editor#1056]
提示说服务器可能正在忙。试了下别的笔记能够导出正常，不知道原因出在哪里

https://www.zybuluo.com/mdeditor#238466

![screenclip](https://cloud.githubusercontent.com/assets/10768193/12073422/07465182-b164-11e5-947c-9e6d3dab7a38.png)

**Comment by ghosert** [comment]
看看是不是有被墙的图片链接。或者找个简单点的文稿导出看看。再不行把markdown原文发到support@zybuluo.com 发自网易邮箱大师

**Comment by BrambleXu** [comment]
图片全是自己截的，应该不是这个原因。我把原稿发到邮箱里了。

**Comment by ghosert** [comment]
200多个图片在一个文档里，实在太多，服务器无法承受那么大压力，可先导出为带样式的HTML，然后用CHROME 打印保存为 PDF，具体步骤已发邮件告知，请查收。
