### ISSUE TITLE
序列图导出为 PDF 的一个问题

### ISSUE THREAD

**Issue by MtZero** [ghosert/cmd-editor#1058]
在客户端和网页上实时渲染的结果如下：
<img width="623" alt="2016-01-03 03 00 12" src="https://cloud.githubusercontent.com/assets/15688152/12075794/985a087c-b1c7-11e5-94f2-23c64320b7fa.png">

导出为 PDF 时是这样：
<img width="806" alt="2016-01-03 03 00 17" src="https://cloud.githubusercontent.com/assets/15688152/12075764/903f5bde-b1c6-11e5-992b-6c3d22cbbda8.png">

而且，序列图和流程图导出为 PDF 时转换成的图片不太清晰。而把网页版的用浏览器直接导出为 PDF 则仍是矢量的图形和文字，希望能够改进。

**Comment by ghosert** [comment]
已经改了，下周发布出来。

**Comment by ghosert** [comment]
已经高清化了。
