### ISSUE TITLE
导出的一点问题

### ISSUE THREAD

**Issue by momo9** [ghosert/cmd-editor#106]
总体来说是非常好用的。不过我还是遇到下面这个问题。

现在很多网站还没有支持Markdown，那我先会将Markdown代码粘到富文本编辑器里，再用`Markdown Here`转换一下，还是挺方便的。

不过作业部落的Markdown代码粘到富文本编辑器里，换行会消失，从而导致格式的混乱。这个有什么解决方法么？感觉原因是代码是纯文本的，如果_输出具有HTML格式的Markdown代码_呢？

**Comment by ghosert** [comment]
原因很简单，因为一般 Markdown 的语法是要求在两行之间多空一行表示换行的，Cmd Markdown 为了方便用户改成了换行就是换行，所以有这个问题。
