### ISSUE TITLE
文档嵌入优酷视频链接出问题<embed>

### ISSUE THREAD

**Issue by mdjsjdqe** [ghosert/cmd-editor#1062]
比如这个代码<embed src="http://player.youku.com/player.php/sid/XMTM3OTM5OTA0/v.swf" allowFullScreen="true" quality="high" width="480" height="400" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash"></embed>

希望快点解决这个Bug，愿作者开心工作hard work HARDER player！

**Comment by ghosert** [comment]
排上日程，尽快。

**Comment by ghosert** [comment]
已在测试环境修复，下周上线。

**Comment by ghosert** [comment]
zybuluo 是 https 的网站，优酷使用的 <embed> 是 http 会被 chrome 等浏览器自动屏蔽，可以参照这个文章自行解除屏蔽：https://kb.iu.edu/d/bdny#chrome
