### ISSUE TITLE
标题输入英文时显示有问题

### ISSUE THREAD

**Issue by Aristotle0** [ghosert/cmd-editor#107]
光标与输入的前一个字体重叠，只在标题会出现这种情况（各级标题），正文不会

系统 mac os x
浏览器safari

**Comment by ghosert** [comment]
换用 chrome 看看，safari 我暂时没有。性能和渲染速度上 chrome 都会快很多。推荐使用。

**Comment by Aristotle0** [comment]
看来不是浏览器的原因，换了chrome之后也是如此
![2014-05-11 5 52 47](https://cloud.githubusercontent.com/assets/7519747/2938144/2b03adaa-d8f2-11e3-85a6-b92b44f55105.png)

**Comment by ghosert** [comment]
手上暂时没有 Mac，不过 Ubuntu / Windows 上 Chrome 是工作的。我有时间找个 Mac 看看。

**Comment by ffq5050139** [comment]
Chrome 上确实有这样的问题
win xp
chrome33.0.1750.117

**Comment by ghosert** [comment]
这个问题主要式因为某些操作系统和浏览器下，英文粗体和正常字体之间不等宽造成的。目测 windows xp 以上的 windows 操作系统没有问题， ubuntu 下仅有 firefox 有问题，mac 也有问题。 

**windows xp 下的 chrome 可以升级到 chrome 34 以上版本试试。**

**Comment by Aristotle0** [comment]
这个是因为这个网站字体的原因吗？我用网页版的onenote没这个问题。

**Comment by ghosert** [comment]
已经解决了，可以去站上试试。
