### ISSUE TITLE
可以不可以添加一些主题，最好提供自定义CSS

### ISSUE THREAD

**Issue by bayuexiong** [ghosert/cmd-editor#1071]
可以不可以添加一些主题，最好提供自定义CSS，现在默认实在是一般，dark主题实在有点介绍不了

**Comment by terranc** [comment]
支持一下可以自定义css

**Comment by backwind1233** [comment]
强烈建议主题功能

**Comment by ghosert** [comment]
已更新，可以自定义CSS了：fhttps://www.zybuluo.com/ghosert/note/378553
