### ISSUE TITLE
列表的三层以上嵌套以及字体调节

### ISSUE THREAD

**Issue by haricheung** [ghosert/cmd-editor#1075]
1. 使用中发现列表仅支持两层，但是平时需要三层和多层嵌套，希望支持。
2. 希望可以自行调节字体大小，写文档时间长了发现编辑框内字体小眼睛容易疲劳，可以调节就好了

**Comment by ghosert** [comment]
你发一个列表例子过来，应该是支持的。可能是你的列表里嵌入了太复杂的语法导致的，最好只是嵌入普通的文本内容。

**Comment by haricheung** [comment]
@ghosert 请看下下面截图。
![image](https://cloud.githubusercontent.com/assets/2599631/12529511/2644d2a2-c1f4-11e5-9a77-d98de5e70288.png)

**Comment by ghosert** [comment]
字体字号CSS样式都可以改了：https://www.zybuluo.com/ghosert/note/378553

**Comment by ghosert** [comment]
多空几个空格试试。
