### ISSUE TITLE
希望增加一键导入所有文稿 & 希望有一个完全基于本地的编辑器

### ISSUE THREAD

**Issue by oopp1800** [ghosert/cmd-editor#1078]
作者好，我重装并导出所有文稿后，发现并没有导入文稿的方式，只能一篇篇找哪些是离线文稿再重新写新文稿。望增加“一键导入所有文稿”的功能。

另外关于作者的回复

> 因为原本对于非离线的文稿，完全可以从服务器端同步过来，不用担心重装系统或 
> 者换电脑的问题。离线文稿隐私是完全确保了，但是在同步或者恢复方面就不那么方便。

其实我的需求是一个**完全本地的 CMD markdown 编辑器**...这就不知道以后能不能见到了..目前 windows 系统上的本地 markdown 编辑器我花了一天时间基本全部试用过一遍，~~因为一开始就用 CMD 把胃口调太高~~确实没满意的，不是样式不行功能不全就是导出不了**带目录的PDF**。
如果有可能的话，希望作者考虑下这个需求（我觉得并不是一个很小众的需求吧...），表示再付一次费也愿意啊..

**Comment by ghosert** [comment]
其实就是对本地文件能编辑修改保存，会加到客户端里去的。WEB版估计做不到了。

**Comment by ghosert** [comment]
可以新建打开本地文件了：https://www.zybuluo.com/ghosert/note/378553
