### ISSUE TITLE
如何删除一些文档？

### ISSUE THREAD

**Issue by junyiliu** [ghosert/cmd-editor#108]

**Comment by ghosert** [comment]
工具栏右上角那一排按钮里，找一找就有了。或者直接按 ctrl+alt+d 快捷键。

**Comment by ghosert** [comment]
注意删除的是当前文档，如果需要删除其它的文档，先访问那篇文档再删除。

**Comment by lanxinyuchs** [comment]
找了N遍（N>5）了，总算找到了……藏的太深？而且一定要打开该文档才能删，咋就不可以在文章列表里直接删呢

**Comment by ghosert** [comment]
因为不鼓励删除文档啊，^_^
