### ISSUE TITLE
关于一键导出功能中的图片导出问题？

### ISSUE THREAD

**Issue by a5635268** [ghosert/cmd-editor#1080]
现在CMD markdown基本上承担了我所有的文档编写需求，其中包括了学习笔记，项目文档，个人简历等等，这些文件都蛮重要的，我都定期一键导出保存备份，以防cmd官网主机发生意外（虽然几率非常渺小），但是问题就来了....

图片怎么办？

万一哪一天cmd官网主机被黑或者出现其他问题，图片怎么找回来？

**Comment by ghosert** [comment]
图片在七牛云存储上，值得信赖，得以托付。会费中有一部分就是付给七牛购买的云存储服务，所以发生意外对方会有担当。

**Comment by a5635268** [comment]
哪能导出图片吗？
