### ISSUE TITLE
能不能加标题及区块颜色

### ISSUE THREAD

**Issue by 456wyc** [ghosert/cmd-editor#1081]
比如标题或块以‘！’开头，代表success，背景绿色，！！代表primary ，背景蓝色，！！！ 代表warning,背景橙色，！！！！代表danger，背景红色 ， 级别差不多和 http://v3.bootcss.com/css/#buttons 一样

**Comment by ghosert** [comment]
色块可以暂时自行写 HTML 嵌 CSS 来解决哈。
