### ISSUE TITLE
在无序列表中编辑公式后，列表之间的间隔变得过分大了。

### ISSUE THREAD

**Issue by zylhub** [ghosert/cmd-editor#1082]
如图所示间隔变大,列表中的每一项换行后同样间隔变大：
![](http://static.zybuluo.com/knight/ugyl9dghvx4gxgtquyplr8kg/Screenshot%20from%202016-01-13%2010-07-24.png)

**Comment by ghosert** [comment]
公式最好不要嵌入列表。。。列表一般指简单列表，没有复杂的东西。可以自行写一些类似

```
#### 1. 公式1
#### 2. 公式2
```

**Comment by zylhub** [comment]
在firefox下出现了这个问题，google浏览器是正常的。cmd使用web版本。系统ubuntu15.
