### ISSUE TITLE
希望能导入由 http://stackedit.io/ 生成的 JSON 数据

### ISSUE THREAD

**Issue by likid1412** [ghosert/cmd-editor#109]
之前一直使用 http://stackedit.io/ 在线编辑器，看到有国产的，立马支持！
但是这里有个小小的问题，就是没有发现导入选项，希望能提供下导入的功能，谢谢！

**Comment by ghosert** [comment]
时间精力有限，我不太会去兼容别人的数据，或许以后可以提供批量上传 markdown 的功能。
