### ISSUE TITLE
关于文本列表的改进建议

### ISSUE THREAD

**Issue by PearlEast** [ghosert/cmd-editor#11]
当文本足够多时，点击文本列表后，一坨一坨的标题出来，我个人感觉有点眼花缭乱无所适从啊。请问可以支持创建文本列表分类吗，或者像浏览器的收藏夹那样，里头可以嵌套创建子文件夹。 谢谢作者的智慧贡献和无私劳动。

**Comment by ghosert** [comment]
列表的问题，我的确有计划改进一下，标记成 enhancement

**Comment by PearlEast** [comment]
那再好不过了，赞。

**Comment by ghosert** [comment]
已支持
