### ISSUE TITLE
支持CSS定制吗？

### ISSUE THREAD

**Issue by vale1534** [ghosert/cmd-editor#1102]
是否考虑支持CSS界面定制，非常期待。

**Comment by vale1534** [comment]
我的建议是，如果用户编辑的内容包括：

``````
```css-hook
// css code here
```
``````

那么将这段css代码追加到这篇文章的css样式。

对于我来说，主要想定制字体和代码块的样式。

**Comment by ghosert** [comment]
这个建议好，我考虑下。

**Comment by wafer-li** [comment]
对此，我建议把这个放到设置里面。

有些时候希望自己的文章具有一个统一的风格，但是每次都复制一大段 CSS 显然不是个好办法。

**Comment by ghosert** [comment]
这个已经有了：fhttps://www.zybuluo.com/ghosert/note/378553
