### ISSUE TITLE
客户端窗口限高了吗，1366*768笔记本上显示不全

### ISSUE THREAD

**Issue by vale1534** [ghosert/cmd-editor#1103]
试了32位和64位，在笔记本上运行时高度超出屏幕，并且调整不过来，要知道这个分辨率是笔记本的主流，没钱买高分屏的用户伤不起。

**Comment by ghosert** [comment]
去 https://www.zybuluo.com/cmd 重新下载一下客户端，现在最小尺寸限制在 800*600 了，可自行调节到这个高度，你的问题应该解决了。
