### ISSUE TITLE
建议开发一个桌面版

### ISSUE THREAD

**Issue by shixiaobao17145** [ghosert/cmd-editor#111]
建议开发一个桌面版的mdeditor。这个就算没有网络也能随手用markdown写文章了。
建议用类似node-webkit这样的东西来做，这样开发成本会低很多。直接用当前的页面和js做一些修改和编译就可以了。
期待~ ：）

**Comment by jemygraw** [comment]
@shixiaobao17145 原来你在这里冒过泡。

**Comment by shixiaobao17145** [comment]
@jemygraw 是的，原来你也来过。。。：）

**Comment by franklinzhang** [comment]
同意，目前用起来还是有点卡，尤其是输入标点符号的时候，老在自动保存上卡顿。

**Comment by ghosert** [comment]
你人在国外吗？

**Comment by shixiaobao17145** [comment]
@ghosert ,我给你讲两个场景。一个是一些项目中有些readme.md想用你的mdeditor编辑，没有桌面版不行。只能用复制里面的内容到网页版中，再弄出来。而网页版一改就提交到mdeditor的服务器上了，这样有些时候是不好的；还有一个场景，比如专门用markdown来写文章的自媒体用户，他们想mdeditor做写作软件，做成桌面版是最合适的，比如他们想做版本控制，做了一批改动后再提交，并且可以查看历史版。以现在的网页版机制就不行。还有，有时候他们并不希望东西存在mdeditor服务器。

**Comment by franklinzhang** [comment]
@ghosert 首先，非常感谢您提供这么好的markdown编辑器，我已经连续十天在上面写论文底稿了。 我人在国内，江苏联通宽带用户。从知识产权保护和卡顿的方面讲，我还是希望能够提供桌面版，如果您需要收取一定的费用，我会积极配合的。谢谢，还有公式编号的事情不知道您考虑的怎么样了。再次感谢。

**Comment by ghosert** [comment]
对公有云的不信任的确是一个问题，但是我也不会拿着网站的信誉开玩笑去泄漏用户未发布的资料。所以我觉得这还是需要一个长期建立信任的过程。譬如，你绝对会认为在Dropbox Evernote 里存放私人数据是安全的。
所以并非是在线平台存储用户的数据有问题，而是要取得用户对网站的信任感。
桌面版本一定会做，但是如果用户只是作为一个工具来使用，我自己也很为难，如果用户觉得好用，也因此受益，比如自媒体或者上论文期刊，不知道收取多少费用比较合理。

**Comment by shixiaobao17145** [comment]
嗯，作者的想法我也赞同的。个人觉得，不管用户拿桌面版作为工具还是别的什么，最重要的是不能流失这一块的用户。作者的心思我也明白，但只能通过产品本身来影响用户的行为和习惯，而不是策略。至于收费问题，就看当前markdown编辑器的需求和市场了。个人觉得还是先积累用户和优化产品本身比较重要。：）

**Comment by franklinzhang** [comment]
我大概理解了张同学的思想：

> - 希望大家都在他的平台上分享内容，有点像[简书](http://jianshu.io/)的味道
> - 希望通过优质的服务让大家逐渐信任他的平台

我提提我的建议：

> 1. 在已经有简书的情况下，张同学的平台要发展要体现一定的差异性
> 2. 让大家建立对您彻底放心您的平台的可靠性和安全性需要一个过程
> 3. 可以同时兼容dropbox、evernote和google drive
> 4. 仍然希望有桌面版，毕竟写学术论文的话，web版还是有点不放心
> 5. 希望引入style的功能，或者引入pandoc等高级发布功能，一键发布成作者希望的格式，如针对微信公共号的、针对长weibo的、针对技术学术博客的等
>    3、4、5这样的高级功能一定要收费，但是价位应当是适用于个人的，不要台阶过高，如99元/月

**Comment by ghosert** [comment]
目前的方向是 IT，技术，科研类的专业文稿，简书是文艺路线，所以编辑器和渲染上这方面的差别明显。譬如渲染代码，支持 LaTeX，时序图，流程图，vim/emacs 等等。技术实现上，这大半年都在优化一个编辑器。后面的确会考虑文稿怎么发布，桌面版怎么做，另外照顾不同需要的用户，可能还有国际版。总之一大堆事情，^_^。上面几点建议都有考虑，除了 style 可能暂时还是由官方提供比较好，每个人的审美观不相同，开放 style 可能会让整体很混乱，我也希望大家在 style 之外专注提升文稿的质量。

**Comment by franklinzhang** [comment]
不好意思，style的事情我没说清楚，我想表达如下含义

> 1. style 只能从官方渠道提供
> 2. style 并非用来炫酷，而是利于在不同的渠道发布
> 3. 免费用户只能用一种默认style
> 4. 每种stlye锁定中英文字体各一种，严禁用户更改

另外探讨下协作的功能，科研论文对写作要求较高，有两种模式：

> 1. 多人协作写作，类似google document
> 2. 一人主力写作，其他人对文章完成类似word那样的评注和修订

如果能完成这个功能，善莫大焉，我们愿意支付word的代价，甚至更高的代价

**Comment by ghosert** [comment]
可以微博私信我一下 @ghosert，告诉我你的邮箱，线下探讨一下。

**Comment by rywiki** [comment]
卡顿确实是个大问题。我现在的文档只有五千来个字，chrome上就开始了。希望客户端/桌面版之类一定要解决这个问题。

**Comment by ghosert** [comment]
https://www.zybuluo.com/cmd/ 全平台客户端已出
