### ISSUE TITLE
高级会员本地图片存储在哪里

### ISSUE THREAD

**Issue by zhaohq90** [ghosert/cmd-editor#1115]
高级会员是可以支持同步到印象笔记的吧，因为示例演示的国际版，所以想再确认下。
高级会员上传本地图片是存储到作业部落自己的服务器吗？建议支持七牛空间，用户自己指定七牛空间，这样方便用户以后迁移，也减轻了作业部落的压力。或者编辑器可以增加一个设置图片域名的设置，编辑的时候输入相对路径，预览和同步到evernote的时候自动拼接域名

**Comment by ghosert** [comment]
对的，国际版和印象笔记都支持。另外存储空间是七牛的，我们付费购买了他们的云存储，图片上传以后是到七牛的服务器的。因为不是每个用户都知道怎么去开通七牛的空间，这个事情我们就自己解决了，用户只需要上传就好了。 发自网易邮箱大师 在2016年01月25日 11:26 ，aprilfish写道： 高级会员是可以支持同步到印象笔记的吧，因为示例演示的国际版，所以想再确认下。 高级会员上传本地图片是存储到作业部落自己的服务器吗？建议支持七牛空间，用户自己指定七牛空间，这样方便用户以后迁移，也减轻了作业部落的压力。或者编辑器可以增加一个设置图片域名的设置，编辑的时候输入相对路径，预览和同步到evernote的时候自动拼接域名 — Reply to this email directly or view it on GitHub.
