### ISSUE TITLE
希望能直接保存修改本地文件，而不用再导出到本地

### ISSUE THREAD

**Issue by wudongyang** [ghosert/cmd-editor#1117]
刚开始用，感觉很不错，感谢作者。

一个建议：
习惯建一个git工程，然后把文档都放到git工程里，在本地修改文档后，提交git。
所以希望能直接保存修改本地文件，而不用再导出到本地。

**Comment by ghosert** [comment]
可以直接保存修改本地文件了：https://www.zybuluo.com/ghosert/note/378553
