### ISSUE TITLE
建议支持更多的服务,比如Dropbox,github,OneDriver,GoogleDOC之类的

### ISSUE THREAD

**Issue by fanicy** [ghosert/cmd-editor#1118]
感谢提供这么好的应用,开发人员辛苦了~
建议支持更多的服务,比如Dropbox,github,OneDriver,GoogleDriver之类的;
云存储用的越来越多了,像GoogleDriver,Dropobx之类的,同步方便,而且应该都提供了访问接口,强烈要求增加~~~
考虑付费中,同时也会给更多的人推荐~

**Comment by ghosert** [comment]
你列举的这些大都被墙，所以即使支持体验也不会太好。Cmd Markdown 本身实际上已经自带云存储和云同步了，如果还是不放心可以自行定期一键导出。
