### ISSUE TITLE
光标错位，输入法各种问题

### ISSUE THREAD

**Issue by ZeekoZhu** [ghosert/cmd-editor#1119]
## 光标错位

本来应该停在行尾，但却落在了行中的某个文字上
## 输入法问题

win10自带输入法不显示候选项
QQ输入法会把部分拼音也带上去

---

以上问题仅出现在cmd markdown 的客户端与网页端

**Comment by ghosert** [comment]
请看下浏览器字体设置，建议使用等宽字体。

**Comment by ghosert** [comment]
参照这个文章更改一下等宽字体：https://www.zybuluo.com/ghosert/note/378553
