### ISSUE TITLE
无法验证邮箱，以及似乎和用户名冲突了？

### ISSUE THREAD

**Issue by think2011** [ghosert/cmd-editor#112]
我的用户名：think2011 
我的邮箱：452125301@qq.com

我只能用 用户名 登录。
用邮箱登录是，告诉我未验证，并且我找不到此邮件。

> 您填写的邮箱帐号尚未验证，请换用【用户名】登录。我们在 2014-03-06 10:24:47 曾向此邮箱发送过验证邮件，请前往邮箱（包括垃圾箱）查收验证。

于是我点击忘记密码，重置了密码，依旧提示。
我用用户名登录进去，却找不到相关设置。

**Comment by ghosert** [comment]
我又给你发了一遍，查收一下。再有问题可以加我一下微博 @ghosert 私信联系。

**Comment by think2011** [comment]
![](http://ntu.me/di/PT6PK/1.gif)

很抱歉，我不用微博哦 ：（ 我就在这里给你回复好了。
1. 如图所示，依然无法验证邮箱。
2. 发现没法点登出，一点就刷新页面了。
3. 貌似我的邮箱也有问题，作业部落发给我的邮件默认都进了垃圾箱。
4. 作业部落真心好用 ;D

**Comment by baoxiehao** [comment]
我的邮箱是baoxiehao@qq.com，在垃圾箱里面收到验证邮件，验证无数次还是提示没有验证，然后重置密码也还是同样的错误，无解啊！！！！！！！！！！！

**Comment by ghosert** [comment]
了解，我回去再给你看看。

**Comment by think2011** [comment]
那个无法登出的问题是因为我的某个chrome扩展引起的。

**Comment by ghosert** [comment]
嗯，想着也是。

**Comment by ghosert** [comment]
我现在帮你看邮箱验证的问题，是哪个 chrome 扩展引起无法登出，你知道吗？

**Comment by think2011** [comment]
一个叫 拖拽搜索（新窗口打开）的插件，图标就是一个 鼠标指针的插件，它不止影响了作业部落，其他网站也出现这种情况。

**Comment by ghosert** [comment]
你是在 windows 下用 chrome 吗？

**Comment by think2011** [comment]
是的。

**Comment by think2011** [comment]
[就是这个插件](https://chrome.google.com/webstore/detail/%E6%8B%96%E6%8B%BD%E6%90%9C%E7%B4%A2/pikkaahnnohhoileadgipnfcklbalemk?hl=zh-CN) ，没有BUG的话，还挺好用的。 ：D

**Comment by baoxiehao** [comment]
拖拽搜索的插件？好像没听说过呢。我用的chrome还是猎豹忘记了，因为经常2个混着用。我在家里的电脑注册时OK的，要不我先试试重新登录是否可以吧。这么好用的MD在线编辑实在是不用可惜呢。

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年5月18日(星期天) 晚上7:39
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "Simpy"baoxiehao@qq.com; 
主题: Re: [cmd-editor] 无法验证邮箱，以及似乎和用户名冲突了？ (#112)

你是在 windows 下用 chrome 吗？

**Comment by baoxiehao** [comment]
你好，刚刚试了chrome确实不行。然后把猎豹（注册用的浏览器）的退出登陆了，重新登录也是一样的提示，说是邮箱没有验证呢。

------------------ 原始邮件 ------------------
发件人: "曾浩";notifications@github.com;
发送时间: 2014年5月18日(星期天) 晚上7:38
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "Simpy"baoxiehao@qq.com; 
主题: Re: [cmd-editor] 无法验证邮箱，以及似乎和用户名冲突了？ (#112)

一个叫 拖拽搜索（新窗口打开）的插件

**Comment by ghosert** [comment]
@think2011 我这里看了一下，应该没问题。感觉还是你的浏览器的问题，麻烦禁用那个插件以后再试试点击 qq 邮箱里的那个链接，按你上面的步骤来。
如果还不行，换个浏览器试试。
有结论告诉我。

**Comment by ghosert** [comment]
@baoxiehao 你有微博吗？私信我 @ghosert

**Comment by ghosert** [comment]
@baoxiehao 我给你重新发了邮件收一下。点里面的链接，按提示一步一步来。

**Comment by ghosert** [comment]
@baoxiehao 成了告诉我一下。

**Comment by think2011** [comment]
@ghosert  抱歉，能够重新发一下邮件给我吗？ 我实在找不到了，而且很奇怪的，邮件老是进了垃圾箱，不知道为什么。

**Comment by ghosert** [comment]
@think2011 发了

**Comment by ghosert** [comment]
qq 的问题，能不能标记一下这封邮件不是垃圾邮件。

**Comment by think2011** [comment]
太好了~~ 我验证通过了~ @ghosert 
1. 邮件是接收到 收件箱 的，然后我点击进去告知验证过期，但是可以重发，于是点击重发。
2. 然后在 垃圾箱 （！！太莫名其妙了）收到了重发的验证邮件，就通过了！

谢谢！！

**Comment by townetowne** [comment]
终于搞好了，帮助他人 ，如果被这个验证整的实在没辙了，**请试试 safari**  ，不谢！
另外，这种基础功能作者能否就写成正常表单来提交？就不敢献技了。
