### ISSUE TITLE
Mac端不能半屏使用，总是超过屏幕一半

### ISSUE THREAD

**Issue by hh23485** [ghosert/cmd-editor#1120]
有时候进行翻译或者写论文，需要参考一些东西，总希望左边一般右边一般，没有双显示器的时候，不能分屏太麻烦了，现在的mac端总是占据屏幕70%的空间，这样剩余的空间很难进行操作其他的东西了，希望能够缩放到屏幕一半。（尽管web端可以随着浏览器放到一半，但是不习惯在浏览器里写东西。。）

**Comment by ghosert** [comment]
请重新去官网下载一份客户端，可以调节到更小的尺寸。 发自网易邮箱大师
