### ISSUE TITLE
流程图flowchart 不全

### ISSUE THREAD

**Issue by Yifei0727** [ghosert/cmd-editor#1121]
关于flowchartjs 流程图显示不全的问题已经修复https://github.com/adrai/flowchart.js/issues/67，
请作者在官方网站 www.zybuluo.com 也及时更新下该js，谢谢。

**Comment by ghosert** [comment]
好嘞，我看看。

**Comment by ghosert** [comment]
我去看了下这个FIX也在本地用了他的最新版本，好像没解决问题，感觉他解决的是竖向的问题，一般用户在Cmd Markdown上是横向比较窄产生的问题，我觉得还是用点击看大图的方式来解决比较好。

**Comment by Yifei0727** [comment]
横向的没必要，版面有限，大家都知道不可能太宽。
因此会采用竖向来解决，因为竖向可以增加版面。

Jay Zhang notifications@github.com于2016年2月14日周日 20:00写道：

**Comment by Yifei0727** [comment]
![image](https://cloud.githubusercontent.com/assets/6064040/13038033/d9141bce-d3c7-11e5-9b61-94b673a492b5.png)
像这种就很别扭，因为显示不全

**Comment by ghosert** [comment]
是不是参考 https://github.com/adrai/flowchart.js/issues/67 你这个问题就解决了？你这个图对应的原始 Markdown 文本是什么？贴一下我看看。

**Comment by Yifei0727** [comment]
### 4. 高效绘制 [流程图](https://www.zybuluo.com/mdeditor?url=https://www.zybuluo.com/static/editor/md-help.markdown#7-流程图)

``` flow
st=>start: Start
op=>operation: Your Operation
cond=>condition: Yes or No?
top=>operation: My Operation
tcond=>condition: Do or Not?
e=>end

st->op->cond
cond(yes)->top->tcond
cond(no)->e
tcond(yes)->op->cond
tcond(no)->e
```

### 5. 高效绘制 [序列图](https://www.zybuluo.com/mdeditor?url=https://www.zybuluo.com/static/editor/md-help.markdown#8-序列图)

**Comment by Yifei0727** [comment]
现在他们那个官网已经可以完全显示了

**Comment by ghosert** [comment]
了解了，可能要到三月头上修了。最近有点其它事，稍安勿躁。

**Comment by Yifei0727** [comment]
马上三月下旬了

**Comment by ghosert** [comment]
flow 问题已上线：https://www.zybuluo.com/ghosert/note/378553 点击 flow 可以全屏看大图了。
