### ISSUE TITLE
强烈希望网页端尽快更新

### ISSUE THREAD

**Issue by chineselzh** [ghosert/cmd-editor#1126]
> 作业部落比简书在书写上、格式解析上、功能完整度、使用体验上都完爆简书，但简书的网页版和宣传上却甩开作业部落几百条街，个人认为很大程度上网页版的开发重视程度是主要原因！希望未来作业部落能借鉴一下它网页的设计方式，希望各平台作业部落越来越好用！
1. `强烈`希望`网页端`尽快更新
2. 可以像简书一样的有个人主页，
3. 找作者的其他文章更人性化，让电脑小白都可以方便的找到。
4. 像简书一样可以查看作者的写作总字数、关注等，可以有效的刺激作者的创作热情！
5. 搜索引擎更快收录新文章
6. 希望作业部落变成写作社区或BLOG形式而不是单纯的网页版的markdown写作软件，更有利于发展

谢谢！

**Comment by ghosert** [comment]
谢谢，一定会实现！

**Comment by ghosert** [comment]
网页端其实一直在更新，这里是更新列表。所以才会让用户觉得体验完爆，体验完爆是不断打磨的结果。。。不过重心的确如你所述可以放在社交，阅读上了。

**Comment by ghosert** [comment]
更新历史在这里：https://www.zybuluo.com/ghosert/note/102771

**Comment by chineselzh** [comment]
一直在默默关注作业部落的发展，见到**`写作体验`**、**`功能完善`**不断改进，但**`文章展示方面`**一直没怎么见到改变，希望新的2016年能看到作业部落的飞速发展和用户的奔走相告！
作者做产品的态度精益求精，赞一个！早日超越~~简书~~绝对不是梦！

**Comment by ghosert** [comment]
简书是文青类，应该风格会和简书不一样。谢谢鼓励。
