### ISSUE TITLE
离线文稿消失

### ISSUE THREAD

**Issue by hgl10** [ghosert/cmd-editor#1127]
写了很久的一份文稿不见了，应该是被垃圾清理软件删除了（用了好几个软件清理垃圾，清理了浏览器缓存之类的，不知道是哪个清除的）。

很重要的一份文档，为了安全特意买的会员，用了离线模式，就这样没了。
不知道还有办法补救没有？这种问题以后如何避免？难道要不停地手工保存在本地？

另，离线文档添加图片必须要来上传到网上？

一天半前已经发送邮件给support@zybuluo.com，还未收到回复，不知道该如何提交问题，不知道写在这里是否合适。

**Comment by ghosert** [comment]
不好意思，可能是我疏漏了你的邮件。离线文稿是存在浏览器的 indexedDB 内，如果没有及时一键导出，又清理了浏览器的缓存，可能的确会被清理掉。这个咋么说呢，离线文稿因为没有同步到云端，无法在云端给你做备份，只能认为是一次本地的灾难丢失数据了。

私密和安全是一对矛盾。即使我们这边是承诺完全遵守作者隐私的。今后可以多使用一键导出功能，及时把重要的文件备份出来，尤其是做清理操作前。

离线文稿的图片是被上传到七牛云存储，相信它们作为一家新兴的云存储服务商也同样会尊重作者隐私。请放心。

**Comment by hgl10** [comment]
好吧，能否在本地建立一个存储中心？自己指定一个文件夹，可以定时自动保存？不然用离线模式，总感觉心里不踏实。

如果不行的话，希望能在介绍离线文稿的地方加上注释，提醒一下别人这种情况。

**Comment by mindseek** [comment]
这个你应该把网页版的风险说清楚的，我两篇论文，就这么白写了，唉，有什么补救的办法吗？

**Comment by ghosert** [comment]
暂时没有。。。不过如果你用客户端新建离线文稿的话，现在会首先让你选择本地文件，这样就在文件系统里也保存了一份。
