### ISSUE TITLE
希望添加插入表格功能

### ISSUE THREAD

**Issue by oucb** [ghosert/cmd-editor#113]
如题。。。

**Comment by ghosert** [comment]
原生支持的。

https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#7-%E8%A1%A8%E6%A0%BC%E6%94%AF%E6%8C%81

**Comment by richaction** [comment]
这表格功能还是太弱了

**Comment by ghosert** [comment]
那就写 html 

https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#9-html-%E6%A0%87%E7%AD%BE
