### ISSUE TITLE
无法发布更新

### ISSUE THREAD

**Issue by tshao** [ghosert/cmd-editor#1131]
之前曾经写过很多篇（上百篇）文章都没有遇到的比较奇怪的一个问题，最近写的一篇文章无法更新，显示“正在提交您的请求……”然后就卡在这里不能动了。

如果将文章删掉一部分是可以发布的，但不确定是具体哪一部分。有时删掉前半段，或是后半段就可以了。文中（应该）没有任何敏感词汇。

**Comment by ghosert** [comment]
已修复。 发自网易邮箱大师 在2016年02月05日 14:41 ，Tony Shao写道： 之前曾经写过很多篇（上百篇）文章都没有遇到的比较奇怪的一个问题，最近写的一篇文章无法更新，显示“正在提交您的请求……”然后就卡在这里不能动了。 如果将文章删掉一部分是可以发布的，但不确定是具体哪一部分。有时删掉前半段，或是后半段就可以了。文中（应该）没有任何敏感词汇。 — Reply to this email directly or view it on GitHub.

**Comment by ghosert** [comment]
修复了。原因：服务器上磁盘空间满了。
