### ISSUE TITLE
今天2016-02-05 下午 16:50 不能导出 pdf.

### ISSUE THREAD

**Issue by fuyb** [ghosert/cmd-editor#1132]
我的帐号是高级帐号。
今天2016-02-05 下午 16:50 不能导出 pdf.

**Comment by ghosert** [comment]
markdown原文发我一下 ghosert@gmail.com 发自网易邮箱大师 在2016年02月05日 16:55 ，fuyb写道： 我的帐号是高级帐号。 今天2016-02-05 下午 16:50 不能导出 pdf — Reply to this email directly or view it on GitHub.

**Comment by ghosert** [comment]
修复了。原因：服务器上磁盘空间满了
