### ISSUE TITLE
建议和看云合作一下

### ISSUE THREAD

**Issue by dotku** [ghosert/cmd-editor#1133]
我觉得看云没有作业部落好看，不过功能上比作业部落要好很多

**Comment by ghosert** [comment]
简单看了一下，应该底下用了 https://www.gitbook.com 的源码。编辑器本身的功能并没有 Cmd Markdown 强大，非原创的代码以后也很难增强，基于 gitbook 的产品层出不穷，每隔一段时间就可以看到一个。最困难的部分并非去全盘整合符合工程师思维的开源项目，而是把IT业界的理念通过技术手段一键式的提供给普通用户，这样才能在易用性，适用度上达到新的水准。

**Comment by dotku** [comment]
主要是他们收费，这边免费的... 就不知道能维持多久，感觉收费软件，用得安心点... 只是看到那边收费的还不如这边免费的好用，又觉得心痒痒...

**Comment by ghosert** [comment]
欢迎付费：https://www.zybuluo.com/payment
