### ISSUE TITLE
编辑栏和预览栏突然不同步了

### ISSUE THREAD

**Issue by wxytongxue** [ghosert/cmd-editor#1135]
> linux 版本
> 
> 前几天好好的，今天用着用着突然不同步了，只一边动，是怎么回事？

**Comment by ghosert** [comment]
因为有些语法用错了，试着删掉一些带 ''' 的段落。 发自网易邮箱大师 在2016年02月06日 14:07 ，王小猿同学写道： linux 版本 前几天好好的，今天用着用着突然不同步了，只一边动，是怎么回事？ — Reply to this email directly or view it on GitHub.
