### ISSUE TITLE
建议增加图片的复制粘贴功能

### ISSUE THREAD

**Issue by LumpyChen** [ghosert/cmd-editor#1138]
![tool-editor](https://www.zybuluo.com/static/img/toolbar-editor.png)
`Markdown`的图片引入方式在某些情况下还算方便
但是更多的情况下图片的引入是来自本地的
或者就是截图
想要填充`url`，发布
这个时候就很麻烦
如果可以直接复制粘贴和文本绑定
可以极大地提高效率

**Comment by terranc** [comment]
强烈支持，希望能直接粘贴图片以及拖转图片进来自动上传。包括能设置自己的七牛密钥什么的都可以的呀。

**Comment by ghosert** [comment]
可以直接拖拽，复制粘帖上传了：https://www.zybuluo.com/ghosert/note/378553
