### ISSUE TITLE
建议优化PDF中LaTeX和文字加粗的渲染效果

### ISSUE THREAD

**Issue by HackerWade** [ghosert/cmd-editor#1140]
相关环境：Win和Mac下均为最新版Chrome浏览器，使用Foxit浏览器和Chrome内置浏览器阅读PDF
1. LaTeX公式在PDF中字重过大，和周围文字很不协调。（Win和Mac平台）
   ![screen shot 2016-02-15 at 09 22 48](https://cloud.githubusercontent.com/assets/12229285/13037923/bdb90594-d3c5-11e5-9080-ed2b36dfc40c.png)
2. 加粗字体渲染时字重略大…怎么说呢…显得好蠢QAQ（已知Mac上存在）
   ![screen shot 2016-02-15 at 09 29 32](https://cloud.githubusercontent.com/assets/12229285/13037948/aae74dbc-d3c6-11e5-905a-176747f50c6c.png)

**Comment by ghosert** [comment]
这个和 PDF 阅读器有关，推荐使用官方的 Adobe Acrobat Reader

**Comment by HackerWade** [comment]
表示公式确实是好多了，但是加粗还是差强人意。
另：可否针对国内较常用的PDF阅读器进行优化呢？我不能保证每台电脑上都有Acrobat
这是使用Adobe Acrobat DC 的效果。
![screen shot 2016-02-15 at 09 46 43](https://cloud.githubusercontent.com/assets/12229285/13038107/22219566-d3c9-11e5-9452-a0d285f43b9d.png)

**Comment by ghosert** [comment]
粗体这个暂时没有别的方法了，对于特定字体字号的加粗就是这么重，每个人的感受不太一样。

**Comment by HackerWade** [comment]
…为什么样稿在同样环境下没有任何问题…

**Comment by ghosert** [comment]
是吗？你的 Markdown 原文是啥？

**Comment by ghosert** [comment]
试试自定义字体字号或者CSS：https://www.zybuluo.com/ghosert/note/378553
