### ISSUE TITLE
［TOC］导出目录有问题

### ISSUE THREAD

**Issue by 396640195** [ghosert/cmd-editor#115]
```
                                  安卓升级sdk使用文档说明

安卓升级sdk使用文档说明安卓升级sdk使用文档说明---导出的html，这里重复了标题
    第一步、准备依赖文件:
    第二步、添加所需权限
    第三步、添加服务Service
    第四步、使用sdk进行升级
        4.1 使用默认UI策略升级
        可选接口
```

目录结构首行应该显示：　目录　　而非重复的标题，总共出现了三次重复的。

**Comment by ghosert** [comment]
生成 [TOC] 的规则是根据标题  # 来的，注意不要多次出现即可。

**Comment by 396640195** [comment]
你好,能否提供在左边的目录结构, 那种排在顶端的,不好,或者提供下面这种方式的供用户自已选择吧.
一般正式做文档的,哪有采用目录放在顶端的, 你说重点是目录,还是内容?  重点当然是内容啦, 目录放左边才是对的啊,这样做出来的文档,也更专业些;

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年7月7日(星期一) 晚上7:56
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "川❤"396640195@qq.com; 
主题: Re: [cmd-editor] ［TOC］导出目录有问题 (#115)

生成 [TOC] 的规则是根据标题  # 来的，注意不要多次出现即可。

**Comment by ghosert** [comment]
目录还是隐藏起来比较好，很多用户 Markdown 用得不太对导致目录很难看，显示的放在左边反而会让文档很难看。

**Comment by 396640195** [comment]
大哥， 这个不是你说了算的。

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年7月7日(星期一) 晚上11:11
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "川❤"396640195@qq.com; 
主题: Re: [cmd-editor] ［TOC］导出目录有问题 (#115)

目录还是隐藏起来比较好，很多用户 Markdown 用得不太对导致目录很难看，显示的放在左边反而会让文档很难看。

**Comment by ghosert** [comment]
没办法，我还是得照顾大多数。。。

**Comment by 396640195** [comment]
大多数，你看下友盟，Bmob，做的文档，有没有放在顶部的？ 唉，个人用的话，那样做无所谓，想要做出一个比较专业，能够给公司用的，那种放在顶部的，不合适；

你说的大多数，只是你自已私下里这么想的，你有调查？你有看过别人的文档怎么做的？ 你还没搞清楚实际需求吧。。。改吧，至少我现在是为公司做产品，正好要用到。

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年7月7日(星期一) 晚上11:26
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "川❤"396640195@qq.com; 
主题: Re: [cmd-editor] ［TOC］导出目录有问题 (#115)

没办法，我还是得照顾大多数。。。

**Comment by ghosert** [comment]
你说的文档啥样子，给我地址我看看。

**Comment by 396640195** [comment]
我都发过两次图片你们了...
再发一次吧,根据我发的文字信息,你百度一下也知道的....

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年7月7日(星期一) 晚上11:43
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "川❤"396640195@qq.com; 
主题: Re: [cmd-editor] ［TOC］导出目录有问题 (#115)

你说的文档啥样子，给我地址我看看。

**Comment by ghosert** [comment]
没百度到。

**Comment by ghosert** [comment]
图呢？还没看到
