### ISSUE TITLE
Ubuntu 下客户端等宽字体问题

### ISSUE THREAD

**Issue by wafer-li** [ghosert/cmd-editor#1150]
Ubuntu 15.10

客户端的等宽字体渲染很难看， Chrome 则没有这种问题。

这个是 Chrome 的
![selection_001](https://cloud.githubusercontent.com/assets/12459199/13178438/426063f6-d762-11e5-9875-b307359f4854.png)

这个是客户端的
![selection_002](https://cloud.githubusercontent.com/assets/12459199/13178439/426643de-d762-11e5-9f3a-40da7c708f3f.png)

请问有什么方法可以解决吗？

**Comment by ghosert** [comment]
字体字号都可以更改了：https://www.zybuluo.com/ghosert/note/378553
