### ISSUE TITLE
客户端安装后出现乱码问题

### ISSUE THREAD

**Issue by liyi139** [ghosert/cmd-editor#1154]
![image](https://cloud.githubusercontent.com/assets/13481088/13239466/60df16be-da15-11e5-931b-8c37b749f591.png)

**Comment by ghosert** [comment]
按如图所示设置：替代 Windows 显示语言

![catch](https://cloud.githubusercontent.com/assets/236040/18246399/116997ee-739e-11e6-86cd-04a9ba3bf850.jpg)
