### ISSUE TITLE
请问能不能考虑支持改变文字颜色？ 

### ISSUE THREAD

**Issue by rainocean** [ghosert/cmd-editor#1155]

**Comment by rainocean** [comment]
即使是高级功能也可以  VIP功能也好啊  
有时候有些需求必须用到彩色字体才能表示  又不想放弃cmdmarkdown  非常困扰

**Comment by ghosert** [comment]
暂时可以自己写html然后内嵌css 发自网易邮箱大师

**Comment by ghosert** [comment]
已更新，可以自定义CSS了：fhttps://www.zybuluo.com/ghosert/note/378553
