### ISSUE TITLE
生成的pdf最后多了一张空白页

### ISSUE THREAD

**Issue by lujb** [ghosert/cmd-editor#1158]
通过Mac客户端生成的pdf最后多了一张空白页，预期是不希望有的（编辑器预览是没有最后的空白的）。

**Comment by ghosert** [comment]
把markdown原文发我邮箱 support@zybuluo.com

**Comment by ghosert** [comment]
我觉得问题不大，可能是因为正好有一两个空行被挤到最后一页了。
