### ISSUE TITLE
印象笔记显示Bug

### ISSUE THREAD

**Issue by kangnux** [ghosert/cmd-editor#1161]
印象笔记**网页版，PC版，手机版**显示不一致，如下段代码。

```
- [ ] 支持以 PDF 格式导出文稿
- [ ] 改进 Cmd 渲染算法，使用局部渲染技术提高渲染效率
- [x] 新增 Todo 列表功能


### 6. 管理工具栏

为了便于管理您的文稿，在 **预览区** 的顶部放置了如下所示的 **管理工具栏**：

![tool-manager](https://www.zybuluo.com/static/img/toolbar-manager.jpg)

通过管理工具栏可以：

<i class="icon-share"></i> 发布：将当前的文稿生成固定链接，在网络上发布，分享
<i class="icon-file"></i> 新建：开始撰写一篇新的文稿
<i class="icon-trash"></i> 删除：删除当前的文稿
<i class="icon-cloud"></i> 导出：将当前的文稿转化为 Markdown 文本或者 Html 格式，并导出到本地
<i class="icon-reorder"></i> 列表：所有新增和过往的文稿都可以在这里查看、操作
<i class="icon-pencil"></i> 模式：切换 普通/Vim/Emacs 编辑模式
```
## 正常显示如下：
- [ ] 支持以 PDF 格式导出文稿
- [ ] 改进 Cmd 渲染算法，使用局部渲染技术提高渲染效率
- [x] 新增 Todo 列表功能

![default](https://cloud.githubusercontent.com/assets/14342048/13143382/ce21fdf0-d686-11e5-9c5f-bd9ec4d839ae.JPG)
## 在印象笔记手机端（ios）和PC端（Windows）显示是下面这样的：

![windows](https://cloud.githubusercontent.com/assets/14342048/13143394/eeda26a8-d686-11e5-9650-eea5aa568f17.JPG)
![default](https://cloud.githubusercontent.com/assets/14342048/13143402/049ca95c-d687-11e5-8b06-cd0037e54c46.JPG)

有时间的话，最好能对应一下。

**Comment by ghosert** [comment]
印象笔记的网页端是好的。。。

**Comment by ghosert** [comment]
有空再看看。

**Comment by kangnux** [comment]
嗯 最好还是稍稍看一下吧，毕竟网页端不是经常用嘛

**Comment by ghosert** [comment]
已修复。
