### ISSUE TITLE
发布分享出去的链接，能不能修改成只看到当前的这份？

### ISSUE THREAD

**Issue by tears008** [ghosert/cmd-editor#1168]
发现分享出去之后，可以通过右侧的菜单看到此用户分享出去的所有文档。
因为不同的文档需要开放给不同的人，但是又不想设置密码。
这个地方能不能改善一下？

**Comment by lishubing** [comment]
同意，我感觉这个功能应该去掉，分享设置密码本来就是为了给指定的用户看，没必要展示其他的用户文章。

**Comment by ghosert** [comment]
好，知道了。

**Comment by liyuj** [comment]
这个建议我觉得合理，现在读者能看到作者所有的文档资料

**Comment by ghosert** [comment]
现在改为只能看到作者公开的文稿，所以设置密码的其它文稿都不可见了。
