### ISSUE TITLE
Foxmail收不到邮件，注册和密码找回都不行。

### ISSUE THREAD

**Issue by yanzhenjie** [ghosert/cmd-editor#1179]
我邮箱是smallajax@foxmail.com。

**Comment by ghosert** [comment]
可以前往用户设置里换一个邮箱。

**Comment by yanzhenjie** [comment]
我是注册时收不到邮件，进去不了用户设置，必须要换一个邮箱注册吗？

**Comment by ghosert** [comment]
没收到邮件也可以用用户名登录的，不一定要用邮箱登录。用户名登录以后，就可以进用户设置了。把鼠标移到工具栏上有你用户名的位置即可看见。

**Comment by yanzhenjie** [comment]
很长时间没成功，就把用户名忘记了，刚才试着登录了几次没成功，有其他办法吗？你们软件非常好用我超级喜欢，就是不登陆不太方便。

**Comment by ghosert** [comment]
用户名应该是这个：Y0LANDA 用来登录就好了。

**Comment by yanzhenjie** [comment]
好的，成功了，非常感谢，祝生活愉快！
