### ISSUE TITLE
登录提示验证码错误

### ISSUE THREAD

**Issue by hzxie** [ghosert/cmd-editor#1183]
![screen shot 2016-03-08 at 22 36 09](https://cloud.githubusercontent.com/assets/1730504/13604756/35fab0c8-e57f-11e5-8045-ff0d726eb942.png)

**Comment by ghosert** [comment]
注意大小写

**Comment by hzxie** [comment]
大写一样不好使~
你测试了吗? 你Close Issue跟玩似的.

**Comment by ghosert** [comment]
根据你的图应该是vAWK，你写了 vawk，再试下，关了我还是会持续回复的。

**Comment by Yifei0727** [comment]
我觉得吧，最后还是改成不区分大小写的好点。 大多数都是这样的。

**Comment by hzxie** [comment]
艾玛~ 我头一回听说验证码还严格区分大小写的.
而且`v`和`V`有区别吗?

**Comment by ghosert** [comment]
你那个截图里有“区分大小写”的字样。

**Comment by hzxie** [comment]
哦~~ 但是用户体验不佳呢~
还是建议改进一下。
毕竟用户不会仔细看那行字的。 :)
