### ISSUE TITLE
可否添加调整字体大小功能

### ISSUE THREAD

**Issue by 1-WEEK** [ghosert/cmd-editor#1186]
系统：win10 64位
在高分屏下字有点小

**Comment by Crepusculo** [comment]
+1 , 希望能像Wiz和Chrome这样支持 'Ctrl' + '+'/'-' 或 'Ctrl' + 鼠标滚轮调整大小的方便功能

**Comment by neviii** [comment]
+1 mac下 感觉字体有些大，想要缩减一下非常困难

**Comment by ghosert** [comment]
字体字号都可以更改了：https://www.zybuluo.com/ghosert/note/378553
