### ISSUE TITLE
导出的PDF末尾有一空白页

### ISSUE THREAD

**Issue by lxyzk** [ghosert/cmd-editor#1189]
导出的PDF文件末尾总是有个空白页。

**Comment by ghosert** [comment]
我觉得问题不大，可能是因为正好有一两个空行被挤到最后一页了。

**Comment by bugs2** [comment]
我也正想提这个问题，应该是bug，我删除了很多行，明显无需换页，仍然会出现空白页。
环境是OS X 10.11.3。导出带样式的pdf，再从safari保存到本地。
