### ISSUE TITLE
普通模式光标问题

### ISSUE THREAD

**Issue by hk20088** [ghosert/cmd-editor#1191]
亲，为啥感觉普通模式下的光标在字体或符号的中间，而不是后面？

**Comment by ghosert** [comment]
浏览器版本，操作系统是啥，浏览器系统里最好有等宽字体。

**Comment by hk20088** [comment]
Win7 64位系统， 用的是客户端。另外在chrome浏览器上也会出现此问题。具体现象如图：http://pan.baidu.com/s/1c1qtE3A

**Comment by ghosert** [comment]
使用等宽字体，看下这个链接修改字体：https://www.zybuluo.com/ghosert/note/378553

**Comment by ghosert** [comment]
等宽字体列表：https://zh.wikipedia.org/zh/%E7%AD%89%E5%AE%BD%E5%AD%97%E4%BD%93
