### ISSUE TITLE
中英文切换问题

### ISSUE THREAD

**Issue by kivihub** [ghosert/cmd-editor#1193]
Vim中，从普通模式变成插入模式的时候，如果要输入中文，需要切换中英文。

期待改进：
在Vim中，能分别记忆普通模式和插入模式下的中英文输入模式。要不然，老切换很费劲。

**Comment by ghosert** [comment]
在中文模式下按一下 shift 键再切换就好了，这个问题 gvim 本尊也没处理。按一下 shift 代价也不大。
