### ISSUE TITLE
【建议】：  已经导出到印象笔记的文章，修改后自动保存时，也会自动同步到印象笔记中

### ISSUE THREAD

**Issue by waterwoodwind** [ghosert/cmd-editor#1194]
如题，这个功能，类似于马克飞象了，相当于可以用印象笔记来存储文章
每次写完了，都要点一下导出到印象笔记，也是蛮麻烦了

**Comment by ghosert** [comment]
印象笔记的 api 很慢，实时保存会很慢，Cmd Markdown 的服务器很快，所以实时保存都是发生在 Cmd 的服务器。马克飞象我记得也是要手动点保存的。

**Comment by waterwoodwind** [comment]
哦，这样啊，我暂时弄个按键脚本，来自动点导出到印象笔记

**Comment by crazelee** [comment]
导入到印象笔记能否指定笔记本
