### ISSUE TITLE
扩展和插件

### ISSUE THREAD

**Issue by guevara** [ghosert/cmd-editor#12]
请问作者能提供`Chrome`插件和`Firefox`扩展吗？最好是离线应用，可以同步到云端

**Comment by ghosert** [comment]
我也有此想法，不过想做成客户端的形式，排入议程。

**Comment by svcvit** [comment]
或者sublime的插件。

**Comment by illuz** [comment]
希望能是插件或扩展形式的，因为这样就能在Linux下离线使用了.
如果是客户端形式希望能照顾下Linux用户，出个Linux端...

**Comment by ghosert** [comment]
客户端已出，插件就不出了。
