### ISSUE TITLE
window客户端不可用（32位）

### ISSUE THREAD

**Issue by p2227** [ghosert/cmd-editor#1200]
运行一篇空白。

我试着把nw的toolbar打开，运行，提示说

```
(program):1 Uncaught ReferenceError: require is not defined
```

**Comment by ghosert** [comment]
试一下六十四位？

**Comment by p2227** [comment]
> 试一下六十四位？

换了一台64位的机器后是可以的，不过有点慢

**Comment by p2227** [comment]
处理完了？需要重新下载吗？

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下看看。

**Comment by p2227** [comment]
ok了
