### ISSUE TITLE
当前版本在360杀毒中检测有病毒

### ISSUE THREAD

**Issue by cskfygit** [ghosert/cmd-editor#1204]
http://static.zybuluo.com/cmd_markdown_win64.zip
windows 64位 CMD MarkDown解开压缩包后，主文件即自动被360杀毒识别为病毒。
请查看代码中是否有问题代码。如果没有的话请与杀毒软件厂商沟通。

**Comment by ghosert** [comment]
代码是在LINUX平台编译的，应该是厂商误报。或者被你机器上的其他文件感染了。可以重新下载。
