### ISSUE TITLE
web版: 保存文稿遇到问题

### ISSUE THREAD

**Issue by kedgeree** [ghosert/cmd-editor#1205]
![default](https://cloud.githubusercontent.com/assets/4084290/13834501/833eeb22-ec2a-11e5-8ecf-65e617013522.png)
会无限弹出上面的提示框。怎么解决呢？

我打开了一个本地的md文件后出现了这个情况。需要提供什么东西来定位问题么?

**Comment by ghosert** [comment]
暂时先把本地MD的内容拷贝进编辑器吧。不在现场很难甄别问题。

**Comment by ghosert** [comment]
一般是因为你开了两个页面，其中一个退出登录了，另一个就会这样。
