### ISSUE TITLE
不能登录 2.0 win 64位，

### ISSUE THREAD

**Issue by forever4313** [ghosert/cmd-editor#1206]
登录不进去了，登录窗口，输入密码用户名以后，进入主界面，依旧是未登录

曾经的操作，仅供参考，
1正常打开应用，
2.点击登录
3 输入用户名密码，默认勾选记住登录状态，登录
4，登录成功，
5，退出，
6 重新进入登录页面，输入用户名密码，去掉勾选记住登录状态，登录
7，跳转主页面，但是显示未登录。

现在是客户端完全不能用，将程序文件夹删除，重新下载新的，也是没办法登录，点击登录，只是在刷新页面而已，不会出现登录窗口了。。。。

**Comment by ghosert** [comment]
你是哪个操作系统

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下看看。

**Comment by forever4313** [comment]
解决，
windows系统，删除
C:\Users\ws007\AppData\Local\Cmd Markdown 问题解决~~~（ws007 为我的本地计算机用户名）
