### ISSUE TITLE
白屏，win64位系统

### ISSUE THREAD

**Issue by zengcanxiang** [ghosert/cmd-editor#1209]
![qq 20160317113134](https://cloud.githubusercontent.com/assets/16033497/13835514/9d62e6d0-ec33-11e5-9a70-0502d77b95e2.png)
不知道为什么打不开了，重新下载也打不开

**Comment by forever4313** [comment]
我是登录不能。。。。。感觉最近发布的这个版本不科学了

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下看看。

**Comment by zengcanxiang** [comment]
好的，我去试下
