### ISSUE TITLE
无法发布更新链接

### ISSUE THREAD

**Issue by jiyiren** [ghosert/cmd-editor#1210]
# 无法发布更新链接了，一直显示正在提交中....

![图片](http://7xknpe.com1.z0.glb.clouddn.com/ddddd.png)

图片地址：[http://7xknpe.com1.z0.glb.clouddn.com/ddddd.png](http://7xknpe.com1.z0.glb.clouddn.com/ddddd.png)

**Comment by ghosert** [comment]
修好了。

**Comment by ghosert** [comment]
磁盘空间满了，清理了一下好了。
