### ISSUE TITLE
vim里用esc键会产生冲突

### ISSUE THREAD

**Issue by cbsheng** [ghosert/cmd-editor#122]
使用vim模式的时候，用esc切换模式会产生冲突

**Comment by ghosert** [comment]
把浏览器的 Vim 插件关一下，可以设置对 zybuluo.com 禁用插件，就好了。还有系统给你发过一个确认邮箱的邮件，你的163邮箱好像直接退信了，注册的时候邮箱填对了吗？是不是有反垃圾邮件设置，可以看一看设置和垃圾箱。如果需要我再重发一封给你。

**Comment by cbsheng** [comment]
禁用了插件就没事了，不过对ctrl+v好像不是可视模式，直接跳行了。我的是mac。邮件在垃圾箱也找不到，麻烦你重发一封吧谢谢

**Comment by ghosert** [comment]
*****612357 是这个邮箱吗？或者微博上私信我确认一下。@ghosert

**Comment by ghosert** [comment]
又退信了，说找不到这个邮箱。
