### ISSUE TITLE
流程图溢屏问题

### ISSUE THREAD

**Issue by ghost** [ghosert/cmd-editor#1220]
当流程图比较宽的时候，在预览模式下下方有滚动条可以滚动显示，可是阅读模式下就会溢屏，部分看不到，到处带样式的HTML也看不到，但是导出pdf可以看到，希望能解决这个问题。

**Comment by mygu** [comment]
是的，我也遇到相同的问题

**Comment by ghosert** [comment]
flow 问题已上线：https://www.zybuluo.com/ghosert/note/378553 点击 flow 可以全屏看大图了。
