### ISSUE TITLE
Chrome 48 下js脚本错误

### ISSUE THREAD

**Issue by gdh1995** [ghosert/cmd-editor#1221]
Win8.1 / 10 x64， Chrome 48 x32下有两个错误，然后渲染失败。IE 11也这样。

7a70106e.layout.lib.min.js:3 Uncaught TypeError: RegExp.prototype.sticky getter called on non-RegExp object

04853a22.mdeditor.min.js:4 Uncaught TypeError: Cannot read property 'renderToc' of undefined

我只用了：*列表、#标题 和 ```SQL，删得只剩一行的时候也错。

**Comment by ghosert** [comment]
看看这篇文章好吗？

https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown

我这里没看到任何错误。看看网络状况是不是好？

**Comment by gdh1995** [comment]
确认了在Chrome下是 #enable-javascript-harmony 的问题。Chrome 48.0.2564.109 (正式版本) （32 位）。去chrome://flags关掉这个选项就好了。

这种报错“RegExp.prototype.sticky getter called”，比较像是JS 新版规范和旧版本有冲突造成的，比如旧版本某个错误但被做了work-around的用法 在新版里被直接throw error了。

我觉得这个问题不难改。大概是一个月前还是两个月前的时候我开着enable-js-harmony也能用Cmd Markdown，所以这次应该只是个别库不够兼容。（抱歉两个月前我chrome的版本不记得了，大概是45/47吧）

**Comment by ghosert** [comment]
你这个选项是不是之前被意外打开了？我最新 CHROME 49 的版本里默认是关闭的。

**Comment by gdh1995** [comment]
我这不是意外打开啊，我是觉得这功能有用，就自己开的，开了一两年了。

CmdMarkdown本来也是没问题的，也就最近才这么错，改改呗
