### ISSUE TITLE
欲充会员，有几个问题想先咨询一下，望回答，谢谢！

### ISSUE THREAD

**Issue by mopsite** [ghosert/cmd-editor#1224]
喜欢，很喜欢，想充成会员，但是充值之前有几个问题，能不能回复我一下。
1.使用cmd markdown有容量大小吗？具体是多大？
2.会出手机端的应用吗？只用于阅读也行。
3.为什么我创建了todo，但是没法勾选？只能通过在编辑页面增加和删除x来实现打钩。在你写的语法教程里，也不能勾选。但是试了一下马克飞象，可以直接勾选复选框的。

**Comment by ghosert** [comment]
1. 没有容量限制
2. 手机直接访问发布过的文稿可以直接阅读，也可以导出到印象笔记以后在印象笔记的手机端阅读。
3. TODO 当时就设计为从编辑区勾画，这个和所有其它渲染格式都保持一致。永远是从编辑区渲染预览区，如果你同时在编辑文字这样反而高效，不用来回切换鼠标和键盘。马象的勾选也并不能反向影响编辑区的内容，刷新页面以后就没有了。
