### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by papdpcpd** [ghosert/cmd-editor#1225]
1. 增加社交功能，交流分享笔记。
   我学Python的，自己写了很多笔记，同时我希望搜藏更过高质量的笔记。
   我觉得cmd-editor可以往博客方向发展，能实现基本的评论、收藏（能看到源.md文件，自己直接编辑）、好友、全局搜索就更加棒了。

2.手机客户端

3.更强功能和自定义设置，就如一些IDE那样，自定义字体..代码高亮.插件.....N多功能啊，我觉得很多能借用过来，总得来说自定义设置太薄弱了。

可以扩展优化提高的地方还有很多..希望增加更多能吸引码农的功能。
已经买会员了，渲染出HTML，直接提取<div>放到博客上，非常的方便啊！这个功能很赞！

继续努力，期待下一版更新！

**Comment by ghosert** [comment]
谢谢建议，继续努力。
