### ISSUE TITLE
Chrome浏览器，中英文混输、中文和数字混输时，编辑区显示异常。

### ISSUE THREAD

**Issue by lishujia** [ghosert/cmd-editor#1239]
![_20160330214417](https://cloud.githubusercontent.com/assets/3197489/14144068/ea2d936a-f6c0-11e5-955f-8b06c8b12717.png)

**Comment by ghosert** [comment]
操作系统是什么？

**Comment by ghosert** [comment]
最好浏览器的字体是等宽字体。

**Comment by ghosert** [comment]
尝试使用CMD MARKDOWN 内置的字体修改功能，选用一种等宽字体试试：https://www.zybuluo.com/ghosert/note/378553
