### ISSUE TITLE
列表为超链时候

### ISSUE THREAD

**Issue by niushuai** [ghosert/cmd-editor#124]
当列表元素为链接的时候，会出现格式错误。
- [aaa](www.baidu.com)
- [bbb](www.google.com)

这样会出现格式错误。

**Comment by ghosert** [comment]
我试了一下没问题，能借个图上来吗？

**Comment by ghosert** [comment]
噢，我找到了

**Comment by ghosert** [comment]
这个段落前后加空行即可。
