### ISSUE TITLE
我不能打开客户端和网页版了

### ISSUE THREAD

**Issue by zhongzilu** [ghosert/cmd-editor#1241]
在我编辑的时候，突然弹出一个弹出框提示我手动进行合并，我点击了【使用本地】按钮，之后就看到网页上或者客户端的顶部一直在重复显示已合并、已保存，于是我就手动保存了一份，然后关闭了浏览器或客户端，之后再打开浏览器或客户端，就一直显示白屏，根本无法编辑，请查清是什么问题，谢谢

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下客户端看看。
