### ISSUE TITLE
可否提供emmet的能力?

### ISSUE THREAD

**Issue by richaction** [ghosert/cmd-editor#125]
可否提供emmet的能力?

**Comment by ghosert** [comment]
请详细说说。

**Comment by richaction** [comment]
我们知道markdown支持html的语法，emmet对于写html有着优化的作用。便于HTML书写。当然也可以延伸对于markdown本身的书写。

**Comment by ghosert** [comment]
我有时间去查查，不过貌似越加越多了。。。有点小众

**Comment by richaction** [comment]
功能总是需要不断完善的。可以分为基础功能和高级功能，基础功能满足小白用户，高级功能满足高端用户。这个方向总是不会错的。另外可以参考这个markdown编辑网站的始祖，现在已经出了beta4了，可以有选择地借鉴。https://stackedit-beta.herokuapp.com/

**Comment by ghosert** [comment]
它的 beta4 我试过， chrome 下 输入法打中文就挂了，老外毕竟对中文的测试有限。总体来说它这个版本在试图自己重头写一个编辑器，精神可嘉，有些功能例如 vim/emacs 这种小众，但是重要的功能，恐怕很难列入计划了。

emmet 我会再看看，实际上要做的事情实在太多，精力时间有限，目前照顾大多数为主。

**Comment by richaction** [comment]
嗯，楼主后期不妨考虑开源，既然选用了github，天然开源属性。人多精力也多，可以更好的迭代。

**Comment by ghosert** [comment]
我又看了看 它的 sequence flow 确实都是以后可以借鉴的。真心不错。

**Comment by richaction** [comment]
嗯，这两个确实有亮点。

**Comment by ghosert** [comment]
目前 Cmd Markdown 还不完全是 StackEdit 的拷贝猫，Cmd Markdown 只是作业部落旗下的一款重要的产品，会和其它服务整合起来。当然也可以单独出来。

至于开源，很多人问过我，我目前无法回答这个问题，因为 StackEdit 应该是 StackOverflow 旗下的项目，它的开发者应该是全职拿薪水做的开发，我的情况不太一样。

容我思量，目前还不太方便。

**Comment by richaction** [comment]
嗯，理解楼主。

**Comment by ghosert** [comment]
暂时关一下。
