### ISSUE TITLE
再也打不开文件了

### ISSUE THREAD

**Issue by sunlc210** [ghosert/cmd-editor#1251]
今天我着去打开去打开一个本地MD文件，但是没有成功，现在一直hang在那里

**Comment by sunlc210** [comment]
https://www.zybuluo.com/mdeditor#337195

**Comment by ghosert** [comment]
可否先尝试复制粘帖那个文件的内容到编辑器里。

**Comment by sunlc210** [comment]
1. 整个界面都没有任何可以操作的地方

2 . 我试着拉一个以前的md文件直接进去，没有收到任何效果

**Comment by ghosert** [comment]
好了吗？上次IM上解决过了？
