### ISSUE TITLE
表格有个bug

### ISSUE THREAD

**Issue by LinkedDestiny** [ghosert/cmd-editor#1252]
| 项目 | 价格 | 数量 |
| --- | --: | :-: |
| 计算机 | $1600 | 5 |
| 手机 | $12 | 12 |
| 管线 | $1 | 234 |

当表格中带有$符号，第一行表格解析会出错

**Comment by LinkedDestiny** [comment]
![39b50ae2-e145-4702-904a-515bbd8c4344](https://cloud.githubusercontent.com/assets/5689061/14346883/de83918c-fce6-11e5-8a13-9acbdd4159d8.png)

**Comment by LinkedDestiny** [comment]
![39b50ae2-e145-4702-904a-515bbd8c4344](https://cloud.githubusercontent.com/assets/5689061/14346913/fae33184-fce6-11e5-84e0-912190e300a1.png)

以上是图片

**Comment by ghosert** [comment]
把 $ 转义一下，写成 \$， 因为 $ 在作业部落是公式的标志符。
