### ISSUE TITLE
文章太难管理了

### ISSUE THREAD

**Issue by Teraflopst** [ghosert/cmd-editor#1258]
文章太难管理了，写了的东西很难找出来。

**Comment by cenxun** [comment]
是的，文章内有支持 <标签>，按理来说，label1 label2 应该支持索引的 ，

```
标签（空格分隔）： label1 label2
```

最好是能够支持 文件夹管理。

**Comment by wissne** [comment]
只可以搜索标题，找到个临时可用方案，把标签写到标题里面

**Comment by Teraflopst** [comment]
我想说的是，根据标签来管理文章基本是不可能的，标签是根据文章内容来打的，打多少还不确定，同一篇文章不同时间你可能会有两种不同的标签方案，也别说多级标签，标签很快就会越来越多，有的根本不好分类，乱七八糟，没有树状文件夹的话，想找到一遍文章实在太难了。至少提供一个文章列表吧。

**Comment by ghosert** [comment]
在搜索框直接打 \* 就是罗列所有文章列表。鼓励用搜索标题，这样最快，否则即使有层次很深的树状文件夹，藏的深的话，一样挺难找的，或许更难找。
