### ISSUE TITLE
边编辑，边保存，卡

### ISSUE THREAD

**Issue by xiaotinglei** [ghosert/cmd-editor#126]
保存太频繁，便输入文字边保存，导致输入不流畅，太卡。
能否实现既能保存文档，又不让人感觉卡

**Comment by xiaotinglei** [comment]
简书http://jianshu.io/ 也是边编辑，边保存，但感觉流畅，希望改进

**Comment by ghosert** [comment]
你人在国外吗？
2014-5-20 上午1:50于 "xiaotinglei" notifications@github.com写道：

**Comment by xiaotinglei** [comment]
我现在在美国

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年5月20日(星期二) 上午6:22
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "xiaotinglei"lxt18717865134@gmail.com; 
主题: Re: [cmd-editor] 边编辑，边保存，卡 (#126)

你人在国外吗？ 
 2014-5-20 上午1:50于 "xiaotinglei" notifications@github.com写道：

**Comment by ghosert** [comment]
对，那肯定是海外网速的问题，一个要投入带宽，另一个今后通过离线版解决。另外cmd 需要做大量额外渲染，比简书复杂许多。具体实时保存的做法并无区别。
2014-5-20 上午6:23于 "xiaotinglei" notifications@github.com写道：

**Comment by xiaotinglei** [comment]
这个不是大问题。

其他的问题才是关键。

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年5月20日(星期二) 上午6:31
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "xiaotinglei"lxt18717865134@gmail.com; 
主题: Re: [cmd-editor] 边编辑，边保存，卡 (#126)

对，那肯定是海外网速的问题，一个要投入带宽，另一个今后通过离线版解决。另外cmd 需要做大量额外渲染，比简书复杂许多。具体实时保存的做法并无区别。 
 2014-5-20 上午6:23于 "xiaotinglei" notifications@github.com写道：

**Comment by ghosert** [comment]
你另外提的问题？
2014-5-20 上午6:35于 "xiaotinglei" notifications@github.com写道：

**Comment by xiaotinglei** [comment]
参考网址：
http://www.sciencedirect.com/
https://www.sharelatex.com/project
https://www.authorea.com/users/6610

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年5月20日(星期二) 上午6:36
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "xiaotinglei"lxt18717865134@gmail.com; 
主题: Re: [cmd-editor] 边编辑，边保存，卡 (#126)

你另外提的问题？ 
 2014-5-20 上午6:35于 "xiaotinglei" notifications@github.com写道：

**Comment by ghosert** [comment]
和简书比较的话，你看看编辑的文字量是否一样，还有浏览器是否是chrome。谢谢，我这里因为网速的问题不太好重现。
2014-5-20 上午6:35于 "xiaotinglei" notifications@github.com写道：
