### ISSUE TITLE
当有多个文档需要编写的时候切换不方便

### ISSUE THREAD

**Issue by lixi-zhou** [ghosert/cmd-editor#1263]
当我有多个文档要编写的时候,切换过来切换过去很不方便,希望作者可以像Sublime,Notepad++一样加个文档的标签在顶部或者旁边,这样切换起来就方便些了.
比如这样
![fig](http://ww4.sinaimg.cn/large/005TbPZpjw1f2w0stlb2fj30ba03e0ta.jpg)

**Comment by ghosert** [comment]
暂时可以用浏览器的多 tab，客户端暂时确实没有。
