### ISSUE TITLE
光标定位错误

### ISSUE THREAD

**Issue by origin2007** [ghosert/cmd-editor#1264]
Web版本，Arch Linux 操作系统，Firefox最新版。

不论是中文还是英文，每行的光标定位随着输入的字符数目的增加而误差增大。如果要修改的化很难定位到需要修改的地方，非常不方便。

**Comment by ghosert** [comment]
这个和字体有关，首先看看FIREFOX是不是用的等宽字体，还有系统里有没有安装等宽字体。其次再看看CHROME有没有这个问题。

**Comment by origin2007** [comment]
调成了等宽字体问题也依然存在，另外在Chrome中也有这种问题。同样的浏览器使用简书里是没有这个问题的。

**Comment by origin2007** [comment]
我发现当使用“轻量编辑器”的时候就没这个问题了。
