### ISSUE TITLE
有时客户端和用浏览器都打不开

### ISSUE THREAD

**Issue by smilesometimes** [ghosert/cmd-editor#1268]
- 环境：win7 chrome
- windows客户端打不开，在chrome浏览器**https://www.zybuluo.com/mdeditor**网址打不开
-  换成ie浏览器，输入网址会要求重新登陆，登陆后用ie可以正常使用。windows客户端和chrome浏览器
  还是不能使用。

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下看看。

**Comment by ghosert** [comment]
还是不行的话，加我微信联系一下：ghosert

**Comment by ghosert** [comment]
题主说已经好了，那就关了。
