### ISSUE TITLE
编辑框可以显示行号 以及其它

### ISSUE THREAD

**Issue by huache** [ghosert/cmd-editor#1271]
今天试用了一下  Cmd Markdown 编辑器的 Vim 模式，真的是非常惊喜！常用的 Vim 快捷键都支持了，甚至连 列编辑、折叠、光标居中、书签 等等 这些统统都支持，一时间竟让我产生了就在用 Vim 的错觉，一看左边没有显示行号，果断输入：
`: set nu`
呃，于是得到提示：
`Error: Unknown option: nu`

不知作者是否可以加上行号显示可选呢，用 Vim 的时候，行号可以帮助快速移动。
还有，我发现虽然支持 `/` 查找 和 `s///` 替换（真的好强大！），但没有历史记录，略微有些遗憾，不过已有的这些已经远远超出我的预期了，对作者 JS 能力佩服得五体投地！

嗯，上面两个算比较小众的需求，最多只是锦上添花，无关紧要。

**真正强烈建议作者能够提供的是，外部域名绑定的功能，或者提供某种简单的方式，让用户能够把文章发布到自己的站点、博客上，付费也是完全可以接受的，希望作者能考虑一下。**

_PS：忽然想起来，有没有可能添加一个 编辑框 和 预览框 换位的设置呢，可以让用户选择在左边编辑右边预览，还是右边编辑左边预览，甚至奇葩一点的上下结构。。。嗯，我也就是这么一说。。。_

**Comment by ghosert** [comment]
行号我下次更新加，编辑区和预览区左右互换可以点击 预览区 右上角 工具栏下方一排透明按钮的第二个，或者使用快捷键 ctrl + alt + x

域名绑定要过一阵子了，暂时先导出 HTML 然后放到你站上好了。

**Comment by huache** [comment]
我刚发现 编辑框 和 预览框 原来可以互换，于是想跑来把 issue 里的 PS 给去掉。没想到作者这么就快回复了，这响应速度必须给个赞！
今天我试了好些个 Markdown 编辑器，在线的、本地的，甚至支持预览的 Vim 插件， 可以负责任地讲， Cmd Markdown 绝对是其中最优秀的，没有之一。作者加油，期待能够早日推出域名绑定！

**Comment by ghosert** [comment]
行号可以了：https://www.zybuluo.com/ghosert/note/378553#6-可以折叠的编辑器行号
