### ISSUE TITLE
阅读模式下的英文字体实在不能忍受！！

### ISSUE THREAD

**Issue by dazhitu** [ghosert/cmd-editor#1273]
编辑模式下的英文字体看起来特别舒服，与中文很容易区别开来，但是！！阅读模式下的英文和中文应该都是微软雅黑字体是么？！非常的中规中矩、字正腔圆，一点也没有代码的感觉，每次看到阅读模式下的代码都特别扭…………太特么丑了好么，处女座完全无法忍受好么！！

So，有个请求，要么，增加英文字体的可选项，要么，就设置一种符号，可以将文字中夹杂的代码块进行标识出来………………拜托了好么……

**Comment by ghosert** [comment]
增加了自定义字体的功能：https://www.zybuluo.com/ghosert/note/378553
