### ISSUE TITLE
图片不能上传显示

### ISSUE THREAD

**Issue by JerryGitHubAccount** [ghosert/cmd-editor#1277]
现在版本，只有高级会员才能进行图片的显示吗？这非常影响用户的使用(起码我现在是这样，不知道其他人)。对我而言，没有图片附件上传，文章里面只能纯描述，而markdown本身就有这个功能。非常建议是否可以让普通用户有这个权限，那样肯定用户更喜欢

**Comment by pwh0996** [comment]
付点钱呗 也不是很贵，作者也不容易

**Comment by ghosert** [comment]
图片上传用了七牛云存储，是需要向他们支付费用的，没有收费负担不起。你也可以找其它图床，先上传到其它地方再在 CMD 里引用图片链接。当然直接用上传最省力。
