### ISSUE TITLE
vim模式下RE，不支持backreference

### ISSUE THREAD

**Issue by codeshold** [ghosert/cmd-editor#1279]
你好
因为cmdmarkdown的产品能很好的结合markdown和vim，所以我购买了会员，但刚用不久就发现，vim模式substitute中正则表达式匹配不支持回溯引用

：s/^(\d)/### \1/g  XXXX

作为一名vim使用者，这是很难接受的，希望能在下一个版本中能完整的支持vim中RE匹配。

谢谢！

**Comment by ghosert** [comment]
其实已经支持了大多数VIM功能，一些不是非常常用的功能也不可能百分百完全支持。多多体谅。

**Comment by codeshold** [comment]
这个其实要看您产品的定位用户是哪些了，注册会员完全是因为支持vim模式，其实像一些set num显示行号的功能也没有，回溯引用途太广泛了，替换修改很方便，一个喜欢用vim的人，估计不怎么会忍受的～～最后， 如果确实不会添加相应功能的话，我也只能放弃这个了工具了～～   来自我的华为手机-------- 原始邮件 --------主题：Re: [ghosert/cmd-editor] vim模式下RE，不支持backreference (#1279)发件人：Jay Zhang 收件人：ghosert/cmd-editor 抄送：wenfengshi ,Author 其实已经支持了大多数VIM功能，一些不是非常常用的功能也不可能百分百完全支持。多多体谅。

**Comment by ghosert** [comment]
世面上并没有一个如您描述的 VIM WEB版，VIM本身开发了几十年，要求完全CLONE未免期许过高，你所说的回朔引用并不常用，最常用的是查找替换。我觉得比较核算的做法是二八原则，部分不能满足的需求可以退回到 VIM 里编辑。这个产品的重点是 MARKDOWN 编辑、渲染、云同步、发布导出批注，VIM 应该覆盖了常用功能。
