### ISSUE TITLE
报个小bug

### ISSUE THREAD

**Issue by cai-q** [ghosert/cmd-editor#1282]
文章在手机上响应式不是太好，特别是flow图会出现遮挡情况，无法看到内容。

**Comment by ghosert** [comment]
flow 的问题在开发环境下已经改好了，耐心等发布，到时候通知。

**Comment by ghosert** [comment]
flow 问题已上线：https://www.zybuluo.com/ghosert/note/378553 点击 flow 可以全屏看大图了。
