### ISSUE TITLE
请坚持简单之美~~

### ISSUE THREAD

**Issue by a5635268** [ghosert/cmd-editor#1288]
稍微浏览了一下很多用户提出的意见，当然是非常好以及非常合理。但是，我想说的是，如果希望功能强大请用为知或者印象，之所以选择作业部落作为我的主要写作管理工具，原因就只有一个，简单。

第一天推出高级会员就毫不犹豫的加入，而为知和印象笔记对我却没这个吸引力。

所以请坚持简单之美~！

**Comment by ghosert** [comment]
谢谢支持。
