### ISSUE TITLE
chrome 英文和中文在一行的时候输入端显示不正常

### ISSUE THREAD

**Issue by Yrp** [ghosert/cmd-editor#1290]
[问题](http://ww4.sinaimg.cn/large/0060lm7Tgw1f3ckxuh6dhj30cl01tt8r.jpg)

**Comment by ghosert** [comment]
字体的问题，看看CHROME里选用等宽字体。最近会出一个版本可以自定义字体，到时你再看看。

**Comment by Yrp** [comment]
好的，谢谢，我试试
