### ISSUE TITLE
作业部落的分享，可以只分享当前的文章么

### ISSUE THREAD

**Issue by backwind1233** [ghosert/cmd-editor#1296]
关于作业部落的分享：
用了作业部落的分享，但是后来发现，我分享给别人了一篇文章，别人点击以后可以看到我所有公开的文章，这真的不是很满足我的需求，请问有没有办法，当我分享了一个链接以后，别人通过链接，只能看到我当下分享的这个链接呢？

**Comment by ghosert** [comment]
公开就是对所有人公开，暂时是这个逻辑，我再想想其它公开方式。
