### ISSUE TITLE
i18n 准备做吗？

### ISSUE THREAD

**Issue by intijk** [ghosert/cmd-editor#130]
至少支持一下全英文吧：

比如，输入标签的时候现在只识别 “标签”， 希望也能识别 "Label"

---

额，我看到Tags了，不好意思，我不能删自己的issue吗

**Comment by ghosert** [comment]
英文支持  tags
2014-5-21 下午9:33于 "intijk" notifications@github.com写道：

**Comment by ghosert** [comment]
没事，你可以 close 这个 issue.
