### ISSUE TITLE
各种图显示不全的 BUG 什么时候能改完？半年过去了

### ISSUE THREAD

**Issue by mritd** [ghosert/cmd-editor#1301]
#1030

这些图的问题半年前以前就开始提，到现在还是绕无音讯，再这么耗下去我会员都到期了好么？我只想问问什么时候能修复，给个期限可以么? 我平时用的真的挺多的，但是一直显示不全 我真心没办法用这些图了，我也不想发牢骚。

**Comment by ghosert** [comment]
开发环境下已经修复了，在写发布日志，就这两天了。

**Comment by ghosert** [comment]
现在修复的方案是点击一下流程图或者序列图，会全屏放大给你看，不知道是不是可以接受？

**Comment by mritd** [comment]
要求不高，能看就行

**Comment by mritd** [comment]
刚更新 很高兴已修复，不过提个小小的建议，没太大影响，能不能在查看大图时候对背景进行模态或者置灰什么的处理？大图和背景内容有点混杂。还有就是 序列图文字太长在大图模式下超出了文本框边界

**Comment by ghosert** [comment]
当时就是想让别人知道这是一个悬浮图，否则别人不知道。。。先这样吧，序列图文字太长可以自定义写 CSS 把字体改小。譬如：

.sequence-diagram text, .flow-diagram text {
    font-size: 13px !important;
    font-family: Arial !important;
}
