### ISSUE TITLE
编辑页与预览页同步滚动问题

### ISSUE THREAD

**Issue by tab-liu** [ghosert/cmd-editor#1302]
https://www.zybuluo.com/tab/note/365661
发布个例子说明一切。 
意思就是说，在一些情况下，我所正在编辑的行没能在右边显示到同样的位置。

**Comment by rgsdg88** [comment]
same problem

**Comment by ghosert** [comment]
对齐是从顶部开始的可以留意一下你的 testtesttesttest 这行在顶部位置是对齐的，再往下，由于编辑区和预览区不可能完全一样高，才导致这个问题，这个就无解了，一般继续往下写，还是会同步出来。

**Comment by tab-liu** [comment]
是否可以这样? 编辑区和预览区不一样高时
- 当正在编辑文档时, 以当前编辑行为基准对齐. 
- 其它时候根据情况调整对齐位置.

**Comment by ghosert** [comment]
那也一样，即使按当前行，譬如，当前行是个图片链接，左边只占了一行，但是图片太大，右边占了一屏，其余的内容还是看不到。

**Comment by tab-liu** [comment]
感谢回复, 是我没表达清楚. 我是想说如果可以显示当前编辑的内容.

 如: 当有一张巨大的图片/流程图时 
- 我编辑图片上方一行内容,  右边大图可以稍向下滚动, 以便显示我当前编辑的行.
- 同样的, 当我编辑图片下方一行时, 右边大图适当向上滚动, 同样能突出我当前处理的行.

目前还没发现有编辑器可以这样的, atom有插件`好像`可以这样子, 但是那个插件有bug, 它会在闪下当前编辑内容后馬上跳到文档头, 体验不好. 如果cmd可以实现一定大赞! 

另外, 赞一下cmd, 我在linux下找了很久, 发现cmd确实不错. 开箱即用. 

P.s. 反过来, 如果在右边查看文档时, 发现有一处要修改, 在我选中或点中**右边**要改的地方时, **左边**可以高亮反馈给用户要修改的行也是个不错的功能. 

当然, 这都不是什么问题, 突发奇想而已. 再次感谢作者大人的回复.
