### ISSUE TITLE
标题与正文字体

### ISSUE THREAD

**Issue by tab-liu** [ghosert/cmd-editor#1303]
在使用时发现, 四,五级标题时与正文字体看着好像没有明显的区别.
建议使用不同的字体, 以便_明显_区分. 

刚买的会员, 希望能坚持写笔记. ；)

**Comment by tab-liu** [comment]
apt-get install git   
- table   
```
apt-get install git
```

**Comment by ghosert** [comment]
现在可以通过自定义 CSS 来实现了。https://www.zybuluo.com/ghosert/note/378553
