### ISSUE TITLE
提一个程序猿重度需要的功能！

### ISSUE THREAD

**Issue by ghost** [ghosert/cmd-editor#1306]
首先， Cmd Markdown做的很好，已买高级会员支持！
希望能提供的功能！
1. 希望能提供像Typora那样code fences的功能。 不知道为什么，我的输入法从来没有能成功打出高亮代码所需要的这个符号： ``` 。 我觉得自己应该不是唯一一个遇到这样问题的人吧。
2. ctrl + v 粘帖图片
3. 多窗口

辛苦了~

**Comment by ghosert** [comment]
CTRL V 粘贴图片 已经解决了，下周放出， ``` 的问题参考说明文稿：https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#6-加强的代码块

**Comment by ghosert** [comment]
已经更新修复了。

**Comment by ghosert** [comment]
ctrl + v 有了，其它 1 好像不会出现，3暂时用浏览器的多窗口来实现。``` 就是连打三个 esc 底下的按键。

**Comment by ghost** [comment]
已更新到最新版本，谢谢啦！：）
