### ISSUE TITLE
文章管理列表能否改进？

### ISSUE THREAD

**Issue by Reposkeeper-zz** [ghosert/cmd-editor#1307]
已入高级会员，现在做的非常好！

有一个小问题，写的文章越多之后，每次打开列表找文章的时候都是一个长长的列表。很不方便。
如果只是找的话，可以用搜索解决。
有的时候需要回顾自己这一个月写了哪些东西，要做一个总结的时候，简直太痛苦了！
能否增加一个类似笔记本按时间排序或分类的功能？

**Comment by ghosert** [comment]
下周会推一个最近修改的文件功能，希望有所帮助。另外可以在文件列表的搜索框里打 \* 号列出所有的文稿。

**Comment by ghosert** [comment]
下周会推一个最近修改的文件功能，希望有所帮助。另外可以在文件列表的搜索框里打 * 号列出所有的文稿。

**Comment by ghosert** [comment]
下周会推一个最近修改的文件功能，希望有所帮助。另外可以在文件列表的搜索框里打 * 号列出所有的文稿。

**Comment by ghosert** [comment]
已经更新修复了。
