### ISSUE TITLE
参考马克飞象

### ISSUE THREAD

**Issue by xiaotinglei** [ghosert/cmd-editor#131]
makedown编辑器基本功能差不多，关键是一些扩展功能。
马克飞象插图功能很爽。还有导出功能也棒，能导出PDF。
希望作业部落改进，进步。http://maxiang.info/

是不是我提的改进地方太多了，都没人回复我了！

**Comment by ghosert** [comment]
定时过来看，忙的时候未必会回复。问题在列表里就不会丢，所以一定要提过来。

你说的这些问题都有人提过，我会放在日程里做。

**Comment by ghosert** [comment]
主要功能差不多的时候，cmd markdown 有无数的细节优化，可以细细体会区别。^_^，如果有一个列表，你可以数出超过十种。
