### ISSUE TITLE
导出到Evernote时权限比印象笔记小，无法将笔记移动到其他笔记本

### ISSUE THREAD

**Issue by f32y** [ghosert/cmd-editor#1314]
将笔记从Cmd Markdown移动到其他笔记本后，同步时出现

> 导出当前文稿出错，请重试或联系我们，错误详情：authenticationToken

推测是因为编辑器只获得了Cmd Markdown这一个笔记本的权限导致的，但如果只能放到这一个笔记本，每次同步后手动移动的话很不方便啊，有什么办法可以解决吗？

参照 #994 取消授权并重新授权多次仍未解决

Update:看了一下到印象笔记的同步，在授权时没有选择笔记本的选项，权限要比Evernote大

**Comment by ghosert** [comment]
好的，我问下 EVERNOTE。

**Comment by ghosert** [comment]
他们说解决了，可否在这里答复我一下是否真的解决了？

**Comment by f32y** [comment]
@ghosert 确实已解决，重新授权之后可以随意移动笔记了，感谢！

**Comment by olafchou** [comment]
@ghosert 我只想说付费了才发现印象笔记不能移动cmd markdown文件和修改文件，这简直太坑了啊，以后不续费了难道就不能再改了？？？我想退款，请告诉我怎么退款
