### ISSUE TITLE
高分屏字体太小

### ISSUE THREAD

**Issue by caozhengxx** [ghosert/cmd-editor#1316]
现在很多电脑开始使用1080p的屏幕，字体看上去真的很不舒服，没法看。

我用的ubuntu，chrome页面可设置缩放，效果还可以。

cmd不能缩放字体，最好能自定义字体。thanks！

**Comment by ghosert** [comment]
自定义字体字号 CSS 已经有了。https://www.zybuluo.com/ghosert/note/378553#1-自定义字体字号以及css

**Comment by caozhengxx** [comment]
@ghosert 恩看到了，买了会员。笔记内容是可以自定义大小了，但是客户端的字体没有改变。

**Comment by ghosert** [comment]
哪个操作系统，我这里都可以啊。是不是你指定的字体其实在系统里是没有的？看看浏览器里有多少字体可以选。
