### ISSUE TITLE
[Bug] 新版导出的 PDF 问题

### ISSUE THREAD

**Issue by wafer-li** [ghosert/cmd-editor#1319]
5 月 16 号上线的新版本导出 PDF 有如下 Bug:
1. TOC 无法进行跳转
2. 脚注中如果有长名字链接，则无法跳转回去。

**Comment by cdhuang-pku** [comment]
同问。而且，无论在编辑的时候，还是在导出的 PDF 里，用 “>” 引用的文字的字号仍然是默认的 16 号（结果与正文的自设字号格格不入……）。

**Comment by ghosert** [comment]
好的，记下了。晚上修一下。

**Comment by ghosert** [comment]
PDF TOC 的问题修好了，字体字号是因为要自己写 CSS 来指定某些元素，你的情况可以这样：

blockquote p {
font-size: 20px;
}
