### ISSUE TITLE
我很好奇，作业部落怎么盈利？

### ISSUE THREAD

**Issue by xiaotinglei** [ghosert/cmd-editor#132]
我们免费使用作业部落，作业部落怎么盈利呢？

**Comment by ghosert** [comment]
我也很困惑，写下你的答案，或者在知乎上提问，o(∩∩)o...哈哈。

**Comment by ghosert** [comment]
感觉你成脑残粉了？o(∩∩)o...哈哈。

**Comment by richaction** [comment]
好欢乐～～

**Comment by bugparty** [comment]
你们太浮躁了，不是每个东西都要盈利的。

**Comment by ghosert** [comment]
@bugparty 没有收入何以为继？

**Comment by bugparty** [comment]
中国互联网思维，“先把产品做大再说”。。。

**Comment by bugparty** [comment]
你看看wps就知道了，wps研发团队数百人，没什么有效地收入，还不是一样继续去做下去吗

**Comment by ghosert** [comment]
这个问题关了。

**Comment by harkhuang** [comment]
>  提出一点小建议
> - 就是如何能让用户更加信任或者依赖你们的产品(不必担心用户数据的丢失)建议和知名企业合作加强品牌知名度!!
