### ISSUE TITLE
有序列表项间插入引用或代码后，序号显示出错

### ISSUE THREAD

**Issue by ithink365** [ghosert/cmd-editor#1323]
有序列表项间插入**引用**或**代码**后，序号显示出错。
详见下图
![image](https://cloud.githubusercontent.com/assets/7018665/15283746/7026b22a-1b7f-11e6-8ac8-3715b8675a55.png)

**Comment by ghosert** [comment]
噢， 这个老问题了，因为有序列表是简单列表不能内嵌复杂语法。可以使用

#### 1. xxxxxx
> ddddd
#### 2. yyyyyy
> eeeeee
