### ISSUE TITLE
希望文档中添加代码折叠功能，有时代码太长占很大的篇幅，不贴又不能很好地说明问题。

### ISSUE THREAD

**Issue by kkli28** [ghosert/cmd-editor#1325]
在markdown文档中，假如放的代码段比较长，会占用很大的篇幅，是否可以通过某些方式实现代码折叠呢？网上查不到这方面的东西，说明此功能还没有，希望添加。刚接触这个，很喜欢你们的编辑器，赞一个！！！

**Comment by ghosert** [comment]
有啊，看下这篇关于代码行的介绍：http://localhost:6543/ghosert/note/3596

**Comment by ghosert** [comment]
看下这篇，关于显示行号，然后折叠行的介绍：https://www.zybuluo.com/ghosert/note/378553
