### ISSUE TITLE
导出pdf时最好导出的是“阅读模式”的排版，现在是"预览模式"右边栏的排版，很挤很丑

### ISSUE THREAD

**Issue by yzsatgithub** [ghosert/cmd-editor#1327]
如标题所说，现在导出pdf时，导出的板式和预览模式时右半边屏幕的排版是一致的，你知道因为只用了半边屏幕，所以东西都非常的拥挤，pdf很丑。但是在阅读模式下，空间很富裕，排版很好看。
然而在阅读模式下，没有导出pdf的那个菜单，以至于只能在预览模式下点击导出pdf。

或者说是不是有导出pdf的快捷键我不知道？？　　　

请有相关困扰的大家给出个主意，或者开发者添加一下新功能吧。

谢谢

我的操作系统是：Ubuntu 14.04 LTS

**Comment by ghosert** [comment]
主要是留白的问题，这个你在PDF阅读器里设置显示为 100% 或者 BEST FIT 就好了。

**Comment by yzsatgithub** [comment]
@ghosert  不是这样的。　每行显示的字数都不一样。

预览模式：
![2016-05-17 10 55 42](https://cloud.githubusercontent.com/assets/10882352/15309952/11aa1bf2-1c1e-11e6-8806-efd6946243dd.png)

阅读模式：
![2016-05-17 10 56 17](https://cloud.githubusercontent.com/assets/10882352/15309954/157cda30-1c1e-11e6-8434-3cbfcc418a50.png)

预览模式明显要挤很多很多。　这样也可以调吗？

**Comment by yzsatgithub** [comment]
@ghosert 您看我上一条说的这种情况通过修改PDF阅读器可以改好吗？
