### ISSUE TITLE
在Mac下输入区的一些问题

### ISSUE THREAD

**Issue by Keningz** [ghosert/cmd-editor#133]
之前在Win下使用都没有太大问题，但是在Mac下发现：
a. 如果使用的是中文，输入区字符和字符之间横向间距很宽，就像是有空格，但是光标工作正常；
b. 如果使用的是英文，那么光标会和字符错位，表现为光标在实际应该出现的位置之前（没有字符间距过宽的问题）。

我使用的是OSX 10.9.2，默认语言为英文，第二语言为中文。测试了Chrome和Safari，都有问题。

多谢:)

**Comment by ghosert** [comment]
我去搞台 Mac 测试一下，手头没有。

**Comment by shixiaobao17145** [comment]
确实有上述所说问题

**Comment by coolbit-in** [comment]
linux下也有这个问题，输入中文没事但英文的话，误差会越来越大，这个bug应该时随vim emacs模式加入的时候产生的。
![image](https://cloud.githubusercontent.com/assets/1282514/3173344/f1719060-ebe4-11e3-8eae-f84d561340f0.png)
如图，光标应该在蓝色位置，但已经偏到了红色位置。
这个BUG影响体验非常严重。

**Comment by ghosert** [comment]
Mac 上的问题已经解决了，最近会更新到网站上，Linux 上我测过 Ubuntu 没有问题，请问你是哪个发行版？

**Comment by ghosert** [comment]
另外如果你的浏览器设置里，看看有没有忽略网站上的字体选项，不要选中这个选项。还可以试试换着 firefox/chrome 试试。

**Comment by ghosert** [comment]
Ubuntu 12.04 LTS 没问题。

**Comment by coolbit-in** [comment]
在LinuxDeepin2013下问题依旧，具体环境信息如下：
OS：Linux 3.8.0-34-generic #49-Ubuntu SMP
Chrome： 34.0.1847.116
字号设置：
![image](https://cloud.githubusercontent.com/assets/1282514/3197381/55dd3982-ed48-11e3-923e-3cd78e9d525b.png)

**Comment by Keningz** [comment]
十分感谢:)

**Comment by ghosert** [comment]
@coolbit-in 手头没有这个发行版。网站指定了使用 Ubuntu mono 的字体，可能是因为 LinuxDeepin 上没有这个字体，可以去下载一个就可以解决这个问题了。

@Keningz Mac 上光标的问题已经解决了，字距过宽暂时没有找到合适的解决办法，过后再处理。
