### ISSUE TITLE
已经发布了的笔记，如果想更新后怎么办？　生成一个新的链接？好麻烦

### ISSUE THREAD

**Issue by yzsatgithub** [ghosert/cmd-editor#1330]
已经发布了的笔记，如果想更新后怎么办？　必须生成一个新的链接吗？好麻烦

**Comment by ghosert** [comment]
不用，已发布的可以点击工具栏上的“发布更新”菜单。注意看工具栏

**Comment by yzsatgithub** [comment]
嗯好的谢谢。　　昨天没有看到这个。可能是没有同步或者保存，这个钮没有变成“发布更新”。
