### ISSUE TITLE
合并有bug , 不停的把云端旧数据合并到本地来.......本地才是最新的

### ISSUE THREAD

**Issue by mmfei** [ghosert/cmd-editor#1331]
合并有bug , 不停的把云端旧数据合并到本地来.......本地才是最新的

超级烦

**Comment by ghosert** [comment]
看看有没有代理，去掉下，这种情况主要是网络不稳定导致，或者建一个离线文稿，不和服务器同步就好了。

**Comment by mmfei** [comment]
这么快回复了. 我是在外面的wifi使用. 网络情况可能不稳定...........这个能否自己设定同步时间? 而不是默认的?

**Comment by ghosert** [comment]
暂时不能自己设同步时间，主要是为了意外崩溃丢失数据，所以尽量都和服务器同步了。可以试试付费的离线文稿功能，那个可以直接保存到本地文件里，而且不和服务器同步。
