### ISSUE TITLE
鼠标右键无法使用

### ISSUE THREAD

**Issue by cataglyphis** [ghosert/cmd-editor#1336]
在cmd markdown 5.18的版本中， 编辑界面鼠标右键无法使用。
windows 10 64bit

**Comment by ghosert** [comment]
ctrl c ctrl v 更快啊 发自网易邮箱大师 在2016年05月19日 11:52 ，Bo Wang写道： 在cmd markdown 5.18的版本中， 编辑界面鼠标右键无法使用。 windows 10 64bit — You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub

**Comment by cataglyphis** [comment]
不过鼠标党还是习惯用右键, 可以直接复制, 粘贴, 会比较方便.  之前的版本是支持的
