### ISSUE TITLE
阅览中的空格个数能不能和纯文本中的一致

### ISSUE THREAD

**Issue by FrancisHe** [ghosert/cmd-editor#1337]
纯文本中空格个数无论有多少个，在预览中都只显示一个

**Comment by xialu4820723** [comment]
这个好像是markdown本身的语法吧。。。不是编辑器的问题。

**Comment by xialu4820723** [comment]
要插入间隔的话可以用全角的空格，因为全角空格被识别为一个字符，
还有其他方法，可以在网上百度"markdown 插入空格"

**Comment by FrancisHe** [comment]
的确是本身的语法，跟 HTML 一致，关闭吧
