### ISSUE TITLE
win7无法正常运行cmd-markdown编辑器

### ISSUE THREAD

**Issue by justbeay** [ghosert/cmd-editor#1342]
![cmd-markdown运行截图](http://s32.postimg.org/d85r7qgud/cmd_markdown.png)
如上图，下载64位版本加压运行后一直是这样子，32位也一样。运行环境：8G内存，64位win7操作系统。

**Comment by ghosert** [comment]
首次运行要联网一下，看看此时又没有网络。

**Comment by justbeay** [comment]
今天重新打开后正常了，不过可以肯定之前网络是好的。也不知道什么原因
