### ISSUE TITLE
强烈建议支持导出 pdf

### ISSUE THREAD

**Issue by chuyue86** [ghosert/cmd-editor#135]

**Comment by xingrz** [comment]
+1

**Comment by Tinghui** [comment]
+1 求捐助账号

**Comment by franklinzhang** [comment]
+1 同求捐助帐号 学生党进绵薄之力

**Comment by ghosert** [comment]
谢谢大家，目前还可以负担，我会评估一下 pdf 导出到底会消耗多少服务器资源，到时再看情况。

**Comment by cntee** [comment]
同建议增加这一项功能，pdf导出某s做的挺好的。
捐钱也没问题啊。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
