### ISSUE TITLE
文章标题为什么要以第一个以及标题为名？

### ISSUE THREAD

**Issue by FrancisHe** [ghosert/cmd-editor#1356]
文章标题为什么要以第一个以及标题为名？不能单独给文档取个类似“标题”的东东吗？想把一级标题作为文章的章节名。

**Comment by ghosert** [comment]
大多数时候这样更方便，可以把第二个一级标题作为章节名。

**Comment by FrancisHe** [comment]
这样不方便啊，比如写文章 A, 第一章叫 "Overview", 写文章 B, 第一章也叫 "Overview", 结果两篇文章都叫 Overview
