### ISSUE TITLE
osx 10.11.5  chrome 浏览器无法正常使用vim编辑模式

### ISSUE THREAD

**Issue by nicozhang** [ghosert/cmd-editor#1367]
及时选择了vim编辑模式，按esc还是会退到普通模式。但是，按钮显示的还是vim模式。

**Comment by guodage** [comment]
楼上是不是用了别的浏览器插件导致冲突了。 我之前用的Vimium插件时也遇到上述情况，禁掉就ok了。

**Comment by nicozhang** [comment]
还真是，我的chrome 有你说的这个插件

**Comment by guodage** [comment]
恩那就是了  添加个例外就好了
