### ISSUE TITLE
在粘贴 俄语 的字符时，会被识别成图片URL

### ISSUE THREAD

**Issue by YuriTu** [ghosert/cmd-editor#1368]
改一下正则吧....

**Comment by ghosert** [comment]
贴几个俄语字符上来我试试，另外操作系统和浏览器版本说一下。

**Comment by YuriTu** [comment]
俄语字符：
Отдельным пунктом «Белой книге» прописана Россия, которая согласно авторам документа, перестала быть партнером и стала конкурентом. В документе отмечается, что Москва «готова насильственно продвигать свои интересы», в качестве примера здесь приводятся события в Крыму и на востоке Украины.

win7旗舰64位
用的客户端出现的这个情况

**Comment by YuriTu** [comment]
另外不是必现...一开始会出现一到两次弹出 ctrl+g的输入图片URL的效果，但是字符能被粘贴上，之后就好了

**Comment by ghosert** [comment]
不能重现。。。看看能不能找到具体的重现步骤再重开这个问题。
