### ISSUE TITLE
同步到网易云笔记或者印象笔记

### ISSUE THREAD

**Issue by chnkarl** [ghosert/cmd-editor#137]
我是网易云笔记的长期用户，但我很喜欢markdown的简单和流畅输入，所以，希望看看是否可以将咱们cmd md实现同步文章到网易云笔记。

另外，是否可以出一个pc版的客户端，这样离线编辑就更好了。

期待回复：chnkarl@qq.com

**Comment by franklinzhang** [comment]
+1

**Comment by tiomke** [comment]
希望可以以markdown文本形式导入

**Comment by ghosert** [comment]
好的，了解了
2014-6-21 下午6:21于 "tiomke" notifications@github.com写道：

**Comment by tiomke** [comment]
@ghosert 
劳驾了，嘻嘻！

**Comment by heliar-mk** [comment]
印象笔记已经有类似的chrome插件了，比较想要可以备份成pdf到dropbox or 到github上的

**Comment by legendxcheng** [comment]
最想要做到同步到印象笔记了

**Comment by luyee** [comment]
最想要做到同步到印象笔记了 +1

**Comment by luyee** [comment]
另外加载很慢，【加载文章图片，请稍后
】。。这是要干啥？

**Comment by ghosert** [comment]
看看你本地访问图片链接是不是很慢。

**Comment by ghosert** [comment]
不想看到这个提示，可以关闭。

**Comment by ghosert** [comment]
已支持印象笔记：https://www.zybuluo.com/ghosert/note/102771
