### ISSUE TITLE
在左边编辑的时候  右边的预览貌似不跟随了

### ISSUE THREAD

**Issue by guodage** [ghosert/cmd-editor#1370]
我记得以前还可以跟随呢，找了半天也没相关的设置
作者是出于什么原因取消掉这个特性了呢？

**Comment by ghosert** [comment]
没有取消，这个问题是因为文档内容写得不正确，检查下文档，注意

``` xxxx ``` 不要写在一行。写成这样：

```
xxx
```

还不行把MARKDOWN原文发我邮箱，我来改。ghosert@gmail.com

**Comment by guodage** [comment]
恩是文档内容的问题。
这里反馈一下
我这么写就会有问题

```
* a title
> * aaa
* bbb
* ccc
```

第一行和第二行中间空一行，就ok了

```
* a title

> * aaa
* bbb
* ccc
```
