### ISSUE TITLE
导出PDF问题

### ISSUE THREAD

**Issue by Jack2code** [ghosert/cmd-editor#1373]
调用 

```
https://www.zybuluo.com/mdeditor/note/downloadPdf
```

接口时，会将当前文档内容作为Form Data传回服务器，在服务器生成PDF之后，再下载。

能不能先同步本地文档到服务器，然后直接在服务器生成PDF，免去将当前文档内容上传服务器这一步。

这样做的好处：
- 同步文档比上传整个文档消耗流量少
- 当使用网络环境对上传有限制时，可以避开限制

**Comment by ghosert** [comment]
这样的话，服务器的压力很大。。。
