### ISSUE TITLE
客户端都是 web 页面吗？

### ISSUE THREAD

**Issue by akarineren** [ghosert/cmd-editor#1378]
下载了 mac 客户端，30多M的文件还以为是全客户端，结果只是嵌入 web 页面， 什么时候支持组件式的开发呢？

**Comment by ghosert** [comment]
内置浏览器引擎已经是大势所趋，开发，部署都比较高效，html5 webkit, v8 等高效引擎支持下，体验和本地引用无异，atom, visual studio 等新型编辑器都是这样做了。

**Comment by akarineren** [comment]
@ghosert 最大的差别就是断网 和 体验 基于网页的开发的确能够高效率 但是还有一些方面是网页做不到的 也不打算做组件版本了吗？

**Comment by ghosert** [comment]
离线可以用的，在线以后会自动同步，现在的HTML5技术没那么孱弱，包括读写本地文件客户端都支持。其实基本上没什么做不到了。
