### ISSUE TITLE
我编辑的时候，突然有人经过，能否添加暂时隐藏的功能

### ISSUE THREAD

**Issue by StanleyYake** [ghosert/cmd-editor#138]
1.  一整个页面都是关于自己代码，或是学习的东西，突然有人经过，能否添加暂时隐藏的功能。
2. 写的过程中，我如果想查看进入网站的那个帮助页面（它确实很好），只能存为书签吗？能否加入帮助按钮
   最后，非常谢谢作者的这个网站，我觉得很不错，I'm new here，thanks again！希望越来越好

**Comment by ghosert** [comment]
突然经过的时候，使用系统的快捷键吧，或者老板键，不在本作职责之内。
帮助页面可以通过点击 ctrl+alt+h 调出。

**Comment by StanleyYake** [comment]
oh，oh 非常抱歉，谢谢
