### ISSUE TITLE
为什么验证链接的邮件收不到？已经试过多个邮箱了，依然收不到

### ISSUE THREAD

**Issue by Mrwow** [ghosert/cmd-editor#1389]

**Comment by ghosert** [comment]
垃圾箱里看看，QQ，GMAIL，SOHU 主流邮箱应该都可以。我刚才试了可以。

**Comment by Mrwow** [comment]
QQ可以，但是网页版的为什么不能打开以前写的文档进行新的编辑呢，我在windows版本下能再编辑之前写的其他文档

**Comment by ghosert** [comment]
可以啊，在工具栏上有个文件列表菜单。 发自网易邮箱大师 在2016年06月11日 12:06 ，Mrwow写道： QQ可以，但是网页版的为什么不能打开以前写的文档进行新的编辑呢，我在windows版本下能再编辑之前写的其他文档 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by neucloudzouaodi** [comment]
QQ收不到验证邮件

**Comment by ghosert** [comment]
在这里 https://www.zybuluo.com/settings/account 换个信箱，然后重新验证，垃圾箱里也看看。

**Comment by neucloudzouaodi** [comment]
腾讯企业邮箱，163邮箱，qq邮箱都试了，都收不到。垃圾箱也没有



zouaodi@neucloud.cn
 
发件人： Jay Zhang
发送时间： 2017-04-01 16:53
收件人： ghosert/cmd-editor
抄送： neucloudzouaodi; Comment
主题： Re: [ghosert/cmd-editor] 为什么验证链接的邮件收不到？已经试过多个邮箱了，依然收不到 (#1389)
在这里 https://www.zybuluo.com/settings/account 换个信箱，然后重新验证，垃圾箱里也看看。

**Comment by ghosert** [comment]
不好意思，刚才邮件服务确实有问题，现在应该已经恢复了，邮件都发出去了。
