### ISSUE TITLE
 关于代码段，

### ISSUE THREAD

**Issue by StanleyYake** [ghosert/cmd-editor#139]
加上带序号的可以出现，可是删掉只想保留后面的，结果代码段出现不了
![qq20140530135022](https://cloud.githubusercontent.com/assets/7522853/3127434/7f4c52e2-e7be-11e3-9f2f-e3794703693a.png)
![qq20140530135045](https://cloud.githubusercontent.com/assets/7522853/3127435/7f4eb532-e7be-11e3-8a8d-b57823358282.png)

**Comment by StanleyYake** [comment]
左边预览的时候，字体突然变化了
![qq20140530140503](https://cloud.githubusercontent.com/assets/7522853/3127515/d3cc360a-e7c0-11e3-9c7a-8d5434aa0147.png)

**Comment by ghosert** [comment]
第一个问题，你暂时在代码段上方加上

---

分割一下，或者使用

> python-rosinstall

第二个问题，$ 是代表 LaTex 公式的符号，使用 \$ 进行转义即可。

**Comment by ghosert** [comment]
加上 分隔符

----

或者使用

>python-rosinstall
