### ISSUE TITLE
【一键导出所有文稿】当标签中包含‘/’时，导出的目录不正确

### ISSUE THREAD

**Issue by Jack2code** [ghosert/cmd-editor#1400]
例如：标签`HTTP/2`，在网页上显示正常，所以标识为`HTTP/2`标签的文章都归类到此目录下。
但是使用【一键导出所有文稿】功能时，
- 导出的压缩包中会将`HTTP/2`拆分成`HTTP`和`2`两级目录
- 所有以`HTTP/2`开头的文章会被放到`HTTP`目录下，然后文章以`2`开头。

以【HTTP/2分析】这篇文章为例，压缩包解压后的路径如下：

```
--HTTP
  \--2
     \--HTTP
       \--2分析.md
```

正确的文件路径应该是：

```
--HTTP/2
  \--HTTP/2分析.md
```

由于特殊符号`/`的关系，能不能采用其他符号代替或者直接忽略`/`符号？

**Comment by ghosert** [comment]
可否把原文写成 HTTP2 或者 HTTP-2 ？
