### ISSUE TITLE
添加对metadata的支持

### ISSUE THREAD

**Issue by riteme** [ghosert/cmd-editor#1408]
我们书写的markdown都会在文章开头写上一段YAML语法的Metadata。像下面这样：

``` md

---
title: Untitled
modifed: 2016.01.02
tags: ...

---

这里是正文内容
```

这个语法Github是支持的，它会在开头显示一个表格，展示其中的信息。
但是Cmd Markdown似乎并不支持这种语法，它会错误的认为这会声明一个标题......
希望能够支持以下这种语法，谢谢！

**Comment by ghosert** [comment]
# 标题
tags: xxx yyy

Cmd Markdown 就是这样支持的，时间戳可以自己加，现在各家有各家的规范，很难做到面面俱到。
