### ISSUE TITLE
[BUG] 打开后什么都不显示,连工具栏都没有,web也是一样

### ISSUE THREAD

**Issue by chaihuoa** [ghosert/cmd-editor#1409]
打开后什么都不显示,连工具栏都没有,web也是一样,从昨晚开始的,刚开始是显示上次编辑的文章,无法切换其他文章,后来就什么都没有了,求解决啊!

mac os 10.11.1

cmd v2.0

**Comment by ghosert** [comment]
用户名多少？文稿标题大概是多少，这个问题主要是因为文稿中包含的 HTML 破坏了CMD自身的结构。我给你从服务器端删掉就好了。
