### ISSUE TITLE
发布时没有设置密码，但输入固定链接后提示要求输入密码

### ISSUE THREAD

**Issue by Seandor** [ghosert/cmd-editor#1417]
具体的链接如下，https://www.zybuluo.com/seandor/note/410502
我试了几次发现，密码是上次设置过的密码。

**Comment by ghosert** [comment]
下次发布的时候，记得把密码框里的密码清空一下，有些情况下浏览器会自动记住密码。

**Comment by ghosert** [comment]
下次发布的时候，记得把密码框里的密码清空一下，有些情况下浏览器会自动记住密码。

**Comment by ghosert** [comment]
下次发布的时候，记得把密码框里的密码清空一下，有些情况下浏览器会自动记住密码。

**Comment by ghosert** [comment]
下次发布的时候，记得把密码框里的密码清空一下，有些情况下浏览器会自动记住密码。
