### ISSUE TITLE
会不会支持快速的导出全部文档以便备份？  还有同步到网盘以便备份呢？

### ISSUE THREAD

**Issue by cxbgithub** [ghosert/cmd-editor#142]

**Comment by cxbgithub** [comment]
同步到evernote 或者 google drive 之类的。。

**Comment by ghosert** [comment]
已经支持导出到 Evernote，也可以一键备份所有文稿，打成 ZIP 包的形式下载。https://www.zybuluo.com/ghosert/note/102771
