### ISSUE TITLE
【建议】文件可以保存到本地目录

### ISSUE THREAD

**Issue by KaixiangLin** [ghosert/cmd-editor#1420]
建议把导出功能换成按 ctrl + s 就可以保存到本地目录，或者自动保存到本地，云端用于做版本控制。

比如我在编辑文件A. 希望可以像正常编辑器一样按Ctrl + S 就可以保存到本地。

**Comment by ghosert** [comment]
目前新建离线文稿的时候可以选择指定路径保存文件，而且也不需要按 ctrl s ，可以随写随存本地文件。

**Comment by KaixiangLin** [comment]
thanks.
