### ISSUE TITLE
标签能不能用其他的字符代替空格来做分隔

### ISSUE THREAD

**Issue by timlight** [ghosert/cmd-editor#143]
中文的话一般没有关系，但是如果我用英文做标签，假如想打**两个单词**，自然**用空格来分隔**比较合适，比如`Swift 资源`。所以能不能用 `,` 或者其他符号比如 `|` 作为分隔？

**Comment by ghosert** [comment]
用空格是为了让规则比较简单，比起其它符号，空格更方便。譬如，豆瓣也是这样处理的，其实你的这个例子里 Swift 已经可以精确定义标签了，资源实际上是一个很模糊的标签可以去掉，如果实在需要可以 Swift-资源 来处理

**Comment by timlight** [comment]
谢谢你的回复。确实如你所说，还是简单点比较好。我也学习了，哈哈。
