### ISSUE TITLE
图片居然要钱

### ISSUE THREAD

**Issue by whtc123** [ghosert/cmd-editor#1430]
太垃圾，免费版本居然不能用图片，浪费我的时间，果断丢弃。赚钱不是这样玩的

**Comment by geekinglcq** [comment]
免费版可以用图片啊，只是不能**上传图片附件**，你可以把图片存在github上然后外链过去。

**Comment by ghosert** [comment]
@whtc123 那赚钱怎么玩？又没放广告，这个钱里有一部分是给七牛云存储的。考虑一下开发者，别太自私了。
