### ISSUE TITLE
这个垃圾合并策略

### ISSUE THREAD

**Issue by stkevintan** [ghosert/cmd-editor#1431]
我也是醉了，两台电脑各写了一半文档，然后在前一半电脑再打开，提示合并。
试问：
1. 就没有直接使用云端版本的按钮么？
2. 误按了Esc键后，提示框就这么没了？你在逗我吗？我后一半的文档全没了啊。

**Comment by denki-san** [comment]
我也遇到这个问题

**Comment by ghosert** [comment]
还是要自己看清楚，否则怎么做也会误操作，看看从文件历史版本里应该可以找回。直接使用云端版本会加，但还是有人会误按直接使用本地版本。esc 我尝试禁用。

**Comment by ghosert** [comment]
合并策略本身没问题，据我所知还没有哪个MARKDOWN有这个功能。
