### ISSUE TITLE
编辑模式下的编辑问题

### ISSUE THREAD

**Issue by spacewander** [ghosert/cmd-editor#144]
编辑模式下，如果改变浏览器的大小（比如变成半屏），原有的文字不能自动换行（不会有水平滚动条），而且光标位置跟实际位置不符合。

我用的Chrome和Firefox都有同样的问题。

**Comment by ghosert** [comment]
因为编辑的模式下，设置了最小宽度，取消了水平滚动条，原意就是想让作者全屏编辑。可否不要半屏写。

**Comment by spacewander** [comment]
呃，那这么说编辑模式和全屏模式就没有差别了……我只是不想有一个预览视图占住右半边的窗口而已

2014-06-07 19:21 GMT+08:00 Jay Zhang notifications@github.com:

**Comment by ghosert** [comment]
我重新开一下有时间修，暂时可以这样，你切到编辑模式，然后放在上半屏，你要看的其它内容放在下半屏。

**Comment by ghosert** [comment]
已经解决了，这两天内会发布到站上，到时会在这里更新。

**Comment by ghosert** [comment]
已经更新到站上了，可以去看看，这个问题关了。
