### ISSUE TITLE
希望导出 HTML 能和预览里面的一样

### ISSUE THREAD

**Issue by timlight** [ghosert/cmd-editor#145]
默认的编辑界面还有预览界面都超有感觉的，字体、排版、颜色都挺好的。但是导出之后格式就会变化了，相比预览中的样式就有些惨不忍睹了。这个在问题里面也有好多人提出来了，加一个 CSS 行不行的？

举个栗子：

预览出来的
![预览](http://xin-kk.qiniudn.com/image/1406/%E5%A5%BD%E7%9C%8B%E9%A2%84%E8%A7%88.png)

实际导出的
![实际导出](http://xin-kk.qiniudn.com/image/1406/%E7%8E%B0%E5%AE%9E%E7%89%88.png)

还有看到你要做 PDF 输出了，记得加入书签支持啊！发现 StackEdit 的 PDF 导出做的蛮好的，可以参考下。

嗯，又来添乱了哈哈，希望有点用，加油做国内最好的！

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
