### ISSUE TITLE
文档排序

### ISSUE THREAD

**Issue by yulongsun007** [ghosert/cmd-editor#1451]
![image](https://cloud.githubusercontent.com/assets/10681593/17018945/bc1e5b4e-4f6c-11e6-90cd-b61730b6db44.png)
这文档排序也是不懂

**Comment by yulongsun007** [comment]
![image](https://cloud.githubusercontent.com/assets/10681593/17164234/d4d12a3c-53f8-11e6-978e-13f273ffb438.png)

**Comment by ghosert** [comment]
是按创建时间排序的。

**Comment by persistlee** [comment]
这个排序能不能搞几种选择啊？如按创建时间，修改时间，字符顺序，手动随意拖动等等
