### ISSUE TITLE
导出PDF一直失败，提示服务器忙。

### ISSUE THREAD

**Issue by rabbielulu** [ghosert/cmd-editor#1463]
![image](https://cloud.githubusercontent.com/assets/19318912/17290608/f774935e-5811-11e6-94b6-6d9a68398d96.png)

已是高级会员了。

**Comment by ghosert** [comment]
看看有没有被墙的图片链接，或者插入的图片是否过多。

**Comment by rabbielulu** [comment]
嗯，好像是图片过多的原因，那控制在多少合适呢？

**Comment by rabbielulu** [comment]
也有可能就是有图被墙了。。T-T我再检查下。谢谢您回复~
