### ISSUE TITLE
VIM模式如何切换

### ISSUE THREAD

**Issue by berryliu** [ghosert/cmd-editor#147]
请问一下vim模式如何切换？正常退回到命令模式是Esc，但是不生效。
能不能简单说明一下与正常的vim使用有哪些区别？谢谢~

**Comment by ghosert** [comment]
如果你安装了 vimium 这类浏览器里的 vim 插件，那会和 cmd markdown 里的编辑器 vim 模式 冲突，一般可以设置 vimium exclude zybuluo.com 这个域名就好了。正常 vim 里绝大多数功能都实现了，还有一些没办法做，但是用起来绝对很爽。

**Comment by berryliu** [comment]
解决了，的确很爽！~谢谢啦！
