### ISSUE TITLE
部分文字不显示

### ISSUE THREAD

**Issue by hapuhundre** [ghosert/cmd-editor#1473]
![default](https://cloud.githubusercontent.com/assets/20013433/17461501/10004036-5cc1-11e6-855c-2d594378f09d.PNG)
如上图，一部分文字在右边预览不到

**Comment by ghosert** [comment]
原文发我看下。ghosert@gmail.com

**Comment by ghosert** [comment]
原文发我看下。ghosert@gmail.com

**Comment by ghosert** [comment]
原文发我看下。ghosert@gmail.com
