### ISSUE TITLE
Windows 10 + Chrome，微软拼音输入中文时存在不兼容的问题

### ISSUE THREAD

**Issue by liuhui0803** [ghosert/cmd-editor#1482]
具体环境是这样：

Windows 10 Build 14393.51，以及自带的微软拼音输入法，Chrome 54.0.2824.0

在 Chrome 中访问作业部落，并使用自带拼音输入法输入中文内容时，会遇到一个奇怪的问题。

首先输入拼音内容，此时可以从右侧的预览区域看到，没等选择要使用的中文字符，拼音内容已经「上屏」了：

![image](https://cloud.githubusercontent.com/assets/1009993/17652898/cd646030-62bb-11e6-8e4e-551f39bbd812.png)

随后正常情况下，为了输入正确的中文字，还需要按一下空格，但此时按下空格后，屏幕上显示的只有对应的拼音字符，没有汉字：

<img width="696" alt="0002" src="https://cloud.githubusercontent.com/assets/1009993/17652903/ed234490-62bb-11e6-98d7-ce158a4765fa.png">

只有再次按下空格，汉字内容才会出现，但与此同时，之前已经「上屏」的拼音内容依然存在。

<img width="691" alt="0003" src="https://cloud.githubusercontent.com/assets/1009993/17652905/fe2075ba-62bb-11e6-8b1d-44638ce8a259.png">

这个问题直接导致只使用微软拼音输入法的情况下，在 Chrome 中完全无法使用。但同样的系统，使用 Windows 10 自带的 Edge 浏览器不存在该问题。

**Comment by ghosert** [comment]
我修一下，这个是 CHROME 53+ 引入的问题， 53+ 应该还不是正式版。

**Comment by ghosert** [comment]
已修复。
