### ISSUE TITLE
请求导出HTML的时候一并导出CSS

### ISSUE THREAD

**Issue by SteinX** [ghosert/cmd-editor#149]
如题所述。
我觉得只要能连同css一并导出的话，自己生成PDF也只是举手之劳。虽然有自己搞这条路，但是懒得折腾....（实际上没有CSS，别的倒还好，关键公式比较难看...）。
鉴于原页面的样式还是比较赏心悦目的，故在此请求，望准予，谢谢。

**Comment by yuchuanxi** [comment]
@ghosert 是的呀，导出的html没有css，在某些场景下真的挺糟糕的，希望能提供css

**Comment by ChuckIsReady** [comment]
dui a

**Comment by cntee** [comment]
感觉ｃｓｓ是部落的一个卖点，所以部落不会支持，同样不会支持ｐｄｆ导出的

**Comment by sunxb10** [comment]
+1

并且希望加入自定义 CSS 的功能，用户可以上传自己的 CSS 文件，如果足够 NB 的话还可以在作业部落网上分享 CSS 方案，再搞个投票，比一下人气神马的 @ghosert

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
