### ISSUE TITLE
一篇文章支持的字符数太少了

### ISSUE THREAD

**Issue by SunnyWind** [ghosert/cmd-editor#15]
我写一篇笔记，有点长。。。保存后被截掉了一段= =！！！

**Comment by ghosert** [comment]
你注册时候的用户名给一下

**Comment by SunnyWind** [comment]
lasdtc

**Comment by ghosert** [comment]
你能不能把文章标题给我？或者把这篇文章发布一下，然后把固定链接给我？

**Comment by ghosert** [comment]
文章标题给一下吧，问题还在吗? 不妨答复一下。

**Comment by SunnyWind** [comment]
"OS Note"
这个笔记由于太长一篇存不了，就分两部分存了，后来另一部分被我不小心覆盖了（就是我提的另一个issue囧）
不好意思，没注意到邮件-0 0-

**Comment by SunnyWind** [comment]
http://www.zybuluo.com/lasdtc/note/207
这是链接

**Comment by ghosert** [comment]
两部分合在一起就太长存不了吗？如果是的话麻烦把两部分合在一起发给我 support@zybuluo.com？我再看看是不是会被截掉。

**Comment by SunnyWind** [comment]
另外一部分已经被我误操作删了啊= =
没了，算了吧。
这个的确是有字数限制的吧？

**Comment by ghosert** [comment]
好的，这个问题我试出来了，多谢，标记成 bug 今晚修复：）

**Comment by SunnyWind** [comment]
辛苦！

**Comment by ghosert** [comment]
我修复完了，你再关闭吧，^_^，否则不符合流程。

**Comment by ghosert** [comment]
修复了，你可以再验证一下，原来最多存 64k 大小的文本，现在可以存最多 1024k 应该足够用了。一篇文稿写三十万中文字也没问题了。
