### ISSUE TITLE
是否可以私密发布？

### ISSUE THREAD

**Issue by pengyuwei** [ghosert/cmd-editor#150]
我只想发布文档给指定的人看，最好发布的时候可以设置密码，只有通过这个密码才能看，或者发布的时候指定用户名，只有指定的登录用户才能查看文档。

**Comment by franklinzhang** [comment]
我建议这个功能还是留给导入笔记功能吧 具体的权限由笔记软件实现

**Comment by ghosert** [comment]
不要，我要发布！

**Comment by garyelephant** [comment]
我也希望有这个私密的功能。

**Comment by ghosert** [comment]
这个修复过了。
