### ISSUE TITLE
未登录前的文件，登陆之后，就不见了，怎么找 回啊 啊啊啊啊啊

### ISSUE THREAD

**Issue by hello-sunbaixin** [ghosert/cmd-editor#1505]
未登录前的文件，登陆之后，就不见了，怎么找 回啊 啊啊啊啊啊

**Comment by ghosert** [comment]
不登录的时候输入超过一百字以后，要离开当前页面会提示你是否要离开，会丢失数据，当时应该把数据保存一下。因为没登录，系统不知道要存给谁。
