### ISSUE TITLE
分频实时预览不同步(包含图片)

### ISSUE THREAD

**Issue by IT-matters-24** [ghosert/cmd-editor#1507]
正常情况下, 我写作时进行滚屏, 右侧的预览也会滚屏, 两者保持一致.
但是当源文本出现图片链接时,右侧预览的内容长度和左侧会发生不一致现象.

**Comment by ghosert** [comment]
这个确实没办法，因为一行链接和图片高度相差太多了。

**Comment by IT-matters-24** [comment]
```
        什么叫没办法啊。。。。很影响用户体验啊发自网易邮箱大师
        在2016年08月29日 13:42，Jay Zhang 写道:这个确实没办法，因为一行链接和图片高度相差太多了。
```

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ghosert/cmd-editor","title":"ghosert/cmd-editor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ghosert/cmd-editor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ghosert in #1507: 这个确实没办法，因为一行链接和图片高度相差太多了。"}],"action":{"name":"View Issue","url":"https://github.com/ghosert/cmd-editor/issues/1507#issuecomment-243036503"}}}

**Comment by ghosert** [comment]
没办法就是怎么做都没办法弥合这个高度差。无论用什么办法都不行。
