### ISSUE TITLE
阅读量的机制有问题

### ISSUE THREAD

**Issue by zkip** [ghosert/cmd-editor#1509]
作者发布的文件自己看也增加阅读量，而且每重新访问一次就增加一次，根本不知道别人有没有访问自己的文章，当然也无法获知真实的阅读量．

**Comment by xuzc** [comment]
这个我也发现了，目前的阅读量可以理解为“文稿被打开次数”。如果方便的话，建议改成“独立IP访问量“的统计。

**Comment by ghosert** [comment]
据我所知，大多数阅读平台都是这样处理的，包括微博，阅读量只是个虚指，只要不是刻意刷，有一定参考意义即可。如果一定需要准确的阅读数字，以后在作者后台可以另外提供。太少的阅读量今后不利于吸引其它读者来看。

**Comment by zkip** [comment]
我觉得阅读量是鼓励作者继续写作的最大动力，如果说这个没有参考价值的话，作者就不会知道自己的文章是否受欢迎，这样一来，不好的文章也可以像好文章一样受欢迎，尽管可能是刻意的，在某些时候，很有可能会大规模的误导读者。
另外作为一个独立开发者或者团队来说，保持自己的风格是非常重要的，如果说连独立开发者都要被大势所趋的话，他们就不了独立者了。
在这里我建议将个人更新访问次数的周期更改为一天，这样或许可以有效防止此类事件的发生。
