### ISSUE TITLE
登陆的时候一直提示验证码错误....

### ISSUE THREAD

**Issue by liuweisj** [ghosert/cmd-editor#151]
输入验证码正确的一直提示错误....

**Comment by ghosert** [comment]
换个浏览器多试几次，好了没？故意加了一些容易混淆的字符比如 t 1

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

2014-06-20 14:54 GMT+08:00 liuweisj notifications@github.com:

**Comment by liuweisj** [comment]
多试了几次好了，大概有二十多次。。。我还以为服务器故障呢。。。这么及时。多谢回复。

发自我的 iPhone

**Comment by ghosert** [comment]
还不行？

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2014年6月20日 下午4:22，liuweisj notifications@github.com写道：

**Comment by ghosert** [comment]
噢，好了就好了，抱歉了。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2014年6月20日 下午4:28，Zhang Jiawei ghosert@gmail.com写道：
