### ISSUE TITLE
chrome浏览器输入法问题

### ISSUE THREAD

**Issue by Dikea** [ghosert/cmd-editor#1513]
在chrome浏览器中，如果使用搜狗输入法在线编辑，就会出现打出的字重复的问题，因为这个原因，弃用了zybuluo

**Comment by ghosert** [comment]
Chrome 53+ 会有这个问题，开发环境已经修复了。下周发出来，到时通知在这里。

**Comment by Dikea** [comment]
好的，谢谢^_^

**Comment by ghosert** [comment]
已修复。
