### ISSUE TITLE
为什么现在按Ctrl-V会弹出来一个添加图片链接的玩意。

### ISSUE THREAD

**Issue by LichAmnesia** [ghosert/cmd-editor#1514]
现在在客户端编辑，粘贴命令怎么会变成这样了？

**Comment by ghosert** [comment]
哪个操作系统？出现这个一般是因为剪贴板里有图片内容，这个内容主要是为了方便用户上传图片，复制粘贴即可上传。试试复制一些其它文字内容把图片从剪贴板里清除是不是能解决你的问题。

**Comment by neildocs** [comment]
前几天，我试过是可以直接复制粘贴图片的，今天遇到问题，Ctrl-V，没有能够把图片粘贴进来，而是弹出了插入图片的对话框。要么输入URL，要么从本地上传。好像是个新问题

**Comment by ghosert** [comment]
现在好了吗？看看是不是会员过期了?

**Comment by neildocs** [comment]
Seems fixed 

Sent from iPhone

On Thu, Sep 8, 2016 at 3:19 AM -0400, "Jay Zhang" notifications@github.com wrote:

现在好了吗？看看是不是会员过期了?

**Comment by neildocs** [comment]
似乎修复了，没有出现同样问题。不会是会员问题，按照屏幕提示，非会员可以Ctrl－V粘贴，会员可以上传本地图片

---

Neil Kong
Email:  neildocs@gmail.com

```
    _____________________________
```

**Comment by ghosert** [comment]
谢谢。
