### ISSUE TITLE
Chrome53 输入BUG

### ISSUE THREAD

**Issue by maplejaw** [ghosert/cmd-editor#1521]
自从把Chrome升级到53.0.2785.89 m。输入中文时有个奇怪的BUG，严重影响使用。具体看请看下面动图，下图中我不停的输入测试两个字。
![bug图](http://static.zybuluo.com/maplejaw/u2mldt51c4k3k44n1x1rd0rr/1.gif)

**Comment by ghosert** [comment]
今天发布出来，不好意思。

**Comment by honeway** [comment]
遇到相同问题，严重影响使用
Windows10 
Chrome Version 53.0.2785.89 m (64-bit)
Ubuntu 16.04
Chrome Version 53.0.2785.92 m (64-bit)

**Comment by maplejaw** [comment]
还没有修复吗？ @ghosert

**Comment by ghosert** [comment]
今晚必发！！！

**Comment by ghosert** [comment]
已修复。@maplejaw
