### ISSUE TITLE
bug报告：左侧书写时“*斜体*”在书写侧也显示

### ISSUE THREAD

**Issue by jrmokjq** [ghosert/cmd-editor#1526]
![image](https://cloud.githubusercontent.com/assets/22074798/18347184/c321c308-75f6-11e6-9b92-e9160f84ff54.png)

**Comment by jrmokjq** [comment]
bug报告：左侧书写时“*斜体*”在书写侧也显示

**Comment by ghosert** [comment]
斜体的效果就是要反映在右侧。
