### ISSUE TITLE
输入中文时,会出现文字混乱的情况

### ISSUE THREAD

**Issue by JimmyVV** [ghosert/cmd-editor#1529]
首先,按照中文输入。 比如我想打"这"
但,结果是 "zhe"
然后, 继续打是就会出现"zhe这"

**Comment by zeahoo** [comment]
同样出现这个状况， 输入中文时，中文不显示。 Chrome 版本 Version 53.0.2785.101 (64-bit)

**Comment by JimmyVV** [comment]
... 能版本回退吗？ 这样,这个工具就用不了了... 而且,我还是付费的... 伤心...

**Comment by JimmyVV** [comment]
@ghosert

**Comment by lechengyu** [comment]
chrome浏览器升级后出现了这个问题，版本 53.0.2785.89 m (64-bit)。
用360浏览器没有上述问题。希望尽快修复

**Comment by vsxen** [comment]
@ghosert    

mac   Version 53.0.2785.101 (64-bit) 同样

**Comment by ghosert** [comment]
今晚就上线，上完在这里通知大家，添麻烦了。

**Comment by iulo** [comment]
@ghosert  今晚提示更新后, mac版本无法打开后自动最大化并且功能区无法初始化
OS X 10.11.6

**Comment by ghosert** [comment]
正在修理。

**Comment by ghosert** [comment]
都修复了。
