### ISSUE TITLE
公式输入不能正常显示

### ISSUE THREAD

**Issue by Edenharder** [ghosert/cmd-editor#153]
如$|a|_1 = a_\epsilon$不能正常显示公式，但行间公式$$|a|_1 = a_\epsilon$$能正常显示，且$|a|_1 = a_e$也显示正常。
![issue](https://cloud.githubusercontent.com/assets/6672134/3355382/42d1ad60-fab2-11e3-9aa6-140315d19759.png)

**Comment by ghosert** [comment]
下面是我这边的效果，不知道对不对？chrome 浏览器，Ubuntu 12.04

![screenshot from 2014-06-22 23 36 30](https://cloud.githubusercontent.com/assets/236040/3351878/0bcb86a4-fa23-11e3-824e-db687bfd9178.png)

**Comment by Edenharder** [comment]
chrome， ubuntu 14.04

```
如$|a|_1 = a_\epsilon$不能正常显示公式，但行间公式 
$$|a|_1 = a_\epsilon$$ 
能正常显示，
且$|a|_1 = a_e$也显示正常。
$|g|_a = |g^\ast|_{a,b}$也显示不正常，好奇怪！

```

**Comment by ghosert** [comment]
在两个下划线前加两个\表示转义即可，两个下划线之间的内容表示斜体，如下所示：

`$|a|\_1 = a\_\epsilon$`

**Comment by ghosert** [comment]
可以暂时先这样解决，毕竟也是问题，找时间解决一下。

**Comment by Edenharder** [comment]
@ghosert 嗯，谢谢！遇到时我都写成行间公式，不太习惯加转义，想和latex输入公式习惯保持一致。

**Comment by ghosert** [comment]
已解决，不用再加额外转义符。
