### ISSUE TITLE
邮件认证没有收到

### ISSUE THREAD

**Issue by kainote** [ghosert/cmd-editor#1530]
你好
注册后，邮件认证一直没有收到信件，
重新发送了好几次，没有用，
更换浏览器也一样，
更换备用信箱依然如此，
请问是否有什么地方我没注意到的?
我的信箱是faion1016@gmail.com
用户名 kaifa

以上问题，谢谢

**Comment by peterzhang41** [comment]
我的也是 zhangzehui41@gmail.com
用户名 peterz-zhang

**Comment by ghosert** [comment]
确实是有问题，刚才修好了，邮件已重发。如果邮件过期，可以点击用户设置

https://www.zybuluo.com/settings/account

选择重发验证邮件，还不行的话可以等24小时后重试。

给您添麻烦了。
