### ISSUE TITLE
注册账号始终无法收到邮件，初步怀疑你们的邮箱服务器出问题了

### ISSUE THREAD

**Issue by qinyuanfa1314** [ghosert/cmd-editor#1531]
作业部落的大神们，本人一枚小白，今天注册账号使用作业部落，始终无法收到邮件，切换邮箱也依旧无法收到，建议你们查查什么问题。

**Comment by ghosert** [comment]
谢谢提醒，已经修复了。请重新尝试一下，如果仍然没有成功可以等待24小时之后再试。
