### ISSUE TITLE
更新后客户端打开白屏

### ISSUE THREAD

**Issue by zybl-jim** [ghosert/cmd-editor#1533]
最近更新后打开客户端是这样的，删除了本地的locales文件夹也没有用
![1](https://cloud.githubusercontent.com/assets/22134412/18419272/80d78a42-7889-11e6-9aaa-9847983c9d1d.png)

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下看看。
