### ISSUE TITLE
[bug]星号的匹配检查有问题

### ISSUE THREAD

**Issue by tiomke** [ghosert/cmd-editor#154]
1，`**粗体**和**粗体**` 的显示结果为**粗体**和* _粗体_ *，应该为**粗体**和**粗体**
2，`~~**删除**部分~~`显示结果为~~*删除*部分~~,应该为~~**删除**部分~~。如果`~~[空格]**删除**[空格]部分~~`则无法显示出删除线。
@ghosert

**Comment by ghosert** [comment]
第一个问题已经解决。最近会发布一个更新上去，到时通知你。
第二个问题，删除线的优先级较高，如果一定要有这个效果暂时可以：

`**~~删除~~**~~部分~~`

删除线需要紧跟内容，不能加空格，这个是为了不让删除线内有留白。

**Comment by tiomke** [comment]
谢谢！
@ghosert

**Comment by ghosert** [comment]
第一个问题已经解决了。
