### ISSUE TITLE
相隔较远的有序列表无法识别为一个列表，总是重新开始计数，忽略我标的数字

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [ghosert/cmd-editor#1543]
比如：
1. 标题1
xxxxx
xxxx
xxxx
2. 标题2

输入内容是2.，但预览显示为1.，也就是重新开始了列表而无法与上面的列表关联。word里也有类似的问题。

可以手动解决，但是较麻烦。不知道作者是否有注意到此问题？

**Comment by ghosert** [comment]
列表是指简单列表，不应该包含复杂的列表项。如果需要可以这样

### 1. 标题1
