### ISSUE TITLE
Linux客户端无法打开，一片空白；但网页版可以打开

### ISSUE THREAD

**Issue by yzsatgithub** [ghosert/cmd-editor#1549]
网络正常，客户端等待很久也只是空白。
情况如图：

![2016-09-19 15 18 05](https://cloud.githubusercontent.com/assets/10882352/18624742/721eca44-7e7c-11e6-9670-f442a3c18849.png)

@ghosert

**Comment by ghosert** [comment]
帐号用户名和我说下

**Comment by yzsatgithub** [comment]
@ghosert   yzsatcmdmarkdown   当时网页版正常，但是客户端空白，很多天了。    今天打开客户端，突然间好了，不知道会否复现。

**Comment by ghosert** [comment]
应该是当时网络有问题。每次启动其实会去连一下服务器。

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下客户端看看。
