### ISSUE TITLE
能否提供一个匿名分享功能

### ISSUE THREAD

**Issue by rywiki** [ghosert/cmd-editor#155]
匿名分享，只给一个短链接，然后别人就可以访问了，至于谁创建的，不能被查。比如pen.io这种。不过，这个跟国内的所谓实名是不一致的哦。能加上么？
另外，纯粹的离线版本不知道有没有计划，比如收藏夹代码的版本。不能上网的时候也想用……太贪心了。

**Comment by ghosert** [comment]
离线客户端有了：https://www.zybuluo.com/cmd
