### ISSUE TITLE
界面使用说明&列表序号匹配

### ISSUE THREAD

**Issue by heliar-mk** [ghosert/cmd-editor#156]
除了markdown的语法说明，建议提供下界面各个按钮的功能说明。。
感觉比较分散，刚开始用找不到对应功能的按钮在哪里。
~

**Comment by heliar-mk** [comment]
列表序号的问题是，如果列表连续，编号无问题。
编号之间如果跨代码段，编号就会自动从1开始

**Comment by ghosert** [comment]
界面说明在每个用户第一篇的初始文稿里有。在 Markdown 语法里有序列表是不能跨代码段的。这个时候可以用  `### 1. xxxx` 来表示段落。
