### ISSUE TITLE
建议调低高级会员的价格

### ISSUE THREAD

**Issue by littlebeandog** [ghosert/cmd-editor#1562]
很喜欢这个cmd markdown,感谢作者的用心制作.

关于高级会员的价格,我觉99/年对于绝大多数人来说略显奢侈了一些.
**奢侈**并不是说99元钱很多,而是心理因素.如果定到30左右一年我相信会有更多人选择支持并主动宣传CMD markdown滴.

毕竟屁股才198,还是买断= =

**Comment by ghosert** [comment]
99元用来吃顿饭，也许也就两个小时，吃完也没什么收获。cmd 可以用一整年时间，收获的何止成千上万？
