### ISSUE TITLE
CmdMarkdown的OSX 用户端不能正确生成时序图

### ISSUE THREAD

**Issue by horsefaced** [ghosert/cmd-editor#1563]
Cmd Markdown 的 OSX 端对```seq 语法不支持，不能正确的生成时序图
<img width="524" alt="2016-09-26 08 49 07" src="https://cloud.githubusercontent.com/assets/953648/18819590/1e4785f6-83c6-11e6-8f02-9465fa0ad1cc.png">
<img width="592" alt="2016-09-26 08 49 33" src="https://cloud.githubusercontent.com/assets/953648/18819595/3b920dd4-83c6-11e6-8303-e25557094650.png">
而浏览器版本可以生成，但->这个语法没有生成箭号

**Comment by rgw5267** [comment]
Mermaid可以用```sequence

**Comment by ghosert** [comment]
我会修一下。网页版是好的。

**Comment by ghosert** [comment]
修复了。
