### ISSUE TITLE
Chromium无法渲染粗体 **text**内部在预览框里面显示未粗体，Ubuntu 16.04

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [ghosert/cmd-editor#1568]
你好，Chrome是正常的，只在Chromium里面出现，是渲染方式不同吗？其他效果暂时未测试。由于Ubuntu下没有Chrome只好用了Chromium。

**Comment by ghosert** [comment]
可以使用下客户端或者在网上查找下，其实是有方法使用 CHROME 的。
