### ISSUE TITLE
vim模式在编辑模式下，屏蔽vimium插件功能失效

### ISSUE THREAD

**Issue by ysrcyx** [ghosert/cmd-editor#1575]
在编辑模式中，使用`Esc`或者`Ctrl+[`退出编辑模式后不会进入普通模式，仍由`vimium`插件控制。
- OS: Ubuntu 14.04
- Browser: Chromium 52.0.2743.116
- Vimium: 1.47

**Comment by ghosert** [comment]
可以设置一下 vimium 对于 Cmd Markdown 禁用。

**Comment by ysrcyx** [comment]
感谢作者回答，没注意vimium的这个功能
