### ISSUE TITLE
seq序列图没有显示箭头

### ISSUE THREAD

**Issue by deeepsky** [ghosert/cmd-editor#1579]
``` seq
牌桌->>客户端:GameStart
牌桌->>客户端:WaitCall
```

无论实线还是虚线都没有箭头。
Safari浏览器编辑，没有箭头。
同步到windows客户端，序列图直接显示成了纯文字。

**Comment by ghosert** [comment]
chrome 上好的吗？

**Comment by ghosert** [comment]
修复了。

**Comment by deeepsky** [comment]
仍然不行在 2016年10月11日，上午12:43，Jay Zhang notifications@github.com 写道：修复了。—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ghosert/cmd-editor","title":"ghosert/cmd-editor","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/ghosert/cmd-editor" class="">https://github.com/ghosert/cmd-editor</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ghosert in #1579: 修复了。"}],"action":{"name":"View Issue","url":"<a href="https://github.com/ghosert/cmd-editor/issues/1579#issuecomment-252675163" class="">https://github.com/ghosert/cmd-editor/issues/1579#issuecomment-252675163</a>"}}}

**Comment by ghosert** [comment]
试下 chrome.
