### ISSUE TITLE
光标有点问题，为什么我定位经常比实际位置偏前？

### ISSUE THREAD

**Issue by xzxxzx401** [ghosert/cmd-editor#1586]

**Comment by ghosert** [comment]
自定义样式菜单里设置编辑区的字体，选择一种等宽字体，例如：Consolas, 幼圆, 黑体

**Comment by xzxxzx401** [comment]
谢谢 是我没看到设置里面的提示

Yours,P.H.S
-------- 原始信息 --------由： Jay Zhang notifications@github.com 日期: 16/10/11  00:41  (GMT+08:00) 收件人： ghosert/cmd-editor cmd-editor@noreply.github.com 抄送： xzxxzx401 xzxxzx401@gmail.com, Author author@noreply.github.com 主题： Re: [ghosert/cmd-editor] 光标有点问题，为什么我定位经常比实际位置偏前？ (#1586) 
自定义样式菜单里设置编辑区的字体，选择一种等宽字体，例如：Consolas, 幼圆, 黑体 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ghosert/cmd-editor","title":"ghosert/cmd-editor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ghosert/cmd-editor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ghosert in #1586: 自定义样式菜单里设置编辑区的字体，选择一种等宽字体，例如：Consolas, 幼圆, 黑体 "}],"action":{"name":"View Issue","url":"https://github.com/ghosert/cmd-editor/issues/1586#issuecomment-252674783"}}}
