### ISSUE TITLE
添加自定义快捷键功能

### ISSUE THREAD

**Issue by satgo1546** [ghosert/cmd-editor#159]
Windows下Markdown Pad用习惯了，于是对Cmd Markdown的Ctrl+H作为heading的快捷键很不熟悉……于是默默地手动输入三个#……

还有就是因为我标题1~6几乎都要使用，建议六种标题可以分开设置快捷键。

**Comment by ghosert** [comment]
其实三个 # 可能更快一些。。。

**Comment by satgo1546** [comment]
> 其实三个 # 可能更快一些。。。

对于我这种强迫症来说，继续在末尾输入三个#浪费了很长时间（

所以还是请求添加个快捷键吧（

**Comment by ghosert** [comment]
就开头输三个即可，后头可以省略
`### 三级标题`

**Comment by ghosert** [comment]
添加自定义快捷键会费一些力气，而且每个浏览器的情况也不一样，再加上已经支持了 vim/emacs， 感觉放开以后会更混乱。暂时这个优先级会比较低。
