### ISSUE TITLE
改动无法撤销

### ISSUE THREAD

**Issue by SunnyWind** [ghosert/cmd-editor#16]
全选文章，然后再粘贴一段其它文字，这个操作无法撤销。我的一篇笔记因为误操作一不小心就毁了（哭）。望修复。

**Comment by ghosert** [comment]
ctrl -z 撤销啊

**Comment by SunnyWind** [comment]
我试了试，总算是试出来了一种条件——在文章刚载入（或者切换回编辑器所在标签页），未对文章进行任何修改的情况下，全选并用任一段文字覆盖文章，无法撤销（即使是ctrl+z）。

**Comment by ghosert** [comment]
文章在初始加载的时候，右边预览区会有提示正在加载，你可以等到加载结束再开始编辑，会比较安全。另外可以选择将编辑好的文章发布，这样发布后的文章就不会因为误操作丢失，除非你再次发布更新。

**Comment by ghosert** [comment]
我又试了试，的确有这个问题，Reopen，争取尽早修复。

**Comment by ghosert** [comment]
已经修复了，你可以再试试，哈哈
