### ISSUE TITLE
小bug：用户【注册】——发送【验证邮件】环节

### ISSUE THREAD

**Issue by lxpingguo** [ghosert/cmd-editor#160]
情况描述：
用户【注册】时，当系统发送【验证邮件】后，若此时将信箱内的【验证邮件】永久删除，则无法登陆系统。
系统提示之前已经发送【系统邮件】，需验证后登陆。
点击【忘记密码】选项，修改密码后系统依然提示需要验证。

我的建议：
（1）在用户第一次登陆时，如提示未验证，添加【再次发送验证邮件】选项。
（2）建议【验证邮件】增加验证时效（如：三天内验证链接有效）。

加油！

**Comment by ghosert** [comment]
多谢提醒，帐号设置的页面正在做，这样即使错过第一次验证，也可以继续重发验证邮件，同时在首次注册的时候会适时提醒查收验证邮件。时效在这些功能上线以后会加，目前如果加上，那很多用户过了时效无法验证，也无法再次重发验证邮件。

**Comment by ghosert** [comment]
已实现。

**Comment by lxpingguo** [comment]
在用户第一次登陆时，如提示未验证（已经误删验证邮件），添加【再次发送验证邮件】选项。

**Comment by ghosert** [comment]
这个有的啊。 发自网易邮箱大师 在2015年07月16日 11:01 ，lxpingguo写道： 在用户第一次登陆时，如提示未验证（已经误删验证邮件），添加【再次发送验证邮件】选项。 — Reply to this email directly or view it on GitHub.
