### ISSUE TITLE
请问数字列表超过10后，第一位消失变成0是什么情况

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [ghosert/cmd-editor#1605]
如题。假如数字简单列表的编号达到10，则会变成0,1没了。

**Comment by ghosert** [comment]
请贴一下MARKDOWN源码，我觉得是因为列表里的元素太过复杂了，简单列表最好只包含简单行。

**Comment by WesleyBlancoYuan** [comment]
我刚才打开文档打算贴源代码，发现有更新就更新了，再看已经没有问题了。所以可以close。谢谢！
原文每个数字后面也不复杂，是一个小段落。不超过五行。
