### ISSUE TITLE
在mac上输入中文时光标异常

### ISSUE THREAD

**Issue by xulsup** [ghosert/cmd-editor#1608]
![image](https://cloud.githubusercontent.com/assets/17876392/19521557/a6769dd0-9646-11e6-9ee7-4dc1ad380ba1.png)
虽无使用问题，但是看着特别影响书写心情

**Comment by ghosert** [comment]
ctrl+alt+R 打开设置菜单，从里面选“自定义样式”，把里面的编辑器部分的字体改成等宽字体。例如：Consolas, 幼圆, 黑体
