### ISSUE TITLE
更新版本后，在客户端点击帮助文档，弹出的是空白页(系统是WIN10)

### ISSUE THREAD

**Issue by luckypm** [ghosert/cmd-editor#1609]
更新版本后，在客户端点击帮助文档，弹出的是空白页(系统是WIN10).

**Comment by ghosert** [comment]
当时联网了吗？

**Comment by luckypm** [comment]
连了，用的浏览器是edge，换其它浏览器就可以

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下客户端看看。
