### ISSUE TITLE
用“花儿芬芳”五笔输入的时候，出现奇怪的符号

### ISSUE THREAD

**Issue by xiaoyaoyuxin** [ghosert/cmd-editor#161]
花儿五笔在键入编码时，会在光标处先插一个空白，而反应在cmd markdown上面，就会出现缺少字符的符号
![cmdedit error](https://cloud.githubusercontent.com/assets/8025850/3428900/05108752-0049-11e4-8ffa-d20254464792.png)

**Comment by ghosert** [comment]
输入正常不？这种输入法没见过。。。

**Comment by xiaoyaoyuxin** [comment]
输入正常。这个输入法是用“多多输入法生成器”生成的。

**Comment by ghosert** [comment]
好像是 firefox 的问题，chrome 上没有这个问题。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

2014-07-01 20:24 GMT+08:00 xiaoyaoyuxin notifications@github.com:

**Comment by xiaoyaoyuxin** [comment]
在Chrome上面，虽然不会出现奇怪的符号，但仍会有个空白，会挡住已经输入的文字。也很影响使用的。

如下图：
![1](https://cloud.githubusercontent.com/assets/8025850/3535892/76095fc6-0808-11e4-942d-75c4b7552539.png)

![2](https://cloud.githubusercontent.com/assets/8025850/3535877/3cf55974-0808-11e4-9b7d-cbe666991830.png)

感觉虽然有输入法本身的原因，但修改编辑器的输入特效应该也能解决这个问题吧……
主要是输入法不太可能解决这个问题：（

**Comment by ghosert** [comment]
已解决。
