### ISSUE TITLE
【重要】冲突发生时需要支持选择使用云端文件

### ISSUE THREAD

**Issue by SimpleExpress** [ghosert/cmd-editor#1655]
在电脑A编辑完成并同步后，没有关闭编辑页面将电脑合上休眠。此时来到电脑B继续完成编辑，并完成最终版本。同步之后再回到电脑A想使用CMD+R来重载页面却触发了快捷编辑，发生版本冲突，然而并没有选项可以选择云端版本，导致误操作使最终完成版本消失而使用了本地旧的版本。

这个问题很严重，导致我的数据全丢了！！！

**Comment by ghosert** [comment]
首先看看历史版本里有没有，可以找回来，因为cmd会记录最近二十多个改动。其次电脑A被关闭以后可能是网络也被关闭了，所以没有及时同步，同步的间隔时间大概是几十秒左右。当你再重载的时候因为没有同步过，cmd是检测到了本地版本和服务器上的版本不一致。所以才提示冲突，当提示版本冲突的时候，其实应该更正两边的差异按确定按钮即是云端版本。提示看仔细一些，有机会可以重现一下这个问题。实际上云端版本是默认的，应该是选错了。
