### ISSUE TITLE
未登录之前内容保存bug

### ISSUE THREAD

**Issue by liminjun** [ghosert/cmd-editor#166]
### 登录之前内容需要保存起来

我今天下午在未登录情况下，快写完一篇博客了。我直接点击了右上角那边的发布，提示我要登录。我以为登录之后，我的内容还会保存在那里。但是悲剧发生了，我登录之后，返回到首页时，之前写的博客没有了。这个可以处理一下。好在我的博客不是很长，我重新写一遍。

**Comment by ghosert** [comment]
不好意思了。但是其实没有登录的时候，每次编辑一直在提醒，登录后保存。。。
