### ISSUE TITLE
刚升级会员，导出pdf和印象笔记都失败，麻烦查看下

### ISSUE THREAD

**Issue by yht520100** [ghosert/cmd-editor#1660]
导pdf提示：导出 PDF 文件失败，服务器可能正忙，请稍后再试，或联系我们
导印象笔记提示：导出当前文稿出错，请重试或联系我们，错误详情：fail to convert

**Comment by tingtinglu** [comment]
我也遇到了同样的问题，购买会员10天了，刚开始一周都没有问题，最近两天就出现了同样的问题，无法导出pdf、也无法导出到印象笔记，任何文件都不可以（**# 无论大小和字数**），麻烦帮忙查看一下问题吧，谢谢！

![qq 20161116102700](https://cloud.githubusercontent.com/assets/15806271/20332510/449e0fc4-abe7-11e6-881c-bbee0ce346ff.png)

![qq 20161116102753](https://cloud.githubusercontent.com/assets/15806271/20332518/5944e4c0-abe7-11e6-9cff-79879e0bb663.png)

**Comment by lechengyu** [comment]
出现同样问题

**Comment by linyini** [comment]
同样问题，导出到印象笔记和pdf都失败。

**Comment by tingtinglu** [comment]
其实想弱弱的问一句，是不是因为cmdmarkdown比较小众，所以出现问题才不会很快有效解决呢？觉得正常情况下的cmdmarkdown真的挺赞的，试了很多其他的markdown编辑器，发现cmdmarkdown最适合自己，所以前几天买了会员，但通过最近这2天出现的问题，心里有点忐忑了，未来不会经常出现各种问题吧？因为现在将工作中的文档记录等方面都由它完成了，如果出现问题不能有效解决，真的还挺郁闷了~希望体谅现在的心情.......真的比较着急......

**Comment by ghosert** [comment]
现在已经修复了。不好意思，最近三年只出现过这一次，用户量太大，原来的硬件没撑住，晚上加硬件。
