### ISSUE TITLE
链接特殊字符无法识别和内容无法复制

### ISSUE THREAD

**Issue by beepony** [ghosert/cmd-editor#1661]
非常喜欢 cmdmarkdown，从免费到付费，一直在使用，而且导出的文档美观度超过绝大多数的 markdown 编辑器。现在在使用过程中遇到两个问题，希望 ghosert 帮忙看下。

1. **链接无法识别**               
这个链接可以在浏览器正常打开，但是加入了 markdown 格式之后，无法识别。
http://beepony.b0.upaiyun.com/ipic/geli-1p-KFR-26GW%3A(26549)FNAa-A1-01.png

![snip20161116_157](https://cloud.githubusercontent.com/assets/7813288/20332508/3df2c93a-abe7-11e6-81e8-60639300a6f8.png)

2. **无法在编辑器里复制文本**                  
我印象从应该是可以的，不知道为啥现在不行了。我使用的是 chrome 54 稳定版

![snip20161116_156](https://cloud.githubusercontent.com/assets/7813288/20332527/620e25ee-abe7-11e6-98f0-3b7d47aa66b0.png)

**Comment by ghosert** [comment]
可否把你的图片重命名后上传到 CMD 的云存储上，这个链接太多特殊字符导致解析失败了。
