### ISSUE TITLE
很急。。，。，为什么导出PDF不行了，。，。，

### ISSUE THREAD

**Issue by XQFHNB** [ghosert/cmd-editor#1662]
大哥，写了半天。今天要用到的pdf呀，。，。，

**Comment by kxguo** [comment]
我也是这问题，希望尽快解决啊……只能先存成网页预打印了

**Comment by XQFHNB** [comment]
网页有水印，临时找了其他产品。流程图画好了也不支持。得个教训，以后不能太依赖这个东西。怎么说尼，爱过！！！！！！！！

**Comment by ghosert** [comment]
已经修复了，用户量太大，导致内存爆掉了，晚上加硬件，请继续支持啊！
