### ISSUE TITLE
代码块位于列表内时识别有误

### ISSUE THREAD

**Issue by ZgblKylin** [ghosert/cmd-editor#1665]
## 复现方法
在编号列表内，某项编号后，通过\```编写代码块，且列表下一项与该项间有空行

## bug表现
  - 下一项的列表编号无法正常识别，而是从1开始
  - 之后内容的编辑器高亮错误，识别为代码块的蓝色高亮

## 目前规避手段
 1. 两个列表项间不留空行
 2. 代码块前加入引用符号\> 

## 截图
 1. 通过引用符规避bug https://www.zybuluo.com/ZgblKylin/note/572009
 2. bug复现https://www.zybuluo.com/ZgblKylin/note/572013
 3. 通过删除空行规避bug https://www.zybuluo.com/ZgblKylin/note/572015

**Comment by ghosert** [comment]
简单列表并不能嵌入复杂格式。最好还是自行写一下：

### 1. xxxx
aaaa
### 2. yyyy
bbbb
