### ISSUE TITLE
关于最新发布的绘图功能

### ISSUE THREAD

**Issue by joexi** [ghosert/cmd-editor#167]
先赞一下这个功能 但是目前貌似处理一些复杂流程图的时候力有不逮，例如
![image](https://cloud.githubusercontent.com/assets/3711488/3493881/3ecd1446-05bd-11e4-9749-ea1ca02f9b65.png)

看不清楚整个流程的走向，都重叠起来了

 代码如下

``` flow
st=>start: Start
e=>end
op=>operation: Your Operation
op1=>operation: Your Operation
cond=>condition: Yes or No?
cond2=>condition: Yes or No?
st->op->op1->cond
cond(yes)->cond2(yes)->e
cond(no)->op
cond2(no)->op1
```

**Comment by ghosert** [comment]
原文的例子为了简单处理就那样画了，实际在 no 那个分支应该加个子处理，这样最后的图就不会重叠了，逻辑上也应该再加子处理然后返回重新处理，判断，加上以后应该是这样：

``` flow
st=>start: Start
e=>end
op=>operation: Your Operation
op1=>operation: Your Operation
cond=>condition: Yes or No?
cond2=>condition: Yes or No?
sub=>subroutine: My Subroutine
sub2=>subroutine: My Subroutine

st->op->op1->cond
cond(yes)->cond2(yes)->e
cond(no)->sub->op
cond2(no)->sub2->op1
```

![screenshot from 2014-07-07 19 34 01](https://cloud.githubusercontent.com/assets/236040/3494691/c5a4fec2-05ca-11e4-8257-24a92afaebc6.png)
