### ISSUE TITLE
自动同步功能没有正常启用！而且摁保存也没用！

### ISSUE THREAD

**Issue by Mimotri** [ghosert/cmd-editor#1691]
![image](https://cloud.githubusercontent.com/assets/17059724/20969539/65895bd8-bcc4-11e6-8157-691b7ea833dc.png)
我写了1个多小时！结果什么都没保存，所有东西都回滚了！还玩毛啊？我还边写边保存的，难道不能在本地多保存一些数据吗？无法保存的时候不提示用户的吗？

**Comment by ghosert** [comment]
当时有无提示冲突，合并的窗口，得仔细看看，网络状况如何，当中断过没？
