### ISSUE TITLE
可以加入保存到网盘的功能么?(调用网盘API实现)

### ISSUE THREAD

**Issue by ghost** [ghosert/cmd-editor#17]
可以加入保存到网盘的功能么?(调用网盘API实现)

顺便想问一下作者,是否允许基于您的代码做二次开发?看了一下您的repo,里面似乎没有开源协议的相关信息...

**Comment by ghosert** [comment]
因为网站提供了保存文稿的功能，暂时不准备接入第三方网盘。

目前此项目为闭源项目，无需解释开源协议。

**Comment by ghosert** [comment]
如果有兴趣加入开发，欢迎和我私下联系，哈哈。

**Comment by ghost** [comment]
原来如此,看到这个放在Github上我还以为是开源的呢,是我孟浪了实在不好意思
