### ISSUE TITLE
印象笔记重度用户，保存印象笔记希望可以选择文件夹，并且在印象笔记中可以更改笔记内容

### ISSUE THREAD

**Issue by wanghao200906** [ghosert/cmd-editor#1706]
印象笔记重度用户，保存印象笔记希望可以选择文件夹，并且在印象笔记中可以更改笔记内容 而不是非要用 作业部落，感觉被绑架了0，0
![image](https://cloud.githubusercontent.com/assets/10395483/21168748/95260c10-c1f1-11e6-9e88-f9d4382c1c49.png)

**Comment by ghosert** [comment]
双向编辑是个难题，没法完全原样输出成 Markdown。 文件夹可以在印象笔记那边选择，这样以后每次导出都会保存在你选择的那个文件夹里了。

**Comment by olafchou** [comment]
@ghosert 根本不能选择
