### ISSUE TITLE
明明点了“立即同步” 也显示同步了 但是内容居然丢失了100多行 第二次了 心累不爱

### ISSUE THREAD

**Issue by loszer** [ghosert/cmd-editor#1717]

**Comment by ghosert** [comment]
立即同步是指同步所有文档，当前文档实际上每次击键只要联网都会保存，没有联网会先存本地缓存，等有网络的时候再同步。你这个情况应该会有处理冲突的窗口显示，看看有没有这个窗口？有的话需要注意处理，不要直接关闭。

**Comment by loszer** [comment]
好开心，刚刚开机的时候，丢失的内容突然回来了。我知道，有那个显示冲突并且编辑的窗口是吧，我之前遇到过，不过这次“丢失”不一样，我想关机（mac）的时候，它弹出类似alert那种窗口提示我，内容没有同步，请不要退出（原话不记得了）。但是，我明明手动点了立即同步的，也显示同步完了。然后关掉，然后“没了”，再现在内容回来了。。。未解之谜。。。不过，还是感谢回复
