### ISSUE TITLE
导出到evernote提示“离线状态下无法使用此功能，请连接网络后重试。”

### ISSUE THREAD

**Issue by ccorzlol** [ghosert/cmd-editor#1722]
导出的时候提示这个错误，上网连接没有问题，网页可以打开，查看了evernote那边的设置，并没有发现evernote的访问权限的记录。同时cmd markdown也没有提示要重新绑定。估计是哪里设置不对？导出的时候并没有提示evernote账号到期，重新绑定之类的

**Comment by ccorzlol** [comment]
任何笔记都无法同步到evernote...已经发邮件到support@zybuluo.com，但是没响应，来github试试看能不能得到回复

**Comment by ghosert** [comment]
已经修复了。
