### ISSUE TITLE
和GitHub渲染效果不一致

### ISSUE THREAD

**Issue by chenjiaxi1993** [ghosert/cmd-editor#1727]
在CMD markdown上编写后输出的.md放到Github上后，渲染效果很不一致，如#后不需要加空格，在CMD里也可以生成，但在GitHub上就不可以，还需要做很多调整才能保证效果一致，能否有选项支持完全一致，在CMD上编写的.md不需要再修改就可以保持和Github风格一致。

**Comment by ghosert** [comment]
不太想和别人兼容，否则没法做下去了。我们支持的效果更多。
