### ISSUE TITLE
编辑时总是出现「人工合并文稿版本」

### ISSUE THREAD

**Issue by Yoona0603** [ghosert/cmd-editor#1734]
这个问题在之前虽然偶尔出现，但并不频繁，于是便没多在意。可是最近则是经常出现，高峰期编辑1-2个字就会出现一次。有试过重新下客户端，但还是无法解决。希望作者能解决一下这个问题，非常影响写作，谢谢。ps：目前发现该问题在客户端出现，网页端貌似没有发现。

**Comment by ghosert** [comment]
关键是本地网络要通畅，看看有没有全局代理之类的东西，去掉试试。

**Comment by Yoona0603** [comment]
本地网络顺畅，已确定没有任何代理服务器或者VPN。如果是网络方面的问题，那么网页端应该会有同样的问题出现。我之前试过重下客户端，在那一段时间内该问题的出现频率就很小，可以说没有。可是过了一天之后问题依旧。我有另外一台笔记本进行相同文档的编辑，这是否会导致该问题的出现？

**Comment by ghosert** [comment]
如果没有别人用同样的帐号在编辑应该不会，另一台笔记本如果同时有人在编辑会有这个问题，如果你在编辑的时候，没有人在那台笔记本上同时编辑，应该不会。

**Comment by Yoona0603** [comment]
的确，若是这样的话我能够理解，但据我所知并没有别人知道我的账号，所以该可能性很小。另外，根据重新下载客户端和网页端不会出现问题的情况来看，我判断是本地客户端的文件出现了问题。有没有可能是客户端的配置文件在同步过一段时间之后就会出现同步错误？刚才测试过VPN（连至香港，ping 15ms）问题依旧。在退出客户端的时候也总会提醒：正在保存文档，若退出则会丢失文件（大概意思）.

**Comment by ghosert** [comment]
配置不会影响网速，从提醒来看，确实是客户端网速出现了问题。重新下载安装试试？或者有没有本地防火墙对这个客户端的网络链接进行了单独的限制？

**Comment by Yoona0603** [comment]
防火墙并没有限制其网速。重新下载客户端之后问题暂时解决，感谢您的协助。若日后使用中该问题再度发生，我会与您联系。再次感谢。
