### ISSUE TITLE
同文档引用及代码中超链接功能

### ISSUE THREAD

**Issue by SNY7** [ghosert/cmd-editor#174]
希望超链接可以增加同文档引用功能，例如“详见 3.2 xxx说明”
希望代码中也可以使用超链接，及同文档引用功能，谢谢。

另外请问序列图可以调整顺序吗，现在貌似只能按照节点的出现顺序为准

**Comment by ghosert** [comment]
超链接可以对文档内的标题做跳转，例如你这个，假设是一个三级标题 `### 详见 3.2 xxx说明` 可以直接引用为：
`[描述](###详见-3.2-xxx说明)`
注意空格需要用 - 来替换。

代码段中不行了，可以在代码段前后加一些说明或者跳转。

序列图顺序按自然顺序来，暂时也不能调整。

**Comment by SNY7** [comment]
原来如齿，谢谢~
