### ISSUE TITLE
Ctrl + S 保存问题

### ISSUE THREAD

**Issue by sunorry** [ghosert/cmd-editor#175]
写代码时由于习惯经常按 Ctrl + S ，即使换成 Sublime 也是经常这么干。

发现在**简书**上也是自动保存，然后在你按 Ctrl + S 的时候也是保存操作，而不是弹出_另存为页面_的对话框。

这不是 bug ，而是一个小建议。

**Comment by wz520** [comment]
Vim 模式里经常 :w 回车的撸过……
还好因为在 cmd-editor 的 Vim 模式里 : 完全没用，不会导致什么副作用(也就向右移动了几个字符而已)

**Comment by ghosert** [comment]
ctrl s 已经被禁止再弹出另存为对话框。 Vim :w 回车也已经完全没有副作用。
