### ISSUE TITLE
同时编辑一个文档导致覆盖

### ISSUE THREAD

**Issue by JarodLi** [ghosert/cmd-editor#176]
两台PC上打开了同一份文档，A上的修改自动保存到云端，B未重新打开该文档而直接去编辑，导致A的修改被覆盖。
保存时能否判断一下版本号，不一致的话提示update？

**Comment by ghosert** [comment]
这个提示是有的，只是不太明显，工具栏的保存字样会变红，而且提示保存错误，的确可以把这个提示变得更明显，谢谢。

**Comment by ghosert** [comment]
现在已经没这个问题了，这种情况下会自动尝试合并，无法合并会提示冲突，然后要求手动合并。
