### ISSUE TITLE
建议-将预览收起

### ISSUE THREAD

**Issue by ghost** [ghosert/cmd-editor#1773]
建议做一个像StackEdit那样的收起预览窗口的功能，经常左右分屏，一边看书一边记笔记，这个时候本来就不宽的窗口硬生生又被分成了两部分，十分地糟心，况且写Markdown本来就不需要实时的看预览效果，Markdown的思想不正是让你专注于内容而不是样式吗？

**Comment by ghosert** [comment]
可以点击编辑区左上角第三个按钮，或者使用快捷键 ctrl + m 按一次进入全屏编辑，再按一次返回左右两屏。
