### ISSUE TITLE
文档丢失

### ISSUE THREAD

**Issue by JarodLi** [ghosert/cmd-editor#178]
3000多字的文档突然就变成空白了！之前还遇到过几处修改莫名其妙被回退的情况。
不丢数据是最基本的可靠性。

**Comment by ghosert** [comment]
你说的这个问题是不是和你同时用两个浏览器操作同一个文档有关？

请提供一下你的用户名，我去服务器的日志里把文章找回来。

**Comment by ghosert** [comment]
希望没有太多损失。这种情况你是第一个提，你提供一下用户名，我查一下原因。

**Comment by JarodLi** [comment]
应该和开两个浏览器没关系，发现前面提交的修改被覆盖的问题之后我就只用一个窗口操作了。
文档倒是没丢多少，本地有备份，现在已经恢复。
我用的是vim模式，就像是浏览器突然卡了一下内容就不见了，重新打开提示“正在打开用户图片，请稍后”之类的。
我的账号：alilijian@aliyun.com
顺便问一句，为什么要关闭这个问题呢？

**Comment by ghosert** [comment]
噢？你是阿里云的人啊，你给我这个阿里云上的 Markdown 打折吗？o(∩∩)o...哈哈。

开着影响不太好，在保护文档方面做了很多事情，不想打击用户信心，以前也没有人遇到过，你的例子需要好好查看日志研究一下。你是哪个浏览器 chrome ?windows ? linux ?

**Comment by JarodLi** [comment]
不是阿里的哈，只是注册了个邮箱而已~
我是做存储的，所以比较关注可靠性。
用的是firefox，win7。

**Comment by JarodLi** [comment]
我知道你是谁了，张佳伟~

**Comment by ghosert** [comment]
怎么了，你认识我？

**Comment by JarodLi** [comment]
我就是在知乎上看到你的文章才用的cmd markdown，呵呵

**Comment by ghosert** [comment]
多谢多谢。。。

**Comment by JarodLi** [comment]
请教一个markdown语法的问题哈。
引用区块里如何显示缩进和换行？谢！
![2014-07-11 20 02 28](https://cloud.githubusercontent.com/assets/3362590/3552231/b2defa1e-08f3-11e4-9c37-de7a15db5df6.png)

**Comment by ghosert** [comment]
好像真不行，语法就是这样的。

**Comment by JarodLi** [comment]
刚刚试了下，马克飞象是可以的。
![2014-07-11 20 12 23](https://cloud.githubusercontent.com/assets/3362590/3552289/ced1f2ca-08f4-11e4-97da-c28119c2cb87.png)

**Comment by ghosert** [comment]
了解，是否可以重发一个 issue ？我解决下。

**Comment by JarodLi** [comment]
我能不能提左右两侧文本没有对齐的问题？

**Comment by ghosert** [comment]
怎么不齐了？

**Comment by ghosert** [comment]
同步率依然世界第一，如果你比较一下其它系统。。。

**Comment by Remaineey** [comment]
内容发布过，但是本地与发布过的不同步，本地部分内容丢失
