### ISSUE TITLE
为什么不支持html的表格？？

### ISSUE THREAD

**Issue by SunnyWind** [ghosert/cmd-editor#18]
如题

**Comment by ghosert** [comment]
表格参考：

http://www.zybuluo.com/mdeditor?url=http://www.zybuluo.com/static/editor/md-help.markdown

例如：

| 项目 | 价格 | 数量 |
| --- | --: | :-: |
| 计算机 | $1600 | 5 |
| 手机 | $12 | 12 |
| 管线 | $1 | 234 |

html 暂时不支持，防止恶意攻击

**Comment by SunnyWind** [comment]
这样啊。谢啦！
