### ISSUE TITLE
文档无法同步，账户无法登录

### ISSUE THREAD

**Issue by mritd** [ghosert/cmd-editor#1800]
当前时间 2017-03-01 10:15 

Chrome 下出现文档点击同步无效，状况为显示已经同步完成；新建标签页打开后文档被重置；开匿名标签页登录一直提示密码错误，所幸的是习惯写完发到个人博客，文档尚未丢失

**Comment by mritd** [comment]
补一张图 
<img width="1361" alt="jietu20170301-222135" src="https://cloud.githubusercontent.com/assets/13043245/23463787/be1b4e64-fecd-11e6-9f15-efa918454460.png">

**Comment by mritd** [comment]
这算是停止维护了？？？

**Comment by mritd** [comment]
准备放弃 转 mweb

**Comment by ghosert** [comment]
不好意思刚看到。。。应该是网络出现问题，所以内容没有被保存到服务器上，这个时候你又要准备撤离，所以开始提示你是否真的要离开本站，因为离开以后内容就会丢。不算BUG，算是个 FEATURE。
