### ISSUE TITLE
Markdown的表格问题100%概论出现

### ISSUE THREAD

**Issue by pathing** [ghosert/cmd-editor#1807]
![1](https://cloud.githubusercontent.com/assets/11513848/23584931/e7bd84a0-01aa-11e7-90d4-c4afead314dc.png)

Markdown如何画出上面那种表格呢

**Comment by ghosert** [comment]
可以自己写 HTML 片段，查看这个例子： https://zybuluo.com/mdeditor?url=https%3A%2F%2Fzybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#14-html-标签
