### ISSUE TITLE
引用区块无法显示缩进和换行，且左右文本未对齐

### ISSUE THREAD

**Issue by JarodLi** [ghosert/cmd-editor#181]
![2014-07-11 20 19 06](https://cloud.githubusercontent.com/assets/3362590/3552337/b6d7365c-08f5-11e4-8d0e-52aa44c184a2.png)

**Comment by ghosert** [comment]
渲染区的元素譬如标题需要更多留白空间使得整体美观，编辑区则需要紧凑书写，因此没有必要在此完全一一对齐，原则上当长篇幅书写时，保证滚动区域两侧对齐，可见使得预览和书写区域都在视图范围内即可。 Cmd Markdown 在这方面的同步算法已然最优。

**Comment by ghosert** [comment]
换行已修复，可以去站上看看，缩进看了一下主流编辑器，包括 github 这边都没有刻意实现。

**Comment by JarodLi** [comment]
看了下，换行确实已经ok了。
张兄你真是敬业，那么晚了还在改bug。

**Comment by ghosert** [comment]
怕你们不满意呗。

**Comment by JarodLi** [comment]
引用区块中，两个单词之间的TAB被替换成了空格。这是不是问题？

**Comment by ghosert** [comment]
这个是故意的。
