### ISSUE TITLE
mac客户端以离线模式打开文稿最后还会上传到服务器

### ISSUE THREAD

**Issue by soniashiss** [ghosert/cmd-editor#1814]
mac客户端以离线模式打开本地文稿最后还会和服务器同步，而且保存的时候本地文稿也不会更新，严重涉及泄密，麻烦尽快修复！

**Comment by neildocs** [comment]
这个有点严重，能细说是怎么的情况吗？是怎么发现后台偷跑的？如果Mac有问题，windows也一样。本质上本地客户端就是套了一个壳

**Comment by ghosert** [comment]
应该不会，请提出证据。

**Comment by neildocs** [comment]
我也希望@soniashiss可以详细解释一下，如果为真，是一个很严重的问题。

**Comment by soniashiss** [comment]
两台Mac A和B，通过坚果云同步文档；mac A上离线创建文件后在本地文件夹下找到了，此时OK；回家用mac B打开离线文档编辑后保存（确定肯定以及一定没有切换到在线的情况），再回到mac A上找我的文件发现还是老版本；最后在在线文档中发现了文件的最新版本
PS：
1. 已经弃用，你们解不解决我都不care了，用脚投票
2. 3月份的问题5月底才有回复，回复还是直接肯定不会，让我提出证据；好那就等我提呗，但是直接回完就closed，这不应该是一个收费的平台该有的态度。
3. 综上，cmd markdown一生黑
