### ISSUE TITLE
提议：显示标题

### ISSUE THREAD

**Issue by tiomke** [ghosert/cmd-editor#183]
文档写得比较长的时候，不能直观地看到文档的标题，需要点击内容目录才看到。在同时编辑多个markdown文件时有一点点麻烦。

**Comment by ghosert** [comment]
为了使得界面更简洁，所以不再用额外的空间显示标题了。一般人写文稿还要看标题的意义不大，应该不会忘记到底自己在写什么。如果需要可以按 ctrl+alt+f 或者 ctrl+alt+o 快捷键來查看。多个 markdown 可以开多个 chrome tab。
