### ISSUE TITLE
建议添加一个「取消Tips」的功能

### ISSUE THREAD

**Issue by yunlux** [ghosert/cmd-editor#184]
每次点新建文稿都会显示：

> # 在此处输入标题
> 
> 标签（空格分隔）： 未分类
> ---
> 
> 在此输入正文

竟然还要手动删除Tips，这是啥设计？

原本Markdown的用意就是要摆脱鼠标，这样又要点击又要圈选，蛋疼不？

**Comment by ghosert** [comment]
Markdown 文法在大多数人中尚未普及，此举是为了照顾新手。

如果你用心看一下。新建文稿后的光标是放置在标题末尾的，你只需要按几个回退键删除 “在此输入标题” 再输入新标题就可以了。

其它标签，正文一样处理，如果你习惯键盘，不想用鼠标，自然会用键盘上下左右移动，删除不需要的部分，如果你还会 vim ， 菜单里也放置了，键盘操作效率会更高。

再不然，大多数人都会用的功能是  ctrl + a 全选，然后按一个 回退键 删除全部模板内容。

绝对算不上蛋疼。

以后我会加一些空白模板，和其它类型的模板。
