### ISSUE TITLE
建议增加导出时取消语法高亮的选项

### ISSUE THREAD

**Issue by switchball** [ghosert/cmd-editor#185]
先描述一下我遇到的问题：我用的是Mathematica语言，语法高亮暂时不支持，这时系统便会用一种默认的语法高亮形式。在导出成html的时候，代码段便会有很多的span。这不太利于之后的处理。

我设想的解决方法是：在```的代码段里，增加一个不使用语法高亮的选项，如把语言设成“none”之类，最后导出时只要有&lt;pre&gt;标签即可。

代码可类似如下：
&#180;&#180;&#180; none
Some Mathematica Code
&#180;&#180;&#180;
导出的时候这部分变为形如&lt;pre class="none"&gt;Some Mathematica Code&lt;/pre&gt;的样子

然后我就可以对导出后的文档再做一些处理了，不需要增加对更多语言的支持，只要增加一个取消语法高亮的选项即可。希望能增加这样的一个小功能。

**Comment by ghosert** [comment]
那不如你书写的时候直接不要用 ``` 的形式了？

**Comment by switchball** [comment]
对哦，我没想到这个办法，那就可以做啦，多谢！
