### ISSUE TITLE
2017-04-14 下午八点，服务器貌似挂了一会儿？

### ISSUE THREAD

**Issue by Alexander-flyer** [ghosert/cmd-editor#1855]
链接超时，大概有个五分钟的样子。

**Comment by Alexander-flyer** [comment]
还有个问题，不知道写在这里能不能看见23333
能不能标注下创建时间？每次更新了文档之后，链接只能看见最后一次提交的时间，看不到文档创建时的时间。

**Comment by ghosert** [comment]
遭遇了ddos攻击。使用 ctrl + alt + i 会有创建时间的。

**Comment by Alexander-flyer** [comment]
如果不介意的话，我是说，链接被分享出去之后，读者看不到文档的创建时间。

2017-04-16 22:25 GMT+08:00 Jay Zhang <notifications@github.com>:

**Comment by ghosert** [comment]
嗯，只能看到更新时间。
