### ISSUE TITLE
插入过多emoji表情时导出到印象笔记时会卡住

### ISSUE THREAD

**Issue by Kuohao-wu** [ghosert/cmd-editor#1862]
#### 导出卡住
![image](https://cloud.githubusercontent.com/assets/16506726/25211700/0cb56912-25b9-11e7-84b8-4c12b96cbe48.png)

#### 切换文档时提示未保存
![image](https://cloud.githubusercontent.com/assets/16506726/25211749/5c610da4-25b9-11e7-9970-2d23939f745b.png)

**Comment by Kuohao-wu** [comment]
手动保存仍不能保存最后一个版本，希望能跟进一下，谢谢。

**Comment by Kuohao-wu** [comment]
重新新建一个笔记又不会，可能我操作有问题。以后如果发现bug再来提

**Comment by ghosert** [comment]
好，你再观察观察，有问题再重开。
