### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by mritd** [ghosert/cmd-editor#1865]
死活提示验证码不对，根本无法登陆

**Comment by mritd** [comment]
已经验证了，后端有非常二的验证拦截；重装系统前两次密码输入错误，后续直接 block，一点提示没有，死活就是验证码错误；挂梯子登录，直接不显示验证码，等我有时间把 MD 全部导出，重要东西放里面太不靠谱了，而且连个 QQ联系方式也没有，只能发 issue，逗我呢

**Comment by ghosert** [comment]
注意大小写
