### ISSUE TITLE
win64客户端无法登陆

### ISSUE THREAD

**Issue by xuesu** [ghosert/cmd-editor#1869]
![capture](https://cloud.githubusercontent.com/assets/7857599/25370650/bd05ffa8-29be-11e7-9ac8-38efb9474c67.PNG)
win64版，明明连上了wifi但是却显示离线状态无法连接
@ghosert

**Comment by ghosert** [comment]
看看网页版能打开吗？是不是局域网屏蔽了 www.zybuluo.com 这个域名。

**Comment by xuesu** [comment]
能，不过有时候明明点了某篇文章却不能跳转，所以一般不用

**Comment by xuxinyi5354339** [comment]
非常抱歉，嗯换了网络可以使用了，果然还是网络的原因，谢谢

**Comment by xuesu** [comment]
非常抱歉，嗯换了网络可以使用了，果然还是网络的原因，谢谢
