### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by cuckootan** [ghosert/cmd-editor#187]
第一个问题是，最近老是打不开网页，想整理下最近学习的笔记都不行，很催泪。。。
第二个问题是，可以开发个pc版的客户端，这样离线也可以进行编辑了，纵使在一些地方上不了网或者服务器异常，也可以轻松搞定学习笔记。

**Comment by ghosert** [comment]
噢？打不开？不会啊。。。。这几天呢？你人在国内还是国外？

**Comment by ghosert** [comment]
已经有离线客户端：https://www.zybuluo.com/cmd
