### ISSUE TITLE
mac客户端 空白

### ISSUE THREAD

**Issue by preke** [ghosert/cmd-editor#1872]
![image](https://cloud.githubusercontent.com/assets/11256346/25473499/413c1ace-2b62-11e7-885a-c2f7dc140472.png)

浏览了一些issues
发现没有这样的问题
mac版本10.12.3
cmd markdown32位和64位都试过了
选择不明身份开发者那里也选了
还是这样的问题？

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下客户端看看。

**Comment by preke** [comment]
Thank you! It did work!
