### ISSUE TITLE
Can I apply for refund?

### ISSUE THREAD

**Issue by xinmeng1** [ghosert/cmd-editor#1875]
Can I apply for a refund? 

I just use the premium member for less than a month and I found the advance function is useless for me.

1. The Evernote sync cannot see the Synced status.
2. There is one time for losing part of an article. (maybe I close the editor too quick)

**Comment by Digi1980s** [comment]
I demand a refund.

Get no response at all from support@zybuluo.com for over 96 hours.

**Comment by ghosert** [comment]
Email is blocked by GFW these days, please add my wechat "ghosert" for refund.

**Comment by ghosert** [comment]
@Digi1980s  sent refund to you.
