### ISSUE TITLE
版本：win10 64 ；使用vim模式无法关联剪切板寄存器；

### ISSUE THREAD

**Issue by lhstock** [ghosert/cmd-editor#1884]
具体情况是这样：
我使用的是vim 模式；然后想把内容复制到别的文本文件中；但是 ggVG 全选 “ +y ” 复制 “ +p "粘贴 或者Ctrl + v 依旧是之前的文本；经测试指令是正确的。不知道是否markdown关联寄存器有错误；有没有办法解决

**Comment by ghosert** [comment]
寄存器要求太高了，毕竟web上操作不了系统剪贴板。但是 ctrl-c / ctrl-v  足够了。
