### ISSUE TITLE
行内公式不能正常显示

### ISSUE THREAD

**Issue by boathit** [ghosert/cmd-editor#190]
$\ {x \mid  \ | x-x_c \ |_2 \leq r \ }$

第一， { }无法显示；第二，范数符号显示出来的是绝对值符号 (为了在github上显示上述latex源代码，我在转意字符后加了空格，测试时记得去掉)

**Comment by sunxb10** [comment]
试试这个：

`$\lbrace x \mid \parallel x-x_c \parallel_2 \leq r \rbrace$`

以及

`$\\{x \mid \\| x-x_c \\|_2 \leq r \\}$`

Cmd Markdown 中**行内公式**和**行间公式**有很大区别，一些指令如`\{`、`\}`、`\|`、`\,`都只在行间公式中有效，在行内公式中使用时需要在前面再加个`\`。作为一种替代方案，可以使用`\lbrace` （左大括号）、`\rbrace`（右大括号）、`\parallel`（范数符号）、`\;`（空格），这些指令在行内公式和行间公式中都能使用。

**Comment by ghosert** [comment]
已解决。

**Comment by ghosert** [comment]
已解决。
