### ISSUE TITLE
代码能不能不拷行数,只拷贝代码段

### ISSUE THREAD

**Issue by oncealong** [ghosert/cmd-editor#191]
十分感谢您的奉献,用着十分好用,通过将cmd markdown写出来的东西导出为html后,博客的排版瞬间高大上了许多.
但是我感觉不仅需要考虑书写者的感受,也要考虑阅读者的感受.感觉现在的cmd markdown中代码功能有点不好,因为用户如果想copy下来代码来试运行,会直接将前面的行号也给拷贝下来,十分影响感受,希望能改进.

**Comment by ghosert** [comment]
好像是的，要不先在 firefox 里拷贝，那里不会把行号拷下来。
