### ISSUE TITLE
是否可添加秘密发布？

### ISSUE THREAD

**Issue by geeklive** [ghosert/cmd-editor#192]
用过若干markdown编辑器，还是习惯cmd markdown，不过写项目文档时候由于公司机密型，需要分享给置顶的几个人看，而目前只支持公共发布后才能有分享链接，能否添加秘密发布，链接给指定人需要输入密钥查看？若无的话，只能用马克飞翔导出到evernote去控制分享权限了- -

**Comment by Zjmainstay** [comment]
+1

**Comment by ghosert** [comment]
目前属于半公开，因为陌生人无法知道你的文档链接。私密发布会做，用发布到组织的形式。请耐心等待更新。

**Comment by ghosert** [comment]
现在发布的时候可以选择设置访问密码，导出到 Evernote 也已经支持了。https://www.zybuluo.com/ghosert/note/102771
