### ISSUE TITLE
输入正则表达式时,有不必要的转义

### ISSUE THREAD

**Issue by oncealong** [ghosert/cmd-editor#193]
\w+([-+.']\w+)_@\w+([-.]\w+)_.\w+([-.]\w+)*

``` C#
\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*
```

大段代码段的时候,可以用`来标识,但是如果我一段话里要用到正则表达式的话,会转义成另外一个语句,就像上面看到的,分别是直接输入和用`标识的

**Comment by sunxb10** [comment]
大段代码块用 <code>```</code> 来标识：
- 输入：
  ```
  \w+([-+.']\w+)@\w+([-.]\w+).\w+([-.]\w+)*
  ```
- 输出：
  
  ```
  \w+([-+.']\w+)@\w+([-.]\w+).\w+([-.]\w+)*
  ```

---

段内代码用 <code>`</code> 标识：
- 输入：
  使用正则表达式 `\w+([-+.']\w+)@\w+([-.]\w+).\w+([-.]\w+)*` 即可匹配所需内容
- 输出：
  使用正则表达式 `\w+([-+.']\w+)@\w+([-.]\w+).\w+([-.]\w+)*` 即可匹配所需内容

---

你提问中的<code>`</code>符号有些被 GitHub 的 Markdown 编译器解析掉了，所以我不太清楚你的意思，只能猜测你要问的是“**如何输入段内代码**”。如果上面的回答还不能满足你的需求，最后只能祭出大杀器了：HTML 标签。 Markdown 支持 HTML 标签，可以直接使用 <code>code</code> 标签输入代码（但这样做有违 Markdown 的哲学和设计初衷，不推荐这种做法）。
