### ISSUE TITLE
希望增加类似于z-tree的功能，需要展现文件组织结构的时候需要

### ISSUE THREAD

**Issue by huang-xiao-jian** [ghosert/cmd-editor#194]

**Comment by ghosert** [comment]
有例子给我看看吗？

**Comment by ghosert** [comment]
噢，就是文件夹功能？感觉现在更流行直接打标签，然后搜索，比一级一级找目录方便。开发代价也小些。

**Comment by huang-xiao-jian** [comment]
抱歉，之前描述错误。就是需要描述整个文件组织结构，想下面这样![tree](http://ww4.sinaimg.cn/mw690/9be5b15ejw1ejg01vlflej20b207omxe.jpg)

**Comment by ghosert** [comment]
目前只有标签和属于标签的文件两个层次。暂时不准备加多层级了。
