### ISSUE TITLE
这个markdown怎么不能右边同步

### ISSUE THREAD

**Issue by olafchou** [ghosert/cmd-editor#1947]
[](url)
<img width="737" alt="2017-06-29 08 31 17" src="https://user-images.githubusercontent.com/19890798/27666300-6d4ca3da-5ca5-11e7-92ce-8a280bae681e.png">

**Comment by olafchou** [comment]
还有这个markdown免费功能有啥用，又不能导出。。。。。。。。

**Comment by yuanzhimeng** [comment]
在``` js之间加一个空格
免费可以做笔记多终端备份, 这个软件本来就是写文档的

**Comment by ghosert** [comment]
最后三个 ``` 顶格写试试。
