### ISSUE TITLE
Title应该加粗处理吧。

### ISSUE THREAD

**Issue by Wizmann** [ghosert/cmd-editor#195]
否则`<h4>`/`<h5>`这样的title比正文还不显眼。

建议把正文大小调小。然后将`<h>`加粗处理。谢谢。

**Comment by ghosert** [comment]
正文太小字体看起来很累。 一般常用 h1 h2 h3 已经足够用， 满屏加粗的效果其实不如现在淡雅清风，当初就是从那个效果改过来的。

**Comment by Wizmann** [comment]
斜体也行啊。。。我这边一般都能到h4/h5的。。。

**Comment by ghosert** [comment]
新版本里重新调整过 h1 - h6 的大小了，等更新通知。
