### ISSUE TITLE
左边编辑区有bug：不能复制；删除字符会一下子删除2个

### ISSUE THREAD

**Issue by 52fhy** [ghosert/cmd-editor#1951]
左边编辑区有bug：不能复制；删除字符会一下子删除2个

**Comment by 52fhy** [comment]
![e](https://user-images.githubusercontent.com/8773263/27759170-08b21e60-5e5c-11e7-9221-2ad46c9dc7ae.gif)

**Comment by ghosert** [comment]
去设置里改一下编辑器字体，改成一种等宽字体，就好了。

**Comment by 52fhy** [comment]
然而并没有什么卵用。。。您也不测试就关闭了这个issue？用户体验现在不重要了么

**Comment by 52fhy** [comment]
还有编辑区为什么禁止复制呢？之前一直很好用的

**Comment by ghosert** [comment]
ctrl+alt+R 打开设置菜单，从里面选“自定义样式”，把里面的编辑器部分的字体改成等宽字体。例如：Consolas, 幼圆, 黑体

**Comment by ghosert** [comment]
之前有人提过，都是这么解决的，所以我就关了。复制可以直接用快捷键复制 Ctrl+C 这种。

**Comment by 52fhy** [comment]
感谢您的回复。经过测试，发现是浏览器插件tampermonkey导致的，禁用就可以了。不用设置字体，默认的挺好
