### ISSUE TITLE
插入图片我cmd+v 为毛给我出来一个对话框

### ISSUE THREAD

**Issue by echoChenH** [ghosert/cmd-editor#1954]
插入图片我cmd+v 为毛给我出来一个对话框
![image](https://user-images.githubusercontent.com/29135608/27761086-20840b76-5e88-11e7-96b8-5f776908ec59.png)什么意思呢~ 我会员过期了吗

**Comment by echoChenH** [comment]
速度回答啊 搞得我写文档头很疼

**Comment by yuanzhimeng** [comment]
哎, 上传文件你总要告诉人家图片在哪吧, 
第一种方式(外链):
直接输入图片地址即可(如果你不懂外链, 或者没有忽略这种方式)
第二种方式(上传本地文件):
点击上传本地图片或附件按钮, 会打开文件对话框, 选择文件上传即可
第三种(剪切板):
如果你是用QQ等截图工具, 截图会直接存在剪切板中, 在cmd markdown编辑器之间按快捷键ctrl + v可以直接上传截图
