### ISSUE TITLE
有个字写错了

### ISSUE THREAD

**Issue by chunjil** [ghosert/cmd-editor#1957]
https://www.zybuluo.com/techird/note/46064

> 现在你可以不用 `document.getElementById()` 了，现代浏览器都把复制了 `id` 属性的元素放在了全局变量里。

复制 ，应该是赋值吧。：）

**Comment by ghosert** [comment]
我不是文稿的原作者，可以用鼠标划一下错误的词语给原文做评注，原作者会看到的。
