### ISSUE TITLE
Dropbpx等云盘的自动同步

### ISSUE THREAD

**Issue by ch0psticks** [ghosert/cmd-editor#196]
求接入Dropbpx等云盘的自动同步，从而也可以离线使用，也实现了备份，避免了每次单独下载的麻烦

**Comment by ghosert** [comment]
Cmd Markdown 本身已经是一个云笔记平台了，备份可以自行下载 ZIP 包，也可以导出到第三方，目前已支持印象笔记和Evernote。https://www.zybuluo.com/ghosert/note/102771
