### ISSUE TITLE
客户端登陆时一直提示验证码错误

### ISSUE THREAD

**Issue by HOBERHUNTER** [ghosert/cmd-editor#1960]
客户端在登陆时第一次输错密码之后会要输入验证码，但是一直提示验证码错误。好几天没登陆上去了

**Comment by HOBERHUNTER** [comment]
之前购买了收费版，现在登陆不上去，解决下啊。一直提示验证码错误

**Comment by HOBERHUNTER** [comment]
![issue](http://ww1.sinaimg.cn/large/006HJ39wgy1fhei84lc07g30in0i3aca.gif)

**Comment by HOBERHUNTER** [comment]
@ghosert

**Comment by ghosert** [comment]
@HOBERHUNTER 区分大小写
