### ISSUE TITLE
一个重度使用者的几点功能建议

### ISSUE THREAD

**Issue by ghost** [ghosert/cmd-editor#1969]
1. 希望可以增加**更多快捷键**，或工具栏，例如表格，等一些语法写起来麻烦点的功能。
2. 希望可以自定义**初始模板功能**，例如，我每次写文章都会加上一些固定的话，每次都复制的话，有些麻烦。
3. 希望可以有一个**注释标记**，可以不渲染某段文字，因为某些博客会有一些自定义语法，要来渲染文本，而 `Cmd Markdown` 并不支持这些语法。
4. 希望可以**严格化Markdown的语法**，本身Markdown语法的标准就不是很明确，导致同样的文本，放到不同的编辑器，渲染的效果大不相同，例如在 `Cmd Markdown` 中 `#： 标题标记` 后加一个空格在写标题与不加空格都可以正常渲染，而我发布到博客的时候就会出错。
(ps：虽然我知道这个可能不会实现，因为实现后，其他用户的文本才会出现各种问题，得不偿失，但是为了Markdown能更加的广泛的被使用，我想规范化还是要进行的。)

**Comment by XieJiSS** [comment]
关于第四点，其实可以通过JavaScript自动插入空格【滑稽

**Comment by ghosert** [comment]
这个需要大家一起努力啊！

**Comment by plus7wist** [comment]
注释标记的话，因为可以嵌入 HTML，所以可以用 `<!-- comment -->` 的吧
