### ISSUE TITLE
关于本地与端的合并

### ISSUE THREAD

**Issue by yovenny** [ghosert/cmd-editor#1974]
我用客户端已经是最新的了，然后再浏览器自动帮我合并，不是应该有一个rebase，user their，use your的选项吗？

**Comment by yovenny** [comment]
定价能不能便宜呀，感觉功能定价似乎小贵。。。

**Comment by yovenny** [comment]
现客户端有恢复历史的功能
从自己使用感受体验确实挺好

**Comment by ghosert** [comment]
多谢支持，浏览器也可以恢复历史。能合并的自己会智能合并，只要没冲突。如果有冲突，会让你选的。
