### ISSUE TITLE
Ubuntu Emacs编辑模式下光标向下Ctrl+N快捷键会和Chrome新建窗口快捷键冲突

### ISSUE THREAD

**Issue by erniu3** [ghosert/cmd-editor#1988]
如题 Ubuntu Emacs编辑模式下光标向下Ctrl+N快捷键会和Chrome新建窗口快捷键冲突 
Google了一下 也没有发现屏蔽chrome快捷键的合适方法 希望考虑解决啊 
Ctrl+N键不能用 这个Emacs编辑模式形同虚设啊！

**Comment by ghosert** [comment]
可以用客户端，客户端上可以用。 在这里下载：https://www.zybuluo.com/cmd
