### ISSUE TITLE
付费用户正式卸载，因为在使用时光标对不正，字体不能使用精准细体两个问题。

### ISSUE THREAD

**Issue by allonli** [ghosert/cmd-editor#1993]
今年的付费用户，在vim模式下光标是乱的，字体也能改到自己满意。长期不更正不回复，两次issue。那就byebye吧，已经卸载

**Comment by ghosert** [comment]
啊？这个问题我在很多帖子里回了，需要在cmd markdown的设置里设置一下编辑器使用等宽字体。
