### ISSUE TITLE
新建文本和已发布不够显眼

### ISSUE THREAD

**Issue by linus-young** [ghosert/cmd-editor#2]
本指望点击用户名可以看到我的已发布什么，或者 activity 。后来才发现要到文本列表里才能看到。

还有就是打开主站的时候，默认显示的是上一次编辑的文件，然后我编辑了一下，以为已经新建了一个文件，发布之后发现原文件已经被覆盖掉了。感觉新建文本的功能不太显眼。

个人意见~ 还是顶一个。

**Comment by ghosert** [comment]
嗯，版面的设计上再斟酌一下，没有造成你损失文本吧？

**Comment by linus-young** [comment]
还好还好，本地保存有副本。 :)

**Comment by ghosert** [comment]
有两种方案，第一：别惊慌，记得按 ctrl-z 恢复改动。第二：就是我估计得给每个文件加历史版本的功能，不过相当耗服务器资源，我看到有些作者完稿一篇文章需要做上千次改动。。。

**Comment by linus-young** [comment]
或者像evernote一样只提供给高级用户开放此功能？ 要不只保存最近的一个版本好了？我觉得还是把新建文件做的显眼一点应该能减少这类错误~

**Comment by ghosert** [comment]
嗯，好，版面上的问题其实需要像你这样的深度用户来提，哈哈。

**Comment by linus-young** [comment]
才写两篇而已啊 =。= 不过很多功能还是很赞的！ 持续关注~

**Comment by ghosert** [comment]
新建和已发布已经单独显眼了。

**Comment by linus-young** [comment]
昨天就用过了，非常感谢！ :+1:
