### ISSUE TITLE
Mac Safari浏览器编辑中文输入不正常

### ISSUE THREAD

**Issue by boring98** [ghosert/cmd-editor#2014]
编辑时使用中文输入法，直接输出了拼音的英文，按空格之后又输出了拼音对应的中文。基本无法使用。自带的拼音输入法和搜狗都是如此。
Mac：10.12.6 (16G29)
Safari：版本 10.1.2 (12603.3.8)

**Comment by ghosert** [comment]
最好还是用chrome.

**Comment by ghosert** [comment]
chrome/firefox/ie 测试的比较多。

**Comment by boring98** [comment]
Thanks.
