### ISSUE TITLE
分享一个文档，结果全部该账户下的文档都能被从菜单出访问到！！！！！！！

### ISSUE THREAD

**Issue by sobbingman** [ghosert/cmd-editor#2016]
这事大家都知道吗？？？？？？

**Comment by sobbingman** [comment]
而且发现之后我取消了发布，结果发现如果之前打开了这个文档，即便在你取消发布之后还是可以再次从右侧菜单反复打开其它任何文章，不会受到限制！！！！
太NB了，这种泄露长期集中使用该应用的人的全部手帐——NB！！！

**Comment by ghosert** [comment]
你取消发布以后，这篇文稿对别人就不可见了，你自己是作者所以可见。你可以登出你的帐号再试试。发布文稿的时候提示过别人可以看到，如果不愿意被别人看到，可以不发布或者设置查看密码。

**Comment by sobbingman** [comment]
我自己是全栈开发+产品，做过的商业项目不少。我并没有用登录过的账号做测试，而是用另外的浏览器和手机（微信内嵌浏览器）测试，一但发布，即便在取消之后，只要对方已经打开了这个页面，就可以通过右侧黑底上的菜单选择任何文章浏览，不再受限是否取消发布影响。除非对方刷新页面，否则可以一直访问下去。
另，在发布的时候，文字明确提示是发布某一个文稿，如“发布文稿后您的稿件可以被他人访问分享，确认发布【XXXXXX】？”，结果该帐户下的全部文稿都被发布了，这样不算是事故吗？
（我永远都不会再为该应用付费，而且也不会使用主号发布任何文章，贵司这种对用户隐私完全蔑视的态度令人发指）



sobbingman@sina.com
 
发件人： Jay Zhang
发送时间： 2017-08-21 07:15
收件人： ghosert/cmd-editor
抄送： sobbingman; Author
主题： Re: [ghosert/cmd-editor] 分享一个文档，结果全部该账户下的文档都能被从菜单出访问到！！！！！！！ (#2016)
你取消发布以后，这篇文稿对别人就不可见了，你自己是作者所以可见。你可以登出你的帐号再试试。发布文稿的时候提示过别人可以看到，如果不愿意被别人看到，可以不发布或者设置查看密码。
