### ISSUE TITLE
求添加同步印象笔记功能

### ISSUE THREAD

**Issue by binlidaily** [ghosert/cmd-editor#202]
真心希望能够加此功能，祝作业部落越做越好

**Comment by i-smile** [comment]
同求

**Comment by ghosert** [comment]
知道了。

**Comment by shateiely** [comment]
@ghosert  跪求同步印象笔记。。。

**Comment by nuomi1** [comment]
希望同步到 Google Drive。

**Comment by garyelephant** [comment]
希望能使用作业部落编辑markdown并保存到Evernote,就像maxing.info那样。

**Comment by ghosert** [comment]
已支持：https://www.zybuluo.com/ghosert/note/102771
