### ISSUE TITLE
希望能做到直接拖拽本地图片上传

### ISSUE THREAD

**Issue by binlidaily** [ghosert/cmd-editor#203]
之前在一个外国博客平台上见过能这么实现，马克飞象也实现了，真心希望能实现此功能！

**Comment by ghosert** [comment]
嗯，好的，图片存储成本比较高，需要购买相关存储服务，争取早日实现。

**Comment by pengyizeng** [comment]
可以用七牛云有10G免费的账号，还有就是可以上传到微博的相册里面，再引用 = =

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
