### ISSUE TITLE
客户端白屏

### ISSUE THREAD

**Issue by longwenzi** [ghosert/cmd-editor#2042]
![default](https://user-images.githubusercontent.com/19801168/30420732-14fc0630-996d-11e7-8404-19b76275cd6d.png)

网页版是OK的，我再切换标签时，出现白屏，重启无效

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下看看。

**Comment by longwenzi** [comment]
删掉后，重新启动，可以继续使用了，感谢
