### ISSUE TITLE
linux客户端，打开保存的文件，标题行光标自动后退一格（每打开一次文件，标题就少一个字）

### ISSUE THREAD

**Issue by qizhengyang2017** [ghosert/cmd-editor#2049]
我安装的是“cmd_markdown_linux64.tar.gz”这个包。
安装好之后，打开软件，点击“文件”，选择最近使用的一个文件，发现标题行光标会自动后移.
这导致我每打开一次文件，标题就少一个字。

**Comment by ghosert** [comment]
啥发行版?是不是 奇行种
