### ISSUE TITLE
两个代码块之间文字被识别为代码的问题

### ISSUE THREAD

**Issue by CxdInitial** [ghosert/cmd-editor#2057]
如果一段文字，被夹在两个代码块中，而且**首行缩进为一个`Tab`键**时，必然出现文字段被识别为代码的情况。
* [正常情况](http://wx1.sinaimg.cn/large/8ae868b1ly1fjxd2alogaj21hc0gvmza.jpg)
![notab](https://user-images.githubusercontent.com/25840869/30867797-7b00c9f6-a30f-11e7-9557-1d36e0a2575b.png)
* [错误情况](http://wx1.sinaimg.cn/large/8ae868b1ly1fjxd2bb7nxj21hc0hkac9.jpg)
![tab](https://user-images.githubusercontent.com/25840869/30867802-7f51b7e0-a30f-11e7-9e2f-d2a61c11fb7c.png)

**Comment by ghosert** [comment]
看下markdown语法说明书，这是个语法，不是个问题。

**Comment by CxdInitial** [comment]
才学疏浅
