### ISSUE TITLE
流程图很酷!! 但是显示不全=.=

### ISSUE THREAD

**Issue by Tunied** [ghosert/cmd-editor#206]
Hi 流程图真的很酷!!!!!!!!!!!!!!!!!!!

不过在编辑模式 和 发布的Link里面 都显示不全

https://www.zybuluo.com/iamzealotwang/note/26969

希望能Fix一下

万分万分感谢!!!

**Comment by ghosert** [comment]
这个是页宽所限，到时或许提供一个下载或者展开的选项。

**Comment by ghosert** [comment]
单击流程图可以放大了。
