### ISSUE TITLE
序号无法正常显示

### ISSUE THREAD

**Issue by taliu** [ghosert/cmd-editor#207]
markdowm代码如下：
### 代码片段
1. 代码一

```
var error="404";
```
1. 代码二

```
var error="403";
```
1. 代码三

```
var error="500";
```

然后我发现显示时，序号不是1，2，3而是全都变1了，这个问题能修改么

**Comment by ghosert** [comment]
序号之间按语法规则是不宜加赛代码段的。可以用
###1. xxx
###2. xxx
