### ISSUE TITLE
如何改变Latex公式在PDF中的字体？默认导出PDF后LaTeX公式都是黑体加粗，很不美观

### ISSUE THREAD

**Issue by AlienYvonne** [ghosert/cmd-editor#2073]
采用默认方法导出PDF后，文本中所使用的Latext公式都是黑体加粗，与普通样式的其他字体放在一起非常不和谐，很不美观。请问能够在CSS里自定义修改吗？不了解CSS，不知道如何使用。
PDF截图效果是这样。有时候公式与文本交杂在一起，很难看……
![tmp](https://user-images.githubusercontent.com/17095038/31505055-913f3b64-afa6-11e7-9c04-99b9dee8d74f.png)
在cmd中预览却是这样：
![tmp2](https://user-images.githubusercontent.com/17095038/31505149-d1b31ec2-afa6-11e7-928d-e57f3da50a06.png)
希望PDF中能保留预览区那种比较清淡的效果。

**Comment by ghosert** [comment]
推荐用 acrobat pdf reader 来看，这个和阅读器有关。
