### ISSUE TITLE
建议客户端可以同时编辑多个文件

### ISSUE THREAD

**Issue by CaiNot** [ghosert/cmd-editor#2078]
有些时候，我想要同时写多个文件，或者说，打开自己以前的文件，一边参考一边写。可是，我每次打开新建文件的时候他都会自动关闭当前文件。所以，建议可以同时打开多个文本。

**Comment by ghosert** [comment]
如果一定要这样，可以开个浏览器多 tab。

**Comment by abelage** [comment]
为什么不可以正视用户的需求呢？
