### ISSUE TITLE
ubuntu14.04 客户端最新版本，打开一片空白

### ISSUE THREAD

**Issue by xspkwy** [ghosert/cmd-editor#2087]
解压并软链接libudev.so.0和libudev.so.1后，打开Cmd Markdown出现一片空白：
![selection_002](https://user-images.githubusercontent.com/20251362/32319521-d56adbcc-bff5-11e7-862f-4454595c7496.png)
错误信息为
`[24416:1102/174744:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.`

**Comment by andylizf** [comment]
同此问题 Windows上的

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下客户端看看。
