### ISSUE TITLE
能不能加个选项——不显示图片？

### ISSUE THREAD

**Issue by SunnyWind** [ghosert/cmd-editor#21]
文档中图片多的话，编辑模式时，左右两边十分不对称，左边编辑的文字没法在右边看到显示效果。
ps: 如果图片的大小能控制就好了...

**Comment by ghosert** [comment]
左边的 Markdown 标签如果代表的是图片，那和右边实际的图片高度的确有非常大的落差。或许的确可以用一个选项来解决，在此之前不如这样，可以把图片标签前的！去掉，例如：

[tool-editor](http://www.zybuluo.com/static/img/toolbar-editor.png)

最后等完稿了再把 ! 加回去显示图片例如：

![tool-editor](http://www.zybuluo.com/static/img/toolbar-editor.png)

**Comment by SunnyWind** [comment]
好吧。。不过最好还是加个选项吧！拜托大神了！
