### ISSUE TITLE
删除键和移动光标键失效

### ISSUE THREAD

**Issue by Cppowboy** [ghosert/cmd-editor#210]
在使用普通模式的高级编辑器时，有时会出现删除键和光标移动键失效的现象，windows8.1操作系统和chrome36.0。

**Comment by ghosert** [comment]
目前手头没有 win8 有机会验证一下，其它操作系统如有此问题也可以提出。

**Comment by Cppowboy** [comment]
你好，这么快收到您的回复真的非常开心，真心希望cmd越来越好。

我并不敢保证一定是操作系统的原因，不过我可以更详细地说明一下出现问题时的状况。好像当cmd上自动保存或者手动保存之后，就会出现这种状况，通过鼠标点击可以移动光标，也可以输入一些东西，但是backspace键和移动光标的按键失效，但是关闭网页重新打开之后又恢复正常。操作系统是windows8.1，用的是谷歌浏览器36.0版本，输入法是微软的必应五笔输入法。希望这些信息能够有帮助的作用。

最后再次祝cmd越做越好。

发件人: noreply@github.com [mailto:noreply@github.com] 代表 Jay Zhang
发送时间: 2014年8月21日 20:17
收件人: ghosert/cmd-editor
抄送: Cppowboy
主题: Re: [cmd-editor] 删除键和移动光标键失效 (#210)

目前手头没有 win8 有机会验证一下，其它操作系统如有此问题也可以提出。

**Comment by PegasusWang** [comment]
同样的问题，ubuntu谷歌浏览器，删除总是失效。

**Comment by ghosert** [comment]
@PegasusWang 操作系统，浏览器版本，还有输入法说一下吧。

**Comment by PegasusWang** [comment]
chromium版本 34.0.1847.116 Ubuntu 14.04 aura (260972)‍
IBus 拼音 1.5.0‍

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年8月28日(星期四) 晚上6:53
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "Pegasus"291374108@qq.com; 
主题: Re: [cmd-editor] 删除键和移动光标键失效 (#210)

@PegasusWang 操作系统，浏览器版本，还有输入法说一下吧。

**Comment by Cppowboy** [comment]
感觉有可能是编辑器的问题，设置为极简模式的编辑器就没有上述问题，但是使用普通模式编辑器的时候偶尔会出现这种状况。

**Comment by ghosert** [comment]
@Cppowboy 你用的输入法是哪个？

**Comment by PegasusWang** [comment]
ibus

------------------ 原始邮件 ------------------
发件人: "Jay Zhang"notifications@github.com; 
发送时间: 2014年8月31日(星期天) 上午8:48
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "Pegasus"291374108@qq.com; 
主题: Re: [cmd-editor] 删除键和移动光标键失效 (#210)

@Cppowboy 你用的输入法是哪个？

**Comment by ghosert** [comment]
已修复。请刷新页面或重启客户端。先关了，还有问题请重开。
