### ISSUE TITLE
导出为html之后，本来的代码高亮，表格线等等均不能显示。

### ISSUE THREAD

**Issue by Cppowboy** [ghosert/cmd-editor#211]
如题，建议导出后的html也能正常显示代码高亮，表格线等等。

**Comment by ghosert** [comment]
了解了。

**Comment by neilss** [comment]
出现相同的问题。

**Comment by Cppowboy** [comment]
导出之后只有html，没有css，所以显示不出来代码高亮什么的吧。

**Comment by ghosert** [comment]
有一些的功能的优先级更高，这个排在列表里了，大家稍安勿躁。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
