### ISSUE TITLE
数学表达式中不能显示“{” 和“}”符号，加了slash也不行，还有建议增加导出pdf功能

### ISSUE THREAD

**Issue by pengyizeng** [ghosert/cmd-editor#214]
数学表达式中不能显示“{” 和“}”符号，加了slash也不行，还有建议增加导出pdf功能，因为直接在网页右键打印另存为的话，显示的目录会变形，漂亮的样式也不能显示。

**Comment by sunxb10** [comment]
试试这个：

`$\lbrace$` 和 `$\rbrace$`

或者

`$\\{$` 和 `$\\}$`

Cmd Markdown 中**行内公式**和**行间公式**有很大区别，一些指令如`\{`、`\}`、`\|`、`\,`都只在行间公式中有效，在行内公式中使用时需要在前面再加个`\`。作为一种替代方案，可以使用`\lbrace` （左大括号）、`\rbrace`（右大括号）、`\parallel`（范数符号）、`\;`（空格），这些指令在行内公式和行间公式中都能使用。

**Comment by ghosert** [comment]
已解决。

**Comment by ghosert** [comment]
LaTex 公式已解决。
