### ISSUE TITLE
问一下已经写了的文档怎么删除啊

### ISSUE THREAD

**Issue by ytche** [ghosert/cmd-editor#2140]
是不是有删除文档的功能?有的话在哪里,一直没有找到.没有的话建议做一个啊,不能删除感觉时间一长看着好麻烦

**Comment by cfzhou** [comment]
我在网页端有看到删除选项啊，你点下文件那个按钮就可以看到了

**Comment by ytche** [comment]
@cfzhou 3Q 找到了
