### ISSUE TITLE
本地图片不能加载吗？我平时写的东西不想发送到网络上给别人看到，只想自己看到

### ISSUE THREAD

**Issue by chauby** [ghosert/cmd-editor#2157]
麻烦作者回复下，如果本地图片必须要发送到服务器才能看到的话，我就不要这个会员了，麻烦告知退费方式？？？

**Comment by ernsky** [comment]
这个是必须的，markdown的写作就是这样啦

**Comment by ghosert** [comment]
别人看不到你的图片地址的，只要你不公布。图片也不是存在我这里，是存在七牛云存储。
