### ISSUE TITLE
售后邮件改为gmail.com

### ISSUE THREAD

**Issue by yuanyuanyuan** [ghosert/cmd-editor#2180]
主题：咨询
    原文：邮件原文包含在附件中。
    时间：Sat, 13 Jan 2018 11:51:04 +0800

无法发送到support@zybuluo.com
    系统应答：(24)the mta server of zybuluo.com -- smtp.asia.secureserver.net(182.50.144.66) reply:550 5.1.1 Recipient not found. at 2018-01-13 11:51:12
    退信原因：收信方运营商认为该收件人账号不存在。
    解决建议：请确认此收件人是否存在。

貌似不能再用了。。。。

**Comment by JimmyVV** [comment]
这 TM 我的记录呢？
最近为啥提示一直更新？

**Comment by Laughtalk** [comment]
这么严重的么，差点买会员

**Comment by xuxiaoleilancy** [comment]
我连续付费两年高级会员，想申请发票，发送给support@zybuluo.com的信件也被退回了。

**Comment by sean-xin-yufeng** [comment]
我刚发的也被退回了。。。
为啥微博上也什么都没有。。。
市面上还有别家有密码分享功能吗。。。

**Comment by sean-xin-yufeng** [comment]
ghosert@gmail.com作者邮箱，楼上可以试试看

**Comment by ghosert** [comment]
邮件改了，发 ghosert@gmail.com 那个邮箱我回头更新一下。

**Comment by ghosert** [comment]
发票暂时没法提供。
