### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Amaindex** [ghosert/cmd-editor#2184]

**Comment by Amaindex** [comment]
刚刚试了div之类的，也都不能用，这个编辑器不支持html吗(´･Д･)」

**Comment by Amaindex** [comment]
还好自定义样式表能用(´･Д･)」我先改一下全局设置凑合一下，作者大大快完善上html的功能啊

**Comment by sonictl** [comment]
> `如果你想<span style="font-size: 13px; color:Blue; border:2px solid Red;">调整图片大小</span>，就用width="400" height="300": <img src="https://www.zybuluo.com/static/img/logo.png" width="100" height="500" />`

竟然有效。

**Comment by Amaindex** [comment]
solved
