### ISSUE TITLE
普通用户能不能关闭云端同步，我只是想有找一个好用的编写工具，不需要云端同步

### ISSUE THREAD

**Issue by wangjingyu0018** [ghosert/cmd-editor#2186]
现在显示每隔30分钟同步，点了也没有反应，对于有需求的人来说这个很方便，但是对于写一下不太方便同步的文档时，这个不能取消，就要被迫换别的编辑器，希望能解决这个问题

**Comment by zuiwoshachangjunmoxiao** [comment]
对，不能关闭云端同步吗？
同步到云端的文件我都找不到了。

**Comment by ghosert** [comment]
高级功能里可以新建离线文稿。。。
