### ISSUE TITLE
作业部落出错啦：），赶紧报告我们：support@zybuluo.com

### ISSUE THREAD

**Issue by l1ll5** [ghosert/cmd-editor#2193]
RT

**Comment by coder-pig** [comment]
大佬，快起床修服务器啦

**Comment by liyuj** [comment]
+1

**Comment by lql0716** [comment]
+1

**Comment by lql0716** [comment]
无法登陆

**Comment by Jumpin2** [comment]
+1

**Comment by chendbdb** [comment]
+1

**Comment by lisaisacat** [comment]
+1 大神你的邮箱都收不到邮件啦

**Comment by xxdf2** [comment]
给你邮箱发邮件 都退回了

**Comment by xxdf2** [comment]
开发大哥们，我使用作业部落一年多了，充值了会员2年。

第一年的时候，使用体验还不错。

现在，我上传图片，经常出现错误，上传图片，服务可用率约50%。体验太不好了，这还能不能再续费啊。

上传图片经常会出现：400 token not specified。

本想给你们截个图的，现在又没有这个问题了。但这个问题发生率还是挺高的，希望你们排查一下，有问题可以随时回复联系我。

**Comment by ryzejiang** [comment]
mac 无法上传图片 今天下午刚刚遇到这个问题 希望尽快修复

**Comment by ghosert** [comment]
好，暂时有事把邮件发到 ghosert@gmail.com 原来的邮箱确实停用了，不好意思了。
