### ISSUE TITLE
mac 无法上传图片！

### ISSUE THREAD

**Issue by ryzejiang** [ghosert/cmd-editor#2196]
点击了上传  然后就一直没有反应了  希望尽快解决！

**Comment by ghosert** [comment]
我这边可以传的，刚试了一下。

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下看看。
