### ISSUE TITLE
登录后页面空白一片

### ISSUE THREAD

**Issue by zxhdaniel** [ghosert/cmd-editor#2197]

**Comment by zxhdaniel** [comment]
![_20180131183505](https://user-images.githubusercontent.com/2572041/35618327-9e22f530-06b5-11e8-868f-c4d39700e4b0.png)

**Comment by zxhdaniel** [comment]
编辑不了了，好紧张

**Comment by ghosert** [comment]
应该好了吧
首次使用要联网。

**Comment by jecyu** [comment]
我发现只要是没登录的，都可以正常显示。登录之后，使用第一次关闭后，下次登陆又变成空白状态了。只要我清楚 cookie 后，可以重新显示。不知道是不是只是我的问题？ 浏览器用 的 chrome。
