### ISSUE TITLE
始终无法合并本地版本，会自动转到离线模式

### ISSUE THREAD

**Issue by YichuanSun** [ghosert/cmd-editor#2199]
网络畅通，编辑其他cmd markdown文档时没有丝毫影响，但是这一个文档始终无法自动合并本地版本，每次要自动合并时，都会马上显示转到了离线模式，也就是无法合并。
![84](https://user-images.githubusercontent.com/30886176/35799002-5e8bf4ce-0a9f-11e8-97d2-f66f2cc708de.png)
![85](https://user-images.githubusercontent.com/30886176/35799004-5ec5f908-0a9f-11e8-9abf-f098a3734cd8.png)

**Comment by YichuanSun** [comment]
在编辑这一个文档时，黑色操作框中可以看到，始终显示离线模式，无法同步和合并。

**Comment by YichuanSun** [comment]
现在发现问题了。我重新打开了一个新文档，他告诉我无法保存。但是网络连接一直正常，一个小时之前该软件没有任何问题，在此期间我也没有更改任何设置。

**Comment by lizengfa** [comment]
好像跟我一样，一直无法保存，咋回事，写了一大堆东西！！！！

**Comment by nyanpasua** [comment]
现在恢复正常了，刚才服务器崩了！~

**Comment by YichuanSun** [comment]
对，现在已经恢复正常了
