### ISSUE TITLE
Cmd Markdown 下载得到的HTML文件为什么没有这个编辑器预览时显示的好看？

### ISSUE THREAD

**Issue by joegege** [ghosert/cmd-editor#220]
能不能让下载的html文件与在线编辑时的预览效果一样？

**Comment by ghosert** [comment]
这个功能需要做出来，暂时还没做。

**Comment by RichardNi** [comment]
确实希望能将导出的html样式和预览时的一致

**Comment by jinzhao1994** [comment]
主要是代码...导出成HTML就不是等宽字体..而且没有高亮了...除了有个行号..别的都不好..

**Comment by zhutoulwz** [comment]
其实，导出的html里没有包含css样式，也就是导出的时候没有将相应的css文件一并导出，可以手动去做，不过有点麻烦

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
