### ISSUE TITLE
同步失败？为什么服务器直接返回 502？

### ISSUE THREAD

**Issue by JimmyVV** [ghosert/cmd-editor#2209]
如果要垮了，能提前知会一声吗？

<img width="572" alt="screen shot 2018-02-23 at 11 36 29 am" src="https://user-images.githubusercontent.com/12005455/36576759-c1e6b742-188d-11e8-86a9-3af6edb301ee.png">

**Comment by sli1989** [comment]
+1

**Comment by ghosert** [comment]
正好相反，是因为用户太多了，正在扩容
