### ISSUE TITLE
新建文件-反复提示 “保存文稿时遇到问题，点击【确认】后重试” 无法使用

### ISSUE THREAD

**Issue by beiyehou** [ghosert/cmd-editor#2210]
![image](https://user-images.githubusercontent.com/7250662/36585777-33883d0e-18ba-11e8-8abc-7f8d0d361752.png)

**Comment by beiyehou** [comment]
网页版也无法使用。
![image](https://user-images.githubusercontent.com/7250662/36585995-f2a80c32-18ba-11e8-8068-82999546beb5.png)

**Comment by gaoxiangyu369** [comment]
一样的问题

**Comment by ghosert** [comment]
用户太多了，正在升级软硬件。
