### ISSUE TITLE
表格在导出到印象笔记中的问题

### ISSUE THREAD

**Issue by fooyoo** [ghosert/cmd-editor#2214]
@ghosert 
**表格在导出到印象笔记中，在PC端无法看到内容。但从旁边的摘要中可以看到有信息。**

例如这个表格
| 项目        | 价格   |  数量  |
| --------   | -----:  | :----:  |
| 计算机     | \$1600 |   5     |
| 手机        |   \$12   |   12   |
| 管线        |    \$1    |  234  |

结果如下：
![image](https://user-images.githubusercontent.com/36770100/36632718-d7eae81e-19c4-11e8-85ba-f76280524e60.png)

在安卓手机上显示是正常的。

请帮忙看一下是什么问题， 多谢！

**Comment by fooyoo** [comment]
自答，应该是印象笔记的问题。

**Comment by ghosert** [comment]
多谢多谢。
