### ISSUE TITLE
希望提供多种预览样式

### ISSUE THREAD

**Issue by tiomke** [ghosert/cmd-editor#223]
当前的预览样式有点过于单一了，只有黑白两种。就个人讲，二级标题的字体不够明显突出，不够大。希望提供多种预览样式，或者支持制定自定义样式。

**Comment by ghosert** [comment]
优质的内容比起样式更重要，不妨安心写作业。

**Comment by tiomke** [comment]
优质的内容确实很重要，但是优秀的样式更能突出重点，抓住读者。markdown作为轻量型的标记语言，既然设置了诸如多级标题、加粗、斜体等多种给内容增色的表达，必然要在最终的预览中良好的区分它们的。

| ![tupian](https://raw.githubusercontent.com/tiomke/TempPics/master/%E6%A0%87%E9%A2%98%E5%8A%A0%E7%B2%97.png) | ![maxh](https://raw.githubusercontent.com/tiomke/TempPics/master/%E9%A9%AC%E5%85%8B%E9%A3%9E%E8%B1%A1%E7%9A%84%E6%A0%87%E9%A2%98.png) |
| :-: | :-: |
| Cmd | 马克飞象 |

段落设计确实已经很不错了，但是**区分还是可以再明显一点**，同样的颜色导致加粗部分的效果不是那么一目了然。请看页面设计的四大原则：

| ![tupian](https://raw.githubusercontent.com/tiomke/TempPics/master/%E9%A1%B5%E9%9D%A2%E8%AE%BE%E8%AE%A1%E7%9A%844%E5%A4%A7%E5%9F%BA%E6%9C%AC%E5%8E%9F%E5%88%99.png) |
| --- |

后面三条都做得很好，但是第一条**对比**确实做得不够。

**Comment by ghosert** [comment]
排版样式参考了中文最佳css排版样式。粗体 weight 也比一般的粗体要小，为了保持页面的清风淡雅，减少厚重感，审美上问题做不到让每个人满意。或许按照你的建议也有其它人不满意，目前还是把主要精力放在一流的功能上。当然我也认为美观度是一流的，但同时保留别人不认同的权力

**Comment by ghosert** [comment]
字体、字号还有 CSS 都可以自定义了：https://www.zybuluo.com/ghosert/note/378553
