### ISSUE TITLE
希望在文本列表的搜索结果上面加上创建时间

### ISSUE THREAD

**Issue by coolazrael** [ghosert/cmd-editor#224]
对于搜索时如果两个文本的标题一样，或者说不记得标题只记得当时创建文本的时间，就需要一个个文本点开看，遮掩感觉太麻烦了。话不多说，请看下面图片说明。

> 现在的效果是这个样子

![](http://shop.lizaonet.com/upload/store/goods/16/16_44e3553a95485aa640ab4798b0c6f73b.png_max.png)

> 期望出现的是这个样子：

![](http://shop.lizaonet.com/upload/store/goods/16/16_98e020232f3e5822c30f0eee42c4d72f.png_max.png)

**Comment by tiomke** [comment]
希望在搜索时能**提供标签查找与文本内容查找**。另外希望能够有**更为完善、方便组织的目录结构**。编辑的文档多了以后目录列表很长，而且旧的文件不提供**删除操作**也使得列表十分冗余。或者通过与某个类似于云盘的文档存储服务**提供存取通道**，类似于马克飞象那样，但是只**存放md源文件**。

**Comment by ghosert** [comment]
1. 文稿可以删除，在【文稿信息】那个图标里最后一项，再找找。
2. 标签和文稿标题都可以通过文本列表上方在你截图里的【搜索我的文本，*显示全部】那个文本框里输入关键字搜索。
3. 创建时间在鼠标指到标题上的时候会显示出来。
4. 标签 + 搜索是比较高效的查找文稿的方式，好过逐级点取。

**Comment by tiomke** [comment]
【搜索我的文本，*显示全部】中单单输入标签的话什么都搜不到啊。这个地方不是只能根据文章标题搜么？

**Comment by ghosert** [comment]
搜索搜的是文稿标题。我会再写清楚些。
