### ISSUE TITLE
知道了

### ISSUE THREAD

**Issue by jingyiZhang123** [ghosert/cmd-editor#2247]
真是牛逼，老子眼看左上各种自动保存，然后退出之后，写了5小时的东西没了。
牛逼！我服，相信你们没在本地存是我的失误，以后不会有了
再见

**Comment by WesternGun** [comment]
@jingyiZhang123 我建议你使用本地文本编辑器，比如sublime text，它也能渲染md文档。都做好了，再复制粘贴到网站上，预览，修改，发布，生成pdf等等。（我认为发布是最重要的，相当于强制保存？至少有个阶段性版本）我也常遇到没法保存的问题……只好直接本地。
