### ISSUE TITLE
win7离线,cmd编辑器只显示一片空白

### ISSUE THREAD

**Issue by liufyi** [ghosert/cmd-editor#2250]

**Comment by ghosert** [comment]
Windows: %LOCALAPPDATA%/Cmd Markdown
Linux: ~/.config/Cmd Markdown
OSX: ~/Library/Application Support/Cmd Markdown

把这几个目录删掉。然后再重新启动下客户端看看。

**Comment by liufyi** [comment]
windows上没有看到这个目录哦。是在安装目录，还是/C/User/userName 目录 ？

**Comment by ghosert** [comment]
去你的资源管理器里，直接输入这个地址，然后回车看看  %LOCALAPPDATA%/Cmd Markdown

**Comment by liufyi** [comment]
清空了还是一样，注明一下，这台电脑（内部使用限制联网）是连不了网的，连接不了互联网。

**Comment by ghosert** [comment]
首次使用一定要连一下网络初始化，以后就不用了。

**Comment by jecyu** [comment]
第一次可以联网可以使用，关闭后，第二次重新打开时又变为空白了，又要重新把 %LOCALAPPDATA%/Cmd Markdown 这个目录删掉才行。系统 win10

**Comment by liufyi** [comment]
也就是说，并不是离线使用，还是需要联网的。我之前试着，在联网的机器，使用过一次，断网，能正常使用。我把安装目录，整个copy到另一台不能联网的机器，但不能使用，是不是也连同这个目录%LOCALAPPDATA%/Cmd Markdown也copy过去才行？
