### ISSUE TITLE
充错高级会员，有什么办法可以转移文档？

### ISSUE THREAD

**Issue by Kuohao-wu** [ghosert/cmd-editor#2254]
我有两个账号，一个账号上没有多少文档，另外一个账号有很多文档，今天发现高级会员过期了，就想继续充值，但是打开浏览器保存的却是另外一个账号登录了，充值之后才发现充错号了，cmd-editor有一键导出所有文档，但是却没有一键导入，请问现在我应该怎么办？

**Comment by ghosert** [comment]
好了没？可以微信上找我。ghosert
