### ISSUE TITLE
我有些文章老是提交不了，咋办？

### ISSUE THREAD

**Issue by pengyizeng** [ghosert/cmd-editor#226]
我有些文章老是提交不了，即使换了新建然后复制进去，再提交也一样无法提交

**Comment by pengyizeng** [comment]
我觉得文章内容并不多，这是一个不小的bug。。

**Comment by ghosert** [comment]
你说无法提交是无法保存吗？有没有出错提示，另外方便的话你文稿的内容发给我，我试试重现问题。

**Comment by pengyizeng** [comment]
一直停留在“正在提交您的请求”，文档下载地址http://pan.baidu.com/s/1hqEFA6K

**Comment by ghosert** [comment]
我看了一下：

Status Code:413 Request Entity Too Large
Content-Length:1334440

这个文档太大了，markdown 内容的确不多，但是渲染成 html 以后包含了大量的公式，整个大小有 1.2 m了，比较大。

我把上传大小的尺寸增大的 2 m 了，应该已经解决了再试试，如果再大，建议拆分文稿。
