### ISSUE TITLE
流程图和序列图没有箭头

### ISSUE THREAD

**Issue by cpunion** [ghosert/cmd-editor#227]
![2014-09-05 9 37 19](https://cloud.githubusercontent.com/assets/8459/4159240/37ea06f2-349d-11e4-9ab9-fb671a63a88d.png)
![2014-09-05 9 37 12](https://cloud.githubusercontent.com/assets/8459/4159241/38326992-349d-11e4-99d3-5cd551c654a8.png)

这是样例文档里面的图，在OS X 10.10/Safari 8.0上面不显示箭头。

**Comment by cpunion** [comment]
```
Failed to load resource: the server responded with a status of 404 (Not Found) https://www.zybuluo.com/static/editor/libs/uml/build/sequence-diagram-min.js.map
```

报了这个错。

**Comment by ghosert** [comment]
这个错和箭头没有关系，是否可以试试 chrome 浏览器，告诉我啥情况。推荐使用 chrome.

**Comment by cpunion** [comment]
![2014-09-19 2 31 18](https://cloud.githubusercontent.com/assets/8459/4331523/a0736d92-3fc6-11e4-95aa-4c92568b6596.png)

Chrome上是这个样子，有箭头，但是流程图里的箭头很小。

**Comment by ghosert** [comment]
目前只支持 chrome 和 firefox 了。。。
