### ISSUE TITLE
对于已分布的文章，是否能取消？？

### ISSUE THREAD

**Issue by yulongsun007** [ghosert/cmd-editor#2286]
对于已分布的文章，是否能取消？？

**Comment by simonkuang** [comment]
结论：可以的，就是比较麻烦。

我现在的方式是：

1. 随意找一篇文章发布；
2. 点开文章固定链接；
3. 右侧边栏有个『三横线』按钮，点进去，能看到自己发布出去的所有文章；
4. 挨个点进去，拿到文章 id；
5. 在地址栏里面找到编辑器 url，替换文章 id，回车，进到已发布文章的编辑界面；
6. 撤销发布；
7. 回到第 3 步，直到所有不想发布的文章都撤销发布。

**Comment by simonkuang** [comment]
不知道上面解答是否能解答问题。问题本身可能存在两种解释。

1. **怎么撤销发布单一文章**。这个问题的回答相对简单，刚才没回答，忽略掉了。
2. **怎么撤销已发布的所有（或者一批）文章**。刚才是解答这个问题。

未免遗漏，补充针对第一种解释的回答。

1. 进入形如 *https://zybuluo.com/mdeditor#<artricle_id>* 的文章编辑页面中；
2. 如果当前文章是已经发状态，顶部菜单『文件』菜单后面，是『发布更新』菜单；
3. 点击『发布更新』，在下拉菜单中，有『撤销发布』一项。点击即可撤销。

**Comment by ghosert** [comment]
谢谢。 @simonkuang
