### ISSUE TITLE
[TOC]的支持不够好

### ISSUE THREAD

**Issue by Huanglijie** [ghosert/cmd-editor#230]
[TOC]
## 第一部分 数理逻辑

 ###第一章 命题逻辑基本概念
  ####1.1 命题与联结词
  ####1.2 命题公式及其赋值

---

 ###第二章 命题逻辑等值演算
  ####2.1 等值式
  ####2.2 析取范式与合取范式
  ####2.3 联结词的完备集

---

如输入上面的文字，[TOC]只显示第一部分，并没有显示下面的子标题。另外#在[TOC]中嵌套使用显示不起作用，上面的文字输出的显示如下：

第一部分 数理逻辑

**Comment by Huanglijie** [comment]
第一张是haroopad写的
![haroopad](https://cloud.githubusercontent.com/assets/8372261/4222705/f93d907c-3915-11e4-8779-792c868518dc.png)
标题#的使用显示有问题 前面有空格就直接显示源文件的内容
![cmd](https://cloud.githubusercontent.com/assets/8372261/4222780/82765108-3916-11e4-8206-acedb7ebb23c.png)

**Comment by Huanglijie** [comment]
解决了，把前面的空格去掉就好了！

**Comment by ghosert** [comment]
谢谢，正解。markdown 规范里要求 # 顶格写。
