### ISSUE TITLE
会员图片无法上传

### ISSUE THREAD

**Issue by wangqingpeng131** [ghosert/cmd-editor#2326]
开了会员，第一次可以上传图片。现在又无法上传了。点击上传图片——选中图片——打开。没有效果。请确认一下。

**Comment by wflfei** [comment]
我也是，没成功过，要怎么用，专门支持一下的，结果这样子。

**Comment by ghosert** [comment]
试过了，好的。。。

**Comment by ghosert** [comment]
操作系统，和客户端，浏览器说下。

**Comment by wflfei** [comment]
@ghosert 你好，现在还是不行: MAC OS 10.12.6，   MacBookPro Early 2015 ,  客户端和chrome上都不行
