### ISSUE TITLE
PDF导出问题

### ISSUE THREAD

**Issue by Medill-East** [ghosert/cmd-editor#2338]
为什么有时候总是无法导出PDF呢
服务器总不能一直在忙吧...
试了很多次 不导出PDF打印的时候很可能又会出问题
很着急啊...

**Comment by IndieMiao** [comment]
同上  一样的问题，付费用户，希望尽快解决，急

**Comment by nmhm** [comment]
同上，请尽快解决

**Comment by cdcx** [comment]
同上

**Comment by ghosert** [comment]
我这边好的，现在好了吗？可能当时服务器有些问题。

**Comment by ghosert** [comment]
另外看看是不是文稿里图片过多了？

**Comment by Medill-East** [comment]
现在貌似已经正常了哦
当时文稿里没啥图片(￣▽￣)"
谢谢啦~






在2018年08月6日 04:26，Jay Zhang<notifications@github.com> 写道：

另外看看是不是文稿里图片过多了？
