### ISSUE TITLE
Windows桌面APP光标错位

### ISSUE THREAD

**Issue by zwangsiyu** [ghosert/cmd-editor#2342]
前两天下了桌面APP，但是用着用着就出现了光标错位的问题，然后删除东西很不方便，经常需要自己去找位置。
APP编辑的字体重新设定过，设为了Calibri Light，看之前Mac的修复有因为字体导致错位的情况，不知道我的这个是不是也是

**Comment by ghosert** [comment]
把字体设置成等款类型的字体就好了。

**Comment by ghosert** [comment]
例如 微软雅黑
