### ISSUE TITLE
现在切换速度越来越慢了

### ISSUE THREAD

**Issue by Woods2016** [ghosert/cmd-editor#2370]
以前切换文章的时候，反应也就是1-2秒，现在切一个文章或者新建一个文章的时候，会卡住5秒甚至更久！技术需要升级了，这个很不舒服，甚至还有一次奔溃，我只能重启！

**Comment by ghosert** [comment]
文章有多少了？

**Comment by Woods2016** [comment]
> 
> 
> 文章有多少了？

将近300篇

**Comment by ghosert** [comment]
有点小多。。。现多开几个浏览器页面吧。。。我也想想办法，因为每次都需要加载，同步服务器上的文章。

**Comment by ghosert** [comment]
没用的删掉点也可以缓解一下。

**Comment by VitoYi** [comment]
是否可以通过桌面应用实现本地存储呢？这样切换会快很多吧

**Comment by ghosert** [comment]
> 是否可以通过桌面应用实现本地存储呢？这样切换会快很多吧

本地是有存储的，但是每次加载还是要去和服务器版本比对的。得知道要不要更新本地的存储。

**Comment by ghosert** [comment]
今天我又试了一下，好像也不太慢，看看是不是网速有问题。

**Comment by eric-songbai-zhou** [comment]
> 
> 
> 是否可以通过桌面应用实现本地存储呢？这样切换会快很多吧

同意！强烈建议@ghosert把产品改成“本地优先”模式，最好在断网情况下提供所有写东西的功能，把在线连接服务器进行同步作为备份——这样使用者可以不被打扰地进行写作，ghosert您在后台服务器方面的成本也可以降低。
感谢！

**Comment by ghosert** [comment]
目前断网的时候可以写的，你可以试试。连上网络后会自动同步。
