### ISSUE TITLE
连接不上，一直提示处于离线状态，无法同步

### ISSUE THREAD

**Issue by SR1s** [ghosert/cmd-editor#2371]
连接不上，一直提示处于离线状态，无法同步
即便是切换历史草稿，理应是正常的，但还是无法同步
还出现一定程度的链接重置

**Comment by VitoYi** [comment]
同，『离线状态下无法同步数据，但可以离线编辑，请连接网络后重试。』
一开始我以为是我网络问题，用手机热点连也不行。联系了几个朋友（都是我推荐他们用的）也是一样的情况。
求作者好好搞一下啊，最近切换笔记是越来越慢了，上传图片还经常  400: token not specified, 今晚正在学习呢，还来了这么一出，在这样真想迁移了啊啊啊~~

**Comment by jbtest3** [comment]
同遇到---离线状态下无法同步数据，但可以离线编辑，请连接网络后重试的问题，要崩溃了；
这个软件是近期被同学安利使用的，为了使用图床，开了会员，本来就像把之前的博客做迁移，结果在迁移过程，上传图片一致提示400: token not specified，求解决

**Comment by githublemon2452** [comment]
同啊，今天早上一直离线，无法上传图片啊

**Comment by chengxuyuan112** [comment]
什么鬼东西，明明网络正常，说我网络有问题，不能创建文件，一直连接不上

**Comment by CaptainSlowWZY** [comment]
现在好像好了。我估计时服务器出锅了。

**Comment by githublemon2452** [comment]
我这里还是不行啊 一整天了

**Comment by eric-songbai-zhou** [comment]
有一种上当的感觉，在花钱购买会员之前，一直没有遇到这种提示，这两天开始用得比较多了，发现离线状态的提示总是出来，而且所有导出文档和插入图片的动作都做不了，好崩溃啊！！！

**Comment by yuyang1995** [comment]
我这里也已经一整天处于离线的状态

**Comment by CaptainSlowWZY** [comment]
问题好像一直都在，今天早上还有。不过刷新几次好像就正常了。感觉客户端不是很稳定，感觉把文章寄存在这里不是很靠谱了。

**Comment by ghosert** [comment]
有人发送政治敏感信息，网站被上级机关封锁了域名，正在积极联系沟通请求解封。

给大家带来不便了，但是确实是不可控因素。

**Comment by ghosert** [comment]
我会在这里随时更新解封的进程。正在积极沟通。

**Comment by GHQiuJun** [comment]
相同的问题，但是一会可以一会又不可以

**Comment by bvanjoi** [comment]
同，是服务器的原因吗

**Comment by Bai-Yingjie** [comment]
https://www.zybuluo.com/
This site can’t be reached
预计多久能恢复访问?

**Comment by helloHu** [comment]
我也一样，昨天开始的

**Comment by SR1s** [comment]
> 我会在这里随时更新解封的进程。正在积极沟通。

在我这边的表现的链接重置。不过奇怪的是，用了梯子，能打开网站，但依然同步不了。
讲道理这种情况不应该是能正常使用吗

**Comment by ghosert** [comment]
恳请大家暂时使用  http://www.zybuluo.com 不要带 https 目前监管部门只禁了 https，我刚才已经紧急修改了设置，开通了 http，所有不能打开的页面，使用 http 目前都可以使用了。我还在和有关部门沟通，争取早日解禁，同时请告知其他用户也使用  http 。

**Comment by jbtest3** [comment]
用的是客户端，怎么切换http？

**Comment by ghosert** [comment]
暂时使用网页版

**Comment by ghosert** [comment]
经过努力沟通，阿里云已经解除了封锁，目前 http 不再使用，请修改 URL 为 https 或者直接访问htttps://www.zybuluo.com 继续使用，所有客户端已经恢复正常。

**Comment by jbtest3** [comment]
求解决，无论是用客户端还是https://www.zybuluo.com，上传图片的，经常性出现“错误：请求报文格式错误。(400：token not specified)”

已经很影响写文档的速度了。。求解决。。
