### ISSUE TITLE
由于被用户传播敏感言论，目前被监管部门封禁了域名，临时解决方案

### ISSUE THREAD

**Issue by ghosert** [ghosert/cmd-editor#2372]
所有的链接使用 HTTP 都可以访问，请修改 URL， 我正在和监管部门沟通，希望早日解封。请帮助我通知您身边的其他用户使用这个临时解决方案。

**Comment by leeduckgo** [comment]
支持cmd-markdown

**Comment by CaptainSlowWZY** [comment]
支持支持！

**Comment by denki-san** [comment]
支持支持

**Comment by harryjudy2240** [comment]
但是无法上传pdf，上传附件时提示400bad token

**Comment by songyingxin** [comment]
支持

**Comment by ghosert** [comment]
经过努力沟通，阿里云已经解除了封锁，目前 http 不再使用，请修改 URL 为 https 继续使用，所有客户端已经恢复正常。

**Comment by ghosert** [comment]
经过努力沟通，阿里云已经解除了封锁，目前 http 不再使用，请修改 URL 为 https 或者直接访问htttps://www.zybuluo.com 继续使用，所有客户端已经恢复正常。

**Comment by git-life-everywhere** [comment]
优化下目录的功能
