### ISSUE TITLE
Windows10 64位下无法打开Windows客户端

### ISSUE THREAD

**Issue by gszyboy** [ghosert/cmd-editor#2373]
你好，我在http://www.zybuluo.com/cmd/下载了Windows64位版的客户端，可是在我电脑上却打不开怎么办？
已经对此做了删除操作。Windows: %LOCALAPPDATA%/Cmd Markdown

**Comment by ghosert** [comment]
请客户端用户暂时使用 网页版本， 因为客户端内部使用的是 https，所有 HTTPS 都已经被监管部门封禁，请使用 http 链接： http://www.zybuluo.com

**Comment by ghosert** [comment]
经过努力沟通，阿里云已经解除了封锁，目前 http 不再使用，请修改 URL 为 https 或者直接访问htttps://www.zybuluo.com 继续使用，所有客户端已经恢复正常。

**Comment by ghosert** [comment]
经过努力沟通，阿里云已经解除了封锁，目前 http 不再使用，请修改 URL 为 https 或者直接访问htttps://www.zybuluo.com 继续使用，所有客户端已经恢复正常。
