### ISSUE TITLE
一直处于离线状态，无法上传图片进行，到处pdf之类都无法操作

### ISSUE THREAD

**Issue by tntlzhang** [ghosert/cmd-editor#2374]
这两天一直处于离线状态，无法上传图片进行，导出pdf之类都无法操作，有时候图片还经常跑偏把其他文章中图片进行替换了 ，我这刚开完会员，现在好感降低一半呀。望赶紧修复下。

**Comment by ghosert** [comment]
由于被用户传播敏感言论，目前被监管部门封禁了域名，临时解决方案 ：
所有的链接使用 HTTP 都可以访问，请修改 URL， 我正在和监管部门沟通，希望早日解封。请帮助我通知您身边的其他用户使用这个临时解决方案。

**Comment by kangkaisen** [comment]
+1

**Comment by auxten** [comment]
App用户怎么办？

**Comment by ghosert** [comment]
请客户端用户暂时使用 网页版本， 因为客户端内部使用的是 https，所有 HTTPS 都已经被监管部门封禁，请使用 http 链接： http://www.zybuluo.com

**Comment by ghost** [comment]
哭了

**Comment by auxten** [comment]
> 请客户端用户暂时使用 网页版本， 因为客户端内部使用的是 https，所有 HTTPS 都已经被监管部门封禁，请使用 http 链接： http://www.zybuluo.com

建议App上一个备用域名更新一下吧，这种事情和有关部门沟通不知道要多久……

**Comment by bin-dogami** [comment]
我还以为你们倒闭了，服务器被关停，有那么一瞬间我在想要不要自己写个 markdown了

**Comment by xiaogu-space** [comment]
挺住，五年积累的东西都在上面

**Comment by joriewong** [comment]
导出所有文稿，使用工具[CmdMarkdownBackup](https://github.com/morgengc/CmdMarkdownBackup)进行备份。

**Comment by auxten** [comment]
建议修改：

1. Web版用一个域名
1. App应该用第二个域名
1. 建议基于国情，所有分享的文章都用第三个域名
1. 所有分享的文章都必须加密码

**Comment by denki-san** [comment]
非常影响工作。。赶紧去备份，写了三年的文档了

**Comment by liangyawang** [comment]
> 这两天一直处于离线状态，无法上传图片进行，导出pdf之类都无法操作，有时候图片还经常跑偏把其他文章中图片进行替换了，我这刚开完会员，现在好感降低一半呀。我这也是刚开的会员  只有网页能登陆 这不好玩啊

**Comment by liangyawang** [comment]
我的所有东西文档 都写在这个上面了

**Comment by lfxls** [comment]
> > 请客户端用户暂时使用 网页版本， 因为客户端内部使用的是 https，所有 HTTPS 都已经被监管部门封禁，请使用 http 链接： http://www.zybuluo.com
> 
> 建议App上一个备用域名更新一下吧，这种事情和有关部门沟通不知道要多久……

这个也挂了?

**Comment by ghosert** [comment]
经过努力沟通，阿里云已经解除了封锁，目前 http 不再使用，请修改 URL 为 https 或者直接访问htttps://www.zybuluo.com 继续使用，所有客户端已经恢复正常。
