### ISSUE TITLE
网站无法访问，无法导出pdf

### ISSUE THREAD

**Issue by harryjudy2240** [ghosert/cmd-editor#2375]
https://www.zybuluo.com
官网无法访问，服务器出问题，会员都没法使用pdf导出功能，请尽快修复

**Comment by ww3113306** [comment]
Me too!

**Comment by ww3113306** [comment]
我的客户端也连接不上网络，无法导出pdf，，，但是现在急用这个功能。。。

**Comment by BalrogMithrandir** [comment]
作业域名被封了，见issue2372，把https改成http，就可以导出pdf了

**Comment by ghosert** [comment]
经过努力沟通，阿里云已经解除了封锁，目前 http 不再使用，请修改 URL 为 https 或者直接访问htttps://www.zybuluo.com 继续使用，所有客户端已经恢复正常。
