### ISSUE TITLE
这两天客户端一直处于离线状态，从客户端进官网提示网络链接失败

### ISSUE THREAD

**Issue by fengcaizhi** [ghosert/cmd-editor#2377]
几天前还可以用，这两天一直处于离线状态，无法上传图片进行，无法到处文档，正好需要导出点东西就出问题 了

**Comment by stone-lyl** [comment]
同，希望作者尽快解决，谢谢。

**Comment by zhu-longge** [comment]
同，希望作者尽快解决，谢谢。

**Comment by 76575537** [comment]
同，希望作者尽快解决，谢谢

**Comment by BalrogMithrandir** [comment]
作者域名被封了，解决方法见issue2372

**Comment by ghosert** [comment]
经过努力沟通，阿里云已经解除了封锁，目前 http 不再使用，请修改 URL 为 https 继续使用，所有客户端已经恢复正常。
