### ISSUE TITLE
作业部落域名屏蔽事件完美解决，目前已经解除封锁，请按此方法继续使用

### ISSUE THREAD

**Issue by ghosert** [ghosert/cmd-editor#2379]
经过努力沟通，阿里云已经解除了封锁，目前 http 不再使用，请修改 URL 为 https 或者直接访问htttps://www.zybuluo.com 继续使用，所有客户端已经恢复正常。

**Comment by VitoYi** [comment]
真不容易，但是老大，上传图片400的问题还是要解决啊

**Comment by ghosert** [comment]
了解，这次风波让我更有动力了。早日解决

**Comment by git-life-everywhere** [comment]
cmd markdown 你会不会再优化，更新呢？为什么目录的问题，你都不关注呢。。大哥。。
