### ISSUE TITLE
Latex公式中文字负间距符号\! 

### ISSUE THREAD

**Issue by ouxiaogu** [ghosert/cmd-editor#239]
Latex公式中文字的负间距符号! 在行内公式`$\!$`与行间公式`$$\!$$`有着不同的解析。
如NA在光学中为 Numerical Aperture，专有名词，在公式中，字母N和字母A应该隔得很近，所以用了Latex中的负间隔符`\!`。
然而，使用CMD-Editor过程中，我发现`$$N\!A$$`可以正确的解析，`$N\!A$`却解析错误，在stackEditor中上面两写法都能正确解析。

**Comment by ghosert** [comment]
已解决。
