### ISSUE TITLE
账号登录不上

### ISSUE THREAD

**Issue by airstarlabs** [ghosert/cmd-editor#2398]
![image](https://user-images.githubusercontent.com/20129614/46793447-54f65700-cd78-11e8-8f0f-f423978666fa.png)

**Comment by airstarlabs** [comment]
我已经在邮件中点击了 激活了 还是不行
![image](https://user-images.githubusercontent.com/20129614/46793495-6ccddb00-cd78-11e8-9ca8-af1994d71afc.png)

**Comment by ghosert** [comment]
用户名登录，不要用邮箱登录
