### ISSUE TITLE
建议换一个等宽字体

### ISSUE THREAD

**Issue by loseblue** [ghosert/cmd-editor#24]
我通常喜欢冒号对齐一类的用几个空白来对齐某些项目，但是非等宽字体对齐后会乱。
一般编程也是用等宽字体，建议换一个等宽的字体。中英文等宽的。

**Comment by ghosert** [comment]
标记为 enhancement

**Comment by jamesfancy** [comment]
> 建议换一个等宽的字体。中英文等宽的

我觉得直接换没必要，不过如果能提供一个设置就好了，这样大家都可以按照自己的喜好来。

**Comment by armink** [comment]
@ghosert 貌似空格等宽还是有问题的，现在作业部落上空格的宽度是英文字母的1/2，大多文本编辑器上空格和英文字母是等宽。
文本编辑器上的文字如果采用空格对齐方式，那么复制到作业部落上会出现无法对齐的情况。
上两张图对比下吧。
第一个是文本编辑器上的效果，第二个是作业部落上的效果。
![qq20140401102620](https://cloud.githubusercontent.com/assets/1734686/2575028/10ce6eb0-b945-11e3-85fc-59b0e938848e.jpg)

![qq20140401102058](https://cloud.githubusercontent.com/assets/1734686/2575010/776a5d2e-b944-11e3-8157-d6856c1a23ee.jpg)

**Comment by ghosert** [comment]
好的，我今天抽空看看，争取解决掉。

**Comment by ghosert** [comment]
已修复

**Comment by armink** [comment]
@ghosert Hi，大神，新版本非常棒，但是发现一点小问题。
新版的作业部落上3个汉字宽度对应5个字符宽度；
但是在文本编辑器上3个汉字宽度对应6个字符宽度，即每个汉字占两个字符宽度。
又给你找了个茬，可别烦我哈~
github上传图片总失败，点击打开连接看对比效果图吧~
[作业部落效果](http://v2.freep.cn/3tb_1404161321031dqp512293.jpg)
[文本编辑器效果](http://v1.freep.cn/3tb_140416132107awba512293.jpg)

**Comment by ghosert** [comment]
噢，没事，发现问题总是好事情。是这样，目前的确只保证了英文字符之间是等宽的，如果要保证英文和汉字之间二比一的宽度比例，我不是很清楚要选哪种字体？或者你能告诉我？另外我个人觉得微软雅黑比较漂亮，所以就首选了这个作为汉字字体，但是这样似乎又会影响宽度比，你知道哪个英文字体和雅黑是二比一等宽的，可以告诉我。

**Comment by armink** [comment]
@ghosert 我用的是Notepad++对比作业部落看的效果，不清楚Notepad++用的什么字体
现在的效果已经非常好了，就是在中英文混合的时候，容易出现格式无法对齐的问题，就像上面的发的那个“[作业部落效果](http://v2.freep.cn/3tb_1404161321031dqp512293.jpg)”图片，第一行和第二行的竖线明显没有对齐。
不清楚这个与中文字号有没有关系。

**Comment by knight42** [comment]
![out](https://cloud.githubusercontent.com/assets/4237254/3889153/e3ec9a06-2209-11e4-91c4-77e505a64c63.gif)

系统环境: ArchLinux，Firefox31
输入英文的时候光标会越走越远，但输入中文时光标正常。是等宽字体问题吗？

**Comment by ghosert** [comment]
应该是发行版的问题。这个问题的原因是发行版的英文宽度和中文宽度的比例有问题，不知道你能否装上 Ubuntu Mono 这个字体，装上这个字体以后在 Linux 系上就正常了。手头没有 ArchLInux 所以没办法测试这个发行版上哪种字体能解决这个问题。

**Comment by knight42** [comment]
嗯，装上 ttf-ubuntu-font-family 后问题解决。

在 2014年8月12日 下午7:20，Jay Zhang notifications@github.com写道：
