### ISSUE TITLE
样式表 404。样式全乱了

### ISSUE THREAD

**Issue by simonkuang** [ghosert/cmd-editor#2407]
> 无法访问此网站
> 网址为 https://www.zybuluo.com/static/assets/mdeditor/45c7d56d.layout.min.css 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
> ERR_CONTENT_DECODING_FAILED

页面样式全乱了。请 @ghosert 大大尽快看看

**Comment by simonkuang** [comment]
![image](https://user-images.githubusercontent.com/2220656/47352771-30419e00-d6ed-11e8-8b1b-cb0de6d3743a.png)

补充一下 chrome 的 console 标签内容吧

**Comment by ghosert** [comment]
我这里好的啊

**Comment by ghosert** [comment]
你换个网络试试？

**Comment by simonkuang** [comment]
> 你换个网络试试？

我这边看还是有问题。不过在 chrome spy window 里面试过，是 OK 的。看来是个例。

状态被缓存了，比较痛苦，不刻意发现不了。只能手动清下缓存。
