### ISSUE TITLE
cmd_markdonw对内嵌html的支持

### ISSUE THREAD

**Issue by Dao-zhi** [ghosert/cmd-editor#2422]
在cmd_markdown中内嵌html的显示效果非常差，有很多属性不能显示，比如bgcolor,还有很多是错误的，下面是一个例子：在cmd_markdoen中用内嵌html写一个表格，代码如下：
``` html
<table><tr><td bgcolor=yellow> 定义表格、行、列
<table border="1"> //table是定义表格
  <tr> //定义表格中的行
    <th bgcolor=red>Month</th>//定义表格中的表头单元格 bgcolor是背景颜色
    <th>Savings</th>
  </tr>
  <tr>
    <td>January</td>
    <td>$100</td>//定义表格中的单元
    <td> <b> $50 </b> </td> //<b>是定义黑体 <i>定义斜体
  </tr>
</table>
```
在其他markdown工具中的显示效果如下图：
![image](https://user-images.githubusercontent.com/34510401/49012490-86a27080-f1b4-11e8-9232-2cc5850f8d16.png)
在cmd_markdown中的显示效果如下图：
![image](https://user-images.githubusercontent.com/34510401/49012532-a3d73f00-f1b4-11e8-8f08-8412d9db3bad.png)
如果对内嵌html支持不好还不如不用支持，这样用户体验真的不好，希望改进。

**Comment by ghosert** [comment]
所有 有 $ 的地方都改成 \$
