### ISSUE TITLE
希望能增加导出PDF功能，并且PDF的支持目录索引

### ISSUE THREAD

**Issue by jim19770812** [ghosert/cmd-editor#243]
很多软件都支持导出PDF，但没见一个导出的PDF里支持目录索引的（可以在PDF里导航，用pdf阅读器打开后也可以点击大纲视图的标题条目快速跳转，就像是word的大纲视图那样），如果cmd-editor可以做到这点就太棒了，

**Comment by fjarcticfox** [comment]
希望至少支持PDF导出吧，毕竟发送文件给非技术人员的话，用PDF或者word才是比较合适的。

**Comment by rywiki** [comment]
发送装个pdf打印机应该就可以了，不过，html到pdf的分页确实是个问题呢。

**Comment by wangkexiong** [comment]
`导出PDF`可以通过先导出HTML，然后`chrome`打开，选择打印，再`选择PDF`搞定。可是这样没有目录啊亲。强烈支持增加这个功能，不然还是选择 `stackedit.io` 好了

**Comment by switchball** [comment]
从html到pdf会遇到各种问题，而且格式也丢失，还是希望能加导出PDF功能，这样就完美了！

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
