### ISSUE TITLE
是不是服务器下线了？

### ISSUE THREAD

**Issue by am1006** [ghosert/cmd-editor#2431]
![image](https://user-images.githubusercontent.com/13403435/50042566-a2a47e00-009f-11e9-85f9-bd6db4cfee99.png)
结合前面提出来的issue，比如图片无法上传。是不是服务器下线？

**Comment by HowQi** [comment]
同问, 昨天我写的题还在上面Orz 正准备对答案

**Comment by ghosert** [comment]
修复了，阿里云升级导致的。
