### ISSUE TITLE
您好，我的帐号无法登入

### ISSUE THREAD

**Issue by q397233** [ghosert/cmd-editor#2438]
不知道什么情况，现在帐号登入不进去，老提示帐号或密码错误，但是我填写都是正确的  q397233   邮箱：297221***@qq.com

**Comment by jiswordsman** [comment]
我也遇到了同样的问题

**Comment by ghosert** [comment]
接到上级通知不得不删除了一些涉及敏感信息的账号，如果需要解禁，联系我邮箱: ghosert@gmail.com
