### ISSUE TITLE
怎么禁止搜索引擎收录

### ISSUE THREAD

**Issue by junlicn** [ghosert/cmd-editor#2449]
我想用 作业部落 管理我的文档，但是有些文档是私有的，不方便对外公开，或者被搜索引擎收录。

怎么禁止搜索引擎收录？  
加上密码，似乎也会出现在搜索引擎里。 标题显示出来了。

**Comment by ghosert** [comment]
有密码是绝对不会泄露内容的。实在怕被人看到就不要公开了。私有文档是不会被收录的。

**Comment by yan234280533** [comment]
@ghosert  高级会员图片的链接是怎么做加密处理的，会不会有泄漏分险 我试一下，不登陆账号也是可以访问图片的

**Comment by ghosert** [comment]
隐私的文稿你不要发布出去，这样图片链接也就没法看到了。图片链接是有随机码的，一般不可能猜到，除非你自己发出去。
