### ISSUE TITLE
作业部落

### ISSUE THREAD

**Issue by VitoYi** [ghosert/cmd-editor#2462]

**Comment by Jack2code** [comment]
迁移到哪里？

**Comment by VitoYi** [comment]
> 迁移到哪里？

印象笔记 + 马克飞象

虽然印象笔记从去年就支持了 Markdown, 但是样式实在是太丑了，导出文档更丑，而且各种的小细节很难受，比如文档内没有一个浮动的目录窗口（不想加 [toc], 看个目录还要翻到顶部），代码高亮看着也特别难受。
但是印象笔记也是有优势的：云存储、跨平台、服务器稳定快速、支持全局/内容搜索、笔记本+多标签形式便于管理等等，还是让我选择了印象笔记，至于样式什么的，还是通过马克飞象来解决吧。

**Comment by vansl** [comment]
> > 迁移到哪里？
> 
> 印象笔记 + 马克飞象
> 
> 虽然印象笔记从去年就支持了 Markdown, 但是样式实在是太丑了，导出文档更丑，而且各种的小细节很难受，比如文档内没有一个浮动的目录窗口（不想加 [toc], 看个目录还要翻到顶部），代码高亮看着也特别难受。
> 但是印象笔记也是有优势的：云存储、跨平台、服务器稳定快速、支持全局/内容搜索、笔记本+多标签形式便于管理等等，还是让我选择了印象笔记，至于样式什么的，还是通过马克飞象来解决吧。

正在尝试从马克飞象转移到作业部落。前者bug太多。

**Comment by Jack2code** [comment]
> > > 迁移到哪里？
> > 
> > 
> > 印象笔记 + 马克飞象
> > 虽然印象笔记从去年就支持了 Markdown, 但是样式实在是太丑了，导出文档更丑，而且各种的小细节很难受，比如文档内没有一个浮动的目录窗口（不想加 [toc], 看个目录还要翻到顶部），代码高亮看着也特别难受。
> > 但是印象笔记也是有优势的：云存储、跨平台、服务器稳定快速、支持全局/内容搜索、笔记本+多标签形式便于管理等等，还是让我选择了印象笔记，至于样式什么的，还是通过马克飞象来解决吧。
> 
> 正在尝试从马克飞象转移到作业部落。前者bug太多。

。。。萝卜白菜各有所爱啊

**Comment by Teraflopst** [comment]
Gist 也可以写笔记

**Comment by zenwan** [comment]
https://stackedit.io/
