### ISSUE TITLE
无法续费高级会员，也没显示会员是否到期。

### ISSUE THREAD

**Issue by taxaser** [ghosert/cmd-editor#2466]
没有地方显示会员开始截止时间，今天开始存离线文档就跳到付费页面，但是
![image](https://user-images.githubusercontent.com/1031857/54729983-4b8fd700-4bc1-11e9-9cc9-9611bbc8288a.png)
我还有一些文档没有转离线，求方便打救阿。

**Comment by Alexander-flyer** [comment]
这个页面是说你已经是高级会员了，再刷新一下试试？
