### ISSUE TITLE
写了一天的文档，刷新了一下，结果没有了...卧槽

### ISSUE THREAD

**Issue by SongLee24** [ghosert/cmd-editor#248]
不是有缓存功能么，我也是一直这么相信的。。。这下把我坑惨了。。。

**Comment by ghosert** [comment]
我给你找回来，把你的用户名和那篇文档的标题给我。

**Comment by SongLee24** [comment]
‍‍‍‍算了，我已经重新写了一份，谢谢回复。

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年10月7日(星期二) 晚上10:21
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "の神奕の"lisong.shine@qq.com; 
主题: Re: [cmd-editor] 写了一天的文档，刷新了一下，结果没有了...卧槽 (#248)

我给你找回来，把你的用户名和那篇文档的标题给我。

**Comment by ghosert** [comment]
缓存是断网的时候用的。你这个例子，我怀疑是开了不同的浏览器或者电脑，一边把另一边覆盖了。操作系统，浏览器给我一下。

**Comment by ghosert** [comment]
当时出这个问题的操作步骤能否还原一下，描述给我？

**Comment by SongLee24** [comment]
win7 - firefox，我就记得我开了很多个页面，然后一个视频页面崩了，提示我重启浏览器，然后我点确定，浏览器自动重启了，结果写得东西就没有了，显示的欢迎界面。。。

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年10月7日(星期二) 晚上10:24
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "の神奕の"lisong.shine@qq.com; 
主题: Re: [cmd-editor] 写了一天的文档，刷新了一下，结果没有了...卧槽 (#248)

‍当时出这个问题的操作步骤能否还原一下，描述给我？

**Comment by ghosert** [comment]
你自己的文稿列表里也没了？

**Comment by ghosert** [comment]
整篇文档就消失了？

**Comment by ghosert** [comment]
按理每次击键都会自动保存。多少能存下来。
