### ISSUE TITLE
建议增加导出为pdf文件

### ISSUE THREAD

**Issue by grunmin** [ghosert/cmd-editor#25]
我认为这是stackedit吸引我的地方，导出的pdf比html格式漂亮得多。
而且建议导出的html提供模板。

**Comment by rulerson** [comment]
顶、我也使用了stackedit、感觉stackedit在页面色调上好很多、另外可以导出pdf。还有就是文件名字、cmdeditor要取第一行标题、stackedit可以自己填

**Comment by ghosert** [comment]
中文的渲染 cmd 会好一些。英文的话，西方人普遍喜欢看小字，所以也不太适合东方人。

文件标题取第一行的标题段落是为了让作者写文章的时候不必在标题框和文章正文之间来回切换。其实是更方便了，写完标题就接着写正文，全程键盘操作。

pdf 导出的功能在酝酿，真正能做到原样导出很难。标记为 enhancement.

**Comment by SunnyWind** [comment]
可以用浏览器（比如chrome）把网页（阅读模式）打印成pdf文件，不过有很多多余的元素/控件会出现在输出的pdf文件里。。。这个时侯我一般自己去改css把display弄成none。。。不过要是有直接的更“纯净”的阅读模式就更好了

**Comment by ghosert** [comment]
你把右侧边栏缩起以后再用 chrome 打印，不过我还是会提供官方的解决方案，:-)。

**Comment by rulerson** [comment]
标题问题还好、转成html后的页面风格问题是否可以调整下、尤其是各个标题的大小和色调、感觉stackedit的看起来更好看点。

**Comment by ghosert** [comment]
最好有个标准我照着做，或者你或者别人会 css 可以帮我整一个发给我，我再调整。暂时请不起美工。

**Comment by pollow** [comment]
说到排版不能不推荐 http://typo.sofish.de/ 了。希望可以导出html的时候将css内联进去。

**Comment by ghosert** [comment]
楼上这个当时我考虑过，后来觉得它的字体线条过细，色调太浅所以没有采纳，我有机会再衡量一下。这种问题总是这样，每个人审美观不同，没有自定义样式很难面面俱到，每个人都照顾到。

**Comment by ghosert** [comment]
PDF 导出 已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
