### ISSUE TITLE
邮箱地址无法解析

### ISSUE THREAD

**Issue by qingdong830** [ghosert/cmd-editor#251]
无法将`<a  hrerf="mailto:123@qq.com">123@qq.com</a>`或`<123@qq.com>`解析成超链接

**Comment by ghosert** [comment]
噢，这个是为了防止被嵌入恶意脚本代码，所以不支持 a 标签，如果有链接需要，请用 markdown 的标准书写方式 

```
[123@qq.com](mailto:123@qq.com)
```

**Comment by qingdong830** [comment]
依然无法转换成超链接

**Comment by ghost** [comment]
[123@qq.com](mailto:123@qq.com)无法转换成超链接
