### ISSUE TITLE
作业部落现在是一个人在维护吗？看更新记录，上次更新是17年初

### ISSUE THREAD

**Issue by zhjchina** [ghosert/cmd-editor#2518]
我现在放了不少资料在作业部落上面，作业部落很好用。但我有个担心：作业部落后面是个人在维护吗？如果是的话，感觉还有单点的风险啊，感觉如果后面是一个公司的话，更稳一些。现在其它云笔记也都慢慢支持markdown了，作业部落后面有什么打算吗？比如有没有考虑过卖给某个公司之类的？我没有恶意，只是感觉以公司的方式来运营更可靠安全

**Comment by danielyang990** [comment]
你还可以登录吗？ 我这边最近一个月尝试登录一直报错 ~

**Comment by zhjchina** [comment]
> 你还可以登录吗？ 我这边最近一个月尝试登录一直报错 ~

可以登陆，有时报错，重试一下就可以了

**Comment by ghosert** [comment]
[Cmd Markdown 发布第十五次更新 -- 斗罢艰险又出发](https://www.zybuluo.com/ghosert/note/2560850)
