### ISSUE TITLE
无法导出PDF

### ISSUE THREAD

**Issue by QianchengKao** [ghosert/cmd-editor#2532]
导出 PDF 文件失败，服务器可能正忙，请稍后再试，或联系我们

**Comment by wanwaner** [comment]
一样 导出服务挂了

**Comment by sunnykaka** [comment]
先用临时解决办法: 选择导出带样式的Html, 然后打开html文件, 按Ctrl+P进入打印, 再选择另存为pdf即可

**Comment by QianchengKao** [comment]
不知道你们啥情况，不管点击什么导出，最后都是一个txt文件，没法打印
