### ISSUE TITLE
这个网站现在还在维护吗?

### ISSUE THREAD

**Issue by liangjihua** [ghosert/cmd-editor#2533]
最近两年站长的微博、github都没有任何动作，issue也没有回复。我有点担心还要不要继续用下去了。

**Comment by wanwaner** [comment]
导出PDF的功能又不好使了  感觉不在有人运维了  是要放弃了吗？

**Comment by QianchengKao** [comment]
怎么退款，我可是买了会员啊啊

**Comment by liangjihua** [comment]
> 
> 
> 怎么退款，我可是买了会员啊啊

我也是会员刚到期，不敢再续了，会员还好说，里面写的东西没了问题就大了。现在在慢慢把原来写的东西往外面搬，什么时候网站访问不了就完蛋了。
说实话，我现在还没找到一个写作体验跟作业部落一样好的替代品，印象笔记，有道云都没有作业部落用起来舒服。
@ghosert 赶紧回来吱个声吧。

**Comment by ghosert** [comment]
简单维护中，请放心，会一直维护下去。

**Comment by QianchengKao** [comment]
> > 怎么退款，我可是买了会员啊啊
> 
> 我也是会员刚到期，不敢再续了，会员还好说，里面写的东西没了问题就大了。现在在慢慢把原来写的东西往外面搬，什么时候网站访问不了就完蛋了。
> 说实话，我现在还没找到一个写作体验跟作业部落一样好的替代品，印象笔记，有道云都没有作业部落用起来舒服。
> @ghosert 赶紧回来吱个声吧。

希望他 千万别不吱声就撤 啊，这么久的资料可不是开玩笑的。或者赶快开发个一键同步dropbox onedrive吧，钱不要紧别丢资料 @ @ghosert
