### ISSUE TITLE
是不是从17年开始就不再维护了?!

### ISSUE THREAD

**Issue by will-mei** [ghosert/cmd-editor#2555]
参考变更历史的最后时间: https://www.zybuluo.com/ghosert/note/102771

**Comment by jiawzhang-sh** [comment]
虽然没有更新，仍在维护，数据库和服务器硬件上投入了。争取继续抽空更新。

**Comment by ghosert** [comment]
虽然没有更新，仍在维护，数据库和服务器硬件上投入了。争取继续抽空更新。
