### ISSUE TITLE
充值Bug导致我会员冲错，在线等！

### ISSUE THREAD

**Issue by best-fq-master** [ghosert/cmd-editor#2569]
我本地 app 登陆的账号是 maxlasting，邮箱为 maxlasting@163.com

网页登陆的是 copperhaze 邮箱是 copperhaze@163.com

我在本地点击 会员充值，结果跳转到了充值页面，没特别说明给哪个账号充值，结果没有给我自己的账号充值成功，能解决一下这个问题不，我需要充值的账号是 maxlasting !

订单编号 2020060822001479571458235741

商家订单号 20200608194541580632

**Comment by ghosert** [comment]
ghosert 加我微信，给你处理下
