### ISSUE TITLE
中文段落首行缩进

### ISSUE THREAD

**Issue by rywiki** [ghosert/cmd-editor#257]
这个首行缩进是中文特有的，英文markdown根本不考虑这个，我在其它的markdown的css中是以三个空格wrap保留的，cmd 这个能满足这个效果么？中文段落稍长一些，没有缩进真不好看。

**Comment by ghosert** [comment]
已更新，可以自定义CSS了：fhttps://www.zybuluo.com/ghosert/note/378553
