### ISSUE TITLE
“一键导出所有文稿”没有包含笔记里面的图片

### ISSUE THREAD

**Issue by LinkHS** [ghosert/cmd-editor#2571]
如题，其实最担心的就是备份问题，如果导出所有文稿不能包含笔记里的图片，那么这个导出有什么意义呢？

其实现在功能基本都满足了，相比各种markdown软件做的很好！尤其还支持自定的css。即使不更新了现在的功能也够用了，但是就怕哪天服务器出了问题，辛辛苦苦做的笔记（目前来说是没有图片）丢了很郁闷，如果老大能支持导出所有文档的图片，我续费10年都没有问题！

感谢!

**Comment by ghost** [comment]
+1

**Comment by majiayao-roborock** [comment]
+1

**Comment by LinkHS** [comment]
内部图片引用不显示，发送邮件被退回，能否处理一下：

![image](https://user-images.githubusercontent.com/8181823/98333130-07be3f80-203b-11eb-9125-e7ddf0dd904d.png)

![image](https://user-images.githubusercontent.com/8181823/98332752-37b91300-203a-11eb-85eb-1f42ec612356.png)

**Comment by ghosert** [comment]
邮箱有重新开通了。support@zybuluo.com 或者用 ghosert@gmail.com

图片无法显示的问题解决了，图片都在的，没丢。导出没办法导出图片了，只要图片链接都在就不回丢。
