### ISSUE TITLE
充值后没有升级会员

### ISSUE THREAD

**Issue by ghost** [ghosert/cmd-editor#2577]
为什么充了钱，却没有会员的权益还是普通会员的权益?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/68680844/90895580-f62ea980-e3f4-11ea-8728-659292ef45d6.png)

**Comment by SovietPower** [comment]
开发者早不怎么管啦 建议只用做在线编辑器和少量的在线存储 其它功能还是要用别的

**Comment by ghosert** [comment]
联系我，给你补一年。。。 ghosert@gmail.com
