### ISSUE TITLE
图片都无法展示了，导出没有影响

### ISSUE THREAD

**Issue by wufffy** [ghosert/cmd-editor#2580]
![image](https://user-images.githubusercontent.com/23655622/93552050-0c069e80-f9a2-11ea-93a5-03e1fe9607d3.png)
图片连接有效

**Comment by leixiyoyo** [comment]
你的问题解决了吗

**Comment by wufffy** [comment]
没有，正在把数据迁到其他工具，图片丢失有点可怕

**Comment by ghosert** [comment]
解决了，没丢，都在的。
