### ISSUE TITLE
本地图片无法显示,请尽快解决啊

### ISSUE THREAD

**Issue by yaowen369** [ghosert/cmd-editor#2583]
开通了付费会员，图片上传之后, 在作业部落的markdown文本中，图片无法展示，但是图片链接放到其他markdown编辑器中就是可以正常展示的，所以应该是图片本身被上传到oss上，只是 展示出了问题。

你们尽快解决啊，我看 issue上好久之前都有人提出来了，你们都没人解决吗？

**Comment by jiaschien** [comment]
好像国庆之间图床裂了。

**Comment by DSXiangLi** [comment]
加一！是支持Http的图床出问题了！chrome浏览器里图片无法展示了。麻烦尽快修复！感谢

**Comment by monkeyDD** [comment]
+1还是不能显示

**Comment by windwolf** [comment]
目前还是没有恢复!! 这个十分严重, 请重视一下啊~~ 积累的好几年的文档, 图全都没了!!

**Comment by ghosert** [comment]
解决了，图片文档都在
