### ISSUE TITLE
图床出问题了！chrome浏览器里图片链接无法展示了。麻烦尽快修复！

### ISSUE THREAD

**Issue by DSXiangLi** [ghosert/cmd-editor#2584]
@ghosert 辛苦看一下这个问题，用作业部落格好今年了，这图片无法加载影响有点大。。。。

**Comment by ghosert** [comment]
是新版chrome引起的问题，正在修。可以先去官网下载客户端，那个没问题。

**Comment by DSXiangLi** [comment]
@ghosert 不只是在作业部落格的web端，在其他博客里用了作业部落格的图片链接也都无法显示。之前都是直接从markdown发布博客所以现在所在所有图片基本都无法显示，辛苦尽快修复一下。 Thanks~

**Comment by ghosert** [comment]
还是浏览器的问题，你单独把图片放在浏览器里看是好的。但是，如果你放在其它博客里，如果对方是https，而Cmd
的图片都是http，所以无法显示。chrome的新版本加了这个限制。

**Comment by DSXiangLi** [comment]
@ghosert 想问下这个有预计的解决时间么？或者有没有临时方案可以绕过chrome的这个限制

**Comment by ghosert** [comment]
先去官网下载客户端，客户端应该没这个问题 http://zybuluo.com/cmd/ 估计还要三四天时间修好。

**Comment by DSXiangLi** [comment]
@ghosert 感谢感谢，以及有个问题是这边修复好之后，我在其他网站引用的部落格的图片链接在chrome上也能正常显示么？

**Comment by ghosert** [comment]
应该可以。

**Comment by DSXiangLi** [comment]
@ghosert 已经过去5个3～4天了，大概还要多久能修复呢？实在不行我就换链接了

**Comment by SovietPower** [comment]
开发者n年前就不管了。。建议只用做在线编辑器和少量的在线存储文档 其它功能还是要用别的

**Comment by ghosert** [comment]
在修中，少安无躁。

**Comment by xuejianqiao** [comment]
有人在解决？

**Comment by ghosert** [comment]
在解决，要点时间。

**Comment by coder-pig** [comment]
大佬，两周过去了还没有进展吗，图床问题影响挺大的🙇‍♂️

**Comment by xuejianqiao** [comment]
@coder-pig  不是两周 是两个月过去了。

**Comment by ghosert** [comment]
稍安勿躁，全力抢修。。。

**Comment by yinguangyao** [comment]
这个问题确实好久了。。。

**Comment by yinguangyao** [comment]
@xuejianqiao @DSXiangLi @coder-pig 找到一个办法可以加载图片了，打开 chrome://settings/content/siteDetails 这个地址，隐私设置和安全性 -> 网站设置 -> 不安全内容，在允许里面添加上 https://www.zybuluo.com/ 这个域名就好了。
不过如果之后 chrome 关掉这个功能，依然是打不开图片了。

**Comment by xuejianqiao** [comment]
证书问题吧，把https的证书升级一下 解决不了问题吗？

**Comment by zzy0471** [comment]
> 稍安勿躁，全力抢修。。。

是不是已经放弃了？不打算改成https图床了？

**Comment by zzy0471** [comment]
> 稍安勿躁，全力抢修。。。

历史图片不用管了，新图片可以搞成https图床吗？

**Comment by ghosert** [comment]
解决了，历史图片都在，新图片也没问题。
