### ISSUE TITLE
作业部落的邮箱问题

### ISSUE THREAD

**Issue by pingchuan11** [ghosert/cmd-editor#2587]
1，邮箱验证码发送50不能验证，收不到验证的码
2，同步印象笔记绑定不了
请给与解决，谢谢！

**Comment by zhangcaiqian** [comment]
也遇到了相同的问题，麻烦解决一下

**Comment by luansheng** [comment]
遇到相同的问题。请作者负责人解决。我已经缴费，成为会员了。如果这样，就太不负责任了。

**Comment by ghosert** [comment]
不好意思，邮箱重新开通了，或者联系 ghosert@gmail.com 我给你们补一年会员。
