### ISSUE TITLE
生成的html代码太复杂

### ISSUE THREAD

**Issue by pengyuwei** [ghosert/cmd-editor#259]
生成的html代码太复杂，一点都不简洁，能不能生成一种最简单的html页面？甚至不带CSS的？

**Comment by ghosert** [comment]
可以在菜单栏里选择导出 html

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2014年10月16日 下午3:11，Peng Yuwei notifications@github.com写道：

**Comment by switchball** [comment]
手动嵌入几个css文件好像就可以了，以前试过的，不过很麻烦。
