### ISSUE TITLE
解决图片加载不成功的一种方式

### ISSUE THREAD

**Issue by yinguangyao** [ghosert/cmd-editor#2591]
找到一个办法可以加载图片了，打开 chrome://settings/content/siteDetails 这个地址，隐私设置和安全性 -> 网站设置 -> 不安全内容，在允许里面添加上 https://www.zybuluo.com/ 这个域名就好了。
不过如果之后 chrome 关掉这个功能，依然是打不开图片了。

**Comment by ghosert** [comment]
不用麻烦了，已经解决了。
