### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by ywb971108** [ghosert/cmd-editor#2594]
2021年了，图片无法加载的问题还没有解决吗，都好几个月了？？？

**Comment by walkdianzi** [comment]
t

> 2021年了，图片无法加载的问题还没有解决吗，都好几个月了？？？

好几个月了吗？我刚出现无法加载，好像作业部落上传的图片都是http的，在markdown里面因为安全问题禁止加载了，其他markdown编辑器好像也是

**Comment by windwolf** [comment]
目前还是没有恢复!! 这个十分严重, 请重视一下啊~~ 积累的好几年的文档, 图全都没了!!

**Comment by lan2720** [comment]
+1

**Comment by wuxinwei** [comment]
浏览器的错误提示
```
GET https://static.zybuluo.com/xxxx/xxxx/xxxx.png net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```
希望老板能看一下

**Comment by ghosert** [comment]
这个问题解决了，图都在的。
