### ISSUE TITLE
邮箱验证不了

### ISSUE THREAD

**Issue by xihale** [ghosert/cmd-editor#2599]
邮箱验证码发不出去,qq和gmail和我自己的企业邮都试了,望解决

**Comment by tt5753** [comment]
163.com也收不到呀

**Comment by xihale** [comment]
没试过,以后有时间试试吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月13日(星期六) 中午1:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ghosert/cmd-editor] 邮箱验证不了 (#2599)





 
163.com也收不到呀

**Comment by Angry-Rabbit** [comment]
这个网站估计凉了，连邮件发送不出来都没有人去解决

**Comment by xihale** [comment]
忘记之后怎么注册的了，反正应该是可以用的
