### ISSUE TITLE
阅读模式的侧边栏能不能隐藏？

### ISSUE THREAD

**Issue by SunnyWind** [ghosert/cmd-editor#26]
在移动端阅读的时侯，侧边栏会覆盖到文字上，影响阅读。

**Comment by ghosert** [comment]
这个功能有的，在右侧栏底部有一个小箭头。不知道你是什么浏览器，其实代码会检测你的设备屏幕大小，如果发觉是小尺寸会自动收起右侧的边栏。你是哪个设备？

**Comment by SunnyWind** [comment]
nexus 10。可尽管是大尺寸，文字还是会被侧边栏覆盖啊。。。我用的chrome浏览器，下面没有小箭头。。。

**Comment by SunnyWind** [comment]
经测试，firefox也没有小箭头啊。。。

**Comment by ghosert** [comment]
噢，当时只在发布模式下才启用了这个特性，你需要发布自己的文章，例如这样的链接：http://www.zybuluo.com/ghosert/note/2 就有这个功能，未发布状态下，我原来想大多数人会在大尺寸电脑上写作，所以没加这个。

**Comment by SunnyWind** [comment]
这样啊，几乎没用过发布模式。。。必竟也不是特地写了给别人看的。。。不过编辑器也没有明显跳到发布模式的入口诶。。。虽然我现在知道只要把地址栏的mdeditor换成用户名就行了。。。

**Comment by ghosert** [comment]
噢，这个是因为你没用过发布功能，发布过就知道 url 应该是什么样子的。

**Comment by ghosert** [comment]
作为作者还是鼓励大家多发布，首先写给别人看，对质量的要求就会高很多，其次把自己的知识分享给别人，回过来别人也会给你建议，互惠互利的事情。

**Comment by ghosert** [comment]
针对你的情况，我会把隐藏侧边栏也加到未发布的状态下。

**Comment by SunnyWind** [comment]
GOOD ：D

**Comment by ghosert** [comment]
已修复。
