### ISSUE TITLE
注脚被重复引用时生成了多余的注脚

### ISSUE THREAD

**Issue by ccwan** [ghosert/cmd-editor#260]
![00](https://cloud.githubusercontent.com/assets/4736131/4660713/0cf0e67a-551b-11e4-877d-6552218ab707.png)

**Comment by ghosert** [comment]
规则就是有几个地方引用了 [^aaa] 就有几个注脚，你这边有三个地方引用。。。序列号在文稿内部是不能重复的，譬如出现 [1][1][2]
这种，只能是 [1][2][3]

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

2014-10-16 17:59 GMT+08:00 ccwan notifications@github.com:

**Comment by ccwan** [comment]
好吧，我其实是想要交叉引用或者文献索引的功能。。。
