### ISSUE TITLE
这个平台还有人在维护吗？

### ISSUE THREAD

**Issue by ybtang21c** [ghosert/cmd-editor#2600]
今天刚刚注册，发现非常喜欢这个平台（包括它的客户端）的编辑风格，甚至可以说是感觉相见恨晚。

但才注意到2017年至今似乎平台已经没有过任何更新。找到这里发现不少人遇到了和我一样的问题，邮箱收不到验证邮件。还有人说交费升级了高级会员，却没有真的升级成功。

我非常希望能长期使用这个平台作为自己日后的写作和记录工具，但是，如果它已经停止维护和更新了，可能还是不得不放弃。

所以，有人能回答我的问题吗？**这个平台还有人维护吗？**

此外，我还想问问，如果自己搭建，哪里可以找到相应的手册。这么好的平台如果就这样荒废了实在可惜呀。

**Comment by ken0225** [comment]
it is almost ended..

**Comment by ghosert** [comment]
最近把所有的基础功能和高级功能全部恢复了。请使用，对不起了。后面会继续维护更新！

**Comment by onism222** [comment]
> 最近把所有的基础功能和高级功能全部恢复了。请使用，对不起了。后面会继续维护更新！

真心希望作者坚持住！大家都支持你。
