### ISSUE TITLE
用户名密码无法登录

### ISSUE THREAD

**Issue by shujiangle** [ghosert/cmd-editor#2612]
![image](https://user-images.githubusercontent.com/22750570/142887846-6ebaca9a-ff44-4554-84ea-d0a906b591e3.png)

**Comment by zDream** [comment]
我也是这个问题，还有人维护吗？

**Comment by Brownkivi** [comment]
同问今天开始就一直这样登不进去了

**Comment by ghosert** [comment]
已修复！
