### ISSUE TITLE
发布无法展示图片

### ISSUE THREAD

**Issue by 535727655** [ghosert/cmd-editor#2616]
![image](https://user-images.githubusercontent.com/20313857/145945922-96274c0f-a4e1-433a-9041-dd5bfcf66d39.png)

**Comment by qq517634644** [comment]
firefox 试一下 这个可以

**Comment by mafgwo** [comment]
图片还是要放在自己可控的地方，可以使用StackEdit中文版，用什么图床自己决定，支持多种图床。

**Comment by ghosert** [comment]
已经恢复了。
