### ISSUE TITLE
有序列表会被代码块截断

### ISSUE THREAD

**Issue by sxd1140** [ghosert/cmd-editor#262]
1. 列表项1

``` javascript
123 
```
1. 列表项2

2 就从头开始了

这种问题应该怎么解决  看到github也是这样的

**Comment by ghosert** [comment]
列表之间不适宜再添加代码段了。列表的本意是简单项的罗列，你这种需求可以换个写法，避免使用列表。例如：
### 1. 列表项1
xxxx
### 2. 列表项2

**Comment by sxd1140** [comment]
有些解释器是可以支持的  因为我是来写一些 code snippet

了解了 感谢
