### ISSUE TITLE
查看之前保存的文件，里边的图片点无法显示了

### ISSUE THREAD

**Issue by 1831647762** [ghosert/cmd-editor#2620]
查看之前保存的文件，里边的图片点无法显示了，这是什么情况，新上传的图片也显示不出来

**Comment by ScarecrowFu** [comment]
估计已经没人维护了

**Comment by icyfang** [comment]
可能是原来的图床开了防盗链

**Comment by mafgwo** [comment]
StackEdit中文版支持多种稳定图床 推荐使用
![image](https://user-images.githubusercontent.com/46500241/184054988-ce4d47c9-b9aa-47f6-9a8a-80d6f2040446.png)

**Comment by ghosert** [comment]
已经解决了。
