### ISSUE TITLE
看上去cmd不维护了，换了个新的工具

### ISSUE THREAD

**Issue by pashangshangpo** [ghosert/cmd-editor#2621]
之前很喜欢用这个cmd来写markdown，但是这个好像已经不维护了，现在使用的Typora，然后再搭配https://blog.csdn.net/u010918911/article/details/125043780 这款工具自动同步markdown到印象笔记，妥妥的。

**Comment by mafgwo** [comment]
还是免费的比较香，StackEdit中文版 https://stackedit.cn ，也非常好用，是开源免费的，源码在 https://gitee.com/mafgwo/stackedit
