### ISSUE TITLE
推荐大家一起使用Cmd Markdown

### ISSUE THREAD

**Issue by Lioncky** [ghosert/cmd-editor#2622]

**Comment by mafgwo** [comment]
StackEdit中文版有深色主题 可以转用StackEdit中文版 开源免费 哈哈

**Comment by KsaNL** [comment]
> StackEdit中文版 https://stackedit.cn 有深色主题 可以转用StackEdit中文版 开源免费 哈哈 ![image](https://user-images.githubusercontent.com/46500241/184054763-cbc64cc6-fd3b-421d-bb49-c038d5d37b0c.png)

试了下 挺好用的感觉 可以吧Commit打开了

**Comment by zzy0471** [comment]
看上去不错，就是不知道会不会没几年也没人管了。我现在用网易云笔记，不管用起来还是没用markdown顺手

**Comment by mafgwo** [comment]
> 看上去不错，就是不知道会不会没几年也没人管了。我现在用网易云笔记，不管用起来还是没用markdown顺手

开源免费，源码在  [StackEdit中文版Gitee仓库源码](https://gitee.com/mafgwo/stackedit) ，不用担心没人管。
