### ISSUE TITLE
以前的文章里的图片无法显示

### ISSUE THREAD

**Issue by WZero98** [ghosert/cmd-editor#2625]
最近搜到了用cmd写的一篇博客，里面的图片全都缺失了

**Comment by WZero98** [comment]
我自己发现了一个解决方法，将页面另存为本地html文件后，将本地文件打开即可查看到图片

**Comment by qicoding** [comment]
用StackEdit中文版 https://stackedit.cn ，支持GitHub图床、或自建的Gitea图床

**Comment by ghosert** [comment]
已经恢复了。
