### ISSUE TITLE
vim 模式经常卡住

### ISSUE THREAD

**Issue by duangao** [ghosert/cmd-editor#263]
你好，写起来使用效果非常好，感谢！
但是我在调整为vim模式以后，经常卡住无法删除任何字符，不知道是什么原因？

**Comment by ghosert** [comment]
浏览器，操作系统说一下。

**Comment by duangao** [comment]
你好，
操作系统 windows8.1，浏览器chrome。
祝好！

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年10月21日(星期二) 晚上8:32
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "duangao"gaoduan0306@gmail.com; 
主题: Re: [cmd-editor] vim 模式经常卡住 (#263)

浏览器，操作系统说一下。

**Comment by ghosert** [comment]
hmmm，windows 8.1 的确没有试过，chrome 浏览器理论上性能最好，你换成 firefox 看看？

**Comment by duangao** [comment]
好的。感谢啦！

------------------ 原始邮件 ------------------
发件人: "Jay Zhang";notifications@github.com;
发送时间: 2014年10月21日(星期二) 晚上8:43
收件人: "ghosert/cmd-editor"cmd-editor@noreply.github.com; 
抄送: "duangao"gaoduan0306@gmail.com; 
主题: Re: [cmd-editor] vim 模式经常卡住 (#263)

hmmm，windows 8.1 的确没有试过，chrome 浏览器理论上性能最好，你换成 firefox 看看？

**Comment by ghosert** [comment]
vi 模式 我也在升版本，希望下次发布新版本能有改善。到时再通知你。

**Comment by ghosert** [comment]
vim 已升级，可以去试试，如果还有问题再告诉我。
