### ISSUE TITLE
反馈几个问题

### ISSUE THREAD

**Issue by bd7xzzxyz** [ghosert/cmd-editor#2633]
1. manjaor linux下 chrome无法在线编辑，客户端也无法编辑，pc端firefox可以编辑，但是无法切换输入法。输入法和chrome在浏览器其他网页都没有问题
2. 在linux下打开文章后，在其他设备再登录pc端图片全部失效
<img width="523" alt="image" src="https://user-images.githubusercontent.com/86887335/218011281-a9368c79-111c-475b-8fc9-72af93bac5b4.png">

希望尽快解决这些问题，为了支持cmd-editor，也购买了会员，但是这2个问题非常严重，已经造成我无法使用。现在更换其他markdown了，有些失望了。

**Comment by mafgwo** [comment]
Linux下用 [StackEdit中文版](https://stackedit.cn)，开源免费，不输cmd-editor

**Comment by ghosert** [comment]
最近重新升级了一下网站功能和客户端，请重新试一下这些问题是否还存在。发邮件给 support@zybuluo.com 送你一年会员。
