### ISSUE TITLE
下载通道怎么关了， 谁能给我一个linux安装包吗？

### ISSUE THREAD

**Issue by LTreeshu** [ghosert/cmd-editor#2635]
如题

**Comment by mafgwo** [comment]
linux直接用 [StackEdit中文版](https://stackedit.cn)，网页的，开源免费。

**Comment by LTreeshu** [comment]
没网怎么办😂😂😂发自我的手机-------- 原始邮件 --------发件人： Douqi ***@***.***>日期： 2023年4月24日周一 19:53收件人： ghosert/cmd-editor ***@***.***>抄送： LTreeshu ***@***.***>, Author ***@***.***>主    题： Re: [ghosert/cmd-editor] 下载通道怎么关了， 谁能给我一个linux安装包吗？ (Issue #2635)
linux直接用 StackEdit中文版，网页的，开源免费。

**Comment by mafgwo** [comment]
支持离线编辑，chrome打开会提示安装chrome插件，没网直接可以在本地离线编辑，因为所有数据在浏览器的indexeddb数据库中都有同步一份的。

**Comment by LTreeshu** [comment]
感谢发自我的手机-------- 原始邮件 --------发件人： Douqi ***@***.***>日期： 2023年4月24日周一 20:26收件人： ghosert/cmd-editor ***@***.***>抄送： LTreeshu ***@***.***>, Author ***@***.***>主    题： Re: [ghosert/cmd-editor] 下载通道怎么关了， 谁能给我一个linux安装包吗？ (Issue #2635)
支持离线编辑，chrome打开会提示安装chrome插件，没网直接可以在本地离线编辑，因为所有数据在浏览器的indexeddb数据库中都有同步一份的。

**Comment by ghosert** [comment]
下载恢复了，客户端也重新做过了，去下载：https://www.zybuluo.com/cmd/
