### ISSUE TITLE
没有有效的服务

### ISSUE THREAD

**Issue by ldypk** [ghosert/cmd-editor#2636]
看了样文，操作确实是所见即所得，但文件导出，损失了最心仪的部分，以为是普通用户的原因，付款升级为高级用户，还是一样。问题有两个：一是导出为MD文件，其他的Markdown编辑器只能显示一般的内容，其中绘图部分不支持，甚至打不开文件；二是输出为html文件，与原文件显示有出入，用的是示例文档。如果等自己辛苦几个月形成的文档，再发现这些问题，就麻烦了，只能在这个网站上看，怎么行？是技术文档，不是要出版的小说。
服务只有提问题入口好用，还是导航到这里，本来是应私下反馈的，只好按其“作业部落”的流程来反馈了。

**Comment by onism222** [comment]
+1

**Comment by ghosert** [comment]
可以把你的文稿地址发到 support@zybuluo.com 看看，应该可以原样导出，如果还想试一下高级功能，发个申请到 support@zybuluo.com 送你免费一年会员。
