### ISSUE TITLE
网站打不开了（被网信办屏蔽）最近更新：基础服务已于 2024/02/20 恢复。

### ISSUE THREAD

**Issue by yiranblade** [ghosert/cmd-editor#2638]
是不是不维护了，我5-6年的数据

**Comment by XugangXie** [comment]
是跑路么，浪费了99一年的RMB无所谓，我里面有数据啊

**Comment by zzy0471** [comment]
大哥，网站如果不打算开了，就提前告知一下，把会员续费功能关掉。我刚续了会员，还有很多年的文章每备份呢

**Comment by zboboan** [comment]
炸了，我的很多笔记呀……千万别不开了

**Comment by zboboan** [comment]
> 大哥，网站如果不打算开了，就提前告知一下，把会员续费功能关掉。我刚续了会员，还有很多年的文章每备份呢

知道怎么联系作者嘛？

**Comment by zboboan** [comment]
> 是不是不维护了，我5-6年的数据

作者怕是几年没有登这个号了吧

**Comment by XugangXie** [comment]
![Uploading 5.png…]()

**Comment by 103yiran** [comment]
作者的邮箱：ghosert@gmail.com。我已经发邮件咨询了。

**Comment by zboboan** [comment]
> 

我也发了

**Comment by zboboan** [comment]
> 作者的邮箱：[ghosert@gmail.com](mailto:ghosert@gmail.com)。我已经发邮件咨询了。

我也发了

**Comment by 103yiran** [comment]
作者回复说因阿里云内容审查问题封禁了，可能需要1到3天解禁。

**Comment by zboboan** [comment]
> 

好的   谢谢

**Comment by AxinAx** [comment]
这次网站崩了，吓得我连夜把笔记搬到语雀了

**Comment by ZHSY** [comment]
> 这次网站崩了，吓得我连夜把笔记搬到语雀了

网站都崩了你怎么迁移的？我要急死了

**Comment by AxinAx** [comment]
> > 这次网站崩了，吓得我连夜把笔记搬到语雀了
> 
> 网站都崩了你怎么迁移的？我要急死了

一个一个导出md的，我本地有客户端

**Comment by ghosert** [comment]
不好意思，我是作者给大家造成困扰。网站因为有用户发表的违规内容，暂时被网信部禁止访问，我正在积极沟通争取早日解禁。在此之前，请把你的注册邮箱或者用户名发送到 ghosert@gmail.com 我会把你的数据备份发给你。我们还有一个微信群，大家可以扫码进来关注事态发展。

目前只能做到这么多，抱歉，非人力所能及。

[
![mmqrcode1708366231773](https://github.com/ghosert/cmd-editor/assets/236040/e968ce63-8d4c-4d36-853f-aff8664d8694)
](url)

**Comment by chirsz-ever** [comment]
@ghosert 作者可以将这条 issue pin 住方便大家找到嘛

**Comment by ghosert** [comment]
已经PIN了



Regards,
Jay Zhang

**Comment by ssyangchn** [comment]
谁发的违规内容找谁去，关平台啥事，真让人无语

**Comment by changedi** [comment]
有最新进展吗

**Comment by ghosert** [comment]
正在解决，请大家积极入群，等待后续方案

**Comment by goldSunshine** [comment]
客户端支持导出全部数据，速度很快

**Comment by xizonghu** [comment]
> 客户端支持导出全部数据，速度很快

从哪里下载客户端的，我记得客户端是主体是webkit，网站打不开了客户端还能用吗？

**Comment by goldSunshine** [comment]
> > 客户端支持导出全部数据，速度很快
> 
> 从哪里下载客户端的，我记得客户端是主体是webkit，网站打不开了客户端还能用吗？

客户端完全可以继续使用，客户端是在之前安装的。

**Comment by goldSunshine** [comment]
> > 客户端支持导出全部数据，速度很快
> 
> 从哪里下载客户端的，我记得客户端是主体是webkit，网站打不开了客户端还能用吗？

我找了一下，我的安装包已经删掉了，可以让作者提供安装包，或许还能登录使用。响应有点慢，但是能打开，能导出

**Comment by claviering** [comment]
> 这次网站崩了，吓得我连夜把笔记搬到语雀了

语雀也崩了

**Comment by squareRoot3** [comment]
@ghosert 作者你好 可以把我的所有笔记发送到我的注册邮箱吗(240064446@qq.com)  感恩

**Comment by ghosert** [comment]
> @ghosert 作者你好 可以把我的所有笔记发送到我的注册邮箱吗([240064446@qq.com](mailto:240064446@qq.com)) 感恩

已经回复你邮件了

**Comment by cbweixin** [comment]
网站还是打不开。 能解决问题吗？

**Comment by ghosert** [comment]
还在解决

**Comment by nobject** [comment]
你好，能帮我把我的笔记发送到845013966@qq.com的邮箱么，注册名是同一个

**Comment by ghosert** [comment]
> 你好，能帮我把我的笔记发送到[845013966@qq.com](mailto:845013966@qq.com)的邮箱么，注册名是同一个

发了。

**Comment by 523592872** [comment]
@ghosert 你好，有客户端吗？或者发我邮箱523592872@qq.com

**Comment by huanghaogit** [comment]
你好，能帮我把我的笔记发送到huanghao_wy@163.com的邮箱么，注册名是同一个

**Comment by sixhui** [comment]
你好，能帮我把我的笔记发送到 liuxh_cn@163.com 的邮箱吗，注册名是同一个，谢谢！

**Comment by ghosert** [comment]
> 你好，能帮我把我的笔记发送到 [liuxh_cn@163.com](mailto:liuxh_cn@163.com) 的邮箱吗，注册名是同一个，谢谢！

这次我发了，但请直接发邮件给 ghosert@gmail.com 索要备份文件，请后来者不要在这个帖子里要了。

**Comment by hust-kevin** [comment]
@ghosert 两个月前我就发送邮件了，你一直没有给我发备份文件，邮箱是1369208691@qq.com

**Comment by ghosert** [comment]
> @ghosert 两个月前我就发送邮件了，你一直没有给我发备份文件，邮箱是[1369208691@qq.com](mailto:1369208691@qq.com)

我当天就回复了，今天又发了一次。

<img width="253" alt="Screenshot 2023-12-14 085040" src="https://github.com/ghosert/cmd-editor/assets/236040/182c77f9-8cec-4b50-8b18-fdbaf2fec992">

**Comment by ghosert** [comment]
目前已经按照网信办要求上传所有资料，正在等待他们回复。分管老师说自己在出差，会答复我。

**Comment by 523592872** [comment]
@ghosert 你好，能帮我把我的笔记发送到 523592872@qq.com 的邮箱吗，注册名是同一个，谢谢！

**Comment by ghosert** [comment]
> @ghosert 你好，能帮我把我的笔记发送到 [523592872@qq.com](mailto:523592872@qq.com) 的邮箱吗，注册名是同一个，谢谢！

请发邮件到 ghosert@gmail.com 索要备份。

**Comment by yuchengxin** [comment]
上面微信群的二维码失效了，可以再发一个吗？@ghosert

**Comment by ghosert** [comment]
> 上面微信群的二维码失效了，可以再发一个吗？@ghosert

已更新，请重新试一下。

**Comment by ghosert** [comment]
网站基础服务已经恢复。https://zybuluo.com/ 使用原用户名密码登陆。
