### ISSUE TITLE
网站打不开了

### ISSUE THREAD

**Issue by WadeAech** [ghosert/cmd-editor#2640]
假如有一天网站真的不开了，请一定一定要提前告知一下，我的笔记还没备份

**Comment by lidaye111** [comment]
真坑啊

**Comment by shanhai1024** [comment]
我的也打不开了啊！！！

**Comment by Raymundo-cj** [comment]
打不开了呀，分享出去的笔记也打不开了，啊啊啊，写了好几年的笔记全在里面呀！！！

**Comment by likfe** [comment]
看这里【网站打不开了（被网信办屏蔽），附上数据导出的方法 #2638】

**Comment by ghosert** [comment]
网站基础服务已经恢复。https://zybuluo.com/ 使用原用户名密码登陆。
