### ISSUE TITLE
能否在目录方面有所改进

### ISSUE THREAD

**Issue by rulerson** [ghosert/cmd-editor#266]
我想提两个建议
1. 能否在生产最终格式时候自动添加目录数字序号、比如1.1 ， 1.2, 1.2.1这样、是的看文档的人一目了然、知道看到什么位置了。
2. 能否自动在文章最前面插入目录。

**Comment by ghosert** [comment]
第一点应该是作者自己添加，强制生成序号可能不是所有人的意愿。
第二点也是，可以通过 [TOC] 自行加。https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#1-%E5%86%85%E5%AE%B9%E7%9B%AE%E5%BD%95

**Comment by rulerson** [comment]
1. 自动生成序号确实不一定是所有都愿意、是否可以做成可选。
2. 谢谢、找到了。不过有点建议、toc自动生成的目录里面、包含了第一层目录、就是这个‘#’，通常这个最终都变成文档标题了，建议不要这个。说道这里、顺便再提个建议、可否把这个level的目录位置展示到中间、表示是文档标题、同时在浏览器的标题上也展示这个。或者可选位置。
