### ISSUE TITLE
文案语法错误

### ISSUE THREAD

**Issue by libook** [ghosert/cmd-editor#268]
“正在加载文章图片，请稍后片刻...”
“稍后”和“片刻”语义重复，请使用“稍后”或“稍等片刻”

**Comment by ghosert** [comment]
了解了，我改下。
你是做
编辑的吗？

**Comment by libook** [comment]
@ghosert 不是。。。只是偶尔用这个写点markdown，因为可以一边写一边看效果。。。不过最近不想用了，因为在我的chromium中会因为半角字符而使光标显示的位置错误。我用半角字符打了一行，光标显示的位置差不多是相同数量的全角字符后面的位置。

**Comment by ghosert** [comment]
能提个图上来不。。。

**Comment by libook** [comment]
![2014-10-30 10 24 03](https://cloud.githubusercontent.com/assets/3395610/4837689/21ace1d8-5fdc-11e4-93d1-02f2e08f783d.png)
后面没有空格，光标显示的位置漂移，不影响输入，但是修改的时候不知道光标到底在哪。

**Comment by ghosert** [comment]
操作系统版本，浏览器版本说一下吧。这个问题主要是因为可能你在浏览器里强制设置了非等宽字体，可否检查一下，使用网站 css 自定义的字体。

**Comment by ghosert** [comment]
“稍等片刻” 的问题已经修复。

**Comment by libook** [comment]
Linux version 3.17.1-1-ARCH (nobody@var-lib-archbuild-testing-x86_64-tobias) (gcc version 4.9.1 20140903 (prerelease) (GCC) ) #1 SMP PREEMPT Wed Oct 15 15:04:35 CEST 201

Chromium 38.0.2125.111 (290379) (64-bit)

**Comment by libook** [comment]
我用的是文泉驿等宽微米黑
![2014-10-30 14 17 45](https://cloud.githubusercontent.com/assets/3395610/4839322/853801a4-5ffc-11e4-8183-b8744fdb6457.png)

**Comment by ghosert** [comment]
这样，你把【宽度固定的字体】设成 monospace 看看

**Comment by libook** [comment]
问题依旧，重启chromium进程也不行

**Comment by ghosert** [comment]
你这个发行版确实手头没有，我在 Ubuntu 上也没问题，我这边用的是 微软雅黑， 文泉的字体也是你自己装的吧。建议先把全部字体换成 monospace 再看看？

我再找找你这个发行版。

**Comment by libook** [comment]
全改成monospace也不行。。。甚至把系统字体都改成monospace了，还是不行。。。
archlinux的发行版其实是没有桌面的，我是根据自己的喜好安装的gnome3，字体也是自己安装的，感觉问题没有出在字体上，可能是x？gnome3？chromium？某些细微配置导致的问题？

**Comment by ghosert** [comment]
增加了自定义字体的功能，你看看能不能CMD自己的字体设置解决这个问题，选用一些等宽字体：fhttps://www.zybuluo.com/ghosert/note/378553

**Comment by ghosert** [comment]
有结果和我回复下。

**Comment by libook** [comment]
有可能是某个软件BUG，在某次软件更新后就好了。
