### ISSUE TITLE
能不能增加多一个导出pdf格式

### ISSUE THREAD

**Issue by clinyong** [ghosert/cmd-editor#269]
目前只能导出html和markdown

**Comment by gillbates** [comment]
是啊，要不每次都要粘贴到本地来输出pdf。

**Comment by Alaya-in-Matrix** [comment]
希望能够导出为pdf, 而不是使用浏览器的打印功能, 并且能够为Pdf分页时改变下样式,

**Comment by zimenglan-sysu** [comment]
是吖, 非常需要这个

**Comment by badpx** [comment]
嗯，PDF 在浏览和打印这块比HTML好太多了，希望能够支持，谢谢！

**Comment by Jack2code** [comment]
苦等导出PDF

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
