### ISSUE TITLE
希望开放HTML标签

### ISSUE THREAD

**Issue by pollow** [ghosert/cmd-editor#27]
写入HTML标签虽然不会显示，但是大多没有效果，是否开了白名单？
这样的话很多功能无法实现，比如右对齐、居中等。

顺便希望开放css

**Comment by ghosert** [comment]
暂时因为安全考虑，屏蔽了 html 代码，如果有强烈要求，可以考虑开放。

css 开放的确可以，标记为 enhancement

**Comment by ghosert** [comment]
已支持。
