### ISSUE TITLE
内容目录 可以支持不自动隐藏吗？

### ISSUE THREAD

**Issue by ilaipi** [ghosert/cmd-editor#276]
用这个写开发文档，感觉很赞。
不过，大量的目录，看的时候，每次要点那个按钮才能打开 内容目录。

现在发布后的页面，两边那么宽，建议按照word的习惯，把内容目录显示在左侧。

**Comment by ghosert** [comment]
点右上角那个内容目录，别点其它地方开着就行了，可以滚动鼠标翻页。

**Comment by ilaipi** [comment]
-_- 要复制内容呢？

**Comment by ghosert** [comment]
感觉带着目录浏览已经覆盖大多数情况了，偶尔复制再点一下即可。概率不大。
2014-11-5 下午6:00于 "杨亚梦" notifications@github.com写道：
