### ISSUE TITLE
我是来提需求的

### ISSUE THREAD

**Issue by x-tropy** [ghosert/cmd-editor#277]
没有以下功能我是找不到理由用的：
1. 支持本地图片拖拽添加；
2. 导出pdf文档；
3. 多文件组织，并以web形式发布供他人阅读；

我用md写PRD，谢谢！~

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938

**Comment by x-tropy** [comment]
这个工具迭代得不错的样子~
