### ISSUE TITLE
可有批量导出的功能？

### ISSUE THREAD

**Issue by zxdy** [ghosert/cmd-editor#28]
RT。。貌似没找到

**Comment by foolyoghurt** [comment]
强烈建议支持该功能！本地留个备份，让人安心点啊，不然万一服务器出问题，数据丢失，本地的缓存也没了，那岂不是损失巨大

**Comment by ghosert** [comment]
没事，免费稳定运行一年，从来没有出过任何问题，站上所有用户可以作证。

**Comment by JoshWu** [comment]
保存在上面的内容是没有问题的, 但是如果用户想自己做一些版本管理的话,就会很麻烦的. 比如我无意中把几行给删除了,然后又关掉了页面. 对于我来说这几行就无意被我删除了. 如果可以批量导出的话,用户可以自己管理版本. 文章的质量会更有保证.

**Comment by ghosert** [comment]
导出可以做，但是你说的理由有些问题，因为即使你自己导出，你也可能会自己删除几行，然后没保存，关闭了。

**Comment by JoshWu** [comment]
所以用户自己可以在本地保存一个版本或者几个版本.在觉得有问题的时候同网上的数据比较一下,起码误删的东西可以找的回来.

**Comment by ghosert** [comment]
这个负担不留给用户了，今后会自己在后台默默留存历史版本。

**Comment by foolyoghurt** [comment]
@ghosert 关键是导出对用户真的是「负担」么？窃以为至少应该给用户一个选择，能够很方面的取回自己所有的数据，比如之前我用cmd记录了很多资料，后来我同学找我要，我想发给他，但是没法导出来，我又不想把我的账号给他，所以只能挨个一个个的去「发布」，然后分享链接给他，这个过程真的相当麻烦，

**Comment by JoshWu** [comment]
楼上的用例. 就是需要"批量导出"的情况. 既不想公开发布,又要发给某些朋友很多文章.

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
