### ISSUE TITLE
一些改进建议

### ISSUE THREAD

**Issue by qso** [ghosert/cmd-editor#285]
对比了一下 CMD和STACKEDIT，我觉得CMD的社区思路是非常好的，来提几点意见。
1、大部分人写MARKDOWN还是到博客上用的，目前的发布似乎只有生成新的页面，没有发布到博客的功能，可能也是因为国内支持markdown的平台还不多吧，如果这条路走不通，为何不自己搞一个。现在只能生成单个文章的页面，似乎没有用户个人的页面，有没有可能发展成博客平台呢，毕竟有这么好的编辑器。
2、至于PDF 人人都是喜欢的，但是stackedit的PDF功能也是收费的，我建议采取类似模式。

总之功能上可以模仿STACKEDIT 另外渐渐形成社区，非常期待CMD的发展

**Comment by lanxinyuchs** [comment]
可以自己手动建一个博文索引的文档作为博客入口https://www.zybuluo.com/lanxinyuchs/note/47049

**Comment by ghosert** [comment]
建议很好，PDF 已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
