### ISSUE TITLE
火狐浏览器中如何重新启用全屏？

### ISSUE THREAD

**Issue by xzyyjy** [ghosert/cmd-editor#292]
一直在用vim模式，今天换了火狐浏览器，点击全屏的时候弹出：是否允许随时按下ESC退出全屏，我选了否（担心跟vim的esc冲突），而且选择了记住选择（手贱）。从此我的火狐再也不能全屏了，点击每任何反应。怎么破啊？？？

**Comment by ghosert** [comment]
你按 F11 全屏吧，应该就没问题了，和 vim 也不冲突。

**Comment by xzyyjy** [comment]
果然F11可以！+1
