### ISSUE TITLE
批注功能右面“私有”按钮hover上去时顶出右侧浏览器边框

### ISSUE THREAD

**Issue by wtbhk** [ghosert/cmd-editor#294]
![qq 20141109221353](https://cloud.githubusercontent.com/assets/4331071/4967588/e2fd5ca0-681a-11e4-90fb-802fac1282f3.png)

顶出浏览器边框下方滚动条出来了

**Comment by ghosert** [comment]
你这屏幕得有多窄才能出这效果。。。

**Comment by wtbhk** [comment]
1366
