### ISSUE TITLE
ctrl+s

### ISSUE THREAD

**Issue by quheng** [ghosert/cmd-editor#302]
能否覆盖掉ctrl+s的快捷键....
随手ctrl+s，一案就出来保存html....好烦人的.....不知能否覆盖掉这个快捷键？
另：求推出pc端的应用T_T  好喜欢这个markdown的编辑器.....

**Comment by zzhdi** [comment]
估计这个比较难，ctr+s 是浏览器的快捷键

**Comment by ghosert** [comment]
已改正。

**Comment by ghosert** [comment]
已改正。
