### ISSUE TITLE
账号无法登录

### ISSUE THREAD

**Issue by skidu** [ghosert/cmd-editor#304]
三个月前发送的验证邮件已无从寻觅
现在账号登录陷入死循环。。。
即使是重置密码后，登录也会立即提示让我去当时发送的那份验证邮件中戳一下链接
可以提供个重新发送验证信件的按钮不？

**Comment by ghosert** [comment]
你如果还记得自己的用户名（非邮箱），可以直接用用户名登录，进去以后再验证一下邮箱。有问题再找我。

**Comment by ghosert** [comment]
或者登录进去以后，可以去这个链接 https://www.zybuluo.com/settings/account 重发验证邮件。
