### ISSUE TITLE
要不支持图片上传呗？

### ISSUE THREAD

**Issue by LeonardoPhysh** [ghosert/cmd-editor#305]
写文档画的图还得找地方才能用，挺麻烦的，可以上传就好多了

**Comment by cdmonkey** [comment]
同意流川的意见，的确是有些不方便。

**Comment by nejyeah** [comment]
简直就是大问题，不能用本地图片，高毛

**Comment by yangws** [comment]
顶，没图片不方便，每次都是线上编辑，复制到本地的编辑器看图片 。

**Comment by flcker** [comment]
顶，插入图片太麻烦了

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
