### ISSUE TITLE
能否支持同步到Evernote?

### ISSUE THREAD

**Issue by CyL0NG** [ghosert/cmd-editor#313]

**Comment by konanzheng** [comment]
如果看别人文章可以直接捡藏内容，如果是自己的文章，发布之后剪藏个地址就好了

**Comment by zldream1106** [comment]
同感，鉴于没有良好的多终端同步功能，多数情况下只能作为 markdown 转换器使用。如果能够联合 evernote 、有道笔记等，做针对性的同步支持（如 马克飞象），使用的人会更多，实用性也会更强。

**Comment by qiufei** [comment]
很希望增加这个功能

**Comment by qiufei** [comment]
http://markable.in/editor/# 
这个就能做到与evernote的导入导出，但是它的界面做的没有cmd markdown好看。

**Comment by ghosert** [comment]
已支持同步到 Evernote: https://www.zybuluo.com/ghosert/note/102771
