### ISSUE TITLE
编辑时文章内容太多时会出现响应迟缓甚至假死的情况

### ISSUE THREAD

**Issue by valaxy** [ghosert/cmd-editor#317]
具体参见这种程度的内容 https://www.zybuluo.com/valaxy/note/48554
编辑时哪怕改一点点都会渲染很久，是因为每次修改markdown，js都会把所有内容解析和渲染一遍吗？

**Comment by ghosert** [comment]
你这个例子比较特殊，因为你写了两千多个标题，具体的原因我会再研究，但是目前来看是因为代码为每个标题分配 hash 码，导致计算量过大。一般正常使用不会有这种问题。

**Comment by ghosert** [comment]
噢，又看了看，是因为需要做 2000 遍 binding event，看有机会改一下。

**Comment by ghosert** [comment]
已经改好了，下版本更新时发布。

**Comment by ipeisong** [comment]
可以考虑使用Reactjs.

**Comment by ghosert** [comment]
已经修复了。
