### ISSUE TITLE
笔记本，屏幕分辨率为1366x768, 全屏编辑模式下“保存中”字样会折换到第二行

### ISSUE THREAD

**Issue by ghosert** [ghosert/cmd-editor#32]
发现一点问题，当我进入全屏的编辑模式时，在最后一行编辑时，页面顶部的保存中老是会使最后一行的字跳上跳下，用着不大舒服。希望能修正一下下

**Comment by minixalpha** [comment]
在ubuntu/chrome下，用ctrl + 增大浏览器显示后，同样的问题也会出现。

我在chrome里手动调整了工具栏的宽度，“保存中”就不会折行了。

感觉最好是能够让“保存中”不要出现，只要让用户知道他们的文档会自动保存就行了，不用一直提示，一直提示会打扰用户。

**Comment by ghosert** [comment]
固定了标题栏的宽度为 850px，原来设置为 50%，固有此问题，已修复。
