### ISSUE TITLE
写了几天的文档, 切换一下文档, 再切换回来就没了, 提示离线模式还原的也是几天前的.

### ISSUE THREAD

**Issue by yougg** [ghosert/cmd-editor#322]
系统从来没有离线过, 为什么总是提示在离线模式.
使用的公司代理服务器连接外部网络, 如果没有提交保存到服务器, 那为什么本地恢复的也是旧的?
这几天的文档还能不能恢复?

note/33668

**Comment by yougg** [comment]
Chrome 控制台中查看网站的Local Storage 里面存的 "local-temp" 内容就是旧的.
写了几天的内容怎么没刷新?

**Comment by ghosert** [comment]
可能是你们公司连接不到我们的服务器。离线引用在做，目前的离线模式只是应急的，并不可靠。

**Comment by yougg** [comment]
如果连不到, 我的所有内容都存不进去了.
现在是只有这几天的内容没有存进去.

如果在线和离线都没有成功保存内容, 能收能给个醒目的提示, 让我自己另外存一份也好啊.

**Comment by ghosert** [comment]
如果你看到有离线保存的提醒，应该都存在你本地的 local storage 了。。。。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2014年12月2日 下午2:23，yougg notifications@github.com写道：
