### ISSUE TITLE
希望能调整编辑器字号

### ISSUE THREAD

**Issue by yiding-he** [ghosert/cmd-editor#323]
希望在编辑器工具栏上放 "A+" 和 "A-" 两个按钮，当用户屏幕比较小的时候，可以通过减小字体来在屏幕上看到更多内容。当然你会说直接用浏览器的缩放不就可以了么。但 100% 缩放强迫症患者可能不喜欢。。。

**Comment by laizony** [comment]
对啊，字体大小不能调整

**Comment by shuhaoc** [comment]
附议！

**Comment by ghosert** [comment]
字体、字号还有 CSS 都可以自定义了：https://www.zybuluo.com/ghosert/note/378553
