### ISSUE TITLE
Bug现身：脚注失效、斜体失效、插入图片失效！

### ISSUE THREAD

**Issue by xzyyjy** [ghosert/cmd-editor#324]
我编辑了一些内容在这个地方：[https://www.zybuluo.com/xzyyjy/note/51144](https://www.zybuluo.com/xzyyjy/note/51144)
- 第一个脚注可以正常显示，第二个脚注就不行了；
- 斜体：*XXX*   依然显示为 *XXX*；
- 插入了两幅图，后面四幅图全插不进去了。

我觉得我的语法没有用错，不知道是不是哪里设置有问题？

**Comment by xzyyjy** [comment]
再补充几个小问题：
- 希望批注也能支持latex
- html标签好像有的不行，比如我想让文字居中，这样写却没用：<center>xxxxx</center>，不知道是不是我html学的不精

**Comment by ghosert** [comment]
第一个注脚和第二个注脚之间空一行：

```
[^footnote]: 只需要任意两点；

[^footnote2]: 只需要任意一点；
```

斜体和插图的问题是这里：

```
#### 1.2.2.5 半正定锥
* 
```

把这里的 \* 号去掉就可以了。插图也正常了。

center 这个标签在新的 html5 里已经不支持了，应该使用 css 代替，你可以写 css

譬如：

```
<p style="text-align:center;">abcdefg</p>
```

批注暂时不支持了 latex 渲染了，直接写 latex 的文本公式吧。

**Comment by xzyyjy** [comment]
好的！
