### ISSUE TITLE
流程图稍稍复杂一点的话表现有点怪

### ISSUE THREAD

**Issue by hexawing** [ghosert/cmd-editor#326]
怪一点是可以接受，毕竟是程序生成出来的嘛，但还会显示不全，这个就麻烦了……
见：https://www.zybuluo.com/hexawing/note/52435

**Comment by ghosert** [comment]
可参考一下详细的语法 http://adrai.github.io/flowchart.js/  有些地方可以按它的语法做调整，譬如箭头的走向等等，另外设计图的时候尽量简单一些。太复杂的时候的确力不从心，不如在外部用工具做好再链接图片过来。

**Comment by hexawing** [comment]
好的，谢谢回复！我研究一下先
