### ISSUE TITLE
能否创建文档内部链接

### ISSUE THREAD

**Issue by wz520** [ghosert/cmd-editor#33]
就是创建一个跳转到文档内某标题的链接。
比如文档内有个标题 `#Header1` ，可以在其他地方写 `[Header1](#Header1)` 创建一个链接到 `Header1` 的链接。（pandoc 更可以简单地写 `[Header1]` ）

好像目前没有这个功能，如果有的话该怎么写？

**Comment by comzyh** [comment]
html 里有个“锚”的概念，你可以参考下。
另外，markdown 的目录插件(TOC那个)已经实现了这个功能。

**Comment by wz520** [comment]
html 我会写，比如

```
<a name="hdr1">Header1</a>

some text...
more text...

<a href="#hdr1">Go To Header1</a>
```

但是第一比较麻烦，第二在 cmd-editor 里写 `<a>` 标签好像根本没用，即使导出成HTML，也看不到我写的 `<a>` 标签。

TOC 要怎么写？

**Comment by comzyh** [comment]
作业部落这个不支持TOC，如果是stackedit的话，在开头写个[TOC]就能生成目录。

**Comment by ghosert** [comment]
大家稍安勿躁，很快支持，标记为 enhancement

**Comment by ghosert** [comment]
已经支持了，可以去站上看看。

**Comment by wz520** [comment]
请问怎么写？  `[Header1](#Header1)` 无效果。
另外发现支持 `[TOC]` 了，nice~ :+1:

**Comment by ghosert** [comment]
暂时只支持到 TOC， 其它特性先不支持了。

**Comment by comzyh** [comment]
TOC! Nice.

**Comment by ghosert** [comment]
我重开一下， [Header1](#Header1) 这个效果应该可以支持。

**Comment by ghosert** [comment]
@wz520  已经修复了，请去网站上体验。
