### ISSUE TITLE
长期使用内存占用巨大

### ISSUE THREAD

**Issue by Goshin** [ghosert/cmd-editor#332]
chrome 39.0.2171.71 m，没截图，用了两个小时左右，内存占用接近1G了。

注：markdown 里有很多死链图片（图片在本地）。

**Comment by ghosert** [comment]
可否把文稿内容让我看下。另外看下刷新页面是否使得内存得到释放。最好截个图把统计内存的方法告诉我。操作系统是哪个？是否还有其它页面打开。系统总内存多少？

**Comment by Goshin** [comment]
文稿怎么给你。关掉标签页再开可以解决，过不久又上来了。统计内存方法就是Chrome 自带的任务管理器。Win7 x86，有其他页面打开。总内存4G.

**Comment by Goshin** [comment]
另外说的是CMD 的标签页内存占了1G，不是Chrome。

**Comment by Goshin** [comment]
文档是这个
https://github.com/1sters/material_design_zh/blob/master/SOURCE/style/icons.md

**Comment by ghosert** [comment]
好像即使不刷新页面，也不关闭 tab，只是切换到其它 tab 一段时间，再切回来， 内存使用就会降下来。不知道 chrome 做内存垃圾回收的原则是什么，但是目测看下来是尽可能占用多的内存，在 inactive 的状态下再释放。后面会使用一些部分渲染的技术，看看能不能让内存降下来，目测短期内，可以通过刷新页面的方式释放内存。看了一下其他的在线编辑器和印象笔记等等，基本都是这个状况。
