### ISSUE TITLE
优化打印效果的 CSS 提议，以及关于 PDF

### ISSUE THREAD

**Issue by xingrz** [ghosert/cmd-editor#335]
目前直接将编辑页面或者永久链接页面用浏览器的打印功能看到的版面是混乱的，如下图。

实际上可以通过 CSS3 的 `@media print { ... }` 选择器做响应式，将不需要打印的元素全部隐藏掉。

同理，如果这个优化做好了，也不需要做单独的 PDF 导出了，Safari 和 Chrome 的打印功能本身自带PDF导出功能。

![2014-12-11 2 13 37](https://cloud.githubusercontent.com/assets/288288/5390058/2b8b9778-8140-11e4-9434-643f960173f1.png)

**Comment by yuchuanxi** [comment]
顶上!

我也很希望作者大大能优化打印样式. 文档在线看的效果还是很赞的, 但是当要打印,或者通过chrome转化成pdf时, 效果却,,,

**Comment by kingice** [comment]
表格一旦导出pdf边框就消失了。

**Comment by Jack2code** [comment]
文档导出是一个大问题！
每次文档导出都需要用PDF编辑器来编辑一下，要不然，很多隐藏的信息都打印出来了。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
