### ISSUE TITLE
从未登录状态到登录状态的内容丢失

### ISSUE THREAD

**Issue by overtrue** [ghosert/cmd-editor#338]
1. 在未登录状态写的东西
2. 点击导出markdown
3. 提示需要登录
4. 登录后发现内容丢失

写了那么多，就不能缓存到本地吗？？？ 又得花那么久重写。。。

**Comment by ghosert** [comment]
工具栏上一直在提示登录后保存呀。
2014-12-17 上午10:12于 "安正超(Carlos)" notifications@github.com写道：

**Comment by overtrue** [comment]
@ghosert 那个我有看见，我理解的是：登录后可以保存到云端，本地缓存应该是编辑器默认的（基于其它编辑器的行为理解），所以， 我登录后我发现没了，然后我使用浏览器的返回功能发现还是无法恢复了。。。 :sob:

**Comment by ghosert** [comment]
未登录不做本地保存的原意是想让大家登录后使用。。。。这样保存最保险，否则本地浏览器被清理，或者换个机器，还是没数据。安全的做法是不登录的时候先试着写几个字，刷一刷页面确定会不会保存。。。

**Comment by overtrue** [comment]
好吧。
