### ISSUE TITLE
有序列表在插入代码后编号会重新开始

### ISSUE THREAD

**Issue by jiminHuang** [ghosert/cmd-editor#340]
有序列表在插入代码后编号会重新开始，如下面这段
1. 这是1

``` python
```
1. 这应该是2，但是还是1

**Comment by ghosert** [comment]
按照markdown标准语法列表之间不应该插入代码段。如果一定需要可以这样：
### 1. 这是1
    code
### 2. 这是2

**Comment by vulgur** [comment]
代码段缩进就好了，和编号内容对齐
