### ISSUE TITLE
能否实现PDF的转换？

### ISSUE THREAD

**Issue by yapian** [ghosert/cmd-editor#341]
`CMDMarkdown`上的预览模式很好看，通过`markdownpad`和`Mdcharm`等类似的工具转换的格式很不标准，很丑。在线转换如`markdowntopdf`，不支持中文。
只要能实现**_PDF转换**_，要我们干什么，你说？

**Comment by Wizmann** [comment]
+1

现在生成PDF基本就是^CV到Word里。。。（好Low。。。

或者可以生成一个干净的可打印页，现在的浏览页里面有好多零碎按钮。打印成PDF时会造成很大的干扰。

谢谢啦。（伸手党默默Orz一下。。。

**Comment by hxlbuzz** [comment]
PDF 可以导出html文件后通过chrome的打印功能生成，不过效果一般，主要代码块在生成的PDF中没有高亮，也会把行号带进去，流程图也无效，如果是纯文字的话还差强人意

**Comment by kentsx-mac** [comment]
+1.同样希望能够直接导出PDF文件。因为很多格式在CMD中支持，其他很多客户端的markdown软件不支持，就不能很好保证文件的效果

**Comment by elemem** [comment]
+1

**Comment by rmokerone** [comment]
+1
要不然真的没有太大的实用性。

**Comment by robertding** [comment]
只要能实现PDF转换，要我们干什么，你说!!!

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
