### ISSUE TITLE
能否在“关于本站”里把作业部落的markdown语法贴一下？

### ISSUE THREAD

**Issue by Wizmann** [ghosert/cmd-editor#343]
我指的是流程图、目录那些东西 。

怎么找也找不到。Google也搜过了。。。

谢啦。（阅后可关闭

:+1:

**Comment by ghosert** [comment]
编辑区，右上角有一排按钮，其中有一个是使用说明文稿：https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown 参照这个就行了。
