### ISSUE TITLE
使用application cache

### ISSUE THREAD

**Issue by liyuankui** [ghosert/cmd-editor#346]
http://diveintohtml5.info/offline.html
仿 http://devdocs.io 这样离线也能使用

**Comment by ghosert** [comment]
正在使用 application cache 这个离线技术做客户端，这个技术本身不复杂。复杂的是做数据同步，比方你在网站上写了十篇文稿，在客户端里要同步过来，否则一旦离线，你又想看以前的文章就不行，另外在离线状态下新建、删除、修改的文稿，一旦网络恢复，还要可以同步回服务器。这些都需要利用浏览器本身的离线存储技术，application cache 只是缓存静态资源，数据存储是另外的技术。最麻烦的是版本冲突的问题，比方，有一篇文稿的版本是1，你在A机器上修改了文稿同步到服务器，版本升级为2，然后切换到离线状态的B机器，文稿版本仍旧是1，你在离线状态下又修改了这个版本1，当B机器恢复网络，同步数据的时候，需要处理此类冲突。

许多云笔记，包括印象笔记都回避了此类问题。

http://devdocs.io 的问题就是没有做数据同步，只缓存了访问过的页面，所以离线状态下查看不了没有访问过的页面。

这些问题都要给出答案才是比较完备的云客户端，正在实现中。

**Comment by ghosert** [comment]
https://www.zybuluo.com/cmd/ 全平台客户端已出
