### ISSUE TITLE
微软拼音下Backspace失效？

### ISSUE THREAD

**Issue by piratf** [ghosert/cmd-editor#347]
先用英文输入了一段，没问题。切换到微软拼音输入几个中文字符后发现Backspace等全部失效。
切到其他窗口再切回来就好了。或者刷新。

**Comment by ghosert** [comment]
操作系统，浏览器版本说一下？

**Comment by piratf** [comment]
Win8，chrome 版本 39.0.2171.95 m

**Comment by ghosert** [comment]
手头暂时没有 win8 能先换个 输入法试试吗？譬如 搜狗？

**Comment by piratf** [comment]
开源工作者好认真！不爱搜狗，地址已书签。过段时间再回来看看吧:-) 加油

**Comment by ghosert** [comment]
firefox ie 下有这个问题吗？只是想做个测试。看看是浏览器的问题还是输入法的问题。

**Comment by piratf** [comment]
参考结果如下

> - 在chrome中`使用Win+空格`切换输入法后会出现Backspace失效，无论是ENG切换微软拼音还是反过来切都会失效。
> - IE会出同样的问题。
> - 火狐正在下载中。
> - 微软拼音中`使用shift切换中英文输入`都没问题。
> - 切换窗口，或者切一下开始菜单就好了。刷新也能解决。之后再切换输入法又挂了。

**Comment by ghosert** [comment]
谢谢了。。。挺详细。

**Comment by piratf** [comment]
火狐一样的问题，供参考。
祝好，渣渣新手求带飞~~开源项目超级棒的[勾

**Comment by ghosert** [comment]
已修复。请刷新页面或重启客户端。先关了，还有问题请重开。
