### ISSUE TITLE
一键导出所有文章markdown

### ISSUE THREAD

**Issue by bowenli86** [ghosert/cmd-editor#349]
Dear ghosert, 能否设置一个一键导出所有文章的markdown的功能，这样就不用一个个的导出了

**Comment by linxd5** [comment]
Dear ghosert , I want this feature too, thank you~

**Comment by xli1224** [comment]
同想要！主要是习惯了本地备份，而且系统搜索时可以搜索到文档内容

**Comment by mintisan** [comment]
是的，本地备个份，有安全感

**Comment by district10** [comment]
这个好，这个可以有，这个应该有。:smile:

**Comment by JoshWu** [comment]
非常需要.

**Comment by 18-1** [comment]
+1

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
