### ISSUE TITLE
真坑

### ISSUE THREAD

**Issue by pixelvm** [ghosert/cmd-editor#350]
编辑了半天的内容 导出时要登录  点击了之后就什么也没有了  尼玛坑挖的好深

**Comment by ghosert** [comment]
左上角一直在显示登录后保存，登录后保存，登录后保存，为啥不看提示呢。。。

**Comment by pixelvm** [comment]
没登录前保存到localstorage也行啊，登录时编辑的内容都没了！！！  这才是坑点。 登录时也不用刷新页面啊。 ajax也OK，这方面体验还是好好优化一下吧。

**Comment by ghosert** [comment]
不能想当然啊，还是按照提示做吧。自己复制粘贴一下也好啊。很多人不愿意注册，可以 localstorage 就不注册了，怎么能形成完整的体验呢。所以一开始就避免 localstorage。坚持一定要注册才有完整保存的功能。
