### ISSUE TITLE
tag有时候显示的不正确

### ISSUE THREAD

**Issue by pingf** [ghosert/cmd-editor#351]
我建立了两篇文稿a1，a2
a1的tag是 “未分类 2”，用空格分隔，所以就有两个tag了
a2的tag是 “未分类” 
其中a1已经发布，a2没有发布
问题是，
当切换至a1文稿时，通过标签查阅，a1在“未分类”和“2”两个标签下
当切换至a2文稿时，通过标签查阅，a1仅在“2”这个标签下，“未分类”标签下只有a2了

**Comment by ghosert** [comment]
:-)，感谢找到这个细小的问题。

当时的考虑就是这样的，理论上已经 a1 已经有一个分类 2 了，所以其实它不属于任何未分类。所以在访问非 a1 的文稿时，不再把 a1 归类到 未分类 下。但是访问 a1 本身的时候，因为 a1 里的标签栏里还存有 未分类的 字样，所以仍旧在 未分类里列出了。

可以把 a1 上的未分类去掉，这样就统一了。毕竟已经分类到 2 了。
