### ISSUE TITLE
能不能把内容设置分段多次上传

### ISSUE THREAD

**Issue by yougg** [ghosert/cmd-editor#352]
内网代理限制请求内容大小,  超过100行必定失败.
然后提示`离线模式`一点都不醒目, 一刷新全没了.

> Request URL:https://www.zybuluo.com/mdeditor/note/update
> Request Method:POST
> Status Code:403 Proxy_UploadNotAllowed
> 
> Content-Length:33149

**Comment by ghosert** [comment]
能和你家网管商量下不？我这边改动挺大的，一时来不及这样改。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

2015-01-04 17:42 GMT+08:00 yougg notifications@github.com:

**Comment by ghosert** [comment]
这个已经改正了，每次只上传差异部分。
