### ISSUE TITLE
公式输入编号问题

### ISSUE THREAD

**Issue by ahuman** [ghosert/cmd-editor#353]
非常感谢你们的工作，我一直在用，感觉非常好。

在这里给你们提一个小小的建议，目前已经能够支持LATEX公式输入了，但不能编号和引用，如果能支持\label和\ref的话，就更好了！

非常感谢！

**Comment by nejyeah** [comment]
支持下，希望引关注，我觉得这个问题很重要，我写的blog基本上都是一堆公式，内有编号简直蛋疼，在编辑时： 
$公式$         （1）  （会自动将空格省略掉，显示成右边）  $公式$（1）
总之蛋疼

**Comment by ghosert** [comment]
已解决。
