### ISSUE TITLE
Mathjax公式颜色问题

### ISSUE THREAD

**Issue by zuyan9** [ghosert/cmd-editor#358]
有些公式的颜色是灰色的，有些是黑色

预览的时候没有问题，分享出去的时候就有问题了

**Comment by ghosert** [comment]
有具体的例子吗？分享一个文稿我看看。

**Comment by zuyan9** [comment]
比方说这个

https://www.zybuluo.com/zuyang/note/62166

有的公式是灰色的……

**Comment by ghosert** [comment]
好的，我记下了，帖子你留着别删，我修的时候会再过去分析一下你的情况。

**Comment by ghosert** [comment]
你这个问题的 markdown 原文有吗？发一份给我 support@zybuluo.com

**Comment by ghosert** [comment]
应该解决了。

**Comment by ghosert** [comment]
重开一下，下次发布的时候再解决下。发布文稿以后有问题。

**Comment by ghosert** [comment]
已修复。
