### ISSUE TITLE
能不能改成左右屏实时绑定？等一下的体验非常不好。

### ISSUE THREAD

**Issue by qiansen1386** [ghosert/cmd-editor#36]
如题。能否告知是如何实现绑定的。我想我可能能帮您做一个PullRequest

**Comment by ghosert** [comment]
这是仁者见仁，智者见智的问题。暂时故意为之。实时绑定未必就会感觉好，而且还占 CPU.

**Comment by qiansen1386** [comment]
这么严重么？您是打算发布为产品，还是发布为服务呢？若发布为产品的话，我们可以自己修改源代码么？若发布为服务的话，能否提供相关配置的选项呢？

**Comment by ghosert** [comment]
暂时还算闭源产品，选项可以考虑提供。^_^。
