### ISSUE TITLE
中文输入法下Vim模式进入编辑模式会全选（容易误删）

### ISSUE THREAD

**Issue by snowsolf** [ghosert/cmd-editor#360]
中文输入法（搜狗输入法7.2.0.2559）下Vim模式进入编辑模式会全选，这样会误删全文，虽然可以回退，但在不知道什么原因的情况下，再在文本列表中选了其它文件或其它退出正在编辑的文档，就再也找不回来所编辑的文档了，望解决！！！

**Comment by ghosert** [comment]
操作系统浏览器版本说下
2015-1-16 上午10:06于 "snowsolf" notifications@github.com写道：

**Comment by snowsolf** [comment]
操作系统：win7 64bit
浏览器：Firefox 35.0
在Chrome下没有这个问题。
- Smartisan T1 -

2015年1月16日，11:56于 Jay Zhang notifications@github.com 写道：

操作系统浏览器版本说下
2015-1-16 上午10:06于 "snowsolf" notifications@github.com写道：

> 中文输入法（搜狗输入法7.2.0.2559）下Vim模式进入编辑模式会全选，这样会误删全文，虽然可以回退，但在不知道什么原因的情况下，再在文本列表中选了其它文件或其它退出正在编辑的文档，就再也找不回来所编辑的文档了，望解决！！！
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ghosert/cmd-editor/issues/360.

---

**Comment by ghosert** [comment]
vim 已升级，可以再去试试。
