### ISSUE TITLE
希望增加本地图片的引用

### ISSUE THREAD

**Issue by mythyygg** [ghosert/cmd-editor#361]
是考虑到技术难度 ,服务器成本没有做吗

**Comment by ghosert** [comment]
确实有成本考虑，但是会尽量克服，第三方的存储服务收费还是挺贵的。

**Comment by Ir1d** [comment]
可以使用网盘外链之类的东西吧……
祝好

**Comment by zbqBaoqing** [comment]
同样的问题！！！无法插入本地图片

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
