### ISSUE TITLE
能不能同步到百度盘或是360盘？

### ISSUE THREAD

**Issue by thelatefuture** [ghosert/cmd-editor#362]
:blush:希望有同步到云盘的功能，国外的Markdown工具好多支持同步到云盘。

**Comment by shesuyo** [comment]
国外的那个是开源的吧？

**Comment by thelatefuture** [comment]
嗯，开源的，http://www.oschina.net/news/50322/markdown-editors-and-tools

**Comment by shesuyo** [comment]
开源的一般开发者就不会提供服务器，所以一般就会接入网盘存储。

**Comment by ghosert** [comment]
这个暂时先不做了，对国内网盘的可靠性存疑。会加强建设自身的文档管理功能。
