### ISSUE TITLE
离线客户端版还没上线吗?

### ISSUE THREAD

**Issue by Andrew-liu** [ghosert/cmd-editor#363]
放鸽子已经快两个月了, 等的快哭了, 在不出客户端就哭晕在厕所里了

其他:

希望增加主题, 现在功能基本完善, 希望在美观性上增加一些选择, 比如增加几个前段模板, 或者增加几个CSS代码高亮文件, 能有多种显示选择, 类似美观性可以参照马克飞象中做的, 感谢

**Comment by ghosert** [comment]
呃。。。这个，的确最近公司事情比较多，自己效率也不太高，但是平均每天能写上五十来行，快了，我再加把劲。

主题什么的，等客户端做完吧。或者你单独再开个 issue ，这个 issue 等客户端出来就关了。

**Comment by heibai01** [comment]
哇，作者真的好棒。我打算用这个来写公司的接口文档，所以真的希望出来私密分享或者离线版的。。。

**Comment by qingyuexiao** [comment]
加油，支持！

**Comment by ghosert** [comment]
快了，快了。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

2015-03-09 21:10 GMT+08:00 qingyuexiao notifications@github.com:

**Comment by ghosert** [comment]
https://www.zybuluo.com/cmd/ 全平台客户端已出

**Comment by heibai01** [comment]
一直在关注作者，微博、v2ex、github.知道作者一路上经历过被人质疑和不理解。但是，cmd离线客户端还是不负众望面世了。加油，我会一直支持您的。

**Comment by ghosert** [comment]
谢谢，还是好人多啊！

**Comment by dissipator** [comment]
权利，支持哦，不过，流程图视乎不能支持中文哦！
还有，你们可能会开放源码吗？
