### ISSUE TITLE
文档持久化，是否支持保存到Evernote、Wiz笔记等？

### ISSUE THREAD

**Issue by heziqiang** [ghosert/cmd-editor#366]
文档持久化，是否支持保存到Evernote、Wiz笔记等？类似马克飞象

**Comment by ghosert** [comment]
其实目前都保存在自己的服务器上，有什么不方便吗？如果觉得文档组织的不好，可以提一下修改意见，我重新组织一下。保存到第三方也会做，可能会是 premium 的形式，暂时还没考虑好。

**Comment by ghosert** [comment]
已支持导出到印象笔记 Evernote：https://www.zybuluo.com/ghosert/note/102771

**Comment by heziqiang** [comment]
well done！
