### ISSUE TITLE
mathjax问题 $\{ x \}$ 显示成x.

### ISSUE THREAD

**Issue by chaoxu** [ghosert/cmd-editor#375]
这里可以看到问题:

https://zybuluo.com/mgccl/note/67072

但是在$$ $$中就不会有这个问题.

**Comment by hexiaoou** [comment]
同意。顶上去。

**Comment by ghosert** [comment]
暂时好像要加两个 \ 解决这个问题，比如：

$\{x\}$

我找时间解决下。

**Comment by hexiaoou** [comment]
哦，谢谢，两个\这个好。
不止花括弧{}，还有井号#，本来也是$#$, $#$都无法正常显示，但是\就可以了：$\#$

**Comment by ghosert** [comment]
加一个 \ 就好了，不需要两个了，其它应该也好了。
