### ISSUE TITLE
我编辑了一个文档，然后我登陆之后好像都没了？还可以找回吗?

### ISSUE THREAD

**Issue by sfshine** [ghosert/cmd-editor#378]
我编辑了一个文档，然后我登陆之后好像都没了？还可以找回吗?哭了！

**Comment by Matrix0xCC** [comment]
我也是这样，一天的心血都没了。。。我日啊。。泪奔了。。~~o(>_<)o ~~

**Comment by ghosert** [comment]
每次击键都在提示：登录后保存。不登录的话，存哪里呢？
