### ISSUE TITLE
导出的html许多样式丢失

### ISSUE THREAD

**Issue by hughfenghen** [ghosert/cmd-editor#379]
源码没高亮  没有背景色  
阅读模式惊艳，导出后感觉好丑啊

**Comment by Tek-Eternal** [comment]
嗯，有同感，怎么能导出跟阅读模式一样样式的html呢？

**Comment by hughfenghen** [comment]
http://write.blog.csdn.net/mdeditor
试试这个，chrome支持离线访问。挺好用的

**Comment by expLin** [comment]
同感，如果导出之后的和预览的一样好看就好了。

**Comment by expLin** [comment]
把后面的css文件下载下来，然后添加到html文件里面，就可以了。

**Comment by Banio** [comment]
同感 希望导出跟阅读模式一样  最好能支持转换PDF

**Comment by qingyuexiao** [comment]
同上，希望导出时能直接把样式加上，目前只能手动添加。。

**Comment by xiaoyuan0821** [comment]
好多人提这个问题。。我也觉得导出没有样式基本等于没用。。不知道作者是否在改进？  多谢！

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
