### ISSUE TITLE
验证码一直报错  然后登不上去

### ISSUE THREAD

**Issue by bnnd** [ghosert/cmd-editor#380]
何解？  你验证码功能太那个了

**Comment by ghosert** [comment]
现在好了吗？

**Comment by ghosert** [comment]
多试几次即可。注意大小写。

**Comment by ghosert** [comment]
安全考虑，所以难度略大

**Comment by bnnd** [comment]
你的验证码还包括大小写的吗？
这也太不走寻常路  简直反人类  :-) 我是直了点  不懂怎么弯
一般验证码是不需分大小写的，为了避免最好在验证码那边给大家提个醒。

**Comment by bnnd** [comment]
熊猫翻滚那篇是我写的（已取消分享）   他们是怎么看到的  虽然我是公开的  但是 哪里能看到公开的文章

**Comment by ghosert** [comment]
理论上看不到，有没有其他人看到了告诉他们了？
