### ISSUE TITLE
建议 “阅读模式”  加入 @media print 样式控制

### ISSUE THREAD

**Issue by vfasky** [ghosert/cmd-editor#382]
生成的文档，好多时候要打印，但

![image](https://cloud.githubusercontent.com/assets/215752/6125377/6464144a-b150-11e4-8a25-52f3fb1a9b67.png)

![image](https://cloud.githubusercontent.com/assets/215752/6125392/82ecc678-b150-11e4-943c-4475c81693ad.png)

这样的预览效果。。。

而且，打印预览处理好后， 在 chrome 可以很轻松的导出pdf ^_^

**Comment by qinbx** [comment]
+1

**Comment by ghosert** [comment]
PDF 已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938 导出 PDF 以后就可以完美打印了！
