### ISSUE TITLE
切换输入法以后退格和删除键无效

### ISSUE THREAD

**Issue by hxshandle** [ghosert/cmd-editor#383]
环境:  window 8.1
浏览器：IE11/Chrome 40

**Comment by zbjxb** [comment]
我也遇到这个问题了。Firefox 35 + Win8.

**Comment by Martianface** [comment]
同样遇到这个问题
OS: Win8.1
浏览器:Chrome 41.0.2272.118 m

切换输入法后还会导致方向键无法使用, 需要切换至另外的标签后再切回当前标签页面才能够恢复.

**Comment by ghosert** [comment]
都是哪些输入法，你们。

**Comment by Martianface** [comment]
谷歌输入法， 版本2.7

2015-05-15 10:13 GMT+08:00 Jay Zhang notifications@github.com:

> 都是哪些输入法，你们。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ghosert/cmd-editor/issues/383#issuecomment-102223907.

## 

Martianface
^_^

**Comment by ghosert** [comment]
已修复。请刷新页面或重启客户端。先关了，还有问题请重开。
