### ISSUE TITLE
编辑栏和阅读烂不同步

### ISSUE THREAD

**Issue by mr7bu9ou** [ghosert/cmd-editor#39]
今天晚上使用时，发现编辑栏上下滚动内容时，右边的阅读栏不同步滚动，以前是好的，FF和Chrome都有问题

**Comment by ghosert** [comment]
## 章节标题

在##章节标题的前后留出空行以表示段落，就可以解决你的问题了。

**Comment by ghosert** [comment]
也算一个 bug， 稍后修复。

**Comment by ghosert** [comment]
问题会出现在类似这样的文稿里，header 上面没有多空一行，已经修复，即使没有多空一行，也可以正常分段，左右栏会也同步滚动。
1. test
2. test
3. test
4. test
5. test
6. test
7. test
8. test
9. test
10. test
11. test
12. test
13. test
14. test
15. test
16. test
17. test
18. test
19. test
20. test

# headerd
1. test
2. test
3. test
4. test
5. test
6. test
7. test
8. test
9. test
10. test
11. test
12. test
13. test
14. test
15. test
16. test
17. test
18. test
19. test
20. test
