### ISSUE TITLE
Ubuntu+Chrome+Emacs模式下，Ctrl+N无法下移光标

### ISSUE THREAD

**Issue by windpls** [ghosert/cmd-editor#393]
OS：Ubuntu GNOME 14.04.2 
浏览器：Google Chrome 38.0.2125.111 (64-bit)
在Emacs模式下编辑时，Ctrl + P, Ctrl + F, Ctrl + B是正常的，可以向上、向右或者向左移动光标，但是Ctrl + N会创建一个新的Chrome窗口，无法向下移动光标，也即, Ctrl + N未能覆盖Chrome的快捷键。

望改进。

**Comment by ghosert** [comment]
这个快捷键 chrome 不让改。。。能换 firefox 吗？

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2015年3月8日 上午11:58，Feng Wang notifications@github.com写道：

**Comment by ghosert** [comment]
可以使用客户端解决这个问题了。
