### ISSUE TITLE
可否增加阅读的荧光笔功能？

### ISSUE THREAD

**Issue by mavericklx** [ghosert/cmd-editor#395]
在阅读的过程中有的地方想着重标记一下。目前有批注和高亮批注功能，可否添加荧光笔功能方便文档阅读，提高cmd的文档编写和阅读体验。

**Comment by ghosert** [comment]
这个功能有啊

https://www.zybuluo.com/ghosert/note/41556

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2015年3月10日 上午11:48，mavericklx notifications@github.com写道：

**Comment by mavericklx** [comment]
但是“高亮批注”后为何没有【Adobe Acrobat 内建的荧光笔】 的那种效果？
个人对背景着色的高亮效果比较注重。

**Comment by ghosert** [comment]
你说的高亮效果是指颜色吗？可否给个截图，光说我无法想象。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2015年3月11日 下午2:11，mavericklx notifications@github.com写道：
