### ISSUE TITLE
水平线 预览的时候 没有显示 （仅预览，发布后的情况未试）

### ISSUE THREAD

**Issue by sharego** [ghosert/cmd-editor#4]
## 水平线预览问题

输入 *****\* 或  ------------- 都没有反应
点击工具栏的 水平线按钮 也如此

---

**Comment by ghosert** [comment]
了解了，当时没有显示是因为在黑色模式下这条线比较刺眼，暂时没有调出比较好的颜色，只做了空行处理，我再尝试改一下。

**Comment by ghosert** [comment]
已修复，我先关了，如果觉得有问题再重开这个问题
