### ISSUE TITLE
LaTex公式是否可以加上编号

### ISSUE THREAD

**Issue by QIanGua** [ghosert/cmd-editor#401]

**Comment by ghosert** [comment]
已解决。

**Comment by QIanGua** [comment]
灰常感谢

**Comment by QIanGua** [comment]
不过貌似有时会有点小问题。
1.比如刚开始输入“\begin{equation}
  \int_0^\infty \frac{x^3}{e^x-1}\,dx = \frac{\pi^4}{15}
  \label{eq:sample}
\end{equation}”的话可以正常显示，可是过一会就只能显示代码了。
2.公式编号貌似只能递增。同一个公式原地修改时编号也会增加。
！！我真的不是挑刺的55

**Comment by QIanGua** [comment]
刷新一下就好了！囧~

**Comment by ghosert** [comment]
暂时先刷一下，我现在在做局部刷新功能，以后不要每次刷应该就木油这个问题了。

**Comment by QIanGua** [comment]
OK  辛苦了
