### ISSUE TITLE
为什么不做可以下载的版本

### ISSUE THREAD

**Issue by hucaser** [ghosert/cmd-editor#405]
在线的markdown编辑器只有有网的时候才能用，要是能弄成离线的就好了。

**Comment by fluviusmagnus** [comment]
根据作者在新浪微博上的公告可以看出他确实在做，只是可能还要再等一段时间。

**Comment by mintisan** [comment]
作者已经拖到[百度网盘](http://yun.baidu.com/s/1qWyWMtA#path=%252FCmd%2520Markdown)了

**Comment by ghosert** [comment]
https://www.zybuluo.com/cmd 可以去这里下载，目前用百度网盘，之后可能会更换。
