### ISSUE TITLE
增加网站的favicon

### ISSUE THREAD

**Issue by intijk** [ghosert/cmd-editor#41]
希望有个logo, 加好favicon, 在 bookmarks bar里就能分辨出来了.

**Comment by ghosert** [comment]
这里谁是美工，帮忙设计一个吧？

**Comment by intijk** [comment]
![zybuluo 48x48](https://f.cloud.github.com/assets/740501/2242781/0f56e7d4-9d10-11e3-891a-e9911b9f9179.png)
![zybuluo 240x240](https://f.cloud.github.com/assets/740501/2242782/19b73cf6-9d10-11e3-9fb6-a6d0cbbdcb84.png)

我设计了一个,你看看

**Comment by intijk** [comment]
我可以传你邮箱个矢量的, github不能传 svg

**Comment by ghosert** [comment]
你用你的邮箱发给我吧，我们讨论一下。

**Comment by ghosert** [comment]
或者往我邮箱发个你的 IM 信箱的联系方式？

**Comment by ghosert** [comment]
谢谢，这位兄弟，已经按这位兄弟的设计增加了。
