### ISSUE TITLE
希望可以加入ctrl+v自动上传图片的功能

### ISSUE THREAD

**Issue by lesonky** [ghosert/cmd-editor#411]
有时候做笔记需要截图,可是找不到好的图床,而且用起来也很麻烦,前些天逛简书的时候发现他们已经实现了这个功能,写起文章来顺溜多了,不过他们那个md比较文艺,不如这里来的专业,所以还是希望这里也可以实现一个这样的功能,让笔记更畅快~

**Comment by ghosert** [comment]
已支持。
