### ISSUE TITLE
vim 模式两个问题

### ISSUE THREAD

**Issue by lluo2010** [ghosert/cmd-editor#415]
vim模式下我发现两个问题：
1. 无法使用 '/' 进行查找。
2. 选择要拷贝的字符串，使用 "_y进行复制， 然后定位到其他行出，准备进行粘贴，使用"_p, 发现鼠标位置又跑到原来选择复制的字符串处了。

希望能fix下，感谢！

**Comment by ghosert** [comment]
已修复。
