### ISSUE TITLE
个人博客 & Markdown

### ISSUE THREAD

**Issue by Lelandycrain** [ghosert/cmd-editor#417]
- 你的Markdown编辑器**很好看**啊，可以**支持的功能也很多**。
- 我用[jekyllnow](https://github.com/barryclark/jekyll-now)模板搭建了自己的个人博客，但默认的Markdown **解释器效果**不好，换了其它几个效果也不理想。
- 那么有没有某种途径可以**直接引用**你的Markdown解释器呢？就像[_config.yml](https://github.com/barryclark/jekyll-now/blob/master/_config.yml)关于Markdown的那行一样。

**Comment by ghosert** [comment]
暂时没有，我做一站式的。
