### ISSUE TITLE
增加批量导出功能

### ISSUE THREAD

**Issue by marklma** [ghosert/cmd-editor#418]
如果不做同步云盘、wiz等，建议可以增加批量导出功能，将所有写的文章一次性压缩导出，方面作者进行批量转换pdf之类的操作

**Comment by YiuTerran** [comment]
赞同，同希望加入批量导出功能。我自己写了个脚本做这个，但是感觉还是官方支持比较好了。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
