### ISSUE TITLE
引用部分不够明显

### ISSUE THREAD

**Issue by jamesfancy** [ghosert/cmd-editor#42]
引用部分左测的粗竖线和背景颜色都太浅了，不够明显，看起来很费劲。

> `Cmd Markdown`的线条色是`#eeeeee`；背景色是`#f9f9f5`，跟页面背景一个颜色
> 相比之下，我觉得`StackEidt`的颜色就好得多，分别是`#e4e9ec`和`#eff1f4`
> `Github`虽然没得背景色，但是竖线也要明显得多，更容易看，`#dddddd`

**Comment by ghosert** [comment]
最新版本已经修复了，请去网站上验收。

**Comment by jamesfancy** [comment]
Got it。代码背景也改成浅色好，安逸。
