### ISSUE TITLE
backspace经常性无法删除，f5刷新后正常，然后一段时间又无效，chrome v41

### ISSUE THREAD

**Issue by goghcrow** [ghosert/cmd-editor#423]
如题

**Comment by ghosert** [comment]
操作系统是啥？

**Comment by ghosert** [comment]
输入法是啥？

**Comment by ghosert** [comment]
是中文的时候发生还是英文的时候，还有都有？

**Comment by ghosert** [comment]
操作系统多少？ 发自网易邮箱大师 在2015年04月11日 10:29 ，goghcrow写道： 如题 — Reply to this email directly or view it on GitHub.

**Comment by ghosert** [comment]
最近更新了下，看看好了吗？

**Comment by igotti** [comment]
chrome和客户端都有这个问题，每次都要刷新，还过来不多久又出现，让人奔溃。

**Comment by ghosert** [comment]
操作系统说下，输入法说下。

**Comment by ghosert** [comment]
已修复。请刷新页面或重启客户端。先关了，还有问题请重开。
