### ISSUE TITLE
编辑Latex公式导致卡顿

### ISSUE THREAD

**Issue by nejyeah** [ghosert/cmd-editor#425]
在一篇博客里面写Latex公式，写个7到8个以上的话，特别卡，而且对于那种比较长的公式貌似是写一个字母Latex公式就会刷新一次，导致公式写多了后面再写公式就特别特别特别卡顿

**Comment by zpike** [comment]
应该是引用了外部工具，工作量大。

**Comment by ghosert** [comment]
噢，忘记关了，应该是六月底修了。
