### ISSUE TITLE
增加本地导入功能

### ISSUE THREAD

**Issue by ghost** [ghosert/cmd-editor#427]
发现只有导出功能，没有本地导入功能

**Comment by zpike** [comment]
只能复制粘贴了

**Comment by bin-dogami** [comment]
复制粘贴太麻烦了，建议加上此功能，这样可以导入编辑器里写的markdown文件，或者从别人那复制过来的文件，

**Comment by ghosert** [comment]
已支持打开本地文件。https://www.zybuluo.com/ghosert/note/102771
