### ISSUE TITLE
在窄屏上工具栏不显示出来

### ISSUE THREAD

**Issue by jamesfancy** [ghosert/cmd-editor#43]
要说窄也不是很窄，是1280x1024的屏。

**Comment by ghosert** [comment]
能截个图过来吗？

**Comment by jamesfancy** [comment]
行，晚上回去截，现在办公室没得条件。

**Comment by jamesfancy** [comment]
今天没有重现，不过布局还是稍稍有点问题。

![image](https://f.cloud.github.com/assets/3953094/2282667/cafc4f26-9fb1-11e3-8c83-e3b7503f0b16.png)

**Comment by ghosert** [comment]
兄弟，这是改版后的效果， 如果不能重现， bug 我关了。
