### ISSUE TITLE
Mac 版本快捷键的问题

### ISSUE THREAD

**Issue by kchen0x** [ghosert/cmd-editor#433]
# Mac 版本下的问题
1. 快捷键提示还是 Ctrl，并不是⌘。
2. 复制、粘贴两大常用快捷键不能使用。
3. 不能右键。

**Comment by ghosert** [comment]
我试了下， Ctrl Command 对快捷键都有效果。
复制粘贴已解决，重新下载即可，新地址在微信群问。
暂时没有需要右键的功能。
