### ISSUE TITLE
账号不能激活也不能登录

### ISSUE THREAD

**Issue by neo-hu** [ghosert/cmd-editor#435]
我登录一直提示
您填写的邮箱帐号尚未验证，请换用【用户名】登录。
我们在 2015-04-25 03:39:23 曾向此邮箱发送过验证邮件，请前往邮箱（包括垃圾箱）查收验证。

但是我已经点了邮箱的激活链接
还是不能登陆 麻烦处理一下 
账号 9656951@qq.com

**Comment by ghosert** [comment]
可以前往 用户设置 页面，重新发送一份验证邮件试试。有问题再找我。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2015年4月25日 下午11:47，neo-hu notifications@github.com写道：
