### ISSUE TITLE
客户端发布地址请放在github

### ISSUE THREAD

**Issue by ivysrono** [ghosert/cmd-editor#437]
github release 标签下可以发布二进制客户端。
从来从来没见过靠谱的程序在百度网盘发布的。
百度动不动就乱杀外链，扛不住的。

**Comment by ghosert** [comment]
github 貌似也会封杀，网速也慢，我再找找可靠的下载站。

**Comment by zhiyue** [comment]
https://bintray.com/ 可以考虑一些这个

**Comment by QunGuan** [comment]
看到下载地址是百度盘，一度以为不是官方的，都没敢下。
