### ISSUE TITLE
Maybe this is a bug.

### ISSUE THREAD

**Issue by intijk** [ghosert/cmd-editor#44]
![snapshot5](https://f.cloud.github.com/assets/740501/2288519/c875ddfa-9ffa-11e3-95e6-4e746392f740.png)
这个呈现对吗， 我也不太清楚，即使在第一行末尾加了多个空格还是一样结果，必须在两行之间加回车才能出公式效果。

**Comment by ghosert** [comment]
确实，不过老版本里也有这个问题，应该不是最近引入的，我看最近修复一下。

**Comment by ghosert** [comment]
已解决。
