### ISSUE TITLE
老弹出”合并“确认对话框，烦人的很啊

### ISSUE THREAD

**Issue by mSoloYu** [ghosert/cmd-editor#440]
2015-04-27 今天编辑更新时，时常弹出来让我确认合并，实在是影响操作和效率，还有，导出pdf功能什么时候排上日程，图片居中显示等常用功能也请考虑加上吧

**Comment by ghosert** [comment]
是因为同时开了几个编辑器在互相改吗？只开一个应该不会这样。再和我确认下。

**Comment by mSoloYu** [comment]
嗯，少则一个，多则三个，昨天开了两个，但以前不会出现这种情况。到晚些时候就不会弹出了。目前不会。

谢谢！

**Comment by ghosert** [comment]
尽量同时只用一个客户端或者浏览器，以前不会其实是在互相覆盖内容，现在弹是为了确保内容不丢失，应该在换机器或者工作地点的时候用，而不是在同一台机器互相改。

**Comment by ghosert** [comment]
再碰到这个问题再在这里留言或者重开这个问题。

**Comment by ghosert** [comment]
已经找到原因，正在解决，解决以后开多个浏览器 tab 或者 客户端都不会再有这个问题了。

**Comment by fluviusmagnus** [comment]
可是我一直单机单页面用也经常弹出合并。也许是我这里网速稍慢一点的缘故，特别快速地更改一小部分就有很大机率要求合并。或者是因为本机时间和服务器时间有差别？

不知道作者这部分代码是怎么写的，暂且提供一个检查的思路吧。

**Comment by fluviusmagnus** [comment]
现在发现以上应该也与输入法（fcitx）字已经上屏，但尚在选字的过程中同步了有关。

另外似乎由于以上种种综合导致，手工合并后手工作出的调整会以某种混乱的顺序与合并前的形式并存。

**Comment by ghosert** [comment]
可以刷新下页面，重启客户端后等待三十秒后重试，会自动推新版本过来，应该就好了。

**Comment by ghosert** [comment]
再重新开下，这种情况还是有可能发生在教育网用户，尤其是带宽不够的用户那边。继续想想办法。

**Comment by ghosert** [comment]
又改进了一次，应该概率不大了，如果还有频繁发生的问题，再重开这个问题。
