### ISSUE TITLE
Mac 客户端点击「轻量模式」的时候会出现一片空白的问题

### ISSUE THREAD

**Issue by X140Yu** [ghosert/cmd-editor#442]

**Comment by ghosert** [comment]
后来好了吗？

**Comment by X140Yu** [comment]
好了好了... 也许只是那一下子

原始邮件
发件人:Jay Zhangnotifications@github.com
收件人:ghosert/cmd-editorcmd-editor@noreply.github.com
抄送:X140Yu529783170@qq.com
发送时间:2015年4月28日(周二) 22:25
主题:Re: [cmd-editor] Mac 客户端点击「轻量模式」的时候会出现一片空白的问题 (#442)

后来好了吗？
