### ISSUE TITLE
可否解释下与 https://github.com/benweet/stackedit 的关系?

### ISSUE THREAD

**Issue by fcyu** [ghosert/cmd-editor#443]
无意中看到，发现你的UI跟 https://stackedit.io/editor 几乎一样，连用的表格，流程图，和序列图的例子都是一样的。而且人家的功能比你强大，还是开源的。能否解释下，这是巧合还是。。。

附上截图，以防万一：
![2a](https://cloud.githubusercontent.com/assets/6926299/7361240/d1a87424-ed87-11e4-88e4-b014a76e5005.jpg)
![2b](https://cloud.githubusercontent.com/assets/6926299/7361242/d1a9b168-ed87-11e4-96f0-78aa6644a803.jpg)
![1a](https://cloud.githubusercontent.com/assets/6926299/7361239/d1a6c566-ed87-11e4-97ba-d6af7ccdef87.jpg)
![1b](https://cloud.githubusercontent.com/assets/6926299/7361241/d1a90434-ed87-11e4-885c-4bbb2425965b.jpg)

**Comment by zpike** [comment]
应该是模仿的，但这个中文支持没cmd好吧。

**Comment by fcyu** [comment]
我觉得加中文支持的话直接fork是最好的手段，呵呵。

**Comment by ghosert** [comment]
确实有人 fork， fork 完了还收费，其实都没什么不可以，但是在搞清楚状况前别乱下结论会比较好。深度的用用，用完了再说到底哪里有差别，是不是 fork。长得差不多是因为很多基础组建大家都是用了第三方，不是我用他，也不是他用我，是我们用别人。我在知乎上的答案关于这个问题：

“
最近 StackEdit 把标题栏更换成 Cmd Markdown 的配色了，所以让很多人感觉是同一个东西。我在去年七月份做完第一版的时候完全不知道 StackEdit 的存在。后来在功能上互有借鉴，源码完全不同。可以回本帖看看更新日志，再上 Cmd Markdown 看看功能区别，StackEdit 对中文输入法有问题，我试下来无法完成一句正常的中文输入。另外就是发展思路上的不同，StackEdit 偏向于个人化的工具，所以它没有设置动态服务器，借助第三方存储。由于国外网盘各种墙，所以在国内访问 StackEdit 会很慢。我要做的是写作平台，所以需要用户注册，登录，保存，分享文稿，稍后会支持批注，评论，收藏和公开阅读。这个项目花费了近一年多的业余时间，购买了各种昂贵的基础服务才能为千千万万的用户提供免费服务，楼上一句“搞的好像你自己做的”未免让人太难堪了。
”
