### ISSUE TITLE
通过web页面导出的HTML不带样式

### ISSUE THREAD

**Issue by liuyujie** [ghosert/cmd-editor#446]
通过web页面导出的HTML不带CSS样式

**Comment by franciszhao** [comment]
嗯 看起来特别丑，Mac客户端导出的也是这个样子。
实时预览的效果就很好，希望导出的HTML效果能跟实时预览的一样。

**Comment by xiaoyuan0821** [comment]
建议加一下，不然导出没有任何意义。。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
