### ISSUE TITLE
「导出Html」改为「导出HTML」是否更恰当一点？

### ISSUE THREAD

**Issue by ya-luotao** [ghosert/cmd-editor#447]
（原谅我是强迫症

**Comment by ghosert** [comment]
有出处吗? 一定要全大写？

**Comment by ya-luotao** [comment]
HTML(HyperText Markup Language) 

HTML是缩写, 所以应该大写.

REF:[HTML - Wikipedia](http://en.wikipedia.org/wiki/HTML)

**Comment by ghosert** [comment]
了解了。

**Comment by ya-luotao** [comment]
:+1:
