### ISSUE TITLE
本地的客戶端是不是其实是一个浏览器？。。。

### ISSUE THREAD

**Issue by swortain** [ghosert/cmd-editor#449]
首先要感谢终于出了客户端。。
感觉既然本地化了是不是能在一个文件夹下列出所有的md文件比较好？。。

**Comment by ghosert** [comment]
客户端为了离线使用，这个是主要目的，所以叫客户端不叫浏览器。你想在哪个文件夹下？系统文件夹还是我做一个UI ？ 现在的 文件列表里不都列出来么，还可以搜索标题。

**Comment by swortain** [comment]
多谢回复！
恩，因为比如像我这样的用户总觉得如果本地没有一个文件和文章相对应的话，就觉得心里没底。。。是我的原因么。。所以我想的是能在客户端的文件夹下有一个文件夹，里面有所有文章的md文件，这样就和mou什么的感觉很像了是吧。
