### ISSUE TITLE
Linux 客户端默认找不到 libudev.so.0

### ISSUE THREAD

**Issue by zforget** [ghosert/cmd-editor#454]
这个应该是 NW 的事，系统里有 libudev.so.1，做一下软链接就可以了，但是还是影响体验。

**Comment by ghosert** [comment]
可否把详细步骤贴在这里，帮助其它人？

**Comment by legolasNg** [comment]
由于systemd项目于udev项目的合并，某些库的命名会发生改变，比如libudev.so.0
被重新命名为libudev.so.1。由于CMD Markdown依赖libudev.so.0这个动态库，所以做一个软连接到新的库：sudo ln -sf  /lib/x86_64-linux-gnu/libudev.so.1   /lib/x86_64-linux-gnu/libudev.so.0 (具体地址是系统情况而定，可以先使用locate命令先找到libudev.so.1这个库文件。)
如有错误，还望指正。

**Comment by ghosert** [comment]
请参考以上网友答案。
