### ISSUE TITLE
标签格式，离线应用，快捷键等

### ISSUE THREAD

**Issue by bin-dogami** [ghosert/cmd-editor#458]
1. 标签这块怎么没弄成符号格式呢，马克飞象的就挺好的， @()[]，我觉得咱们这也可以这样弄
2. 当我没网的时候就没法查看自己写的了，比如快捷键设置什么的。不过这个倒不是个容易的事。
3. 希望有快捷键的,比如 ctrl+super+s直接发表

**Comment by ghosert** [comment]
标签其实不应该那么繁琐，输入那么多 @()[] 其实输入代价挺大的。
基本每个功能都有快捷键，鼠标悬停在图标上查看即可。没网的时候在浏览器里输入 https://www.zybuluo.com/mdeditor 支持离线应用。或者去下载我们的客户端，详情见这里：https://www.zybuluo.com/ghosert/note/90884
譬如发表是 ctrl+alt+p

**Comment by ghosert** [comment]
建议把 https://www.zybuluo.com/mdeditor 收藏起来，离线也可以访问。

**Comment by bin-dogami** [comment]
离线客户端已下载。正在体验中的，感觉特别棒
