### ISSUE TITLE
希望能加一个category 

### ISSUE THREAD

**Issue by micln** [ghosert/cmd-editor#46]
一个任意深度的 category 

或者 tab

这样就能系统的管理文稿了。

不亚于一个office

**Comment by killent** [comment]
这个可以有。。。

**Comment by zzhdi** [comment]
强烈要求支持，并且希望今早实现

**Comment by ghosert** [comment]
正在开发这个功能

**Comment by ghosert** [comment]
已支持

**Comment by micln** [comment]
嗯，试了。很方便，
不过，默认列表是合起来的，每次点开都很麻烦。能否再稍稍优化一下。thx~

**Comment by ghosert** [comment]
是这样，一篇文稿可以对应有多个标签，这样的话，如果默认都打开，在列表里会看到许多一样标题的文章在不同的标签下，实际使用上感觉会更差。

你的问题可以这样处理，ctrl+alt+f 打开文件列表以后，直接在搜索框里输入 \* 号，这样所有的文稿都罗列出来了，这样才最高效，全程键盘不切换鼠标。
