### ISSUE TITLE
pc客户端-版本为win32-问题为“中文标签”无法显示

### ISSUE THREAD

**Issue by dotisi** [ghosert/cmd-editor#463]
pc客户端-版本为win32-问题为“中文标签”无法显示

在新建的文档中，中文标签是无法显示的，效果可以看这里。

![20150430153456](https://cloud.githubusercontent.com/assets/12182190/7408412/2267bab4-ef4f-11e4-92ed-63ab4159b5bc.jpg)

**Comment by ghosert** [comment]
操作系统版本多少？确定还在用 win32 的操作系统吗？ win7 64位版下没有这个问题。

**Comment by dotisi** [comment]
我现在家里面用的是win7-64位，用在百度云下载的64位客户端打开编辑的文档，还存在问题的，中文标签不显示。而且之前反映的32位的电脑，和现在64位的电脑不是同一个电脑。详见下图

![qq 20150505145910](https://cloud.githubusercontent.com/assets/12182190/7468141/55560c5a-f337-11e4-9c58-e84d8b95a33e.png)

64位系统版本

![qq 20150505150020](https://cloud.githubusercontent.com/assets/12182190/7468163/8e81ef94-f337-11e4-8a75-98260cc3465d.png)

在web下没有问题

![21](https://cloud.githubusercontent.com/assets/12182190/7468238/675c409e-f338-11e4-8337-5efd4f7d9b33.png)

也不知道，是不是我个人遇到了这类问题。

**Comment by ghosert** [comment]
重新下载一下客户端：http://pan.baidu.com/s/1qWyWMtA#path=%252FCmd%2520Markdown 好了告诉我。
