### ISSUE TITLE
特殊格式内容不能自动换行

### ISSUE THREAD

**Issue by Dream4ever** [ghosert/cmd-editor#466]
用符号 `` 包括起来的文字，会强制显示在一行中，而不是自动换行，这样的话后面的内容就会显示不出来。

![1](https://cloud.githubusercontent.com/assets/2596367/7439656/4dd10d1e-f0b6-11e4-9fb4-e74d4a8e029d.jpg)

**Comment by ghosert** [comment]
这种只适合短语，长句请用其它格式突出。
