### ISSUE TITLE
增加帮助，本地打开，导出pdf

### ISSUE THREAD

**Issue by nylzhy** [ghosert/cmd-editor#467]
希望可以有一个帮助文件，（我把开始的那个给删掉了），哪怕是一个指向帮助链接也好，还有就是希望可以打开本地文件，然后就是希望最后可以加上“导出为PDF”的功能

**Comment by ghosert** [comment]
已支持打开本地文件。https://www.zybuluo.com/ghosert/note/102771

**Comment by ghosert** [comment]
帮助文档在编辑区右上角的问号图标里。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
