### ISSUE TITLE
客户端能否提供版本号?

### ISSUE THREAD

**Issue by knight42** [ghosert/cmd-editor#469]
linux 上打包需要

**Comment by ghosert** [comment]
噢？想怎么打包？

**Comment by knight42** [comment]
我想在 Archlinux [AUR](https://aur.archlinux.org/) 上维护这个包, 但写 PKGBUILD 的时候需要填写版本号, 所以希望作者您能够提供. 

另外, 个人建议软件名能不能用下划线或连接线代替空格? 还有就是压缩包能否采取更规范的命名方式? 就是像 Cmd-Markdown-v1.0-x86_64.tar.gz 这样的. 麻烦了~~

**Comment by ghosert** [comment]
好的，内部的版本号就是 v1.0.0，格式方面我下次注意。 多谢打包。 发自网易邮箱大师 在2015年05月04日 12:20 ，knight-96写道： 我想在 Archlinux AUR 上维护这个包, 但写 PKGBUILD 的时候需要填写版本号, 所以希望作者您能够提供. 另外, 个人建议软件名能不能用下划线或连接线代替空格? 还有就是压缩包能否采取更规范的命名方式? 就是像 Cmd-Markdown-v1.0-x86_64.tar.gz 这样的. 麻烦了~~ — Reply to this email directly or view it on GitHub.

**Comment by knight42** [comment]
现在最新的版本号是1.1.0?

**Comment by ghosert** [comment]
对的，你咋么看出来的？命名方式部分参考了你建议的。考虑到普通用户，所以略作了简化。

**Comment by knight42** [comment]
额..猜的 ;) 版本号最好也写在文件名里吧~这样就不用每次问了

**Comment by ghosert** [comment]
我下次更新完以后，会写在右上角的【关于】里
