### ISSUE TITLE
[建议]希望加入打印版本,就顺便实现了Chrome中导出 pdf了

### ISSUE THREAD

**Issue by dongly** [ghosert/cmd-editor#471]
文档有打印需求,现在打印是很乱,希望加入一个可打印的样式.这样打印起来就会好看多了.也等于同时实现了导出PDF了(在Chrome中可打印到pdf).

**Comment by woodworm0125** [comment]
同意楼上的观点，希望加入导出pdf文件状态

**Comment by Garlandal** [comment]
我也希望加入导出pdf的功能，cmd-editor用的是最多的，但是每次导出pdf还得用stackeditor。

**Comment by idreamsoft** [comment]
直接全选 右键打印 然后另存为 就是PDF了  还用加什么导出

**Comment by ydleenudt** [comment]
至少在离线客户端还是加入导出pdf会更好，或者模仿马克飞象和Haroopad的方案，至少加入输出带样式的html的功能然后用chrome另存为pdf。pandoc配置太麻烦，导出pdf算是硬需求了。

**Comment by Garlandal** [comment]
直接右键的话感觉样式好乱

**Comment by idreamsoft** [comment]
要全选啊 不全选的话 可以点阅读模式后在右键打印

**Comment by ghosert** [comment]
各位少安勿躁，没累死前都会加。:)

**Comment by kk17** [comment]
支持，期待这个功能

**Comment by kk17** [comment]
在作者没有实现打印版本前我导出markdown用这个chrome插件[Markdown Preview Plus - Chrome Web Store](https://chrome.google.com/webstore/detail/markdown-preview-plus/febilkbfcbhebfnokafefeacimjdckgl)预览然后打印

**Comment by ghosert** [comment]
Cmd Markdown 有自己的语法和渲染效果，第三方的渲染效果以及打印效果并不能媲美，PDF 导出已经做好了，完美复刻原作中的 HTML 效果，会和其它一些高级功能一并发布，大家稍安勿躁。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
