### ISSUE TITLE
[建议] 希望增加「手动同步文章」的功能

### ISSUE THREAD

**Issue by ghost** [ghosert/cmd-editor#472]
就是关闭默认的自动上传功能，让用户自己选择什么时候同步。

每次写着写着就弹个窗说有冲突，体验好差...

**Comment by ghosert** [comment]
这个问题应该已经解决了，你开的是客户端还是 web 版，还是都同时开了在编辑？同时在编辑是会有冲突。连上网络，刷新下浏览器或者重开一下客户端再试，这个问题解决过了。

**Comment by armink** [comment]
@ghosert 下午写的文档，晚上回去打开发现少了好多，不会和这个有关系吧~用了大半年了都没有出现过丢数据的情况。

**Comment by armink** [comment]
@ghosert 确认下场景：下午是在公司电脑写的文档，回家电脑再看就丢了很多内容。

**Comment by ghosert** [comment]
是哪天发生的事情？五月五号今天发生的？先确定家里和公司的版本都已经推送过最新版本了？明天再试试看看还有没有这个问题。加我下微信 ghosert 我们私聊。

**Comment by ghosert** [comment]
明天再去公司看看，那些内容是不是还在，另外公司连接 www.zybuluo.com 的速度如何？

**Comment by ghosert** [comment]
已和 @armink 沟通过，可能是网络问题，如果还有问题请重开这个问题。先关了。

**Comment by ghost** [comment]
只开了 windows 客户端，写着写着就弹框说冲突了。（这几天确实没怎么弹出来

**Comment by ghosert** [comment]
@zhangwenbin 楼上有这种问题的时候再立马到这里留言并注意保护现场。我在线支持。

**Comment by ghost** [comment]
已经没问题了，谢谢。
下次遇到这类问题，我在微博/微信 at 你吧
