### ISSUE TITLE
离线版文字解析丢失，如图

### ISSUE THREAD

**Issue by gebitang** [ghosert/cmd-editor#473]
离线win64版本：文字丢失
![issue](https://cloud.githubusercontent.com/assets/1187857/7456310/18ac0682-f2b6-11e4-8201-f468607105af.png)

web正常版本：
![webok](https://cloud.githubusercontent.com/assets/1187857/7456351/6e0d4e92-f2b6-11e4-96f6-ea271855ddfd.png)

**Comment by ghosert** [comment]
重新下载一下客户端：http://pan.baidu.com/s/1qWyWMtA#path=%252FCmd%2520Markdown 好了告诉我。
