### ISSUE TITLE
更新之后太卡

### ISSUE THREAD

**Issue by xiaogu-space** [ghosert/cmd-editor#475]
今天早起更新之后获取页面变慢，而且发布更新不了

**Comment by gebitang** [comment]
我也遇到这个问题：无法发布更新。
//edit： 发布等待的时间较长，还是可以更新成功。

另外，会较频繁地弹出提示 云端、本地不一致，让编辑保存。
使用alt+tab切换回来好像就会弹出提示。

**Comment by xiaogu-space** [comment]
而且打开新界面下面都会提示  "正在同步本地文稿..."

**Comment by chenxiaobin** [comment]
我也是，在线的网页地址打开很慢，客户端的更慢，一直处于空白状态

**Comment by ghosert** [comment]
已经增加了带宽，应该好了。
