### ISSUE TITLE
Windows 离线版在 Chrome 中下载告警

### ISSUE THREAD

**Issue by zane-ng** [ghosert/cmd-editor#476]
下载完成后，Chrome 会提示：

Win64.zip is no commonly downloaded and could be dangerous. （ Win32.zip 同。附：[Google官方解释](https://support.google.com/chrome/answer/2898334?p=ib_download_blocked&hl=en&rd=2)）

虽然可以手动通过菜单保存文件，KIS 2015 扫描也没有问题。但是我一开始以为压缩包真的有马然后取消了……

Chrome 版本号：42.0.2311.135 m

**Comment by ghosert** [comment]
我在 linux 上打的包，应该没有木马。
