### ISSUE TITLE
osx64版客户端打开很慢

### ISSUE THREAD

**Issue by WKPlus** [ghosert/cmd-editor#480]
打开之后，只能看到标题栏为“node webkit”字样，然后至少等待30s+才能看到标题栏变成“cmd markdown...”，再然后等待30s+才出现文字进入可编辑模式。

我看了一下，在等待过程中，三个node-webkit进程大部分时间都是sleeping状态，是在访问网络么？

**Comment by numbcoder** [comment]
是的，我这也很慢！
建议不要使用 node-webkit，太重了， 这个基本要被淘汰了，现在都用这个 https://github.com/atom/electron

**Comment by ghosert** [comment]
刚才带宽不够，现在已经增加了带宽，应该好了。
