### ISSUE TITLE
win 64 

### ISSUE THREAD

**Issue by transposition** [ghosert/cmd-editor#481]
win 64 客户端打开后，鼠标转了几秒钟之后，没有任何东西，

**Comment by ghosert** [comment]
已经增加带宽，应该好了。

**Comment by transposition** [comment]
还是老样子……

**Comment by ghosert** [comment]
现在呢？web版呢？应该好了呀。

**Comment by transposition** [comment]
64位的还是老样子，打不开，但是32位的可以哦，系统是win 7 64位的

**Comment by ghosert** [comment]
留个IM 方式给我
我给你私下里说。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

2015-05-05 17:10 GMT+08:00 transposition notifications@github.com:

**Comment by transposition** [comment]
1009896477 thaks
