### ISSUE TITLE
求开源

### ISSUE THREAD

**Issue by idreamsoft** [ghosert/cmd-editor#482]
为什么不开源

**Comment by catroll** [comment]
专门跑 Github 上建立一个项目用来接受反馈？

**Comment by woodworm0125** [comment]
开源了，怎么盈利？

**Comment by zylhub** [comment]
这是作者幸苦劳作的结果。开源与否，我们作为free使用者，也是受益者，没有理由强求、也不应该强求。

**Comment by idreamsoft** [comment]
楼上的 我什么时候用强求开源了
能开源当然是最好
就算不开源码 基本也可以从页面上把JS扒下来照样能用

**Comment by ghosert** [comment]
楼上好凶残，不扒 JS 不是也照样能用吗？为啥要去扒呢？

**Comment by idreamsoft** [comment]
用是可以用 也只能在你们网站上用 如果其它地方有用到 还要每次都要复制来复制去的 
只是这么好的工具 不能集成到别的程序里有点可惜
像kindeditor，CKEditor  这些编辑器开源的不是还活得好好的
kindeditor还有很多商业授权
我也能理解作者为什么不开源
但是个人认为开源是有益无害的
或者能不能提供相应的接口
总比直接扒 JS的方式好吧

**Comment by ghosert** [comment]
那是在国外吧，我暂时的精力只能维持在产品开发上，在没有想好其他的出路前，暂时不能贸然决定是否开源。

还有 扒 这个事情好像我也没认可过。。。，这样做真的好吗？

**Comment by idreamsoft** [comment]
好吧
kindeditor 国产的 
扒JS只是极端的做法而已
我还是尊重作者 放心不会去扒JS的^_^
看来只能找找同类开源的产品
