### ISSUE TITLE
升级后加载太慢

### ISSUE THREAD

**Issue by hlyang1992** [ghosert/cmd-editor#483]
最近一次升级后加载异常慢, 而且浏览器中无法编辑, 左边的编辑栏无法编辑无法滑动, 输入文字无法左边编辑栏无法显示但却在右边的预览栏其他位置显示!

环境: chrome Version 41.0.2272.76 Ubuntu 14.04 (64-bit)

**Comment by ghosert** [comment]
已增加硬件，加载速度快了。看看还有没有问题，回复一下。
