### ISSUE TITLE
希望可以像marxico 一样可以支持上传本地文件，限制文件大小或者有收费服务都可以接受

### ISSUE THREAD

**Issue by dragonkid** [ghosert/cmd-editor#488]

**Comment by Bart2048** [comment]
+1

**Comment by moioo** [comment]
建议增加图床功能，用户可以自行设置如又拍云、7牛,就如http://yotuku.cn/    。。。。
有这个功能确实会方便很多。
为了以后的发展。。。。收取一定的费用可以接受

**Comment by ghost** [comment]
+1，如果能像云笔记那些，支持粘贴图片进去就好了。
写文章贴图片，像 QQ空间 这些图片的 url 贴了也显示不了，不太方便。（因为它的 url 没有 png 这些后缀

支持收费。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
