### ISSUE TITLE
【离线版/win64】代码块中无法显示中文

### ISSUE THREAD

**Issue by yiding-he** [ghosert/cmd-editor#489]
如下图所示，两处代码块里面的中文均无法显示出来。

![2015-05-05 12 16 44](https://cloud.githubusercontent.com/assets/900606/7466973/de59519a-f320-11e4-9f64-be70a883515d.png)

**Comment by ghosert** [comment]
嗯，有些人报了这个问题，但是我的 windows 上又是好的，我再看看。

**Comment by ghosert** [comment]
重新下载一下客户端：http://pan.baidu.com/s/1qWyWMtA#path=%252FCmd%2520Markdown 好了告诉我。
