### ISSUE TITLE
加强导出的功能，支持HTML样式，以及导出PDF格式

### ISSUE THREAD

**Issue by Drinkey** [ghosert/cmd-editor#49]
用这个东西写报告，写完发现copy出来和export出来的东西没法用，希望增强这方面的功能

**Comment by shjanken** [comment]
同意！写了个东西但是不适合发布，能导出成PDF就好了

**Comment by RichardNi** [comment]
同意！至少要加强HTML的导出功能，预览时的所见导出就应该完整保留样式。

**Comment by blbailei** [comment]
赞同~

**Comment by xyapp** [comment]
强烈赞同。。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
