### ISSUE TITLE
linux32位客户端用不了

### ISSUE THREAD

**Issue by youngitachi** [ghosert/cmd-editor#492]
我的系统时linux mint17.1, 双击Cmd Markdown没有反应啊

**Comment by ghosert** [comment]
看看出错信息，然后参考下这个答案：https://github.com/ghosert/cmd-editor/issues/454

**Comment by youngitachi** [comment]
谢谢,按照那个方法确实解决了.顺便说一下,百度云上linux32的那个文件名为linux32tar.gz,实际上应该为linux32.tar.gz吧?

**Comment by ghosert** [comment]
啊？我去改改。
