### ISSUE TITLE
客户端和网页版同步有问题

### ISSUE THREAD

**Issue by leowenyang** [ghosert/cmd-editor#493]
在同时使用客户端和网页版的时候，同步出现问题， 客户端中写的文章没有同步到网页版上。打开网页版后，客户端的文章消失

**Comment by ghosert** [comment]
确定你这边的版本是最新的了吗？这个问题应该已经解决过了。给我一个 IM 方式我们私聊，最好录一段小视频给我。ghosert 加我微信。
