### ISSUE TITLE
不支持编辑本地文件么？

### ISSUE THREAD

**Issue by betaforever** [ghosert/cmd-editor#494]
不支持编辑本地文件么？就不能只当一个编辑器使用吗，什么鬼！

**Comment by ghosert** [comment]
暂时先自己复制粘贴下，过后在加各种。

**Comment by yjfvictor** [comment]
编辑本地文件，这个功能还是挺重要的。

**Comment by betaforever** [comment]
是啊，编辑器非常不错，而且还支持vim的编辑方式，就是不能直接编辑本地文件和保存。只能先用Haroopad。

**Comment by ghosert** [comment]
本地概念已经落后了，云笔记素王道。

**Comment by betaforever** [comment]
云筆記是比較好，但是如果我想用一個編輯器來編輯hexo的文件，來搭建自己的博客。那麽，每次都需要複製一遍到編輯器，再導出，再重命名，這得有多痛苦。

**Comment by ghosert** [comment]
有得必有失，除非支持指定某些文件的非云笔记功能。

**Comment by betaforever** [comment]
謝謝你的回復

**Comment by ghosert** [comment]
已支持打开本地文件。https://www.zybuluo.com/ghosert/note/102771
