### ISSUE TITLE
客户端意义不大

### ISSUE THREAD

**Issue by shuhaoc** [ghosert/cmd-editor#495]
如果仅仅是使用node-webkit将web端包装到一个客户端中，这样的客户端在使用体验上与Web端有什么优势呢？本地客户端应该具备本地资源直接利用的优势，具备性能优势，具备交互体验优势，但是目前这样的客户端看不到任何优势。

**Comment by yjfvictor** [comment]
我也注意到了，完全就是个“客户端”（需要连接服务器的），而不是彻底完全离线的（因为首次访问需要联网）。这样子真的很难说比网页版有什么优势。

实际上我们希望的是类似[MarkdownPad](http://markdownpad.com/)或者[ReText](http://sourceforge.net/p/retext/home/ReText/)这样的完全离线的桌面软件，而不是一个客户端。

![MarkdownPad](http://markdownpad.com/img/markdownpad2.png)

![ReText](http://sourceforge.net/p/retext/screenshot/retext-kde.png)

我倒不是说一定要重构成native代码，用Web技术来实现完全离线的桌面软件也行。比如微软最近推出的[Visual Studio Code](https://code.visualstudio.com/)编辑器，也支持Markdown的预览。

![Visual Studio Code - Markdown preview](https://cloud.githubusercontent.com/assets/6044012/7479482/7a829bc6-f394-11e4-872a-77153ea65bf3.jpg)

**Comment by ghosert** [comment]
三个原因：
1. 普通用户并不关心背后的技术，好用，有自己的特色就行，可以比对一下Cmd Markdown在云同步，智能合并，编辑器本身，渲染能力方面本身的优势。
2. 客户端的重大意义是离线使用。即使浏览器版现在也可以离线使用，对于大多数用户并不习惯离线去使用浏览器。现代意义上的软件都是互联网优先的，所以不是为了做客户端而做，而是需要先有离线能力，然后顺便做客户端方便那些不习惯通过网址使用离线应用的人。在桌面上放图标，双击可运行最方便不过，首次运行需要网络的代价并不大。
3. 桌面客户端 html 化是大势所趋，大家也说了 微软 visual studio code 都在这么干，以微软的财力都如此，作为一个独立开发者，财力，资源受限，没有必要再去各个系统上重新写一套，那样再过一年两年都无法增加新功能，只能不停的重写现有代码。

**Comment by yjfvictor** [comment]
1.普通用户并不关心背后的技术，我也不关心。我关心的是：①彻底完全离线（第一次使用也不用联网）；②编辑本地文件。
2. 客户端的重大意义是离线使用。真的做到了吗？第一次使用还是要联网。首次运行需要网络的代价并不大吗？我这边的情况是这样：完全没有网络环境，只能用U盘复制安装程序。
3. 桌面客户端 html 化是大势所趋。是的，我也觉得没需要重构成native代码，但是希望的是彻底完全离线。像Visual Studio Code那样，虽然是用Web技术实现，但是也是完全离线的。

**Comment by ghosert** [comment]
这种案例实在太少见了，按我的设想大多数时候都是有网络的，偶尔会在没有网络的情况下使用。你那边的机器真的完完全全不能有一次联网的机会吗？
编辑文件暂时先复制粘帖一下文本，稍后再加打开文件就行了。
如果一定要首次启动不联网也能工作也是有办法，你什么操作系统？

**Comment by shuhaoc** [comment]
关键问题是，如果仅仅是将Web端用node-webkit包装成exe分发，这样的用户体验与直接使用浏览器有什么优势呢？

**Comment by ghosert** [comment]
很多人看到浏览器就不用了，很多人认为浏览器就等于要在线用，不能离线用。所以想也不想就不用了。而且还要打开浏览器输入网址，比双击图标麻烦。小屏幕下，浏览器上面的地址栏菜单栏会占据宝贵的屏幕空间，node-webkit里都去掉了。还有些譬如 emacs 模式需要的常用快捷键 ctrl + n 在浏览器里被浏览器占用了，默认是打开新窗口，在 node-webkit 都解决了。另外，浏览器毕竟是沙箱模式无法访问本地资源，node-webkit 是可以的，以后的新功能譬如 pdf 转换，插入图片都可能利用这些本地资源来做。还有系统托盘，等等等等。

要用发展的眼光看问题，这个只是第一步。

**Comment by yjfvictor** [comment]
1.情况不少见。很多安全意识强的公司，都不允许员工的机器连外网。只连个内网。
2.复制粘贴文本当然可行，就是感觉不太爽。本来想右键直接开Markdown编辑器的，结果还要先右键文本编辑器。
3.用的操作系统是 Windows 7 x86 和 Linux  x64

**Comment by ghosert** [comment]
已然可以直接拖拽文本到编辑区打开文件了。

**Comment by ccxuy** [comment]
@ghosert 我这边也有需求首次启动不联网也能工作，os是win7，请问怎么操作呢？
