### ISSUE TITLE
渲染卡住了

### ISSUE THREAD

**Issue by ding** [ghosert/cmd-editor#50]
我把StackEdit https://stackedit.io/ 的说明文档直接贴进去，准备测试一下同样的文档两遍的显示效果。发现cmd这边一直提示“正在加载文章图片，请稍后片刻... ”已经一个上午过去了，还没有结果。

**Comment by ghosert** [comment]
我试了一下，没问题。你试试刷新一下，再看看是不是有被墙掉的链接在页面里面，github 本身就会断断续续被墙。
