### ISSUE TITLE
Win7 64位客户端中文标签不显示

### ISSUE THREAD

**Issue by xuelu520** [ghosert/cmd-editor#505]
![qq 20150507091217](https://cloud.githubusercontent.com/assets/3634237/7506889/2ebca1e0-f499-11e4-92d7-f42653e46e3f.png)
如图所示，英文的标签正常显示，中文则显示异常，望修正。

**Comment by workwsl** [comment]
同上，遇到此类问题。

**Comment by ghosert** [comment]
重新下载一下客户端：http://pan.baidu.com/s/1qWyWMtA#path=%252FCmd%2520Markdown 好了告诉我。

**Comment by xuelu520** [comment]
![image](https://cloud.githubusercontent.com/assets/3634237/7650506/b4a93a34-fb29-11e4-84c5-6b021fdadff9.png)
看起来没问题了
