### ISSUE TITLE
mac客户端问题

### ISSUE THREAD

**Issue by chenkai** [ghosert/cmd-editor#506]
hi 
cmd markdown 产品总体做的非常不错.
原来一直采用在线版本,但最近几个月经常需要出游.所以在路上经常没有网络的情况离线编辑和写作就显得极为的重要.这点切实我核心需求.

关于mac 离线客户端这里面有几个问题需要改善:

A：下载包.
在官方cmd markdown离线按包装包 大到180M. 我当时看到这个包大小一直很换衣一个编辑器需要这么大吗.
下载解压包后发现. 原来离线安装包里面包含三个平台全部的32和64的安装包.
但我明明选择的是仅仅需要mac 客户端而已.
所以建议在独立尽力一个下载页面，针对下载的平台和系统不同(32&64位)对安装包进行区分.
因为这样利于分发.

B：验证邮件
官方打开cmd markdown离线版本注册新的用户后,到现在都没有收到认证邮件.
不知道是什么问题.

C：自动全屏
cmd markdown每次离线客户端打开都是自动充满全屏,建议不要采取这样设置
因为并不是所有情况都是需要覆盖全屏.大部分场景是需要查看核对其他资料进行写作.
所以这个默认打开 建议已一定大小进行屏幕居中就好.
不要每次打开都是全屏 还需要重新设定大小.
可以在编辑器上给一个简单选项即可.

D：权限
cmd markdown发布文稿之后.
发现排版很美观.看着极为舒服的.
但是我有一个核心的需求是我希望自己写的东西在online上时
需要给我指定可看.
所以如果能够给出一个加密或者根据邀请着邮箱方式来查看即可.
所以这里需要一个有效控制的私密的权限问题.
建议你们考虑一下这个需求.
因为针对团队内部分享文稿时大多是需要保密的 这个对协作非常有用.

改写cmd markdown做的杰出的产品.
希望一如既往做的更好.

chenkai
best&regard 
beijing

**Comment by ghosert** [comment]
意见都不错，我再考虑下。
A 可以改进
B 不知道你这边是什么信箱，可以再等等，不行的话可以通过用户设置里更换邮箱。
C 一般都配了双屏，所以我倒没注意这种问题，我再权衡下，全屏是为了鼓励无干扰写作。
D 这个可以有。

**Comment by chenkai** [comment]
@ghosert 
A:下载包这个最好强烈推荐做一下.对客户端的分发太重要了.
B:认证邮件收到了 只是到了垃圾邮件坐了分类而已.
C:但有些情况大部分打开mac是单屏 需要自己写点东西
D:权限这个是刚需. 望尽快支持. 因为现在我在cmd marddown上写的都是倒出来 在别的地方做成加密分享.

**Comment by ghost** [comment]
你好！编辑时，双屏页面为什么不能同步到相应位置？

**Comment by ghosert** [comment]
A 已经提供了单独的下载链接
D 私密性上可以设置访问密码，或者新建完全离线的文稿。

**Comment by ghosert** [comment]
@Lincoln-King 我们的同步算法应该可以保障同步到相应的位置。如果不行是因为左右的差异太大，例如，左侧是一个图片链接，右侧是一整个图片。尽量多写 # ## ### 开头的标题会有助于算法定位位置，同步更准确。
