### ISSUE TITLE
建议：登录/注册之前暂存已输入内容或者增加提示

### ISSUE THREAD

**Issue by Yumozhi** [ghosert/cmd-editor#507]
兴致勃勃写了一两个小时突然想起没登录之前不能保存万一有个三长两短不就白写了
然后手欠点了登录
然后跳转回去
然后之前写的内容就全！没！了！
本来没有事
然后现在就真的就白写了...

弄得我想直接弃用...

就没有考虑过试用用户用到一半想注册一下而跟我一样没先保存的么...

---

搜了下原来早就有人提这个问题，可是一直没有解决
作者希望用户注册...
其他的就不说了

在跳转之前你至少给个提示吧

**Comment by yjfvictor** [comment]
其实可以在“登录”和“注册”两个按钮那里搞一个 `onclick="alert('未保存的文章会被丢弃')"`

或者干脆加个全局的

``` JavaScript
window.onbeforeunload = function() {
    return '您的文章尚未保存。确定要离开此页吗？'
}
```

**Comment by ghosert** [comment]
好的，这个我加个警告，其实编辑器上方每次击键都有提示，登录后保存。。。。

**Comment by ghosert** [comment]
好吧。。。突然想起没登录的时候，基本动作是先复制。。。。反正我加个警告好了。。。

**Comment by ghosert** [comment]
加了警告了。
