### ISSUE TITLE
降低自动保存的频率

### ISSUE THREAD

**Issue by nylzhy** [ghosert/cmd-editor#509]
自动保存的频率太快了，往往一句话还没有写完，自动保存几次，造成卡顿的现象较为明显，尤其在处理数学公式时。希望增加自动保存频率的设置，是情况由用户决定更好，尤其针对离线版，谢谢

**Comment by ghosert** [comment]
这个和自动保存的频率没有关系，主要式 latex 公式本身比较耗时，我会再改进。

**Comment by ghosert** [comment]
应该已经优化到不卡了。https://www.zybuluo.com/ghosert/note/123892
