### ISSUE TITLE
强烈建议：加入批量导出md或HTML文件功能

### ISSUE THREAD

**Issue by viclab** [ghosert/cmd-editor#511]
cmd markdown虽然很方便撰写随时随地撰写md文件，但由于个人知识库管理要求更强大的分类以及检索等资源管理方面的功能，所以，我会定期从cmd markdown中导出文件，存入个人知识库方便管理，所以强烈建议增加批量导出文件的功能，目前仅支持一次导入单个文件

**Comment by JoshWu** [comment]
我也是强烈建议加入批量导出的功能. 因为cmd-editor的一个弱项是没有版本管理, 有时候会的无意修改也被保存,而且很难发觉.
如果加入批量导出的话, ,用户就可以自己解决版本管理问题了.

**Comment by ghosert** [comment]
没有版本管理可以加

**Comment by JoshWu** [comment]
如果加入版本管理那就最好了.而且最好是跟git兼容.

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
