### ISSUE TITLE
PC 客户端一个小BUG

### ISSUE THREAD

**Issue by kiddx01** [ghosert/cmd-editor#512]
某此情况中文显示不了, 如下, "过滤字段" 显示不了. 在网页端是正常的. 
### Subset of fields `过滤字段`

不需要将fields所有显示出来, 需要过滤某些fields

```
from django.core import serializers
data = serializers.serialize('xml',SomeModel.objects.all(),fields=('name','size'))

```
### Subset of fields `过滤字段`

不需要将fields所有显示出来, 需要过滤某些fields

```
from django.core import serializers
data = serializers.serialize('xml',SomeModel.objects.all(),fields=('name','size'))

```

**Comment by ghosert** [comment]
重新下载一下客户端：http://pan.baidu.com/s/1qWyWMtA#path=%252FCmd%2520Markdown 好了告诉我。

**Comment by kiddx01** [comment]
可以了!! 感谢
