### ISSUE TITLE
HTML导出的问题

### ISSUE THREAD

**Issue by soniaxu7** [ghosert/cmd-editor#513]
使用HTML导出的文件，通常是没有样式的，看上去很丑……

但是如果直接在发布页面右键另存为，这个时候因为样式文件的路径是http路径，反而能够保存下来样式。

能否做到导出的HTML就自带样式文件呢

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
