### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by heibai01** [ghosert/cmd-editor#514]
不管离线或在线都建议加入打开(or导入)本地markdown文档的功能.
不知道作者是出于什么考虑(这个功能应该很简单的)。

另：问个问题啊，这个是用node webkit实现的吗？小弟在用nodejs做web开发，但是对本地应用不是很清楚，是否可以推荐些入门资料？感谢:D

**Comment by ghosert** [comment]
这个已经实现了。
