### ISSUE TITLE
能否增加程序流程图的支持？

### ISSUE THREAD

**Issue by xworks** [ghosert/cmd-editor#523]
增加UML流程图，不少markdown编辑器也都支持的流程图，类似这样的：
![snip20150510_1](https://cloud.githubusercontent.com/assets/1674714/7554684/edc01de8-f763-11e4-845a-ed6bdce6c7af.png)

**Comment by ghosert** [comment]
这不是支持了么？仔细读读帮助文档: https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#7-流程图
