### ISSUE TITLE
预览和编辑栏不同步

### ISSUE THREAD

**Issue by langdamao** [ghosert/cmd-editor#53]
![image](https://f.cloud.github.com/assets/6916588/2383291/cd5dad36-a8f9-11e3-8476-07d62fc34a76.png)
有时候差一行，有时候差挺多... 是因为我写的格式不对么？

**Comment by ghosert** [comment]
因为两边一个是纯文本，一个是渲染后的html，因此高度上不可能做到完全一一对等，也没有必要，只要右边的内容匹配左边就可以了，另外，多用 #， ##， ### 这种标题标记，会使得定位更准，两边的块计算主要使用 #， ##， ### 来做的。
