### ISSUE TITLE
用户配置同步问题

### ISSUE THREAD

**Issue by Thunderlbc** [ghosert/cmd-editor#530]
每次打开cmd markdown都需要重新地设置输入模式为Vim, 可否在用户设置中添加 一些如输入模式, 同步频率等用户个性化配置同步功能. 可以让用户不用每次登录都重新设置习惯配置.

**Comment by ghosert** [comment]
你是哪个系统，应该登录以后在同一台电脑上只需要选择一次，下次启动默认还是 vim

**Comment by Thunderlbc** [comment]
额, 跟我清理过cookies有关. 不好意思~, 谢谢回复~
