### ISSUE TITLE
期望windows客户端提供一个近期文章列表的功能

### ISSUE THREAD

**Issue by hilliate** [ghosert/cmd-editor#531]
目前只能通过标签找文章，一旦文章的标签设置比较多，看起来就杂乱了。
其实用户主要需要编辑近期的几篇文章，期望能像word那样，提供一个“最近编辑文章”的列表，里面按时间倒序排文章即可。

**Comment by ghosert** [comment]
可以使用标题搜索功能。

**Comment by jolinx** [comment]
能不能把所有的文章都以目录的形式显示出来呢。其实我们记录文字不只是写，最重要的是供以后翻阅，当文章多了，通过搜索*的方式就显得麻烦了。

**Comment by ghosert** [comment]
不管怎么组织，内容多了，搜索最方便啊。目录的形式现在不是也有吗？还分了 tag 了。

**Comment by hilliate** [comment]
你的手机通讯录，有没有“最近通话人”功能，为什么提供了“搜索”，还要提供“最近通话人”的功能？甚至“最近通话人”往往是通讯录进去之后的默认功能。
这么做的原因就是：用户打电话时，往往会打给自己最近联系过的人，这种情况能匹配用户大部分的需求，用户直接选择，往往要比搜索输入字符要快速的多。

在写文章的时候也是这样，我需要编辑的文章，往往是近期写的文章，呈现出来，直接点击编辑，效率最高。

**Comment by ghosert** [comment]
最近访问过的文稿已支持：https://www.zybuluo.com/ghosert/note/378553
