### ISSUE TITLE
实时预览不显示中文问题

### ISSUE THREAD

**Issue by jerryqiu** [ghosert/cmd-editor#533]
下面这种格式是预期效果

```
m|0|北京欢迎你！|test
```

但在实时预览页面中不显示中文，效果如下：

```
m|0|          |test
```

**Comment by ghosert** [comment]
这个应该是 windows 客户端的问题， 网页版好的，已知晓。

**Comment by jerryqiu** [comment]
Windows客户端的预览，标签内包含中文的都显示不出来

![image](https://cloud.githubusercontent.com/assets/284632/7645785/e9144576-faec-11e4-9d8c-d010f615f3e5.png)

![image](https://cloud.githubusercontent.com/assets/284632/7645788/f61c30c6-faec-11e4-89b1-2c4f2d82685a.png)

**Comment by ghosert** [comment]
能留个 im 给我吗？

**Comment by ghosert** [comment]
重新下载一下客户端：http://pan.baidu.com/s/1qWyWMtA#path=%252FCmd%2520Markdown 好了告诉我。

**Comment by jerryqiu** [comment]
已经修复了，多谢！
