### ISSUE TITLE
期望客户端中编辑表格功能增强……

### ISSUE THREAD

**Issue by l1xnan** [ghosert/cmd-editor#534]
像此链接中的 http://www.tablesgenerator.com/markdown_tables

**Comment by jolinx** [comment]
打不开这个链接。
其实语法和编辑wiki差不多，无论是字体格式还是单元格颜色亦或是合并拆分单元格，都可以实现的。
但是像公式这种高级功能肯应该是不行的，那样的话你还是用excle吧
