### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by pgboy1988** [ghosert/cmd-editor#536]
今天使用了一下,发现功能很强大.样式也非常不错.但是有几点不爽的地方:
1,不能导出pdf.
2,导出的html样式颜色全没了.
3,不能上传本地图片.
其他都非常好.特别赞的是流程图的功能

**Comment by pgboy1988** [comment]
还有一个就是不能看文章列表..比如我新建了一个文档然后我想看以前写的那个.结果发现必须删除当前这个才能看到以前的那篇

**Comment by ghosert** [comment]
嗯，正在做这些。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
