### ISSUE TITLE
客户端 ` ` 不能正常预览中文

### ISSUE THREAD

**Issue by iliyz** [ghosert/cmd-editor#537]
![2015-05-15_104512](https://cloud.githubusercontent.com/assets/9245965/7645979/9e28c8a4-faef-11e4-812a-4205929f9cb2.jpg)
![2015-05-15_104527](https://cloud.githubusercontent.com/assets/9245965/7645980/9e2af8f4-faef-11e4-9b8a-6779701d9035.jpg)

**Comment by ghosert** [comment]
能留个 im 给我吗？
我和你在线聊下，我这里没有机器可以重现这个问题。

**Comment by ghosert** [comment]
重新下载一下客户端：http://pan.baidu.com/s/1qWyWMtA#path=%252FCmd%2520Markdown 好了告诉我。

**Comment by iliyz** [comment]
重新下载的客户端没有问题  ◕‿◕

![2015-05-16_153018](https://cloud.githubusercontent.com/assets/9245965/7665226/8a8422f2-fbe0-11e4-8d16-25b7fd6157c1.jpg)
