### ISSUE TITLE
centOS 6.5 运行不了呀

### ISSUE THREAD

**Issue by JustLookAtNow** [ghosert/cmd-editor#540]
./Cmd Markdown: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
centOS 只有上libnotify-0.5.0-1.el6.i686
并没有libnotify.so.4何解？

**Comment by ghosert** [comment]
https://github.com/ghosert/cmd-editor/issues/454

参考下这个答案即可。
