### ISSUE TITLE
中文拼音正在输入显示云端跟本地不一致

### ISSUE THREAD

**Issue by waterschen** [ghosert/cmd-editor#542]
用中文输入法正在编辑的时候经常弹出消息框说云端的文件跟本地的文件不一致，因为上次同步的时候中文输入法才输入到一半，文稿上还是拼音未选定中文，客户端直接把拼音字符同步上去了，然后选定拼音后就检测到云端文件跟本地文件不一致。

**Comment by ghosert** [comment]
哪个操作系统，输入法是什么说一下。

**Comment by ghosert** [comment]
这个问题主要是因为你那边连接 Cmd Markdown 的网速过慢。出现这个问题的频率高不高？

**Comment by waterschen** [comment]
用的是 MAC OS X 10.10 的系统输入法，确实是网速过慢造成的，昨晚网速不好时隔几分钟就出现一次，今天网速较好还没重现过。

**Comment by ghosert** [comment]
我再改一下，1秒内未返回的请求视作失败。下次重发。

**Comment by ghosert** [comment]
又修了一下，你刷新下页面或者重启客户端后会有更新提示，更新以后再看看如果网速很慢是不是还有这个问题。

**Comment by ghosert** [comment]
还有这个问题吗？

**Comment by waterschen** [comment]
没有了，以后有问题再报告一下 ：）
