### ISSUE TITLE
Ubuntu下软件的图标显示不正常

### ISSUE THREAD

**Issue by Toudsour** [ghosert/cmd-editor#545]
变成了这样
![image](https://cloud.githubusercontent.com/assets/11494514/7669371/e885d496-fca2-11e4-9a9f-6df0a4330b8e.png),建议liunx客户端下给一个图标,便于自己创建快捷方式
此外Ubuntu将部分lib文件改了点名字,运行有些问题(用户需要自己解决)

**Comment by yangao07** [comment]
用这个图标
![cmd](https://cloud.githubusercontent.com/assets/5309122/7696639/a4d71d50-fe31-11e4-9ba6-c8ae0b077f7c.png)

然后给程序建立个链接，我就是这么用的
![default](https://cloud.githubusercontent.com/assets/5309122/7696650/bc785cbc-fe31-11e4-9571-1f0021ab8394.png)

**Comment by ACBingo** [comment]
ubuntu下怎么安装该软件啊。。。
小白求。。。。

**Comment by fluviusmagnus** [comment]
直接解压，在解压出的文件夹中找到可执行文件双击打开运行即可。

作者并未针对发行版打包，也就是采用了类似“绿色软件”的形式发行，因此严格意义上说并不需要安装。

2015/05/29 17:19、ACBingo notifications@github.com のメッセージ:

**Comment by ghosert** [comment]
参考一下这个答案，然后再双击。https://github.com/ghosert/cmd-editor/issues/454
