### ISSUE TITLE
编辑长公式的时候，左边编辑区一直在抖

### ISSUE THREAD

**Issue by intijk** [ghosert/cmd-editor#55]
![report](https://f.cloud.github.com/assets/740501/2393969/ebbf1508-a9a3-11e3-8903-9f9d1ef13423.png)
在编辑这样一个长公式的时候， 持续请求生成新的mathjax，就造成了右边一直在更新高度，这时候左边就一直在抖动，我猜实现的时候为了左右对照左右都在不断的调整高度，但是当我没有输入完整个公式的时候，这样的“抖动”造成的输入体验很不好，眼睛跟来跟去的，感觉光标乱跑。所以希望能否在这种情况下延迟对齐的操作，从而减少编辑的时候的“抖动”。

**Comment by ghosert** [comment]
目测没有碰到这种情况，你用的机器屏幕分辨率多少，操作系统，浏览器是什么？在编写完公式以后，写文字的时候还抖吗？如果不抖，可以在写公式的时候切换到 独立编辑模式，编辑完再切回来，或者录个屏过来发我邮箱，让我看看咋么抖的。

**Comment by ghosert** [comment]
还有你人在中国还是美国，网络状况如何？

**Comment by intijk** [comment]
我在美国，网速没问题。

大概是这样出现的，我没有全屏我的浏览器，为了对照方便，左边开了个pdf文档，整个浏览器是在右侧的一半屏幕，我用的是1080p的23寸显示器。

2014-03-12 1:18 GMT-05:00 Jay Zhang notifications@github.com:

**Comment by intijk** [comment]
Under Firefox 27. 
编辑的时候，左边的内容喜欢占满全屏，即使我加了好多空行在下面，编辑的时候就自动又跑回来了。
然后我再编辑其它东西的时候，就会抖，不知道这是一个还是两个问题。你可以把屏幕拉到右边的一半试试。如果还不清楚就只好给你录一个了。

**Comment by ghosert** [comment]
我照你说的做了，也没有重现这个问题。你全屏浏览器还会有这个问题吗？如果你觉得方便给我录一个吧，谢谢了。另外你这个状况，倒不如配双显示器，我自己工作用三台的。

**Comment by intijk** [comment]
我想是这样的，左边是用户的视口，控制区，应该永远应该主动控制变化，而没有任何的被动变化。

当左边下面加了很多空行的时候（有时候只是为了单纯的把底部内容居中），右边又不会生成一段空白垫底，这时候尝试对齐的时候就来控制左边的视口了，这是编辑的时候不太想见到的，所以我的建议是尝试对齐的时候，如果调整了一边的视口，那么这里就是用户care的地方，另一侧是作为参照的，就不要尝试动用户调了视口的这一侧， 只动另一侧的。如果要调整高度，可以尝试在低端留百。

**Comment by intijk** [comment]
行，我给你录一个吧。
PS：桌子就这么大，资金也有限，无法土豪配。

**Comment by ghosert** [comment]
好的，谢谢了。全屏浏览器也有这个问题？

**Comment by ghosert** [comment]
实际上，应该是在你编辑的时候，永远不动编辑区，只动预览区，除非你主动移动预览区，你的情况确实不知道咋么造成的，或许录一个就清楚了。

**Comment by ghosert** [comment]
应该修复了，你在试试，答复我一下。

**Comment by ghosert** [comment]
主要是屏幕过窄以后，保存中字样会折行，造成抖动感，现在固定宽度了。

**Comment by intijk** [comment]
亲测已修正，赞效率。

**Comment by ghosert** [comment]
好的，那我关闭这个问题了。
