### ISSUE TITLE
Hi,自定义CSS的功能好加吗

### ISSUE THREAD

**Issue by RubberBear** [ghosert/cmd-editor#550]
我写了点文字：https://www.zybuluo.com/mdeditor#100734-full-reader。
有个问题，就是标题层级太多了，四级标题的文字大小和三级标题的文字大小一样，这样如果不看目录的话不是很好区分，不知道增加自定义CSS的功能是否好做，谢谢。

**Comment by ghosert** [comment]
你把文章发布出来以后再把链接贴给我，你这个链接别人是看不到的。

**Comment by RubberBear** [comment]
是我看错了，其实h4和h3还是有所区别的，就是区别不大。不好意思

2015-05-19 10:40 GMT+08:00 Jay Zhang notifications@github.com:

**Comment by ghosert** [comment]
已更新，可以自定义CSS了：fhttps://www.zybuluo.com/ghosert/note/378553
