### ISSUE TITLE
怎么找回历史记录，我的文章就剩下标题了，刚刚不小心点错了

### ISSUE THREAD

**Issue by Flyfishering** [ghosert/cmd-editor#551]
它说云端跟本地不一致，电脑一卡，就点错了，结果一篇文章（论文）就只剩下标题了，泪奔啊！
求告知，怎么找到历史记录，痛苦了半个月写的东西，，，，，

**Comment by ghosert** [comment]
别急，我帮你找，标题告诉我。

**Comment by ghosert** [comment]
留个邮箱给我，找到以后发给你。

**Comment by ghosert** [comment]
用户名也说一下。

**Comment by Flyfishering** [comment]
标题：基于小波变换的图像信息隐藏算法检测
用户名：fiy-fish

太谢谢你了，没想到你会这么快回复我，前两天在知乎看到你的作品，感觉挺适合我的，就拿来写代码笔记，越写越顺手，就顺便把论文也用这个写了。。。。。。。
以后再也不会点错了！！！！

**Comment by ghosert** [comment]
邮箱有吗？我发给你？还是贴在这里？

**Comment by Flyfishering** [comment]
fish625@foxmail.com

麻烦你了！
终于不用重写了

**Comment by ghosert** [comment]
稍等十分钟左右，正在处理数据。

**Comment by ghosert** [comment]
内容好像不多？

**Comment by ghosert** [comment]
已经发了，你看看有没有漏，如果不全我再找找再之前的数据。

**Comment by Flyfishering** [comment]
这个是我今天重写的，如果只有这么短的话我都不好意思麻烦你，不知道还能不能找回来，不过还是要感谢你，耗费了你那么多时间帮我找！

**Comment by ghosert** [comment]
你确定之前没有换过标题？

**Comment by ghosert** [comment]
没事，我再找找，数据太多，:-)。

**Comment by Flyfishering** [comment]
没有，当我的文章被我失误操作丢失之后，我的反应是这样的
1.关掉客户端，用浏览器打开cmdmarkdawn，结果发现浏览器里的文章也是残缺的。
2.然后，在客户端点击了撤销发布，以为这样可以找回历史文件，结果失败
3.用浏览器尝试2.步奏还是失败。
4.尝试点击了所有我能够点击的按钮，仍是失败，然后我就放弃尝试，来github找你帮忙！

我能提供的线索只有日期
今天的文章都是缺损的
上一次发布的文章一定是完整的！

就是不知道云上面有没有按照日期记录

**Comment by ghosert** [comment]
没事，应该在的，很快就能找到，我再找会。

**Comment by vanechu** [comment]
ghosert, 你好. 我也遇到同样的问题, 能否帮忙找回.
我的用户名是chlx, 文档名叫做Computer Architecture HW3. 
非常感谢.

**Comment by ghosert** [comment]
@vanechu @Flyfishering 你们最后一次正确编辑大概是什么时间？最好精确到小时

**Comment by Flyfishering** [comment]
2015/5/16
中午 1点左右

**Comment by vanechu** [comment]
19日10点半 - 11点半 之间

**Comment by vanechu** [comment]
刚才有错误, 是19日22点半 - 23点半 之间

**Comment by vanechu** [comment]
文档应该是分了几个部分(3.7 3.8 3.10 3.12),  最后的3.12 分了 a-e 五个部分

**Comment by ghosert** [comment]
@vanechu 邮箱留一个。

**Comment by vanechu** [comment]
vanechu.cs@gmail.com, 已向你的邮箱发过邮件

**Comment by ghosert** [comment]
@Flyfishering 是这样，我往前查了七天的所有数据都没有找到，你还记得最后一次发布是什么时间吗？

**Comment by ghosert** [comment]
@vanechu 现在最新的数据是到21点，22点以后的数据要明天才有，我明天再找，今天找不动了。

**Comment by vanechu** [comment]
@ghosert  非常感谢! 这么晚还在帮忙, 能先把21点的数据发给我吗?   如果可能的话, 能否在明天下午前帮忙再找一下,  因为deadline 在明晚上.  再次感谢!

**Comment by ghosert** [comment]
@vanechu 中午之前应该可以找回来。

**Comment by vanechu** [comment]
@ghosert 先感谢, 真乃业界良心!

**Comment by ghosert** [comment]
我准备开始找了。

**Comment by vanechu** [comment]
@ghosert  期待

**Comment by ghosert** [comment]
你这个标题记清楚了么？还有什么其他关键字？

**Comment by vanechu** [comment]
@ghosert 关键字有如下 "MULTD" "ADDD" "12" "cycles" "Not help" "critical path" "queue"  "3.7" "3.8" "3.10" 等

**Comment by vanechu** [comment]
@ghosert 标题应该就是"Computer Architecture HW3"  不过不是十分确定

**Comment by ghosert** [comment]
好，我再查查。

**Comment by ghosert** [comment]
是昨天晚上十点以后丢的？这些关键字都木油啊。

**Comment by ghosert** [comment]
除了这个时间点，再想一个编辑过的时间点给我。

**Comment by vanechu** [comment]
@ghosert 我都是在线编辑 然后没有点保存的.      能恢复现有最近的一版就行,   昨晚上七八点开始一直在写~

**Comment by ghosert** [comment]
文章 id 还记得吗？

**Comment by vanechu** [comment]
打开这篇显示的是 #103622  不知道是否是ID

**Comment by ghosert** [comment]
mysql> select \* from user_notes where id = 103622;
+--------+---------+---------------------------+----------------------------------------+--------+-----------------+-------------+--------+------------+------------+---------------------+-----------------+---------------------+
| id     | user_id | title                     | details                                | public | publish_details | anchor_list | active | version_id | created_by | created_date        | last_updated_by | last_updated_date   |
+--------+---------+---------------------------+----------------------------------------+--------+-----------------+-------------+--------+------------+------------+---------------------+-----------------+---------------------+
| 103622 |    9510 | Computer Architecture HW3 | # Computer Architecture HW3

---

 |      0 | NULL            | c1qv        |      1 |          8 | chlx       | 2015-05-18 20:41:53 | chlx            | 2015-05-18 20:45:00 |
+--------+---------+---------------------------+----------------------------------------+--------+-----------------+-------------+--------+------------+------------+---------------------+-----------------+---------------------+

**Comment by ghosert** [comment]
最后一次更新是 20：45：00 说明你之后的数据都没有传到服务器上来。你说一直写到十点多是不是断网了不知道。。。

**Comment by vanechu** [comment]
啊... 只有重写了...  谢谢你!   之前写一直都会备份到本地, 这次大意了,  我是看右下角一直有同步成功的提示, 就没有管

**Comment by ghosert** [comment]
好诡异，右下角同步成功，说明连着网，怎么会没有传上来。。。

**Comment by vanechu** [comment]
有没有可能在本地找回呢?

**Comment by ghosert** [comment]
你是客户端还是浏览器

**Comment by vanechu** [comment]
浏览器  Ubuntu 15.04 + Chrome

**Comment by vanechu** [comment]
我之前用developer tool 查了 IndexedDB里内容. 可惜是和线上一样的

**Comment by ghosert** [comment]
内容多不多？先访问 www.zybuluo.com 然后按快捷键
shift+ctrl+i
然后选到这个里看本地数据：
![screenshot from 2015-05-20 15 09 52](https://cloud.githubusercontent.com/assets/236040/7720646/5b9f403c-ff02-11e4-97a4-4d862170a31c.png)

**Comment by ghosert** [comment]
可以用鼠标拷贝复制，那篇文档先别再修改。

**Comment by ghosert** [comment]
注意 base details 这两个字段里的内容就是你本地的文稿内容。如果没了就找不回来了。

**Comment by Flyfishering** [comment]
我想我的应该是找不回来了。
因为我之前点击了撤销发布

**Comment by vanechu** [comment]
对 我就是查了这个,  不过是和线上一样的.  我重写吧,  谢谢啦!

**Comment by ghosert** [comment]
好吧。。。

**Comment by ghosert** [comment]
安全期间，我之后还是加个历史版本的功能，唉。。。

**Comment by catlalalasia** [comment]
我在mac os 系统使用的版本，写完之后按了立即同步，也显示同步完成了，但重新打开软件却是之前的版本？怎么能找到同步的版本呢？在线等，很着急。。。用户名lalalasia
