### ISSUE TITLE
上传图片

### ISSUE THREAD

**Issue by fzbing** [ghosert/cmd-editor#556]
本地图片不能上传.
这个问题还是要解决吧

**Comment by wwzzz11** [comment]
同问本地图片
或者怎么上传也行。。

**Comment by AshitakaAkasaka** [comment]
**本地图片插入**这个功能的确挺有用的。
希望开发这个功能！

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
