### ISSUE TITLE
几点建议与问题

### ISSUE THREAD

**Issue by fangbaiyi** [ghosert/cmd-editor#557]
先肯定一下，软件做得不错，但有几点建议不吐不快：
第一个建议是文章的备份问题，现在软件里面是有导出功能，我且不管他的导出功能好不好用，但貌似没有一键全部导出，等文章一多，更新的频率多了，一篇一篇导出显然是不适合的，最好是能一键导出成chm，有利于离线备份，因为在中国，一个软件一旦稍有些成绩，总不免商业化与收费的问题，毕竟服务器什么的都是要钱的，这个本人理解，但没有本地备份，总有些隐忧存在心里。
第二个建议，希望在全屏编辑界面加入相关的统计信息，如字数什么的，我是用软件写小说的，对于今天写了多少字一般比较关心。

问题请教：
在软件里面空格是用什么标记实现的，如html的空格，那个太烦了。
先这样，我工作去了。

**Comment by ghosert** [comment]
ctrl + alt + i 可以查看字数，其它的后续考虑下。

空格是什么情况，没看懂。。。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
