### ISSUE TITLE
总是提示本地和云端更改不同步

### ISSUE THREAD

**Issue by epiciskandar** [ghosert/cmd-editor#559]
编辑过程中，隔一会就会出现提示，很烦人。当我使用输入法输入一个词语后，它会提示我刚输入的词语和一个空格存在冲突，web端和windows客户端皆是这样

**Comment by ghosert** [comment]
网速的问题，我再修一下，别着急。

**Comment by ghosert** [comment]
又修了一下。你再看看，有问题第一时间再报告。

**Comment by zzy0471** [comment]
> 
> 
> 又修了一下。你再看看，有问题第一时间再报告。

老大，我最近也出现了这个问题，应该不是网速的问题，网速还行
