### ISSUE TITLE
建议增加选中部分的tab缩进功能

### ISSUE THREAD

**Issue by intijk** [ghosert/cmd-editor#56]
就是选中一部分文本（一般是代码），点击Tab，选中部分不是被替换成Tab而是在行首插入一个Tab。对应的，点击Shift+Tab，若行首存在Tab则删除行首的Tab。

**Comment by ghosert** [comment]
光标移到行首然后 Tab 不行吗？你想批量做多行？

**Comment by intijk** [comment]
是的

**Comment by ghosert** [comment]
暂时不妨先在 IDE 里写好再贴过来吧，这样也保证代码在贴过来前是经过调试可运行的。目前有优先级更高的功能要做，需要照顾到更广的用户群。

**Comment by ghosert** [comment]
已支持。
