### ISSUE TITLE
是否可以预览本地的markdown文件?

### ISSUE THREAD

**Issue by samael65535** [ghosert/cmd-editor#563]
就像marked那样的预览器, 虽然Cmd Markdown的渲染和排版很漂亮, 虽然有emacs模式,但是和我用的emacs还是不一样.

marked对我最大的问题就是不能使用各种markdown的插件(比如代码高亮, flowchart)

Cmd Markdown对我最大的问题是编辑器不好使

**Comment by ghosert** [comment]
编辑器其实还可以啊？可以具体说说哪里不好。或者实在不行，先在 marked 里面写好，再贴过来修改。 emacs 应该实现了大多数，我自己用 vim 模式，挺顺的。emacs 我自己确实不大用。

**Comment by samael65535** [comment]
1. emacs 上的Meta键， Cmd Editor上映射的是opt 键，mac上映射的是cmd键，在emacs 里M-w是复制，但到发浏览器里成了关闭标签。

2.对于Cmd editor里的搜索，虽然支持，但是没有mini buffer，所以感觉怪怪的。

3. Emacs模式下不支持全局替换，这个可能也有些不方便。

4. 一般用Emacs写markdown 都会使用markdown-mode，里面有也key-binding之类的没有支持。

其实像emacs 和vim这些东西一旦定制化程度高了，用别人的怎么都会有些不顺。所以想有没有可能像 [marboo](http://marboo.biz/zh_CN/) 可以实时预览本地文件。

一家之言 :)

在 2015年5月22日，14:15，Jay Zhang <notifications@github.com> 写道：

**Comment by samael65535** [comment]
1. emacs 上的Meta键， Cmd Editor上映射的是opt 键，mac上映射的是cmd键，在emacs 里M-w是复制，但到发浏览器里成了关闭标签。

2.对于Cmd editor里的搜索，虽然支持，但是没有mini buffer，所以感觉怪怪的。
1. Emacs模式下不支持全局替换，这个可能也有些不方便。
2. 一般用Emacs写markdown 都会使用markdown-mode，里面有也key-binding之类的没有支持。

其实像emacs 和vim这些东西一旦定制化程度高了，用别人的怎么都会有些不顺。所以想有没有可能像 [marboo](http://marboo.biz/zh_CN/) 可以实时预览本地文件。

一家之言 :)
- 发自 Smartisan T1 -

在 2015年5月22日，14:15，Jay Zhang notifications@github.com 写道：

**Comment by ghosert** [comment]
快捷键冲突可以试试客户端？浏览器本身拦截了很多快捷键。其它太特殊的 markdown binding 之类就没办法照顾了，太个性化了。

**Comment by ghosert** [comment]
已支持打开本地文件。https://www.zybuluo.com/ghosert/note/102771
