### ISSUE TITLE
导出的html能保留css吗？

### ISSUE THREAD

**Issue by c98** [ghosert/cmd-editor#570]
去掉了排版，导出的html有何意义呢？

**Comment by ghosert** [comment]
本来想让别人自己写 css。所以导出的 html 干净点。

**Comment by monolithic** [comment]
我也想要提这个问题。我想文档写好了发布出去给指定的人访问，发现是公开地址的。所以想导出html发给别人，结果发现没有css样式。
另外能不能像网盘一样，文档发布时可以选择完全公开，还是验证码访问

**Comment by yodfz** [comment]
不能保留CSS。。意义何在。。。
你又没提供其他可以编写的东西。
至少你要给一个默认的样式排版吧

**Comment by ghosert** [comment]
木油 css 就是纯数据加标签。是最理想的应用自定义 css 的场景，只不过工作量大点，或者去其它地方抄一个 css 过来，秒用。

**Comment by xiaoyuan0821** [comment]
导出来没有任何样式，真的是丑爆了。。。能不能加一下默认样式，就跟预览的一样就行了~~~

**Comment by ghost** [comment]
预览样式真的挺好的，希望可以提供。

**Comment by c98** [comment]
的确，自动化是非常常见的需求。我现在就是通过 pandoc 导出 html，然后命令行往 html 中插入 css 样式，网上确实有很多 markdown 的 css 资源，尽管作者的这个更棒 :+1 : )

我主要用于自动化工作，将结果以markdown样式的html输出给工作组。

**Comment by ChuckIsReady** [comment]
https://www.zybuluo.com/ChuckIsReady/note/22322
这样就可以导出带有它格式的html了，不过需要自己再清理下sibar什么的。

**Comment by liuzheng9110** [comment]
@ChuckIsReady   https://github.com/mathjax/MathJax  js 应该在这个开源库里面

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
