### ISSUE TITLE
MAC Safari 下网站工具栏图标无法显示

### ISSUE THREAD

**Issue by zhz** [ghosert/cmd-editor#571]
如图，而且感觉safari下加载页面总是卡住。

![snip20150524_4](https://cloud.githubusercontent.com/assets/3191131/7786211/0420f7c4-01f0-11e5-8614-16e1da81b6aa.png)

**Comment by ghosert** [comment]
我这边使用了 font awesome 的字体，你可以去这个网站看看：
http://fortawesome.github.io/Font-Awesome/3.2.1/icons/
理论上你看到的应该也是方框，问题应该在浏览器对字体的显示设置上。你可以 google 下这个问题，看看 safari 下什么设置会导致这个问题。或者下载客户端换chrome，速度，性能会更好。
