### ISSUE TITLE
更新日志和更新版本不一致吗？

### ISSUE THREAD

**Issue by heibai01** [ghosert/cmd-editor#572]
mac客户端总提示升级，点击之后跳转到网页去下载。
百度网盘里的最后修改日期是2015.05.16
但是您自己的变更纪录已经写到2015.05.25了。

**Comment by ghosert** [comment]
不太一样，跳去网页下载是因为客户端主程序升级，变更里的更新是功能更新。一般来说主程序升级可能几个月一次，但是功能更新一两周一次，功能更新不需要升级主程序，你去网页下载一个新客户端那个提示就没了。
