### ISSUE TITLE
能否支持打开本地文件的编写和保存呢？？

### ISSUE THREAD

**Issue by jmychou** [ghosert/cmd-editor#573]
已经习惯了`Markdown`的语法，有时候本地记笔记的时候也习惯于用MD写，所以应该添加支持本地文件编写的功能，赞一个！！:thumbsup:

**Comment by ljxiong313** [comment]
我怎么觉得这个markdown的客户端就是将web端的拿出来，然后做了一个壳子呢？

**Comment by ghosert** [comment]
可以读下这篇看看做了哪些改进：
https://www.zybuluo.com/ghosert/note/90884

**Comment by ghosert** [comment]
已支持打开本地文件。保存之后会用导出的形式来做。
https://www.zybuluo.com/ghosert/note/102771

**Comment by ghost** [comment]
每次都要导出好麻烦啊，难道不能`Ctrl+s`直接保存到原文件吗。。。。  
而且我导出后怎么默认是Unicode编码，都是乱码，得改成UTF-8才能显示。。。。
