### ISSUE TITLE
光标定位问题

### ISSUE THREAD

**Issue by yinxufeng** [ghosert/cmd-editor#574]
一级二级标题，光标放到段落末尾，实际显示确不在末尾，会有字符在光标后面
![image](https://cloud.githubusercontent.com/assets/1935092/7804569/6ad4ab02-0397-11e5-9125-aa6f4e3a59f6.png)

**Comment by ghosert** [comment]
和你自定义的字体有关，最好选等宽字体，实在不行可以下个客户端看看。

**Comment by yinxufeng** [comment]
我用的就是网盘最新客户端，cmd_markdown_win32/64。
不知道跟我分辨率是不是有关系，1920*1080

**Comment by ghosert** [comment]
这样，去网页版，然后看看有没有指定对于任意网页使用自定义的字体，如果有的话，去掉这个选项试试。

**Comment by yinxufeng** [comment]
没有针对网页设置字体，**chrome64** 
![image](https://cloud.githubusercontent.com/assets/1935092/7827430/c72d3a6e-0459-11e5-9b78-adfb90f64132.png)

同一个浏览器对比**stackedit**没有这个问题

**Comment by yinxufeng** [comment]
IE11正常，一级标题光标紧贴着最后一个字，稍微在字上一点点
客户端使用的chrome内核，跟我chrome浏览器上现象一样

**Comment by COOLMASON** [comment]
我也出现了这个问题，可能的原因是我昨天安装了新字体（不带中文），今天打开客户端后编辑的内容就以这种字体显示。
解决方法：1. 删除新安装的字体；2. 不删字体，客户端设置为轻量编辑器。

**Comment by yinxufeng** [comment]
我没有安装字体，默认宋体

**Comment by ghosert** [comment]
字体、字号还有 CSS 都可以自定义了：https://www.zybuluo.com/ghosert/note/378553 试试设置等宽字体就好了。
