### ISSUE TITLE
【强烈建议】增加“同步到印象笔记”功能

### ISSUE THREAD

**Issue by viclab** [ghosert/cmd-editor#576]
【强烈建议】增加“同步到印象笔记”功能
【强烈建议】增加“同步到印象笔记”功能
【强烈建议】增加“同步到印象笔记”功能

**Comment by spsl** [comment]
同感，愿意付费

**Comment by lanshenghai** [comment]
貌似有一个收费软件可以搞定，马克飞象。本人没有用过。

**Comment by lihaiyang** [comment]
需要保存到各种云盘的功能, 至少dropbox先给支持下呗.

**Comment by ghosert** [comment]
嗯，这个都会加，不要着急。

**Comment by ghosert** [comment]
已支持：https://www.zybuluo.com/ghosert/note/102771
