### ISSUE TITLE
win 64 客户端打开后，什么东西都不显示，就是一白板。。。

### ISSUE THREAD

**Issue by zhnuaa** [ghosert/cmd-editor#577]
同样win 64 #481问题
系统windows server 2012r2 x64
不管是32位还是64位客户端面打开直接是就是白板什么都没有。。。
客户端实质上还是需要连接到服务器才能工作？

**Comment by ghosert** [comment]
不完全正确，首次打开需要联网下载一些数据，以后可以断网使用。

**Comment by zhnuaa** [comment]
网络状态改善后成功打开了。但是本地状态不能新建文档也不能打开本地文档？

**Comment by ghosert** [comment]
新建可以，打开本地在做。暂时手工复制一下内容到新建的文档里。
