### ISSUE TITLE
OS X 客户端实现 PDF 导出功能

### ISSUE THREAD

**Issue by boathit** [ghosert/cmd-editor#578]
既然作者已经出了 Mac OS X 下的客户端，能否考虑加入 PDF 导出功能，因为 OS X 系统有内置的 PDF导出功能，添加进客户端应该不难。可以参考 MacDown 的 PDF 导出功能(http://macdown.uranusjr.com/blog/post/4/macdown-023-pdf-and-printing/)

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
