### ISSUE TITLE
建议增加导出为pdf的功能

### ISSUE THREAD

**Issue by Jamestone** [ghosert/cmd-editor#583]
建议增加导出为pdf的功能，且能保持预览的样式，更便于分享。
感谢！

**Comment by Shyujikou** [comment]
支持这个功能，此外还希望增加一个打印视图，方便用户以最终渲染样式打印出来。

顺便，导出HTML建议增加一个选项允许在导出的文件中嵌入CSS样式。

**Comment by harry10086** [comment]
+1

**Comment by LDNN97** [comment]
++1

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
