### ISSUE TITLE
是否可以把客户的md文件同步到github上

### ISSUE THREAD

**Issue by lanshenghai** [ghosert/cmd-editor#585]
这样方便版本管理和导出。
每次编译以后都可以上传上去。编辑的时候可以同步下来。
把github当成一个数据仓库。

**Comment by mytxzz** [comment]
有道理，把github当数据库，那是不是可以支持本地图片了

**Comment by ghosert** [comment]
git push pull 都是进程操作，比较慢，不满足实时要求，而且每次编辑都要存一个状态也没这个必要，版本管理导出会用另外的方式做。
