### ISSUE TITLE
Cmd Markdown问题及建议

### ISSUE THREAD

**Issue by snowsolf** [ghosert/cmd-editor#587]
## 问题
1. 显示视图最下面左右滚动条，在把视图拉倒最底端时出现，而在未到最底时不出现，这个应该不出现的才对吧！
## 建议
1. 黑色主题时选择字段颜色不够明显。
2. 目录及标题加编号，这个觉得挺不要的。
3. 标题变色，阅读的时候背景一个颜色，特别是黑色主题的时候，三四级标题和内容傻傻分不清啊！
4. 添加自定义JavaScript和CSS，作为一个爱折腾的人，强烈要求！！！

**Comment by ghosert** [comment]
出现左右滚动条是因为有部分内容过宽了。

**Comment by snowsolf** [comment]
过宽不是应该有自动换行吗？为什么就无序列表在显示的时候不进行自动换行呢？这个应该可以有吧！@ghosert

**Comment by ghosert** [comment]
列表不宜书写大段文字，表格，序列图，流程图也没办法换行。有空再看看。

**Comment by ghosert** [comment]
已更新，可以自定义CSS了：fhttps://www.zybuluo.com/ghosert/note/378553 流程图序列图可以点击看全屏了。
