### ISSUE TITLE
求添加本地图片

### ISSUE THREAD

**Issue by Jeffrey95** [ghosert/cmd-editor#592]
可以像别的Markdown编辑器那样直接拖入本地图片

**Comment by mytxzz** [comment]
同求，如此这般搭建个个人博客完全不费力了，什么wordpress 啥的，立马显得太low了

**Comment by qinyuanpei** [comment]
呵呵，你看到的是直接拖入本地图片，其实内部需要将本地图片上传到服务器然后返回一个远程图片地址

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
