### ISSUE TITLE
打开本地文件出错

### ISSUE THREAD

**Issue by jmychou** [ghosert/cmd-editor#599]
打开以前的`markdown`文件报错，用`cmd`导出的文件，然后再用`cmd`打开也报错，什么鬼？？？？
![1](https://cloud.githubusercontent.com/assets/8901183/8027129/40c60c62-0dc3-11e5-96de-5378fe039b4d.png)

**Comment by ghosert** [comment]
操作系统说下。用的哪个版本说下，是客户端还是浏览器？浏览器的话哪一个？

**Comment by ghosert** [comment]
好像 windows 上有这个问题，我找时间修下。

**Comment by ghosert** [comment]
已修复。
