### ISSUE TITLE
导出 html 的格式不完整

### ISSUE THREAD

**Issue by ghosert** [ghosert/cmd-editor#6]
### From User:

就是我现在如果导出html或者markdown文件，可能是因为缺CSS文件？所以格式都是不完整的。

有什么办法完整的备份么？

**Comment by ghosert** [comment]
导出的问题本身比较麻烦，因为 css/js 需要单独下载到文件夹，这样你得到的就是一个 html + css/js folder，不太简洁，所以目前只提供一个简单的 html 下载，另外我自己有一些私心，希望文稿更多的在网络上被分享。：） 如果作者只是把它用来当编辑器，而没有分享出来，我会觉得做这个东西的价值就小了很多，但是这个是一个网站和作者之间的博弈，毕竟作者会认为文稿自己导出会更有安全感或者归属感？可以告诉我导出这个需求对于用户的必要性？ 我还需要深入考虑然后决定到底咋么解决导出的问题。

**Comment by ghosert** [comment]
### From User:

非常感谢建议。我理解您的用心，我也觉得这个编辑器是最适合快速的发布和共享文档， 比起自己搭建wordpress要简单很多。

其实导出对我来说，只是想做个备份，一个是怕自己不小心删除了什么东西，又是实时保存，弄丢内容，第二个是怕万一服务器出问题，自己本地有个 备份，不过现在想起来，其实只要把左侧栏的内容拷贝下来，也就可以恢复文档。

**Comment by comzyh** [comment]
css 可以用style 标签内嵌，python-markdown就是这么做的
