### ISSUE TITLE
希望加入“标签”、“上传图片”和“表格”功能

### ISSUE THREAD

**Issue by zzy0471** [ghosert/cmd-editor#60]
标签指文章的标签，加入标签后可以根据标签分组和搜索。上传图片的功能也很实用。虽然标准的markdown没有表格，但是加上的话肯定会很方便使用者的

**Comment by ghosert** [comment]
其它几个都会加，表格目前就支持，看这里：https://www.zybuluo.com/mdeditor?url=https://www.zybuluo.com/static/editor/md-help.markdown#6-表格支持

**Comment by ghosert** [comment]
标签已支持，图片的问题其它issue里提过，这个先关掉
