### ISSUE TITLE
在有序列表后面加入代码样例无效果

### ISSUE THREAD

**Issue by mayaming** [ghosert/cmd-editor#600]
![shot](https://cloud.githubusercontent.com/assets/5228203/8027589/be656c18-0dcc-11e5-866a-fb2a64ee9ff9.png)

**Comment by ghosert** [comment]
列表里不宜嵌入代码段，列表只是给简单的语句使用的。可以自行使用 ##1. xxxx

**Comment by mayaming** [comment]
这个不是在列表里嵌入代码段，而是在列表后面几次换行后插入代码段。此时左边显示的是代码段的样式，但右边显示的不是，一定要在列表和代码段间插入水平线才能让代码段起作用，这个是设计就是如此吗？

**Comment by ghosert** [comment]
噢，那可能是个问题。你先插个水平线解决下吧。
