### ISSUE TITLE
增加快键键支持

### ISSUE THREAD

**Issue by hasibagen** [ghosert/cmd-editor#609]
想问个功能,标题是否可以快捷键,比如ctrl1是h1,ctrl2是h2,以此类推,目前的标题快捷只有ctrlh,而且只有两种,种类太少,一般标题都有好多集,可以增加这个功能么?

或者可以直接支持自定义快捷键么?

**Comment by ghosert** [comment]
直接打字吧，也挺快的 # ## ###
