### ISSUE TITLE
关于高级编辑器的问题

### ISSUE THREAD

**Issue by anngg2008** [ghosert/cmd-editor#610]
1.页面过于卡顿，基本连字都不能打
2.光标键不能用，按光标键没有反应

浏览器:Firefox 38.0.5

**Comment by ghosert** [comment]
请换用 Chrome 或者客户端版本提升性能。如果文稿内有大量 LaTex 公式，也可能造成这种情况，正在改进。

**Comment by ghosert** [comment]
https://www.zybuluo.com/cmd 下载客户端。
