### ISSUE TITLE
·标记的代码内使用$符之后换行就失效了

### ISSUE THREAD

**Issue by cowcomic** [ghosert/cmd-editor#612]
`
$a
$b
`
上面就是例子

**Comment by ghosert** [comment]
$ 是 latex 的一个特殊符号，有 $ 的时候转义一下  \$a \$b

**Comment by cowcomic** [comment]
加上转义之后，阅读模式也有这个转义符。。。。
`
\$a
\$b
`

**Comment by ghosert** [comment]
噢，我看了下。`$a $b` 这类标签内本来就不允许换行。你可以用
```
$a
$b
```

**Comment by cowcomic** [comment]
三个也不行，试了
跟一个效果一样

**Comment by cowcomic** [comment]
哦，好了
原来是我的```没有顶头写。。。。
