### ISSUE TITLE
现在的导出很不错,但是如果能直接保存到本地就完美了

### ISSUE THREAD

**Issue by ChenGuangXing** [ghosert/cmd-editor#613]
感觉cmd-editor是目前所有md编辑工具中最好用的, 没有之一.

不过有很多项目的文档要写, 他们都是以md文件的形式放到github上的, 最方便的方法就是把支持鼠标双击打开和保存文件. 

希望作者考虑一下. 谢谢

**Comment by CoderIvan** [comment]
+1

我也在想办法可以把MarkDown同步至github上

**Comment by CoderIvan** [comment]
#585 我觉得不需要实时同步到GitHub，我个人只需要完成一个里程碑就push一下

**Comment by x8087** [comment]
+1非常需要

**Comment by yichaosun** [comment]
希望能保存本地＋preview的PDF导出，方便打印，跪谢

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
