### ISSUE TITLE
既然出了跨平台客户端，尽量做到本地化

### ISSUE THREAD

**Issue by xirong** [ghosert/cmd-editor#615]
尝试了mac下的客户端，其实仍旧是网页版的功能，我想当做普通的编辑器来，右键打开文件都不能办到，既然要做平台上的客户端，尽量mac、window、linux都有各自的设计，当然这是很费心事的，如果依旧免费，可以将某个版本的开源，大家一块来写，一块做；如果自己做，完全可以尝试收费方式，web版免费，mac、window平台收费，产品做的好，就会有人支持！（也算是一种商业化的尝试）:smile:

**Comment by ghosert** [comment]
右键打开只是没加，暂时可以从其他地方拖拽文本进编辑器就是打开。跨平台只是第一步，后面再陆续改进。
