### ISSUE TITLE
公式导出为html后无法正确显示开根号

### ISSUE THREAD

**Issue by seapex** [ghosert/cmd-editor#619]
图片传不了，如题

**Comment by ghosert** [comment]
发 markdown 的内容过来

**Comment by seapex** [comment]
$$ I_{Th-pu} = \sqrt { \frac {1+P_{EC-Rpu}} { 1+P_{EC-Rpu}\frac { P_{ec} } { P_c } } } \hspace{3em} (3)$$

**Comment by ghosert** [comment]
已修复：https://www.zybuluo.com/ghosert/note/102771
