### ISSUE TITLE
有没有考虑过把Cmd Markdown封装成一个应用软件

### ISSUE THREAD

**Issue by jamesfancy** [ghosert/cmd-editor#62]
比如在Windows下，双击运行，编辑文件，不需要在线保存的。
工作中会遇到一些敏感内容不方便写在Web上的

**Comment by ghosert** [comment]
如果只是作为工具使用，你愿意为这个工具付费吗？我更愿意把一个工具做成一个写作平台。基本上如果你不发布自己文稿，别人无法看到里面的内容，所有内容都加密处理了。

**Comment by jamesfancy** [comment]
加密处理当然好，但是你得获得企业的信任，让企业相信加密之后即使你作为程序的开发者都不能看到文档的内容，当然要企业信任这一点很难。

另外还有一个问题需要考虑的是，所有在线的东西都要求网络稳定，而局域网内部署可以更少这方面的担心。

至于付费……也许企业会，但我不会。如果我愿意付费，我就买MarkdownPad Pro了。

**Comment by ghosert** [comment]
嗯，所以你的回答，解释了我暂时不会考虑单独做一个应用的原因。因为耗时耗力做完以后，用户只是把它作为撰写私人文稿的工具使用，而且还不愿意为这个工具付费。

对于开发者来说，只有两个情况让我愿意持续改进开发。
1. 用户用来撰写私人文稿，愿意为这个工具付费。
2. 用户愿意来这个平台上写作，发布，分享，免费使用。

要么能让开发者吃上饭，要么能让开发者精神上获得满足感。

**Comment by ghosert** [comment]
关于数据安全，其实无关在线或者本地应用。在线应用可以对数据做加密存储处理，本地应用也可以在后台在用户不知情的情况下向服务器发送数据，数据安全完全基于道德准则而不是技术手段。

**Comment by jamesfancy** [comment]
> 嗯，所以你的回答，解释了我暂时不会考虑单独做一个应用的原因。因为耗时耗力做完以后，用户只是把它作为撰写私人文稿的工具使用，而且还不愿意为这个工具付费。

不好意思，我没表达清楚。付费与不付费，关键在于心理接受程度，我都曾考虑过付费购买MarkdownPad Pro，但最终决定没买，原因很简单，我看中的Pro版是支持Github的语法，但问题是我付费购买之后写出来的文档，非Pro版不能正确显示，换句话说，就只能我自己看，而不能跟团队分享，那我买它还有啥意义呢？如果Cmd想收费，我觉得需要考虑这个问题，就好像Adobe Acobat和Adobe Reader之间的关系，什么收费，什么免费，如何让付费用户能达到自己的意图，都需要仔细考虑。

如果老板能正确理解数据安全的问题，那么我们团队可以使用现成的东西，比如Tower.im，我也就不会费尽心思去想咋个分享交流Markdown的问题了。而我之所以问你是否会封装独立运行版本的意思也就是，希望能有一个小范围内使用的Markdown分享工具。.md文件是否在线（指局域网）无所谓，因为有SVN，但用什么写和看Markdown，是个问题。

目前我们仍然是用的MarkdownPad免费版，用最基本的Markdown语法，也还过得去。
