### ISSUE TITLE
在脚注前或后输入空格后，后面的所有字符都会移至下一行

### ISSUE THREAD

**Issue by leonewang** [ghosert/cmd-editor#620]
无空格时
![2015-06-17 23 19 30](https://cloud.githubusercontent.com/assets/7222573/8211045/87da16da-1547-11e5-872d-1bb5daf872eb.png)
在 ‘我是上帝’ 前加一个空格，无变化
![2015-06-17 23 21 35](https://cloud.githubusercontent.com/assets/7222573/8211062/a0fd4812-1547-11e5-8258-aa69eb822ef9.png)
在 ‘‘我是上帝’ 后加一个空格，后面文字换行
![2015-06-17 23 22 24](https://cloud.githubusercontent.com/assets/7222573/8211371/2b18018a-1549-11e5-8b73-7edc0c3c28cb.png)
而在脚注前后添加空格都会导致换行（图省略）

**Comment by ghosert** [comment]
这个是已知问题，但也不影响什么，不要随意加空格即可。。。
