### ISSUE TITLE
标签使用问题

### ISSUE THREAD

**Issue by yutiya** [ghosert/cmd-editor#624]
手动输入 标签: 分类 编辑器没有将其解析成对应的文档，mac客户端下使用反馈

**Comment by ghosert** [comment]
我这边没法重现这个问题，好像都是正常的。有没有全文，发过来看看。

**Comment by yutiya** [comment]
问题已解决，一份文稿只能使用一次标签，重复使用无效
谢谢  
标签功能，属于文档归类，我还以为类似锚标记的功能
