### ISSUE TITLE
win8.1 64位客户端 删除键、方向键经常会失效

### ISSUE THREAD

**Issue by YangShaoyue** [ghosert/cmd-editor#626]
win8.1 64位客户端：
在切换输入法输入内容之后删除键、方向键一定会失效。在英文输入法下，按回车键换行后，删除键、方向键也一定会失效。用alt+tab切换一下窗口或是手动在客户端刷新才能解决这个问题。这个问题还是挺严重的，导致快没法正常使用了...

编辑器做得很好~加油加油

**Comment by ghosert** [comment]
输入法是哪个？
可以换用搜狗输入法看看吗？

**Comment by YangShaoyue** [comment]
用的是必应拼音输入法、微软自带拼音、微软自带英文输入法。用搜狗拼音试了下问题一样，感觉跟用哪个输入法无关，只要任意两个输入法之间一切换就出问题。

**Comment by ghosert** [comment]
你切换输入法的快捷键是啥？

**Comment by YangShaoyue** [comment]
win + 空格

**Comment by ghosert** [comment]
已修复。请刷新页面或重启客户端。先关了，还有问题请重开。
