### ISSUE TITLE
Emacs 模式下,无法共享系统的复制

### ISSUE THREAD

**Issue by anerchen** [ghosert/cmd-editor#636]
随意复制一网址,然后在Cmd Markdown(win)中无法通过Ctrl+y进行粘贴,希望改进!!!

**Comment by ghosert** [comment]
需求太小众，没有精力做。

**Comment by o3o3o** [comment]
同求这个的支持。 记得之前是好使，更新了2.0后，就不好使了。
还有其它的问题： alt_shift+w 复制不能生效

**Comment by songjinghe** [comment]
确实比较小众，现在只能先退出全屏写作模式，然后切换到普通编辑器模式，然后Ctrl-V，然后在切换到emacs编辑模式，然后再进入全屏写作模式。即可～
