### ISSUE TITLE
单个笔记超过几M文本会导致编辑器无法打开并修改的情况

### ISSUE THREAD

**Issue by LichAmnesia** [ghosert/cmd-editor#637]
有大文本的情况下，编辑器就无法打开。同时编辑器无法修改更新那个大文本的笔记

**Comment by LichAmnesia** [comment]
补充：并不是不能修改，而是会打开加载非常慢。

**Comment by ghosert** [comment]
渲染性能已优化，可以再试试。https://www.zybuluo.com/mdeditor#102771
