### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by TaceyWong** [ghosert/cmd-editor#643]
在WIN8环境下正常，换用WIN7，不知为何界面一直是空白，不知是软件是否有什么依赖。

**Comment by ghosert** [comment]
试试 win 32位的版本 https//www.zybuluo.com/cmd 另外首次使用需要联网，之后都可以离线使用。有问题再留言。

**Comment by TaceyWong** [comment]
确实，第一次必须得联网，那几天实验室断网，直接从U盘安装的。感谢你的作品！
