### ISSUE TITLE
可以删除文章

### ISSUE THREAD

**Issue by vsxen** [ghosert/cmd-editor#646]
可以删除文章 必须有啊

还有就是有些时候,右边界面明显比左边慢,不同步,需要刷新才可以

**Comment by ghosert** [comment]
删除有的，点击右上角"新文稿"菜单右边的小箭头。不同步的问题今天下午又改了改，你看看还有没有问题，有疑问再留言。

**Comment by vsxen** [comment]
没有了 很好用
