### ISSUE TITLE
GFM格式的代码块标记，在列表中引用时无法正常处理

### ISSUE THREAD

**Issue by fengyie007** [ghosert/cmd-editor#65]
GFM中```格式的代码块标记在引用时，通过缩进1个或以上空格来保证后续列表不中断，而你的程序无法正常处理，导致无法实现以下Github中的列表显示效果

测试代码如下

``````
1. Always try to use a CDN to include jQuery on your page. [CDN Benefits](http://www.sitepoint.com/7-reasons-to-use-a-cdn/)  
    ```js
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/jquery-1.11.0.min.js" type="text/javascript"><\/script>')</script>
    ```
sdf

1. Implement a fallback to your locally hosted library of same version as shown above. [More Info](http://css-tricks.com/snippets/jquery/fallback-for-cdn-hosted-jquery/)  
``````

在Github中显示效果如下：
1. Always try to use a CDN to include jQuery on your page. [CDN Benefits](http://www.sitepoint.com/7-reasons-to-use-a-cdn/)  
   
   ``` js
   <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="js/jquery-1.11.0.min.js" type="text/javascript"><\/script>')</script>
   ```
   
   sdf
2. Implement a fallback to your locally hosted library of same version as shown above. [More Info](http://css-tricks.com/snippets/jquery/fallback-for-cdn-hosted-jquery/)  

---

你网站上效果截图：

![2014-03-31 4 08 22](https://cloud.githubusercontent.com/assets/241077/2564971/f3033332-b8ab-11e3-8c39-f0b48181b357.png)

**Comment by ghosert** [comment]
我试了一下，你暂时可以把那两行 script 的代码连同 ``` 一起都缩进一下就好了。

**Comment by fengyie007** [comment]
@ghosert 嗯 确实可以。不过现在MarkDown好多标准，感觉好乱啊。你这个是要完全兼容GFM的标准么？

**Comment by ghosert** [comment]
也没要刻意遵守谁，如果用户可以习惯我的，用来实际写东西就好了。如果 Cmd Markdown 流行起来，那就是标准了呗。
