### ISSUE TITLE
按删除键没有反应

### ISSUE THREAD

**Issue by glfruit** [ghosert/cmd-editor#650]
在编辑文本时有时会出现可以输入文字，但是想按退格键删除内容却没有反应的情况，并且出现的频率非常高，大概5~10分钟就会出现一次，不管是桌面版还是Web版都有同样的问题。

**Comment by ghosert** [comment]
输入法是啥？

**Comment by glfruit** [comment]
Mac Yosemite + 百度拼音

**Comment by ghosert** [comment]
已修复。请刷新页面或重启客户端。先关了，还有问题请重开。
