### ISSUE TITLE
有序列表不连续问题

### ISSUE THREAD

**Issue by SteinX** [ghosert/cmd-editor#652]
插入代码块之后有序列表的序号会复位，而插入引用就没有问题.....
有劳作者修复，在此先谢过。

![此处输入图片的描述](http://i1249.photobucket.com/albums/hh512/Gottesgarten/miscellaneous/ordered_list_break.png)

**Comment by ghosert** [comment]
按照 Markdown 语法，尽量不要在列表里放太复杂的内容了。

**Comment by ghosert** [comment]
可以用这种替代： 

```
## 1. 项目1
说明1
## 2. 项目2
说明2
```
