### ISSUE TITLE
不能上传本地图片

### ISSUE THREAD

**Issue by xiaogu-space** [ghosert/cmd-editor#655]
建议开通上传本地图片功能

**Comment by stefory** [comment]
是啊。 这是个相当致命的问题。。居然不能上传本地图片。

**Comment by ted-dev-42** [comment]
要租用服务器来保存图片，成本太高了。

**Comment by rywiki** [comment]
暂时的解决办法就是用微博的图片存储咯，微相册。其实，我觉得还是用自己的路由建站存图片好一点，反正也不是访问量很大吧.imgs.us也还可以

**Comment by stefory** [comment]
只要产品好，适当收费也是OK的。。。反正我个人用着这个编辑器挺舒服的，但是别太贵哦~ 那个马克飞象用着还没那么爽，唯一好处就是自动保存到印象里了，这点可以效仿。

在 2015-07-04 13:03:44，tedjiang notifications@github.com 写道：

要租用服务器来保存图片，成本太高了。

**Comment by Dev-Wiki** [comment]
可以使用七牛存图片

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
