### ISSUE TITLE
希望增加导出为PDF的功能

### ISSUE THREAD

**Issue by ted-dev-42** [ghosert/cmd-editor#656]

**Comment by yichaosun** [comment]
希望能保存本地＋preview的PDF导出，方便打印，跪谢

**Comment by Jack2code** [comment]
+1。有时间就过来溜个圈，看看什么时候支持

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
