### ISSUE TITLE
装载长文给个进度条吧

### ISSUE THREAD

**Issue by rywiki** [ghosert/cmd-editor#659]
今天打开客户端，半天没动静，还以为死了呢。结果是我之前打开了一篇长文。不过，话说才八万多字，也不算长吧。
开始的时候给个进度条我觉得稍微好一些。

**Comment by ghosert** [comment]
有的时候也就是网速慢，稿子能公布出来我看下不？里面放的图片多不多？

**Comment by ghosert** [comment]
现在会放一个正在加载图片的提示。

**Comment by rywiki** [comment]
大约是网速慢吧，新疆这边上网各种诡异。文档纯文字，没图片。话说图片倒是挺快的，主要还是看图床的速度吧。
