### ISSUE TITLE
在编辑区的东西没有被渲染且刷新后消失

### ISSUE THREAD

**Issue by LDNN97** [ghosert/cmd-editor#661]
打开CMD Markdown时，第一次编辑的东西可能不会被渲染和保存，必须刷新一下才行，但之前编辑的东西都会消失。

**Comment by ghosert** [comment]
是某个文档才发生还是都会发生？可否把文档寄送给我 ghosert@gmail.com 编辑区的内容没有还是预览区的内容没有？

**Comment by LDNN97** [comment]
都会发生，编辑区的内容预览区只会显示一部分就不再显示，刷新后之前编辑区有而预览区没有的部分就会消失，也就是那些编辑区有而预览区没有的没有被保存

**Comment by ghosert** [comment]
你的操作系统，浏览器告诉我一下。还有发生这种情况是在编辑的过程中，还是第一次加载完以后？

**Comment by ghosert** [comment]
你的操作系统，浏览器告诉我一下。还有发生这种情况是在编辑的过程中，还是第一次加载完以后？

**Comment by ghosert** [comment]
你的操作系统，浏览器告诉我一下。还有发生这种情况是在编辑的过程中，还是第一次加载完以后？

**Comment by ghosert** [comment]
你的操作系统，浏览器告诉我一下。还有发生这种情况是在编辑的过程中，还是第一次加载完以后？

**Comment by ghosert** [comment]
偶尔发生还是总是能发生？如果是偶尔一般是什么样的情况下发生，主要想问下怎么重现这个问题。

**Comment by LDNN97** [comment]
Win:Chrome 43 Ubuntu Kylin:Chrome 43
是偶尔发生的，多在你新建一个文稿写完一行后出现，如下图：
![](http://i1.tietuku.com/6461ddb9333e6552.png)

**Comment by ghosert** [comment]
已经解决了，你再试试，没问题说下。

**Comment by LDNN97** [comment]
恩，好了 : )
