### ISSUE TITLE
VIM 编辑模式的粘贴问题

### ISSUE THREAD

**Issue by bwangelme** [ghosert/cmd-editor#663]
我使用vim模式编辑时，用yy复制当前行，然后移动到另外一行去粘贴，结果不仅把原有内容粘贴了，还会出现很多的kkkk和jjjjjjjjjj这样的字符。

![cmd_md_qu](https://cloud.githubusercontent.com/assets/11701497/8545493/c0ecdbf2-24e1-11e5-9ca6-e6e8ee9b4682.png)

**Comment by ghosert** [comment]
看看是不是还会发生？浏览器，操作系统说下。因为我没遇到过。

**Comment by bwangelme** [comment]
今天又试了一下，已经没有这个问题了。

我电脑是CentOS6.6 GNome2.28.2，浏览器是chromium 31

还担心我的操作环境太小众了你们解决不了呢，嘿嘿，看好你们哟！

**Comment by ghosert** [comment]
好，暂时关了。
