### ISSUE TITLE
怎么删除和看到自己发布的文章，包括别人发布的文章

### ISSUE THREAD

**Issue by cnlinjie** [ghosert/cmd-editor#664]
怎么管理自己的文章，一些之前的草稿删不掉，点击发布，都不知道发布到哪。别人发布的文章怎么看呢？

**Comment by ghosert** [comment]
注意看工具栏，新文稿旁边有个下拉箭头，点下有删除项。发布就是给你分配一个网址，点网址就是你的文章，把这个网址给别人就可以看，没有网址的人看不到。工具栏上那个发布更新旁边也有个向下的箭头，点下可以找到发布的网址。

**Comment by cnlinjie** [comment]
是我疏忽了，感谢。
