### ISSUE TITLE
无序列表的一个bug

### ISSUE THREAD

**Issue by chadami** [ghosert/cmd-editor#665]
![2015-07-07 11 05 02](https://cloud.githubusercontent.com/assets/8320951/8549441/59ba147e-24fd-11e5-8878-0003a29e46a5.png)

在使用 - 来表示无序列表时，会出现这样的bug

**Comment by ghosert** [comment]
这个不算 BUG， 因为在第三行下面有 - 是指 - 上方的文字是一个二级标题，你继续输入空格+文字就会正常。
