### ISSUE TITLE
Win8.1下使用久了会自动关闭

### ISSUE THREAD

**Issue by biousco** [ghosert/cmd-editor#666]
一个下午都开着写东西，偶尔会突然就关闭了。
但是重新打开的时候内容都还在

**Comment by ghosert** [comment]
是客户端还是 web 版，WEB版的话哪个浏览器版本？输入法说下？

**Comment by biousco** [comment]
抱歉没说清楚
客户端版v2.0 
使用系统自带的输入法
电脑是笔记本 64位win8.1 系统一直保持自动更新
最近才出现的
有外接21寸的显示器 笔记本装了ssd但是客户端装在机械硬盘上

**Comment by ghosert** [comment]
在其它电脑上会有这种现象吗？你的系统稳定吗？内存是否够？

**Comment by ghosert** [comment]
每天都会发生还是每隔几天发生还是如何？

**Comment by ghosert** [comment]
还是就发生一天，但是发生了几次？重启有效吗？

**Comment by biousco** [comment]
只在自己的电脑上用过作业部落
系统挺稳定的 
闪退这两次都是我在看书做笔记的时候发生的 就看一小节打一些字 当时没有在干其他事 内存应该足够
文章里有用到html的表格标签 用了大量的列表 文章大概3000字
之前用来写博文就没有这个问题

**Comment by biousco** [comment]
发生了三天 每天2次左右 都是看书做笔记的时候 就是长时间打开 时不时往上面敲字
而且都是发生在我打字的时候 打了一串拼音客户端就突然没了

**Comment by ghosert** [comment]
输入法是哪个？这个很重要。

**Comment by biousco** [comment]
Win8.1自带的默认输入法
昨天又出现了。不过当时是打开放在那里，没有打字，在看书的时候自动关闭了

**Comment by ghosert** [comment]
是同一篇文档还是，其它文档都会这样？

**Comment by biousco** [comment]
最近写的三篇文档会出现。同一篇文档出现1~2次退出

**Comment by ghosert** [comment]
我这边也试试开一整天看看。你可以尝试去资源管理器里复制粘贴回车这个：  %LOCALAPPDATA% 然后删掉 Cmd Markdown 的文件夹，然后再重新启动 Cmd Markdown 看看还会不会这样。

**Comment by biousco** [comment]
好。下午我也继续用。

**Comment by ghosert** [comment]
幷未出现，WIN8下也做了更新，请最近两天再观察下，有问题再重开这个问题，先关了。

**Comment by biousco** [comment]
OK
