### ISSUE TITLE
关于vim模式的建议

### ISSUE THREAD

**Issue by bwangelme** [ghosert/cmd-editor#669]
请问一下vim模式能不能添加一个laststatus=2的选项，这样最地下就能出现一个状态栏，显示文件名以及列号了，就像这张图一样：

![cmd_md_vim](https://cloud.githubusercontent.com/assets/11701497/8594583/a857dd64-2674-11e5-8a4d-5dd7a44f3f06.png)

**Comment by ghosert** [comment]
此类小众需求暂时没有精力做了。
