### ISSUE TITLE
文本量大时，输入HTML起始标签后卡死

### ISSUE THREAD

**Issue by satgo1546** [ghosert/cmd-editor#670]
例如在沙箱页面中的开头输入`<b>`，然后就会死机一段时间。因为它没有结束标签，所以就一直会加粗到文本末尾。由于Cmd Markdown是实时渲染的，所以如果不及时打上`</b>`它就会去渲染整个页面的粗体，导致死机。

**Comment by ghosert** [comment]
你是 chrome 浏览器吗？沙箱页面是指那篇欢迎文稿吗？我这里没有卡死啊？但是这样做确实会让部分渲染的算法失效，因为整个页面的内容都发生了变化。

**Comment by satgo1546** [comment]
确实是Chrome（偷懒用了世界之窗封装的版本，31.0.1650.63）。沙箱就是Cmd Markdown 简明语法手册。文本量越多卡死越厉害，不过也可能和别的因素有关。我随便弄了一点测试文字（约100000字），输入标签后卡死了10秒。

**Comment by ghosert** [comment]
可否试下正版chrome，最新chrome版本也已经43了，你这个略旧。机器性能如何？十万字也太夸张了，沙箱我没问题。
