### ISSUE TITLE
如果中文输入法状态下能在vim的normal模式下识别按键就更好用了。

### ISSUE THREAD

**Issue by li360** [ghosert/cmd-editor#672]
建议，如题。

> 另：和win8的自带输入法有点不兼容，我更换了`小狼毫`输入法兼容性好了点。

**Comment by ghosert** [comment]
这个好像原生 gvim 也没做到吧？

**Comment by li360** [comment]
哦，我的 vim 好像改过，时间长忘记了。使用的时 esc 后直接没有输入法了，insert 模式自动换回输入法。
也许 `cmd-markdown` 可以接收到 `esc` 后能够模拟按一下 `shift` ， 我不知道这样是否可行，只是猜测。

**Comment by ghosert** [comment]
暂时先这样吧。

**Comment by sumbrilliance** [comment]
按一下esc会切回输入法，期待这个功能。

**Comment by ghosert** [comment]
我一般都是直接在中文状态下直接按一下 shift 就切换到英文了，然后 VI 的快捷键都能用了。在按一下 SHIFT 到中文编辑。
