### ISSUE TITLE
使用win8.1自带的微软拼音输入法输入中文的时候出现bug

### ISSUE THREAD

**Issue by Dounm** [ghosert/cmd-editor#673]
微软拼音输入法在输入的时候就会在文本上显示拼音，选词后拼音被替换为中文。
但是作业部落里选词后，拼音不会消失，而中文却没有出现。希望开发者能够修复一下bug

**Comment by ghosert** [comment]
暂时先用第三方输入法用下。

**Comment by ghosert** [comment]
或者不要使用 IE 浏览器也没这问题。
