### ISSUE TITLE
PDF导出打印＋本地存储

### ISSUE THREAD

**Issue by yichaosun** [ghosert/cmd-editor#679]
PDF导出打印＋本地存储：这里指的是preview编排好的格式，跪谢～这样才不仅仅停留在仅仅在线页面显示。。。。。

**Comment by yichaosun** [comment]
每天都过来看一看，顶一顶

**Comment by ghosert** [comment]
执念好强。

**Comment by SubLuLu** [comment]
>  `yichaosun commented 3 days ago`
> PDF导出打印＋本地存储：这里指的是preview编排好的格式，跪谢～这样才不仅仅停留在仅仅在线页面显示。。。。。 

👍🏻

**Comment by progmboy** [comment]
+1

**Comment by Jack2code** [comment]
+1

**Comment by KerwinChen** [comment]
+1

**Comment by freeaquar** [comment]
+10086 顺便说下,用chrome自带的转pdf分页不是很满意

**Comment by StosenXiao** [comment]
+1008611，万般希望出转换pdf，这样我就能帮你大力宣传了。

**Comment by Hoooxz** [comment]
在等导出PDF

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
