### ISSUE TITLE
希望增加检索功能

### ISSUE THREAD

**Issue by qinf** [ghosert/cmd-editor#68]
有些东西写完就忘了，希望能增加检索功能(全文检索就更赞了)。也可以支持标签功能，方便快速查阅。

**Comment by ghosert** [comment]
标签和标题的检索在做，下周可以发布，全文还需要点时间。

**Comment by ghosert** [comment]
已支持

**Comment by liuyongming0612** [comment]
全文检索支持了？？？

**Comment by liuyongming0612** [comment]
没有全文检索，一旦文章和内容多了之后，想找点东西太不方便了，人的记忆是模糊的，需要根据一些关键词找到之前的记录，不然笔记就没有存在的必要了。估计很多人都会有这个感觉，这是痛点
