### ISSUE TITLE
Chrome使用划词翻译插件后，编辑区会一直显示翻译按钮

### ISSUE THREAD

**Issue by armink** [ghosert/cmd-editor#681]
## 现象

 ![图片](https://dn-coding-net-production-pp.qbox.me/596f7a69-4731-4da2-9fd7-6c32cb265e86.png) 

如图所示，正常只有选中某段文字才会显示翻译按钮，但是在编辑区，我的鼠标移动到哪，翻译按钮就会在哪追加，非常影响用户体验。

碰到这个问题，我有对比
- 马可飞象
- Mahua
- StackEdit
- CSDN博客编辑器

这些在线MD编辑器都没有这个问题
## 划词翻译插件
- 名称：划词翻译
- [【插件地址】](https://chrome.google.com/webstore/detail/%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/ikhdkkncnoglghljlkmcimlnlhkeamad)
## 谷歌浏览器
- 版本：43.0.2357.132 m

**Comment by ghosert** [comment]
我们使用的编辑器功能较丰富，你划右边预览区不行吗？

**Comment by armink** [comment]
@ghosert 我压根就没有划词，只要光标在编辑区就会有这个问题。

**Comment by ghosert** [comment]
可否暂时停用下？因为这种 CASE 太少了。

**Comment by armink** [comment]
只能这样了。虽然Case少，但我觉得也不应该把这个issue关掉。

**Comment by ghosert** [comment]
实在花不了时间处理了，不好意思。
