### ISSUE TITLE
客户端切换文章的时候能不能不要同步

### ISSUE THREAD

**Issue by nus1998** [ghosert/cmd-editor#683]
慢死了, 虽然我的网速是100M专线

用客户端的, 基本不会再去网页编辑, 除非换了电脑, 所以客户端只要在打开的时候刷新下就可以了. 至于切换文章, 既然用户可以设定30分钟同步, 那么只需保存到本地就好了, 等30分钟时后台自动更新就好

**Comment by ghosert** [comment]
慢不是因为同步，因为同步不会重复上传下载文稿，只处理和服务器不同的部分。感觉是你的电脑和服务器之间比较慢，是否可以换其它地方电脑试下？

**Comment by nus1998** [comment]
虽然作业部落的带宽应该不大(响应也比较慢, 用网页的方式看起来的), 不过这个问题可能跟它无关, 也跟渲染无关. 我新建两个文稿(无任何内容), 断开网络, 切换这两个文稿的时候, 也会白屏(最上面的工具栏保持灰色, 工具选项全部消失) 2~3秒钟. indexed db性能没有这么渣吧?

**Comment by ghosert** [comment]
我说句实话，要是这样的话，是不是该换电脑了？我这里都是秒切啊。

**Comment by nus1998** [comment]
好吧, 虽然cpu是渣了点, 才3GHZ双核, 内存也就8G, 不过一个编辑器的文稿切换速度(就一行标题, 来回切换, 还不是第一次)居然比打开个新浪/淘宝首页还慢...我也是醉了

**Comment by ghosert** [comment]
所以我让你换台电脑试试啊，和你说了秒切啊。看看是不是系统的问题啊啊。

**Comment by nus1998** [comment]
换了一台电脑, 用手机录了下(应该是25帧/秒), cmd客户端切换文稿白屏35帧, 输入淘宝网址到屏幕显示网页(包括图片, 不在屏幕范围内部分不知是否下载完毕) 45帧, 好吧, 算是正常吧

**Comment by nus1998** [comment]
另: 两台都是win7 x64. 印象的文稿切换完全看不到延时(估计3帧以内), 即使leanote也跟印象几乎相当. 以收费为目标的话, 这个体验确实差了点.

**Comment by ghosert** [comment]
切换文档并不是常见用例，常见用例是编辑和渲染。印象切文稿快了，它的编辑很弱。同步也根本没带智能合并的算法啊。给你简单粗暴的覆盖了。客户端在底下做了什么事情可以参见这篇：https://www.zybuluo.com/ghosert/note/90884

何况也没收费。倒贴两年业余时间和上万资金买服务器。你这文风都是渣啊，醉啊，我很难没情绪。

**Comment by nus1998** [comment]
我说渣和醉, 只是因为你根本就不知道我的电脑如何就说该换了然后直接把issue close了. 如果说是因为"indexed db性能没有这么渣吧", 那么我道歉, 就我自己看来前两post应该没有冒犯之处, 仅仅是提问题而已, 如果有, 再次说抱歉.  无论如何, 为导致你情绪不好说抱歉.

说到收费, 在这个主题之后我本来想发个建议, 提议你针对单项功能搞众筹,  比如本地图片/附件, pdf导出等. 用户交的众筹费用可以考虑作为以后年费的(部分)抵消. 不过目前看来, 在我这边几台电脑试来, 白屏至少1秒的体验确实不好, 你就是让他无响应1秒等背后做完工作再切换都好(当然这个又要时间). 另外有时打开时就白屏在那里超过10多秒都没有响应, 这个也许也是我系统个例, 不过理解你目前状况, 如果没有多数用户抱怨的话, 切实干点其他事情更有效率.

我觉得如果印象支持md(以及语法高亮/公式等扩展), 那根本就没其他类似软件的空间. 至于你说切换文档不是常见用例, 我的做法是自己记录下一些资料, 然后经常要回去看(切换倒是经常的, 编辑就一次), 可能我跟cmd的主流用户不同吧, 只好再去折腾下其他的note taking, ^_^

**Comment by ghosert** [comment]
编辑的时候用客户端，只是为了查看在 WEB 上多开几个 TAB 就行了，切换 TAB 总不慢了，所以才有编辑和阅读模式两种。如果可以发布，发布出去以后在发布页面看更快了。因为连编辑器都没了。

我关这个是因为你说能不能不要同步，不要同步的理由是切换慢，但是实际上切换慢不是同步造成的，所以除非有其它理由，否则切换同步还是保留。基于此，这个 ISSUE 就可以关了，因为标题已经不合适了。如果觉得还是要改进切换慢，可以再发 ISSUE。而且也没其它人报所以我确实有可能做其它更重要的事情。

你自己也试出来了大多数机器1秒，我和你说换机器也没说错。印象收集收集资料就好了，编辑器有什么好说的。它过一百年也不会做这种小众市场。

你第一个 POST  里第一句话我已经不 HAPPY 了。我忍住给你回答，结果还来个渣，扯以收费为目标，你也知道我免费在做，辛苦解决问题，这种态度我有什么心情。
