### ISSUE TITLE
发布文章，导致本地文字丢失

### ISSUE THREAD

**Issue by chenlai** [ghosert/cmd-editor#684]
洋洋洒洒写了1000多字，点发布，一下子就没了，找都找不回，痛苦啊，到底怎么回事。
估计是字数限制的原因。

**Comment by ghosert** [comment]
网友们这种误操作还是很多的，但是我可以帮忙找找看。文章标题说下。

**Comment by ghosert** [comment]
字数没限制。很多人写一两万也没问题啊。

**Comment by chenlai** [comment]
可能当时网络也有问题，提交了很长时间，后来记得就点了一下确定。发现就剩下半个小时之前的文字了。后来文字没了，就撤销发布了。
我重新发布了一下，只剩下题目了
地址：
https://www.zybuluo.com/chenlai89/note/134277

题目是　　关于优衣库试衣间事件思考

**Comment by ghosert** [comment]
我这里看了下，好像写到一百来字的时候，客户端那边就没上传新的内容过来，是不是期间断网了？然后在断网状态下你又点击了发布，导致提交很长时间。感觉发布，撤销一连串动作之后，又编辑了下内容把本地写好的那个1000多字也弄丢了。

因为文字没到服务器上，无能为力了，下次加个历史记录的功能吧。
