### ISSUE TITLE
发布以后丢失了部分变更

### ISSUE THREAD

**Issue by LazyLei** [ghosert/cmd-editor#686]
不太确定跟发布有没有关系，发布完最新版本以后换了电脑登陆，发现笔记里的数据变成了一个比较老的版本，发布的内容还是最新的

**Comment by ghosert** [comment]
暂时从发布的页面再拷回来整理下把。换电脑登录，理论上会做同步。

**Comment by LazyLei** [comment]
不是的，第二次登陆的电脑上没有做过编辑。编写工作都是在前面一台电脑上做的

**Comment by ghosert** [comment]
我知道😊 发自网易邮箱大师 在2015年07月17日 11:39 ，LazyLei写道： 不是的，第二次登陆的电脑上没有做过编辑。编写工作都是在前面一台电脑上做的 — Reply to this email directly or view it on GitHub.
