### ISSUE TITLE
Vim 模式下切换输入法导致进入 command mode

### ISSUE THREAD

**Issue by LnLou** [ghosert/cmd-editor#687]
我用 ahk 把 ctrl + space 改成了 win + space。在其他编辑器中可直接用 ctrl + space 切换中英文。在 cmd-editor 中 ctrl + space 会进入 command mode，导致无法输入中文（中文输入法下不能回到输入模式，英文输入法下一旦切成中文输入法就会又进入控制模式）。

可能是 vim 模式的切换包括了 esc 以外的键？希望可以自定义，谢谢！

**Comment by ghosert** [comment]
最好还是不要HACK键位，这样的 CASE 比较少，我也有心无力了。
