### ISSUE TITLE
纯粹的离线编辑

### ISSUE THREAD

**Issue by kkpapa** [ghosert/cmd-editor#688]
在一些情况下，希望能够有纯粹的离线编辑，也就是说希望可以编辑本地文件而不需要登录，也不希望这些编辑的本地文件被自动同步到服务器上。自动同步大多数时候是希望的功能，但某些情况下希望能够不使用同步，比如公司有相应的安全策略，不允许将工作相关的文档同步到外部服务器上。

纯粹的离线编辑功能(不需要登录，不自动同步)可不可以提供？

**Comment by ghosert** [comment]
这个编辑器从在线发展而来，目前还是在线优先的原则，因为确实很多功能需要服务器，譬如同步，云存储。安全上的顾虑可以理解，目前只能全凭互相之间建立的信任了，不过两年来应该没发生过任何安全事故。

**Comment by ghosert** [comment]
离线文稿可以读写本地文件了。https://www.zybuluo.com/ghosert/note/378553
