### ISSUE TITLE
这个是不是编辑器实现bug？

### ISSUE THREAD

**Issue by qinf** [ghosert/cmd-editor#69]
如图
![2014-04-05_093311](https://cloud.githubusercontent.com/assets/1277293/2621698/b5fe02fe-bc62-11e3-96fd-d74843616410.png)
左侧列表1，2，3，但是右侧没有第3个

**Comment by ghosert** [comment]
建议嵌套层次不要太多了，你可以把“问题描述”那行删掉，或者留个空行在那行后面试试。

**Comment by qinf** [comment]
还是不行的
