### ISSUE TITLE
Queue<T>不能显示<T>

### ISSUE THREAD

**Issue by hdkn235** [ghosert/cmd-editor#691]
< T > 是有什么特殊语法吗？

**Comment by ghosert** [comment]
<T> 被认为是 HTML 了，你可以用在前面加四个空格以
段落的方式显示。

**Comment by hdkn235** [comment]
找到解决方案了将`<`替换成 `&lt;` 就可以了，这个应该是Markdown的基本语法，在 (Markdown 语法说明 )[http://wowubuntu.com/markdown/] 可以看到
