### ISSUE TITLE
highlight code

### ISSUE THREAD

**Issue by wxx422** [ghosert/cmd-editor#694]
Dear Author:
        Thank you very much for such a wonderful markdown tool, and I like it very much. As for code highlight, will you support vim scheme, for example, monokai (https://github.com/Voidly/voidy-Vim/blob/master/colors/monokai.vim, looks like sublime text). Thank you very much.

**Comment by ghosert** [comment]
有截图吗？

**Comment by wxx422** [comment]
![image](https://cloud.githubusercontent.com/assets/5442237/8777401/541b74ea-2f2a-11e5-817f-59021af15893.png)

**Comment by wxx422** [comment]
![image](https://cloud.githubusercontent.com/assets/5442237/8777524/0e10729c-2f2b-11e5-81ed-3e396cdb7c18.png)

**Comment by ghosert** [comment]
好像和 Cmd Markdown 的黑色主题差不多嘛。

**Comment by wxx422** [comment]
这个是cmd markdown的黑色主题，和第一张图对比一下，在色彩上还是有些区别的。不知道能不能支持主题的配置，就想vim可以用其他的配置文件配置主题一样。此外，cmd markdown导出HTML的时候，HTML中的code部分是没有颜色的效果的，这个是我哪里没做对还是本身就是这样。
![image](https://cloud.githubusercontent.com/assets/5442237/8778068/4f9116e2-2f2e-11e5-80ee-82472701312b.png)

**Comment by ghosert** [comment]
导出带样式是在做，完全匹配别人的主题这个需要花费的精力太大，每个人的审美观也不一样，就不做了。不开放主题还有一个原因是想统一站内文稿的样式。

**Comment by wxx422** [comment]
好的，谢谢你耐心的解答。祝愿cmd markdown越做越好
