### ISSUE TITLE
Cmd Markdown web版应用嵌套问题

### ISSUE THREAD

**Issue by sdc6882278** [ghosert/cmd-editor#696]
引用多层嵌套的时候有些问题
![cmdm](https://cloud.githubusercontent.com/assets/5699389/8793410/b90efc72-2fa8-11e5-98b5-15de8c140268.png)
左侧的第二个二级引用，与第二个三级引用 均比他们的第一个多了 >.
理论上应该是 一级引用 > 二级引用 >> 三级引用 >>> ,不管他们是区块的第几个引用都应该如此，不晓得这个是设计如此，还是Bug。
平台 linux 4.1 chrome 43.0.2357.134 (64-bit)

**Comment by ghosert** [comment]
具体我也没想过这种复杂嵌套的情景，目前这个效果完全是代码意外渲染出的效果，我没有设想过。

**Comment by sdc6882278** [comment]
在引用嵌套和嵌套无序列表会有奇奇怪怪的问题出现，比方说下图在一级引用里面无序列表如果带“>”标识会失效，而二级引用里面带“>>”则不会失效，解决方法是删掉一级引用开头的粗体。
![image](https://cloud.githubusercontent.com/assets/5699389/8816229/90499104-3056-11e5-8506-ecc77863120f.png)
与之类似的即使没有复杂的嵌套，引用开头的粗体会影响到后面的无序列表。
![image](https://cloud.githubusercontent.com/assets/5699389/8817755/00ed39f2-306a-11e5-88ff-33018270e772.png)

**Comment by ghosert** [comment]
有序列表和无序列表里暂时不要加入复杂嵌套了，按 MARKDOWN 语法，列表应该只包含简单的文本内容。如果实在需要包含复杂的内容，可以使用下面这种方式：

```
### 1. xxxxx
       fffffffff
### 2. yyyyy
       fffffffff
### 3. zzzzz
       fffffffff
```
