### ISSUE TITLE
导出html在浏览器中显示效果没有编辑器效果好

### ISSUE THREAD

**Issue by suninrain086** [ghosert/cmd-editor#697]
导出的html在浏览器打开并没有代码的语法高亮？ 

并且效果比在编辑器中差多了……

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938

**Comment by suninrain086** [comment]
高级会员这点服务，还按年收费，有点贵啊。。。

2015-09-15 21:07 GMT+08:00 Jay Zhang notifications@github.com:

**Comment by ghosert** [comment]
噢，基础服务诚意满满的，包括高级会员的成本压力不小，过后会不断继续增强，有需求提。 Regards, Jiawei Zhang 在2015年09月16日 09:57 ，曾亮写道： 高级会员这点服务，还按年收费，有点贵啊。。。 2015-09-15 21:07 GMT+08:00 Jay Zhang notifications@github.com: > Closed #697 https://github.com/ghosert/cmd-editor/issues/697. > > — > Reply to this email directly or view it on GitHub > https://github.com/ghosert/cmd-editor/issues/697#event-409760046. > — Reply to this email directly or view it on GitHub.

**Comment by suninrain086** [comment]
好吧，我的邮件你们都能及时回这点我还是挺满意的 ：） 也祝软件越做越好！

2015-09-16 14:00 GMT+08:00 Jay Zhang notifications@github.com:
