### ISSUE TITLE
看到作业部落后很惊喜,提几个问题

### ISSUE THREAD

**Issue by sunminghong** [ghosert/cmd-editor#7]
1\如何支持在手机上用(我用了,基本不能用)
2\插入图片可以考虑上传后在填到markdown吗?

**Comment by ghosert** [comment]
1. 本身打算主要是给编辑文字用，所以放弃支持手机了，码字的时候打键盘会快一点：）， 但是文稿发布以后分享给别人的链接是对手机做了优化的，可以被别人读到。所以基本上，写的时候用电脑，读的时候可以用手机。
2. 图片上传比较消耗服务器，但是肯定会做，目前先放一下。

**Comment by PearlEast** [comment]
请问是用python写的吗?

**Comment by ghosert** [comment]
对，不过实际上 JavaScript 代码比 Python 多很多

**Comment by ghosert** [comment]
已经可以上传图片了，手机上暂时只能看看别人发布的文稿。不能写。
