### ISSUE TITLE
希望能自訂 markdown 線上顯示時的 CSS

### ISSUE THREAD

**Issue by amoshyc** [ghosert/cmd-editor#70]
目前線上顯示時的字體大小、英文字體皆不是很滿意，希望能自訂，謝。

**Comment by ghosert** [comment]
英文字体下一个版本会改一下，你觉得哪个比较好，字体希望大一些还是小一些。你显示器多大？

**Comment by amoshyc** [comment]
英文字體的話，我希望起碼能有 Times New Roman 或 Arial，怎麼說這也是較常使用的字體。
至於字體我希望能大一點，我的顯示器是 1600x900，畫面上的英文字看起來大約只有 10, 11px 而已。（我想這很可能是我自己電腦的問題，我平常 chrome 都是開縮放 150% 在看網頁，但使用 Cmd Markdown 時這樣會導致上方工具列排版產生錯誤，所以我在這網站時都縮放 100%）

另外，我想請問，以後可能開放自訂主題嗎？

**Comment by ghosert** [comment]
字体我目前选的是 16px，已经相当大了，你可以检查一下设置。

目前是想提供一个用户都满意的排版，对大多数用户开放自定义反而会导致排版混乱。

对于高级用户以后或许可以提供一些自定的主题。

**Comment by ghosert** [comment]
已更新，可以自定义字体字号CSS了：fhttps://www.zybuluo.com/ghosert/note/378553
