### ISSUE TITLE
windows 64位桌面版无法使用

### ISSUE THREAD

**Issue by Jack2code** [ghosert/cmd-editor#700]
解压后，运行`Cmd Markdown.exe`，启动了三个进程，然后只有一个`node-webkit`的对话框，空白的，啥都没有。
是我打开的姿势不对？

PS：我的是Windows 7 64bit

**Comment by Jack2code** [comment]
补充一下，是Windows 7 64位。

**Comment by ghosert** [comment]
有些机器是有这个毛病，你试试 Win32 那个版本的 CMD MARKDOWN 试试，有人就这么解决了。

**Comment by Jack2code** [comment]
其实是公司网络有代理的问题。
不管是32位还是64位都无法正常使用，而我在家里的电脑是OK的。
CMD在不能访问外网的情况下就显示为一片空白？能不能提供一些错误页面？例如：404、500？

**Comment by ghosert** [comment]
噢。。。原来是没网络，假设是有网络的，那我先关了。
