### ISSUE TITLE
作者大大快来,发现一个核弹级大bug !!!

### ISSUE THREAD

**Issue by tianxiayu007** [ghosert/cmd-editor#704]
建立bat1,内容如下:

> @echo off
> set PATH=%~dp0\bin;
> start cmd

建立bat2,内容如下:

> @echo off
> start cmd

虽然两个`bat`文件差不多,但运行结果差距巨大:
bat1现象:打开的是markdown的编辑器!!!! 并且即使我改了markdown的执行文件名称或者改了其所在的文件夹都是这个现象,我的天,markdown是怎么找到自己所在位置然后执行的???哪里加了系统服务吗??`cmd`这3个字母已经被施展了魔法,如果改成`cmd.exe`那就一切正常..或者将这个bat放到不是`用户桌面`的地方也行...
bat2:一切正常
看起来真不知道哪个地方搞的鬼啊.. 而且cmdmarkdown在C:\Users\用户\AppData\Local 目录下有非常大的配置文件,快40兆了,一点都不绿色啊....
现象录制如下:[百度网盘](http://pan.baidu.com/s/1gdJCYlH)

**Comment by tianxiayu007** [comment]
应该是编辑器在注册表里写了什么数据影响了cmd..找不到..现在把cmdmarkdown卸载后`start cmd`提示拒绝访问..真不知道哪 个键值出了问题啊

**Comment by ghosert** [comment]
AppData local 下面那个目录可以删，相当于删除了本地数据。重启应用后会再生成，这个目录因为保存里你的所有本地数据还是蛮重要的。至于其它问题，等我细看，好像都是你改出来的问题？

**Comment by tianxiayu007** [comment]
基本上没改动什么...上面也不算什么bug哈,大惊小怪了...应该就是软件影响到了注册表...很神奇的是改动程序名目录名依然能被找到并启动...清下注册表就可以了..大费周章啊..希望软件更加绿色化..别把配置整到用户目录了..

**Comment by ghosert** [comment]
数据配置进用户目录是底层开源框架做的，我看看能不能改，不能改就加个清理按钮好了。

**Comment by crysiswen** [comment]
要是我卸载了不会影响cmd的使用吧

**Comment by ghosert** [comment]
不会。
