### ISSUE TITLE
导出的HTML与页面显示的不同

### ISSUE THREAD

**Issue by cqzhao** [ghosert/cmd-editor#712]
导出的HTML很多格式都没有了。很不好看，怎么破

**Comment by Lingzo** [comment]
如何原样导出 HTML啊 ， 能不能提供直接PDF 打印出来，

**Comment by cqzhao** [comment]
**设置**的那个按钮里有啊。

**Comment by cenxun** [comment]
希望导出的html带上样式

**Comment by tanxd2002** [comment]
这个问题很严重！导出的HTML没有样式，表格都没了。

**Comment by tanxd2002** [comment]
这个问题很严重！导出的HTML没有样式，表格都没了。

**Comment by ted-dev-42** [comment]
确实这样的，在编辑预览界面多好看啊，一导出就变得惨不忍睹了。

**Comment by Hoooxz** [comment]
如果可以直接导出PDF就可以解决这个问题了

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅并支持我们：https://www.zybuluo.com/ghosert/note/167938
