### ISSUE TITLE
在編輯模式下，開啟閱讀模式的快捷鍵（Ctrl + Alt + M）沒有作用

### ISSUE THREAD

**Issue by amoshyc** [ghosert/cmd-editor#72]
在編輯模式下，開啟閱讀模式的快捷鍵（Ctrl + Alt + M）沒有作用，但主題切換（Ctrl + Alt + J）及全屏（F11）可以使用。

不太理解這樣的界面邏輯，那一排工具列是只在預覽模式才有作用嗎？還是編輯模式及預覽模式都能使用？

**Comment by ghosert** [comment]
当时的考虑是阅读模式和写作模式的过度一定要通过预览模式，确实没有考虑你这样的使用情况。标记为功能增强。

**Comment by ghosert** [comment]
已修复
