### ISSUE TITLE
保存到网盘

### ISSUE THREAD

**Issue by upad** [ghosert/cmd-editor#73]
可不可能自动保存dropbox、box、百度国内外的网盘（指定目录下）或evernote、wiz笔记软件呢？这样可以省掉备份到本地，像box、wiz中又方便网盘/笔记内的交流。

**Comment by ghosert** [comment]
就保存在 Cmd Markdown 的网站上有什么问题吗？我试图提供一站式的解决方案。保存到网盘，一个会增加开发工作量，第二，我也不清楚网盘的可靠程度，是不是会被墙。

**Comment by shjanken** [comment]
我觉得就保存在cmd上挺好。如果需要保存到其他网盘上可以使用导出么。

**Comment by ghosert** [comment]
如果真的需要保存到第三方的功能，以后会作为高级会员功能推出。

**Comment by huyinghuan** [comment]
我以前都是使用https://stackedit.io/ 来写文档的。可以同步到dropbox。觉得这点比较好

**Comment by ghosert** [comment]
暂时没有此计划，希望大家谅解。
