### ISSUE TITLE
产品建议

### ISSUE THREAD

**Issue by simonkuang** [ghosert/cmd-editor#735]
作为一边网络查找资料、一边记录整理的码农，希望能有一个 chrome extension 版本的“作业部落”，这样的话在一个打开了十几二十个窗口的 chrome 中才不用麻烦地来回切换。

**Comment by simonkuang** [comment]
从[另外一个issue](https://github.com/ghosert/cmd-editor/issues/742#issuecomment-129724199)中看到了新的作业部落现在已经有全平台客户端了，很高兴啊！这样也能满足我提这个提议时希望达到的目的。

you could close issue, please.

**Comment by ghosert** [comment]
暂时可以在CHROME中打开不同的页面来做切换。
