### ISSUE TITLE
文章多了，比较难找

### ISSUE THREAD

**Issue by shjanken** [ghosert/cmd-editor#74]
现在陆陆续续也写了点文章了，但是文章多了之后，要在长长的文章列表中寻找比较讨厌。能加入搜索功能么？

**Comment by ghosert** [comment]
感觉你要的是这种东西吧，哈哈。

![screenshot](http://ww3.sinaimg.cn/large/8368c33egw1ef9o8z4oioj21ao0si42r.jpg)

**Comment by shjanken** [comment]
**对呀** 标签什么的最有爱了，这个功能还在测试？还是已经正式推出了？

**Comment by ghosert** [comment]
正在准备发布，请等待。。。

**Comment by ghosert** [comment]
已修复
