### ISSUE TITLE
希望离线也能写文章

### ISSUE THREAD

**Issue by GuojieLin** [ghosert/cmd-editor#742]
有时候在外没有网络,想要想要写文章就没办法写,希望能够离线可以写文章保存着本地,在线的时候再进行同步

**Comment by ghosert** [comment]
有两种方式：1. 如果曾经访问过网站，离线的时候，再访问 https://www.zybuluo.com/mdeditor 也可以打开使用，离线保存，联网后会自动同步。
2. 使用客户端 https://www.zybuluo.com/cmd

**Comment by GuojieLin** [comment]
你好,我是用客户端的，因为有一次在车想想写东西，没有网络的情况下，客户端无法打开，所以以为必须联网才可以

**Comment by huweipro** [comment]
64位客户端2.0版，windows 8.1操作系统
没登陆没联网的情况下在客户端执行各种操作（新建、导出等）都提示“此功能需要登录。。。”
不能真正离线

**Comment by GuojieLin** [comment]
那次是没有提示,就是软件卡住 没任何反应

**Comment by huweipro** [comment]
多等一会右下角就会有提示“此功能需要登录。。。”

**Comment by ghosert** [comment]
离线需要至少曾经在有网络的状态下打开过一次。新建导出需要在登录状态下离线后使用。所以如果你至少打开过然后登录过以后就可以离线了，包括新建和导出。
