### ISSUE TITLE
导出带格式的html格式

### ISSUE THREAD

**Issue by ficenow** [ghosert/cmd-editor#743]
如题，这个功能在考虑中不，真的很需要啊:smile:

**Comment by nonozone** [comment]
嗯，这个我也很需要，最好自己辛辛苦苦做出来的文档，导出来的html格式也很美观就棒了。这样在写一些产品文档的时候，就舒服多了。

**Comment by licairong** [comment]
+1，导出的HTML没有格式，这点很需要，保持预览窗口的效果导出就可以了

**Comment by zjzaaa2005** [comment]
+1 希望还能导出带格式的PDF

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
