### ISSUE TITLE
注册时邮箱验证，点击重发就404

### ISSUE THREAD

**Issue by Altriaex** [ghosert/cmd-editor#747]
RT
第一次发验证邮件的时候没有及时点。
点击重发就404了。

**Comment by rexxarM** [comment]
The page which is 404:

https://www.zybuluo.com/email_request/verification

Click in [用户设置](https://www.zybuluo.com/settings/account)

Last test in 08-12 14:41:01.489

**Comment by ghosert** [comment]
你这是从链接里摘要出来的所以是404。我点击后没这个问题。
