### ISSUE TITLE
长文章乱跳问题比较严重

### ISSUE THREAD

**Issue by FlatMapIO** [ghosert/cmd-editor#75]
当文章超过页面高度时, 页面就会乱跳, 根本没法用. 希望能帮忙解决~~

**Comment by ghosert** [comment]
你能把文稿发布一下，把链接贴给我看吗？

**Comment by ghosert** [comment]
还有说明一下你的 屏幕大小，浏览器，操作系统，具体什么时候会出现这种情况，是在写文稿的时候还是其它情况下。

**Comment by FlatMapIO** [comment]
文稿:  https://www.zybuluo.com/huodon/note/8020

问题重现:  在文章的尾部, 添加代码段  ```  CODE  ``` , 文章就会跳到顶端,  拉到最下面打一个字又会开跳. 

屏幕尺寸: 24"
分辨率: 1920 x 1200
系统: Windows 8
浏览器: Chrome 33

**Comment by ghosert** [comment]
我看了一下，应该就是向上移动了一小端距离，再打字也不是总是出现这种状况，你说的是会一直跳到页面开始的地方吗？

**Comment by FlatMapIO** [comment]
嗯, 会总是跳到开头.

因为长文章总是不给底部预留空间, 编辑区无法处于屏幕中段, 所以只能在屏幕最最底行进行编辑, 因此我用 CODE 段留了空白段, 结果就开始乱跳了.

**Comment by ghosert** [comment]
这样的 case 比较少， 你还是 先别用 `CODE`, 你可以在底部用多个换行來留白。

**Comment by ghosert** [comment]
重新看了一下，确实有问题，就是在光标在编辑区底部的时候，如果从底部删几行就会有这个问题，正在解决。

**Comment by ghosert** [comment]
这个已经修复了。
