### ISSUE TITLE
图片上传入口

### ISSUE THREAD

**Issue by nostone000** [ghosert/cmd-editor#752]
其他功能，对于我的工作来说，基本是ok的。但是这个图片添加功能太难用了。就算不能直接食用本地路径，最起码提供一个本地图片上传的入口啊！希望能有所改进！

**Comment by mythyygg** [comment]
作者之前有说,已经在日程上了

**Comment by qiudesong** [comment]
这个必须有，每次图片都要存到网盘，然后分享，得到链接才行

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
