### ISSUE TITLE
文章越来越多,希望能在搜索栏输入标签时,列出该标签下的文章列表

### ISSUE THREAD

**Issue by mythyygg** [ghosert/cmd-editor#753]
文章多了,标签多了,要找到某篇时要去点开标签,下拉 找到文章.
如果能在页面当中 通过快捷键调出列表搜索栏,输入标签,显示当前书签的所有文章,然后快速选择

例如我要找到`pandas` 这篇文章 输入`python : panda` ,就能快速定位,类似于sublimetext中的功能
![image](https://cloud.githubusercontent.com/assets/3206693/9279701/c433963e-42eb-11e5-9987-aece0604e959.png)

**Comment by ghosert** [comment]
ctrl+alt+f 然后直接输入文章标题的部分关键字就可以过滤出对应的文章，然后直接用方向键选择，用回车访问加载，挺快的。
