### ISSUE TITLE
产品建议

### ISSUE THREAD

**Issue by qiudesong** [ghosert/cmd-editor#760]
希望全屏的时候，能把滚动条隐藏。

**Comment by ghosert** [comment]
可否截屏过来看看。 Regards, Jiawei Zhang 在2015年08月21日 11:10 ，qiudesong写道： 希望全屏的时候，能把滚动条隐藏。 — Reply to this email directly or view it on GitHub.

**Comment by qiudesong** [comment]
![default](https://cloud.githubusercontent.com/assets/12410088/9406525/c2afde7e-4833-11e5-805f-05a8abc086bc.png)
如图，全屏预览模式下，右边的滚动条没有隐藏

**Comment by qiudesong** [comment]
希望在全屏模式下，按esc键能退出全屏模式。

**Comment by ghosert** [comment]
切回双屏的快捷键是 ctrl + alt +m   滚动条是为了方便鼠标下拉。
