### ISSUE TITLE
win10系统下客户端版字体出现乱码

### ISSUE THREAD

**Issue by hoxis** [ghosert/cmd-editor#762]
![cmd markdown](https://cloud.githubusercontent.com/assets/5113809/9405428/28c260b0-482a-11e5-8b40-10bfc83295ed.png)
如图

**Comment by ghosert** [comment]
在浏览器设置找一下设置，允许自定义字体。

**Comment by ghosert** [comment]
参考下这个：https://github.com/ghosert/cmd-editor/issues/571

**Comment by hoxis** [comment]
我用的是Windows的客户端版的出的问题，浏览器里面是正常的。

**Comment by ghosert** [comment]
按如图所示设置：替代 Windows 显示语言

![catch](https://cloud.githubusercontent.com/assets/236040/18246399/116997ee-739e-11e6-86cd-04a9ba3bf850.jpg)
