### ISSUE TITLE
编辑和展示的顺序乱套了

### ISSUE THREAD

**Issue by sharexun** [ghosert/cmd-editor#763]
编辑框显示的内容在最后，但是到最终生成的页面相应的内容却跑到上面去了。

直接访问页面：https://www.zybuluo.com/sharexun/note/125130

直接看页面上的章节，13 章节的内容跑到 9.3 章节下了。

**Comment by sharexun** [comment]
晕，现在显示又正常了。难道还有中间状态吗？

**Comment by ghosert** [comment]
那我关了。
