### ISSUE TITLE
编辑和预览内容不一致

### ISSUE THREAD

**Issue by sharexun** [ghosert/cmd-editor#765]
![image](https://cloud.githubusercontent.com/assets/1962099/9432460/ba2948de-4a55-11e5-9212-41a727a9eecd.png)

编辑内容和预览内容（包括发布后的）不一致。

https://www.zybuluo.com/sharexun/note/125130

**Comment by ghosert** [comment]
markdown 原文发我一下： ghosert@gmail.com 另外刷新能解决吗？

**Comment by sharexun** [comment]
刷新不能解决的 :(

**Comment by sharexun** [comment]
内容发你邮箱了，你看下，基本显示是乱套了，

**Comment by ghosert** [comment]
还好，就是少了你标的那块。

有几种改法：
1. 把**14. 网关 gateway 配置说明** 改成标准的标题形式：  ### 14. 网关 gateway 配置说明
2. > 每条 access.log 日志记录都会存储有 访问时间，访问号码，请求的URL路径，UA 等等信息； 这句最好不要使用 > 做前缀，因为这句本身在列表里，列表只供简单内容使用，最好不要嵌套复杂标签。
