### ISSUE TITLE
合并提示太弱，出现旧版本覆盖了新版本的情况

### ISSUE THREAD

**Issue by byronhe** [ghosert/cmd-editor#767]
有个文档修改了一天了，换到旧机器上后，合并提示一闪而过，导致旧版本的数据把新版本的给覆盖了。
被坑的好惨！
欲哭无泪。。。

求加保护，比如合并操作涉及删除的字数大于200字，要求用户手动输入验证码确认。
或者发现旧改动要覆盖新改动，要用户输入验证码确认。
或者云端能保存个多个备份，比如30分钟保存一个备份，万一覆盖了，能找回来。
或者起码在用客户端的情况下，在本地多保存几个备份

**Comment by ghosert** [comment]
出现此提示的时候还是认真看下，如果仔细处理了就不会有这个问题。手动输入确认对有经验的人来说也是一种负担。

历史版本的功能会考虑提供的。

**Comment by byronhe** [comment]
合并提示太弱，点错一不就覆盖了新版。
对于这种可能造成用户数据丢失的场景，不能一句“还是认真看下”就怪罪到用户头上啊。

**Comment by ghosert** [comment]
合并提示的时候，有说明，有差异部分的红绿高亮标注，有确认，有取消，还弹了单独的窗口，把背景都暗了下来，从我的角度挺警醒了。。。

你本身也有损失，我怎么能怪罪用户，我就是提醒注意一下，以后在大量文字有增删的时候记录下历史版本，我同意这样做更好，即使用户有误操作还可以找回来补救，强加更多的规则同样会引起部分人的反感。
