### ISSUE TITLE
win10系统CMD Markdown菜单乱码

### ISSUE THREAD

**Issue by itechq** [ghosert/cmd-editor#771]
Cmd markdown 2.0在win10下运行，导航菜单乱码，如下图所示：
![qq 20150829202337](https://cloud.githubusercontent.com/assets/2050839/9561867/d740fbda-4e8b-11e5-9d08-615f9090abbe.png)
请问怎么解决？

**Comment by hoxis** [comment]
同样的问题啊

**Comment by DongWeiMa** [comment]
+1

**Comment by ghosert** [comment]
按如图所示设置：替代 Windows 显示语言

![catch](https://cloud.githubusercontent.com/assets/236040/18246399/116997ee-739e-11e6-86cd-04a9ba3bf850.jpg)
