### ISSUE TITLE
页内跳转与中文输入退格

### ISSUE THREAD

**Issue by huangjj27** [ghosert/cmd-editor#772]
1.求问业内跳转应该怎么实现
2.中文输入退格有几率在输入法框退到第一个字母的时候也把最后一个中文退了

**Comment by ghosert** [comment]
页内跳转是指什么？
你用输入法是？操作系统，浏览器版本，是否客户端？

**Comment by huangjj27** [comment]
页内跳转指的是访问当前页的标签/标题，已经通过设置锚点暂时解决，求不用HTML设置描点的方法。

第二个问题是：用搜狗输入法在win7的360浏览器上面输入时出现的问题，不是客户端，因为是用朋友的电脑。

**Comment by ghosert** [comment]
360浏览器，确实没去支持。chrome/firefox/id/safari 应该都支持了。

暂时只能先自己用 html 写一个 id="Header1"
然后这样：
[Header1](#Header1)
