### ISSUE TITLE
支持PDF导出

### ISSUE THREAD

**Issue by zhengxiaowai** [ghosert/cmd-editor#775]
PDF导出 比导出HTML有用多了

**Comment by nonozone** [comment]
同样很需要这个功能。

**Comment by tandaly** [comment]
很需要这个功能，导出html后样式也变了，导出PDF还是很有必要的，期待能有这功能

**Comment by songsuoyuan** [comment]
希望添加这个功能……

**Comment by wxzhou** [comment]
我也需要。因为并非所有人都用markdown，即使用markdown也不一定用cmd markdown。某些cmd的功能，例如todo list，在别人那里看不到。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
