### ISSUE TITLE
我现在用chrome无法切换文章了

### ISSUE THREAD

**Issue by kneep** [ghosert/cmd-editor#780]
chrome是最新的44版本。点另外一篇文章，刷新后，还是原来打开的那篇，没法工作了。
目前我不清楚此问题复现的路径，最近开始变这样的。firefox最新版本没有问题。

**Comment by ghosert** [comment]
可以把CHROME 重新安装下吗？或者试试我们的客户端也行啊。

**Comment by kneep** [comment]
后来我清空cookie后貌似可以了。
