### ISSUE TITLE
to-do list建议使用别的格式

### ISSUE THREAD

**Issue by wxzhou** [ghosert/cmd-editor#783]
现在to-do list的格式是：如果未完成则在列表开头加[ ]，如果完成了则加[x]。但感觉x通常表示“叉”，有未完成或失效的意思。建议改用v或_来表示已完成，因为v是最接近“对勾”的符号，而_有填充的感觉。

或者只有[ ]表示未完成，中间无论填充什么字符都表示完成。

**Comment by wxzhou** [comment]
抱歉我忘了这个编辑框本身支持markdown……

我本来是说用*号也用来表示已完成（谁知变成了斜体）。

**Comment by ghosert** [comment]
好吧，我先关了，这个 TODO 语法式参考了 GITHUB 的形式，应该算半个标准了。。。
