### ISSUE TITLE
建议导出html时增加css

### ISSUE THREAD

**Issue by wxzhou** [ghosert/cmd-editor#785]
很多人都报告了生成html后格式丢失的问题。我是网页小白，刚才临时抱佛脚地看了一点CSS，冒昧揣测一下，似乎只要在生成的html的head里加上一段固定的CSS代码就可以保留格式了。

例如在cmd里输入：

``` md
`foo` `bar`
```

预览是这样的：
![qq 20150904183949](https://cloud.githubusercontent.com/assets/8687574/9681919/60569298-5334-11e5-968a-c5ecbeeec3c7.png)

生成HTML代码后，在Firefox里打开，是这样的：
![qq 20150904184043](https://cloud.githubusercontent.com/assets/8687574/9681935/7f12391c-5334-11e5-9053-baffe3c1af76.png)

但是如果在HTML代码的head部分加上如下代码：

``` html
<style type="text/css">
code{
    background-color:#d6dbdf;
    padding:2px;
    border-radius:5px;
    font-family:Consolas;
    color:#2c3e50;
}
</style>
```

再在Firefox里打开，就变成这样了：
![qq 20150904184251](https://cloud.githubusercontent.com/assets/8687574/9681967/cb34caa8-5334-11e5-9b49-5f3e8f864f4b.png)

限于时间关系，我没有测试其他部分应如何设置CSS。不过我猜测，各个部分（粗体、斜体、标题等）的CSS应该是固定的，所以生成的时候往文件开头插入一段固定代码就行了，这似乎不难实现。代码块语法高亮功能貌似复杂一点，我不太懂。

**Comment by ghosert** [comment]
敬请期待，九月八日的发布，都做了。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
