### ISSUE TITLE
买个高级会员支持一下。

### ISSUE THREAD

**Issue by fyxsky** [ghosert/cmd-editor#787]
**开发不易，支持一下。
坦白讲，价钱真心不便宜，主要是年费模式让价钱变得不便宜。希望越做越好吧。
忽然在想，后面如果调低价格，咋个办咧。**

另外，我想问一下，如果我想把CMD写的文档，在wordpress上发布，同时保留CSS，有办法么？

**Comment by fyxsky** [comment]
坦白讲，价钱真心不便宜，主要是年费模式让价钱变得不便宜。希望越做越好吧。

**Comment by ghosert** [comment]
谢谢支持！年费确实比较通用的做法，只是譬如许多商家会采取例如每月 10 元，年费打折为99元这种策略，让用户心理更能承受，也许也可以按此处理，但是暂时还是实报实销吧。毕竟如果工具有用，也值得上一顿饭钱 ：）

如果想发布在 WORDPRESS，你又已经购买了高级会员，可以尝试导出带样式的 HTML，然后导入 WORDPRESS 看看？不知道 WORDPRESS 又没有导入 HTML 这种功能？

**Comment by kneep** [comment]
@ghosert 我觉得收年费很正常，但确实有点小贵。是否考虑给我们这种活跃的老用户做点优惠活动？毕竟刚刚开始收费，人气很重要。我的建议是一开始便宜点，吸引老用户加入高级会员，也算小小回馈一下支持作业部落壮大的老用户们。接下来一边观察，一边再决定后面的价格策略，比如随着功能的增加，再逐渐涨点。另外，转pdf为什么在服务器端完成？我看马克飞象是利用chrome的保存为pdf功能，生成的文档效果很好啊，作业部落用这个功能的效果就惨不忍睹了，可能是没有针对这个功能调试过吧？能不能用这个做个穷人版的导出pdf功能？

**Comment by ghosert** [comment]
这个是作业部落生成的 PDF 样稿，可以查看下：

https://www.zybuluo.com/static/editor/cmd-manual.pdf

文档段落之间没有任何错排，截断，左侧也自动生成了目录结构，效果完美，在服务器端完成是为了保证生成 PDF 的效果，会使用更专业算法和类库保证生成质量。CHROME 毕竟不是专门生成 PDF 用的，效果没有那么完美，另外服务器的网络状况会好很多，可以保证生成文档的成功率。

**Comment by kneep** [comment]
嗯，这我一早就看过了，效果是还不错。

**Comment by woodenTail** [comment]
买了两年,觉得99按年还是贵,有没有终身制,续不起了
