### ISSUE TITLE
请问有没有考虑增加同步到github、dropbox或者其他云存储上的功能？

### ISSUE THREAD

**Issue by qinf** [ghosert/cmd-editor#79]
如题，增加这样的功能类似push到github pages，或者转存到dropbox上。我是看到StackEdit上有这些功能，觉得还是不错的。不知道cmd-editor会不会做?

**Comment by sjtubinlong** [comment]
同意，一直希望有这个功能

**Comment by ghosert** [comment]
github dropbox 在国内的网络服务并不稳定，Cmd Markdown 也不是 StackEdit 的拷贝，实时网络存储和标签功能是希望用户在 Cmd 安家，这里提供一站式的服务，省却配置的麻烦，许多用户恐怕都没有 dropbox github 的帐号吧。

**Comment by strivek** [comment]
也希望有这个功能，毕竟github可能更适合分享吧

**Comment by ghosert** [comment]
暂时没有此计划，希望大家谅解。

**Comment by qinf** [comment]
@ghosert 做实时网络存储和标签功能是希望用户在 Cmd 安家，提供一站式的服务，这可能是我们对没有认识到cmd-editor的一面吧，以前我一直把这东西当成自己的小小网络笔记本用，冏。最后，望cmd-editor做的更好。
