### ISSUE TITLE
PDF导出失败

### ISSUE THREAD

**Issue by Jack2code** [ghosert/cmd-editor#790]
刚刚升级为高级会员，尝试一把导出PDF功能，结果失败。

提示信息如下：

> 导出 PDF 文件失败，服务器可能正忙，请稍后再试，或联系我们

PS:我在使用公司网络，有代理，经常会离线，但刷新页面，重新同步后依然无法导出

**Comment by ghosert** [comment]
两个原因，一个是文档里是否包括被墙的图片，链接，如果是会因为这个造成无法访问。第二就是可能目前试用此功能的人过多导致。还有就是你公司那边的网络条件是否太差？可以稍后再试下。

**Comment by ghosert** [comment]
测试过，目前我这边一切正常。

**Comment by fyxsky** [comment]
@ghosert 我测试的也没问题，只是反应速度稍有点长，大概5-10秒的样子。

**Comment by Jack2code** [comment]
@ghosert 我F12看了下，是发起downloadPdf的POST请求时，文件大小超过公司限制，被公司拦下来了。

我司的限制太严格，看来在公司网络几乎不可用。图片无法上传，文档基本无法导出。如果能出一个手机客户端就好了：（

**Comment by ghosert** [comment]
可否联系下网管？实在爱莫能助啊。。。我先关下了。
