### ISSUE TITLE
一键导出所有

### ISSUE THREAD

**Issue by YinChangSheng** [ghosert/cmd-editor#794]
使用 一键导出所有文稿 会中文乱码
![乱码一](http://7nj37k.com1.z0.glb.clouddn.com/blog/cmd-editor/20150908154748.png "中文乱码")
![乱码二](http://7nj37k.com1.z0.glb.clouddn.com/blog/cmd-editor/20150908154730.png "中文乱码")

我是 window7 32位 操作系统 chrome 版本 45.0.2454.85 m

**Comment by ghosert** [comment]
请使用WINZIP/WINRAR/7ZIP 等压缩软件解压，WINDOWS 自带的压缩软件不支持 UTF8 导致此问题。

**Comment by YinChangSheng** [comment]
呵呵。把最重要的 压缩包 解析器忘了。问题已解决。
