### ISSUE TITLE
无法验证邮箱，未知名错误

### ISSUE THREAD

**Issue by JenneyHong** [ghosert/cmd-editor#797]
我下载了客户端，注册了账号，但是发送验证邮件的时候我的邮箱没有接收到。换了一个邮箱也是没有接收到。
现在只能用用户名登陆，麻烦帮我解决一下这个问题，谢谢！ @ghosert

**Comment by whatot** [comment]
我也不能用gmail验证

**Comment by ghosert** [comment]
请再登录进去以后重新发送一下。应该可以收到的，只是有的时候服务器稍忙，另外就是可能会有点延迟，还有垃圾箱看一眼哈。
