### ISSUE TITLE
代码区块包含多个$时缩进出错

### ISSUE THREAD

**Issue by duanby** [ghosert/cmd-editor#799]
用4个空格建立的代码区块中包含多个$时，如下：
    A=src
    B=${A}
    C=${A}/lib
    D=bin
显示时第3行会多一段缩进，第4行就正常了。

shell脚本中经常出现多个$，所以我认为这个问题还算挺普遍的。希望能够解决，谢谢！

**Comment by duanby** [comment]
TAT上面显示时出了点问题。请手动给每行代码前面添加4个空格。

**Comment by ghosert** [comment]
$ 是个特殊符号，请在 $ 前加 \ 转义，譬如：

A=src
B=\${A}
C=\${A}/lib
D=bin

**Comment by morusleaf** [comment]
可是这样修改后，导出的HTML里就多出了 \ ，@ghosert

**Comment by ghosert** [comment]
你再试试，不会多出来的。

**Comment by morusleaf** [comment]
如果前面不加4个空格确实不会多出\，但是当作代码引用时就会多出\

**Comment by ghosert** [comment]
拿代码引用的时候不加也没问题吧？ Regards, Jiawei Zhang 在2015年09月09日 13:20 ，morusleaf写道： 如果前面不加4个空格确实不会多出\，但是当作代码引用时就会多出\ — Reply to this email directly or view it on GitHub.

**Comment by morusleaf** [comment]
举个例子吧
![2015-09-09 6 58 24](https://cloud.githubusercontent.com/assets/7351197/9760109/d434e0f4-5724-11e5-9e49-f1c14d01f6ea.png)
如果不加\，缩进就会出错；如果加了，就会显示\

**Comment by ghosert** [comment]
好像是有点问题，暂时先这样行吗？

```
    A=src
    B=${A}
    C=${A}/lib
    D=bin
```

**Comment by morusleaf** [comment]
多谢！一定程度上解决了问题。
但是如果我希望在有序列表中插入代码，又出现了问题（我真的不是抬杠啊）。如图：
![2015-09-09 10 52 09](https://cloud.githubusercontent.com/assets/7351197/9765470/ea3110c2-5746-11e5-8321-4ba0d1459135.png)
如果像第一段shell代码那样顶格写，则`2. 二`实际显示为`1. 二`，可能shell代码把一个列表分成了两个。
如果像第二段shell代码那样缩进了写，虽然不会分割列表，但是又出现了代码缩进的问题。

**Comment by ghosert** [comment]
有序列表里不适合放复杂的语法。用 ### 2. 这种來代替有序列表。

**Comment by hezhizhen** [comment]
试试在2上面加一行空行
