### ISSUE TITLE
登录成功页面显示的问题

### ISSUE THREAD

**Issue by PearlEast** [ghosert/cmd-editor#8]
每次登录完之后，页面显示说你所访问的页面不存在神马的，其实已经登录成功了。
可以检查一下吗。 多谢开发者的辛勤劳动和宝贵时间。

**Comment by ghosert** [comment]
你登入前的那个地址可能不对，你保证每次是从 http://www.zybuluo.com/mdeditor 进去的应该就对了，试试再告诉我。

**Comment by PearlEast** [comment]
我明白你的意思，情况是这样，我先log out, 再log in, 有时就出现了我上面说的问题。

现在似乎又好了。

**Comment by ghosert** [comment]
好，有问题的时候再告诉我，最好把详细的过程记下来，包括从哪个 url log out 的。这个问题我先关了。

**Comment by PearlEast** [comment]
好的，谢谢，我该截图的。
