### ISSUE TITLE
字体顺序调整建议

### ISSUE THREAD

**Issue by xingrz** [ghosert/cmd-editor#802]
## 目前状况

目前（2015/09/09）CMD的字体样式是这样的：

``` css
font-family: Microsoft Yahei, Hiragino Sans GB, WenQuanYi Micro Hei, sans-serif;
```

即**微软雅黑**优先级高于**冬青黑体简体中文**（Hiragino Sans GB）。
## 存在的问题

~~Mac OS X 上（印象中至少从 10.8 开始就）自带了微软雅黑~~，而冬青黑体（同样是自带）在 Mac OS X 上的显示效果要**远远好于**微软雅黑。即是说，这个顺序导致本该更优秀的冬青黑体没有起作用。
## 建议

把 `Hiragino Sans GB` 提前到 `Microsoft Yahei` 之前
## 更进一步的建议

从 Mac OS X 10.11 El Capitan（目前处于公测阶段，尚未正式推送）开始，新增了比上述两款字体更加优秀的**苹方**黑体（`PingFang SC`），建议将这个字体加入在 `font-family` 最前，以便在系统有这个字体的情况下优先使用。
## 总结

就显示效果来说，在 Mac 上：`PingFang SC` > `Hiragino Sans GB` > `Microsoft Yahei`

就兼容性来说：绝大部分 OS X 自带 `Hiragino Sans GB` 及 `Microsoft Yahei`，即将自带 `PingFang SC`

建议 CSS 更改如下：

``` css
font-family: PingFang SC, Hiragino Sans GB, Microsoft Yahei, WenQuanYi Micro Hei, sans-serif;
```
## 截图对比

![目前效果](https://cloud.githubusercontent.com/assets/288288/9759242/40c2e128-571e-11e5-8a23-d4233b692134.png)
_上图：目前只有微软雅黑起作用的效果_

![冬青](https://cloud.githubusercontent.com/assets/288288/9759276/7dc12940-571e-11e5-897a-76d78fca7fca.png)
_上图：将冬青提到雅黑之前的效果_

![苹方](https://cloud.githubusercontent.com/assets/288288/9759304/ac7a7552-571e-11e5-8484-7ba8382bccee.png)
_上图：在字体列表前面加入苹方的效果_

**Comment by xingrz** [comment]
另外，兰亭黑（`Lantinghei SC`）也是 Mac OS X 上自带的一款很不错的中文字体，现在 36kr 就用了这个字体。

**Comment by ghosert** [comment]
很好的建议，有时间会尽量采纳，原来意味 MAC 上不会有微软雅黑，不知道为什么也会有？是因为装了 微软的软件吗？

**Comment by xingrz** [comment]
哦，原来是因为我安装过 Microsoft Office for Mac，所以系统有了微软雅黑…

**Comment by liuquanqing** [comment]
支持，『微软雅黑和方正兰亭黑是兄弟字体，分别为屏幕和印刷优化。
雅黑用的是 Segoe UI 的变体，而兰亭黑是仿 Helvetica 风格』

**Comment by liuquanqing** [comment]
@ghosert

**Comment by ghosert** [comment]
这种改法对 WINDOWS 用户有何影响？他们有 东青 和 苹方 字体吗？

**Comment by xingrz** [comment]
@ghosert 不会，他们会回退到微软雅黑。

**Comment by ghosert** [comment]
好的，我国庆里改下，国庆后更新。

**Comment by liuquanqing** [comment]
。。  现在还是编辑栏的字间距大的不行，字体好像也没变化

**Comment by liuquanqing** [comment]
@ghosert

**Comment by ghosert** [comment]
已调整：https://www.zybuluo.com/ghosert/note/102771

**Comment by xingrz** [comment]
感谢，这次真的爱不释手了

**Comment by liuquanqing** [comment]
赞！

2015-12-06 17:27 GMT+08:00 XiNGRZ notifications@github.com:
