### ISSUE TITLE
希望能够支持历史版本的功能

### ISSUE THREAD

**Issue by wjc133** [ghosert/cmd-editor#803]
上次在公司写了很长一篇文档，回了家里同步出了问题。想恢复都恢复不会来，严重降低体验了呀~

**Comment by ghosert** [comment]
同步的时候如果有冲突，稍微仔细处理下冲突，当然我这里也会加历史版本。真的有很多数据，可以购买高级会员，我们协助找回来。

**Comment by ghosert** [comment]
已支持历史版本：https://www.zybuluo.com/ghosert/note/102771
