### ISSUE TITLE
何时修复win10菜单乱码问题啊？

### ISSUE THREAD

**Issue by itechq** [ghosert/cmd-editor#808]
用了你们软件一周，体验挺好的，很想买你们高级版，但是唯一不足就是win10下菜单导航是乱码啊。何时可以修复这个问题啊？

**Comment by hoxis** [comment]
同问！！！

**Comment by ghosert** [comment]
按如图所示设置：替代 Windows 显示语言

![catch](https://cloud.githubusercontent.com/assets/236040/18246399/116997ee-739e-11e6-86cd-04a9ba3bf850.jpg)
