### ISSUE TITLE
批注换行

### ISSUE THREAD

**Issue by JenneyHong** [ghosert/cmd-editor#810]
今天体验批注功能的时候发现不能用enter换行，是要用其他的方式换行还是暂时没有这个功能？
系统可以提供enter换行，这样比较方便且美观！@ghosert

**Comment by ghosert** [comment]
主要是因为批注可能被公开，而有人恶意输入很多换行，整个版面会非常不好看，所以一般都会自动删除换行。反而把换行作为结束输入的信号。

**Comment by JenneyHong** [comment]
那么可以设置成excel那样，自动换行？这样应该可以避免有人输入大量的空白换行

joan2hong@foxmail.com

发件人： Jay Zhang
发送时间： 2015-09-11 09:51
收件人： ghosert/cmd-editor
抄送： JenneyHong
主题： Re: [cmd-editor] 批注换行 (#810)
主要是因为批注可能被公开，而有人恶意输入很多换行，整个版面会非常不好看，所以一般都会自动删除换行。反而把换行作为结束输入的信号。
