### ISSUE TITLE
建议把页面的title改为文档名

### ISSUE THREAD

**Issue by iuphero** [ghosert/cmd-editor#814]
小建议：
把html里面的title改为此文档的文档名，这样一个浏览器多个标签打开多个文档时，能准确辨认应该跳转到哪一个文档

**Comment by iuphero** [comment]
@ghosert 大哥, 这个issue进展怎样了, 全国人民都需要, 赶紧滴 :smile:

**Comment by ghosert** [comment]
我已经分配给自己了，小事一桩啊，不着急，下周和大功能一起发哈，你可以截屏。

**Comment by ghosert** [comment]
已修复：https://www.zybuluo.com/ghosert/note/102771
