### ISSUE TITLE
希望增加对行内数学公式的支持

### ISSUE THREAD

**Issue by zhonglingshan88** [ghosert/cmd-editor#816]
在编辑一些文字时将公式置于行内比较美观，且每条公式均占用一行太占空间。希望能够增加对行内公式的支持。

**Comment by ghosert** [comment]
这个本来支持的： https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#5-latex-公式

**Comment by ghosert** [comment]
这个本来就支持的：https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#5-latex-公式

**Comment by zhonglingshan88** [comment]
好的，看来是我没有仔细看说明文档……另请问是否支持扩展宏包？
