### ISSUE TITLE
建议将导出和删除功能放在工具栏上

### ISSUE THREAD

**Issue by minixalpha** [ghosert/cmd-editor#82]
新的版本把导出和删除隐藏在“新文稿”的下拉菜单中了，找了半天才找到，感觉没有原来那样的交互方式方便，有什么特别的考虑吗？

**Comment by imbyron** [comment]
我是到了这里才找到。
交互确实不方便。

**Comment by ghosert** [comment]
工具栏上空间有限，所以把【发布】和【新文稿】突出了，至于删除和导出目前还不重要，大多数情况下用户是很少删除的，导出以后会单独放一个图标在工具栏上，可以导出到更多的地方，目前的导出还很弱，不用也罢。

**Comment by imbyron** [comment]
@ghosert 
　　是这样的，我不太清楚他人是怎样使用这个工具的，我是把它当做MarkDown代码编辑器+文章共享一起来用的。
　　至于文章共享，突出发布是没有问题的，但是作为Markdown编辑器的话，我编辑完之后就复制到了博客上或者其他地方，编辑的这个稿子就不需要存在于平台之上了，所以我本人其实删除用的最多。
　　至于你说的现阶段删除和导出还不重要，需要弱化我是可以理解的，但是，现在的问题是把这两个功能放到了新文稿右侧的下拉三角中，这样会给用户带来极大的困惑，一般不会把视线关注到这个下拉三角，即使关注到，也会在潜意识中以为是新文稿的一个功能。
　　还有新文稿右侧的文章列表按钮视觉功能化比较弱，我需要点开之后才知道是什么功能，而且在用的过程中总要想那么一秒钟。
　　所以如果可能，建议你可以把这个按钮和上面提到的删除导出功能规划一下，看看怎样展现更为合适。:-)

**Comment by ghosert** [comment]
其实你不想发布的文章，可以打个标签归类到某个标签下面就可以了，也不需要删除。。。删除是我想无限弱化的功能，当然你的案例比较特殊，没想到这么需要删除。导出做强以后，我会单独突出。目前，根据你的需求，最方便的删除是 ctrl+alt+d，比直接点图标快多了。

**Comment by imbyron** [comment]
@ghosert 
嗯，就是说要看用户和你怎样定位这个产品了。
我最开始就是当一个MD编辑起来用，现在发现发布功能做的很漂亮，就开始两个功能一起来用。

**那么我就想：**
- 把发布的，待发布的文章，我可以放在分类标签中
- 而我当做编辑器写的文章，则希望删掉。

若果你想把删除无限弱化，也是可行的，但是需要给用户一些有效的产品引导。:-)

**Comment by ghosert** [comment]
导出和删除已经从小尖头里移出到菜单里，比原来明显了。
