### ISSUE TITLE
使用```高亮代码时，出现这样的标签。<div class="md-section-divider"></div>

### ISSUE THREAD

**Issue by RolandXu** [ghosert/cmd-editor#820]
实际显示效果看这个网页.
截图如下
![image](https://cloud.githubusercontent.com/assets/1150966/9841837/d9fdb2f2-5ad7-11e5-8dae-1135cf5d4fd9.png)

**Comment by ghosert** [comment]
```int max(const char \* str);```

这句改成

`int max(const char \* str);`

``` 一定要换行，不换行则用 `
