### ISSUE TITLE
发布的文章的 LaTeX 公式统统无法显示。

### ISSUE THREAD

**Issue by shibuyanorailgun** [ghosert/cmd-editor#823]
系统：Ubuntu 14.04，浏览器：火狐 40。

比如：[https://www.zybuluo.com/nrailgun/note/172983](https://www.zybuluo.com/nrailgun/note/172983)

**Comment by ghosert** [comment]
点过去让我看到自己被完爆了？ 看看这里，了解下 CMD 到底有多震撼吧，少年。http://www.zhihu.com/question/19637157/answer/17395758

**Comment by shibuyanorailgun** [comment]
对不起，无意冒犯，这实在是我太无理了，我为此道歉。

**Comment by shibuyanorailgun** [comment]
之所以这么说是由于法克飞象支持编辑器换成 solarized 的主题，个人觉得 CMD 黑色主题比较模糊，而且会导致图片反色无法观看。再次为自己的失礼而道歉，非常抱歉。

**Comment by ghosert** [comment]
那你把原文MARKDOWN 发过来我看看为啥不显示公式。还有措辞改下，不要攻击 CMD。

**Comment by ghosert** [comment]
ghosert@gmail.com 这个信箱发原文。

**Comment by shibuyanorailgun** [comment]
好吧，我已经修改了。原文 和 屏幕截图 一起发给你了。

**Comment by shibuyanorailgun** [comment]
非常感谢你的答复，也非常感谢你的辛苦创作。我刚刚看到自己的发布的文稿可以正确显示了。十分感谢，也十分抱歉，十分羞愧。

**Comment by ghosert** [comment]
噢，也没什么其实，我提高点颜值就是了。
