### ISSUE TITLE
【增加功能】截图后直接粘贴图片到CmdMarkDown中

### ISSUE THREAD

**Issue by dongbingliu** [ghosert/cmd-editor#826]
无意之中碰到了CmdMarkdown，使用后发现很适合自己。
全平台同步编辑，很Nice，
价钱也还比较合理，

【建议】作者能增加截图后直接粘贴到MarkDown中。
马克飞像已实现此功能

**Comment by ghosert** [comment]
实际上此使用场景并不多，优先级较低。 Regards, Jiawei Zhang 在2015年09月16日 17:27 ，JerrryLiu写道： 无意之中碰到了CmdMarkdown，使用后发现很适合自己。 全平台同步编辑，很Nice， 价钱也还比较合理， 【建议】作者能增加截图后直接粘贴到MarkDown中。 马克飞像已实现此功能 — Reply to this email directly or view it on GitHub.

**Comment by tq5124** [comment]
我挺支持这个建议的，比如在OSX中用快捷键截图后直接粘贴。希望能考虑

**Comment by liuquanqing** [comment]
作为编辑人员，这个使用场景非常多

**Comment by liuquanqing** [comment]
但是由于编辑对排版要求高，还是用第三方的编辑器排版一下好。。

**Comment by dongbingliu** [comment]
@ghosert @tq5124 可能没有完全理解我的意思，本地直接截图复制粘贴CmdMarkdown，但图片实际默认以附件上传到服务器保存。
不用使用者保存截图，再以上传附件形式贴图。
省掉了中间的一步，交互性更强。谢谢考虑。

**Comment by miaoyaoyao** [comment]
其实这个功能非常有用。哎。就没有完美的markdown编辑器吗？我也期待cmd markdown能实现截图上传和直接拉本地图片上传

**Comment by ghosert** [comment]
@miapyaoyao 没那么夸张哈，最多算小瑕疵。原因是这边的上传是实时进行传到七牛那边，按照html的安全限制并不允许用程序的方法修改本地图片的地址，这样只能让用户手动选择或拖拽确保安全。本地图片是可以拖拽的。按ctrl g 然后把本地图片拖拽到选择按钮上就会开始上传。

**Comment by ghosert** [comment]
我会再看看文档想想其他办法。

**Comment by 123Daoxyz** [comment]
@ghosert cmd-editor这边能不能支持用户自己输入自己的七牛账号？我想把自己的图片托管到自己的七牛空间下面（PS:我是开发者，有技术基础）

**Comment by ghosert** [comment]
可以直接粘帖上传了：https://www.zybuluo.com/ghosert/note/378553
