### ISSUE TITLE
离线功能很弱

### ISSUE THREAD

**Issue by easeyang** [ghosert/cmd-editor#827]
其他平台我不知道我用的osx平台。
首先说句这个编辑器很赞。我用markdown写东西才一周不过有个几个痛点。
1.离线功能太弱，我有时候就是想用cmd markdown来打开本地一个文档，不需要放到云端他自动给我弄到云端了

2.没有资源管理功能，建议左边添加本地资源管理

**Comment by ghosert** [comment]
已增强离线文稿：https://www.zybuluo.com/ghosert/note/102771

**Comment by ghosert** [comment]
又增加了离线文稿可以保存到本地文件的功能。暂时关了。
