### ISSUE TITLE
【bug】对表格支持有问题

### ISSUE THREAD

**Issue by waylife** [ghosert/cmd-editor#836]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

![image](https://cloud.githubusercontent.com/assets/3348620/9992640/eec12632-60a5-11e5-8b7c-3806ad218aac.png)

**Comment by ghosert** [comment]
$ 有特殊含义，属于 LATEX 语义，所有有 $ 的地方请使用 \$ 转义。

**Comment by waylife** [comment]
额，有相关说明文档么？

**Comment by ghosert** [comment]
以后加。 Regards, Jiawei Zhang 在2015年09月22日 10:43 ，RxRead写道： 额，有相关说明文档么？ — Reply to this email directly or view it on GitHub.
