### ISSUE TITLE
公式之后会强制重新开始新段落，计算没有换行。

### ISSUE THREAD

**Issue by miaow1988** [ghosert/cmd-editor#837]
$$xyt$$形式的公式之后会强制重新开始新段落，例如：

Donating input as $x_t$, we want to learn a function $y_t=f(x_t)$ such that $y_t$ is temporal invariant. This can be described as
$$ \arg \min_{f(\cdot)} \sum_t (y_t - y_{t+1})^2. $$ 
Here, the euclidean distance is used for measure the temporal variance.

其中公式与最后一句话间有明显的超大的段落间距，显然是另开了新段落。但实际上此处不应有新段落。

**Comment by ghosert** [comment]
Donating input as $x_t$, we want to learn a function $y_t=f(x_t)$ such that $y_t$ is temporal invariant. This can be described as

$$ \arg \min_{f(\cdot)} \sum_t (y_t - y_{t+1})^2. $$ 

Here, the euclidean distance is used for measure the temporal variance.

这样是不是好点。。。

**Comment by miaow1988** [comment]
更精确的描述如下：

正常情况：
Donating input as $x_t$, we want to learn a function $y_t=f(x_t)$ such that $y_t$ is temporal invariant. This can be described as $$ \arg \min_{f(\cdot)} \sum_t (y_t - y_{t+1})^2. $$ Here, the euclidean distance is used for measure the temporal variance.

加一个换行在$$后，出现巨大间距：
Donating input as $x_t$, we want to learn a function $y_t=f(x_t)$ such that $y_t$ is temporal invariant. This can be described as $$ \arg \min_{f(\cdot)} \sum_t (y_t - y_{t+1})^2. $$ 
Here, the euclidean distance is used for measure the temporal variance.

加两个换行在$$后，上述巨大间距反而变小：
Donating input as $x_t$, we want to learn a function $y_t=f(x_t)$ such that $y_t$ is temporal invariant. This can be described as $$ \arg \min_{f(\cdot)} \sum_t (y_t - y_{t+1})^2. $$ 

Here, the euclidean distance is used for measure the temporal variance.

**Comment by ghosert** [comment]
暂时可否这样：

Donating input as $x_t$, we want to learn a function $y_t=f(x_t)$ such that $y_t$ is temporal invariant. This can be described as

$$ \arg \min_{f(\cdot)} \sum_t (y_t - y_{t+1})^2. $$

Here, the euclidean distance is used for measure the temporal variance.

**Comment by miaow1988** [comment]
先这样用着吧，我只是报告一个Bug而已。^_^
