### ISSUE TITLE
邮箱验证不好使

### ISSUE THREAD

**Issue by ghost** [ghosert/cmd-editor#842]

**Comment by ghosert** [comment]
为了防止滥用24小时内最多发五份邮件。可以过二十四小时再试，或者二十四小时后进入用户设置换邮箱再试。 Regards, Jiawei Zhang 在2015年09月23日 08:21 ，Richard Zhang写道： 我向我的hotmail发送了5次邮件，现在收件箱（包括垃圾箱）没有收到邮件 — Reply to this email directly or view it on GitHub.

**Comment by jumperz** [comment]
微软的邮箱，@live.cn，（包括垃圾箱）也收不到验证邮件。

**Comment by ghosert** [comment]
能否去用户设置页面先改下邮箱吗 Regards, Jiawei Zhang 在2015年09月25日 10:34 ，jumperz写道： 微软的邮箱，@live.cn，（包括垃圾箱）也收不到验证邮件。 — Reply to this email directly or view it on GitHub.

**Comment by jumperz** [comment]
刚刚修改为live.cn地址，提示已发送验证邮件

**Comment by jumperz** [comment]
我用这个邮箱再回一次。多谢关注。
Date: Thu, 24 Sep 2015 19:38:20 -0700
