### ISSUE TITLE
Mac OS X 下的 ctrl + b 快捷键冲突

### ISSUE THREAD

**Issue by boathit** [ghosert/cmd-editor#847]
在 OS X 下因为已经有了 command + b 快捷键，能否将 ctrl +b 快捷键取消，因为这与 Mac 默认的系统快捷键冲突，手指已经习惯了 emacs 式快捷键，在想后退光标的时候热不住按 ctrl + b

**Comment by GerrieWell** [comment]
设置有个 emacs 模式.
没有就更新一下

**Comment by boathit** [comment]
一直在轻量编辑器模式下使用系统默认的快捷键，把 emacs 模式忘了，多谢啦。
