### ISSUE TITLE
问题和建议

### ISSUE THREAD

**Issue by alvintangzc** [ghosert/cmd-editor#859]
为了支持作者，已经冲了高级会员。有几个问题：
1. 不挂ICP备案信息真的好吗？因为要常用，对网站安全很在意。不只数据还有政策相关的。
2. 什么时候能同步evernote之类的平台？
3. 查看文章的密码现在可以无限尝试吧？有没有什么预防机制？

**Comment by ghosert** [comment]
ICP 备案有，没有是不能开站的
已支持 evernote：https://www.zybuluo.com/ghosert/note/102771
密码可以试，但是还是比较安全的。。。
