### ISSUE TITLE
有什么办法修改字体吗

### ISSUE THREAD

**Issue by OriLiMu** [ghosert/cmd-editor#862]

**Comment by liuquanqing** [comment]
说好的国庆后解决字体优先级问题呢。。

**Comment by ghosert** [comment]
在憋大招，快了。

**Comment by OriLiMu** [comment]
: ), we count on you.

513278236@qq.com

发件人： Jay Zhang
发送时间： 2015-10-29 10:22
收件人： ghosert/cmd-editor
抄送： woshichuanqilz
主题： Re: [cmd-editor] 有什么办法修改字体吗 (#862)
在憋大招，快了。
―

**Comment by liuquanqing** [comment]
赞，加油

**Comment by ghosert** [comment]
字体、字号还有 CSS 都可以自定义了：https://www.zybuluo.com/ghosert/note/378553

**Comment by ZHAIXINGZHAIYUE** [comment]
你好，我怎么知道有多少字体可选？如何知道字体的名字?

**Comment by ghosert** [comment]
可以从给你的浏览器的字体设置中看到。凡是在浏览器可以选到的字体，都可以直接复制粘贴到CMD
