### ISSUE TITLE
<table>表格大片空白行的问题

### ISSUE THREAD

**Issue by zhchnchn** [ghosert/cmd-editor#868]
Markdown表格格式支持的功能太弱了，我一般使用`<table></table>`嵌入表格，但如果在一篇文章中嵌入很多个比较大的表格时（`<tr>,<td>`等很占空间），在右侧版面预览时就会出现一大片空白，CmdMarkdown为保持左右版面同步，这个可以理解。但是在导出为带样式的html，或导出为PDF时，仍然有大片空白，很影响版面美观和连续性。希望能在导出时，把多余的空白行去除。

**Comment by ghosert** [comment]
截个图过来。

**Comment by zhchnchn** [comment]
例子如图：
![空白](http://static.zybuluo.com/zhchnchn/geqs9k7vved8atrzwqbll0mg/1.png)

**Comment by ghosert** [comment]
好奇怪，我在帮助文档里的例子是好的：

```
<table>
    <tr>
        <th rowspan="2">值班人员</th>
        <th>星期一</th>
        <th>星期二</th>
        <th>星期三</th>
    </tr>
    <tr>
        <td>李强</td>
        <td>张明</td>
        <td>王平</td>
    </tr>
</table>
```

**Comment by ghosert** [comment]
噢， 是不是因为你最后一个 `<table>` 写错了？应该是 `</table>`

**Comment by ghosert** [comment]
确认是这个问题，这个问题关了。

**Comment by zhchnchn** [comment]
非常感谢。
