### ISSUE TITLE
关于高级会员的购买方式

### ISSUE THREAD

**Issue by kin9-0rz** [ghosert/cmd-editor#870]
现在都是买个水果都扫码了，希望能支持手机扫码支付。之前都想买了，只是要登录支付宝，barabara一堆……最后，选银行卡，太麻烦……

会员今天已购买，希望做的越来越好吧。

**Comment by ghosert** [comment]
嗯，主流的扫码方式无论支付宝还是微信都需要企业营业执照，正在办理。不扫码确实不方便。
