### ISSUE TITLE
不能在本地编辑后直接存到本地

### ISSUE THREAD

**Issue by bopjiang** [ghosert/cmd-editor#876]
本地打开到文件，好像还是传到云端了。
使用其他编辑器编辑本地markdown文件，cmd根本感知不到。
一定只能用cmd编辑吗？ 不能有用其他编辑器编辑，cmd渲染的选择吗？

**Comment by ghosert** [comment]
离线有在做了，会尽量贴近你这类需求。

**Comment by ghosert** [comment]
这些都做了：https://www.zybuluo.com/ghosert/note/378553
