### ISSUE TITLE
为什么现在网页端打开这么卡

### ISSUE THREAD

**Issue by nejyeah** [ghosert/cmd-editor#877]
打开慢，其次开始写的时候很卡，半天才反应显示东西出来，what's wrong with you ?? 以前很流畅的啊，现在卡的我基本不能用了

**Comment by ghosert** [comment]
哪个操作系统，哪个浏览器？同一台机器同一个网络下客户端版本是什么情况，先详细说明下。一般来说是浏览器的问题。而且最好用 CHROME 性能最好，其它浏览器不能保证。

**Comment by ghosert** [comment]
还有是不是该重启电脑看看？

**Comment by ghosert** [comment]
以前是啥时候？最近一个月没更新过代码，应该不是代码的问题。

**Comment by ghosert** [comment]
没回复我先关下，有问题继续回复即可。
