### ISSUE TITLE
【求新功能】历史版本

### ISSUE THREAD

**Issue by LyZane** [ghosert/cmd-editor#878]
非常需要这个功能，哪怕简陋点，不用代码版本管理那么复杂。
相当于历史备份，每次改文档之前，用户手动备份一下，填个备注什么的，生成一个历史版本。

为这个功能，你再多坑我点钱我也是肥肠愿意的。

**Comment by ghosert** [comment]
已经做完了，就是没发布而已！哈哈哈哈！等更新吧！

![screenshot from 2015-10-13 18 30 38](https://cloud.githubusercontent.com/assets/236040/10452632/c872e0da-71d8-11e5-86d4-fb0149131812.png)
![screenshot from 2015-10-13 18 31 41](https://cloud.githubusercontent.com/assets/236040/10452633/c876ef36-71d8-11e5-9a8b-e3688fcb4909.png)

**Comment by zyl54586** [comment]
期待！

**Comment by ghosert** [comment]
已支持历史版本：https://www.zybuluo.com/ghosert/note/102771
