### ISSUE TITLE
希望能加上权限相关

### ISSUE THREAD

**Issue by KevinLinKai** [ghosert/cmd-editor#882]
现在分享出去的文章
从网页右边的“文本列表”中
能看到该作者的所有文章
希望能加上权限 区分《私有》和《公开》
私有的地址，也可以分享出去
但是观看人只能看到一篇文章
不允许得知作者的其他文章
这样会更加安全一些
光靠密码感觉还是不够的

**Comment by ghosert** [comment]
现在已经改为你说的逻辑了。

**Comment by ghosert** [comment]
只能看到当前分享的加密文稿和所有的公开文稿，其余的加密文稿已经隐藏了。
