### ISSUE TITLE
客户端：发布文稿时设置密码的问题

### ISSUE THREAD

**Issue by JimChenWYU** [ghosert/cmd-editor#883]
当你不是高级会员时，发布文稿那时错手按了设置密码那里，会自动弹出网页要求你升级为高级会员，但是当你关闭网页再切换到客户端时，光标又会在设置密码那里，然后又弹出网页，一直这样循环...

**Comment by ghosert** [comment]
是个问题，会尽快改。 发自网易邮箱大师 在2015年10月16日 16:11 ，JimChen写道： 当你不是高级会员时，发布文稿那时错手按了设置密码那里，会自动弹出网页要求你升级为高级会员，但是当你关闭网页再切换到客户端时，光标又会在设置密码那里，然后又弹出网页，一直这样循环... — Reply to this email directly or view it on GitHub.

**Comment by ghosert** [comment]
这个修复过了。
