### ISSUE TITLE
代码块行数过多时会出现行数移出背景色的情况

### ISSUE THREAD

**Issue by AshitakaAkasaka** [ghosert/cmd-editor#889]
当行数过多时会出现行数移出背景色的情况
e.g:
![problem](https://cloud.githubusercontent.com/assets/11502905/10608158/66530ebe-7770-11e5-83ca-4553d3a815b7.png)

**Comment by ghosert** [comment]
噢，原来设计的时候没想到会贴那么多上来。。。毕竟是用来做代码片段的展示比较多。。。而非大批量粘贴。。。

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

2015-10-20 21:20 GMT+08:00 AshitakaAkasaka notifications@github.com:

**Comment by AshitakaAkasaka** [comment]
这算个小瑕疵吧，毕竟像我这种使用的估计也不多。

**Comment by ghosert** [comment]
先关了。。。
