### ISSUE TITLE
导出HTML的时候，能否直接把样式也包含进来

### ISSUE THREAD

**Issue by amoszhou** [ghosert/cmd-editor#89]
RT,要不然导出的格式真心没法看。想贴到自己博客上去，那格式。。。默泪了

**Comment by sumiaowen** [comment]
支持楼上，现在用Mou就是以为可以导出CSS样式，不过不喜欢Mou的样式风格。

**Comment by ghosert** [comment]
已作为高级会员功能发布请参阅：https://www.zybuluo.com/ghosert/note/167938
