### ISSUE TITLE
新注册账号没有及时邮箱验证，之后就再也登录不上去了。

### ISSUE THREAD

**Issue by lisaRao** [ghosert/cmd-editor#890]
昨天注册了新账号，当时没有及时邮箱验证，直接就开始写文档了。结果今天早上登录，反复提示没邮箱验证，要求更换账号，或邮箱验证，去点击邮箱验证链接再登录，仍然提示需要邮箱验证。一直登录不上去，也找不到本地存储，现在账号中写的文档也没了。

可能验证链接失效了，建议有个入口可以点击重新发邮箱验证链接之类的。这种注册了因为没及时验证就需要更换账号的体验简直。。。。

**Comment by ghosert** [comment]
提示式说用用户名或者邮箱登录，即使没有验证过邮箱，可以始终用用户名登录。登录上去以后，重新验证邮箱或者换个邮箱验证都可以的。

**Comment by lisaRao** [comment]
![qq 20151022103910](https://cloud.githubusercontent.com/assets/4928307/10655649/2e9475dc-78a9-11e5-979e-bae08ffabd02.png)

**Comment by ghosert** [comment]
对啊，就是用你的用户名登录啊，不是用你的邮箱登录啊.

**Comment by lisaRao** [comment]
谢谢 ！！习惯用邮箱直接登录，没记住用户名。

**Comment by ghosert** [comment]
没有验证过的邮箱，不能证明就是你的，所以不能用来登录，就是这个逻辑。譬如你知道某个朋友的邮箱，用他的邮箱來登录，那当你朋友用这个邮箱也来注册的时候就被你占用了。

**Comment by lisaRao** [comment]
恩，明白。
