### ISSUE TITLE
建议：添加可以显示隐藏编辑器行号的功能

### ISSUE THREAD

**Issue by QiuMP** [ghosert/cmd-editor#892]
vim模式下没有行号很不方便。。

**Comment by QiuMP** [comment]
同时可以让行号变化颜色，以知道自己修改了哪一行

**Comment by huangjj27** [comment]
顺便希望增加选择代码是否加入行号的功能

**Comment by ghosert** [comment]
https://www.zybuluo.com/ghosert/note/378553#6-可以折叠的编辑器行号
