### ISSUE TITLE
bug：PDF导出问题

### ISSUE THREAD

**Issue by meyergin** [ghosert/cmd-editor#897]
使用pdf导出功能后，流程图或公式的单行宽度过大时，直接截断了，部分内容就看不到了；另外流程图或时序图导出pdf后，打开报错-绘图失败，部分图无法完成加载

**Comment by ghosert** [comment]
流程图是比较复杂的渲染，失败和 PDF 软件有关，可以换一个就好了。

**Comment by ghosert** [comment]
这个已经修复了。
