### ISSUE TITLE
无法设置本页面的锚点

### ISSUE THREAD

**Issue by huangjj27** [ghosert/cmd-editor#898]
在当前页面某处设置了锚点跳转<a href="#subflow"> 和锚点<span name="subflow" />
然而每次点击跳转都新打开一个窗口而不是在本页面定位

**Comment by ghosert** [comment]
https://github.com/ghosert/cmd-editor/issues/356

**Comment by ghosert** [comment]
参考这个：https://github.com/ghosert/cmd-editor/issues/356
