### ISSUE TITLE
关于代码高亮功能的建议

### ISSUE THREAD

**Issue by coolbit-in** [ghosert/cmd-editor#9]
使用```标识的代码段，在复制的时候会把行号也拉进去，别人考代码的时候不是很方便，这一点Octopress做的很好，它又行号，但是复制的时候，行号部分不会被拉进去

**Comment by ghosert** [comment]
嗯，了解了，找时间改一改。

**Comment by ghosert** [comment]
我又看了看，Firefox Chrome 下面都没有这个问题，你用的是哪个浏览器，啥版本？操作系统报一下。

**Comment by coolbit-in** [comment]
抱歉啊，我昨天只是拉黑了一下。。看到行号被拉黑了，以为会被复制上。。额，以后会多加测试，再报告的。。不好意思(>_<)
在 2013-10-25 下午9:17，"Jay Zhang" notifications@github.com写道：

**Comment by ghosert** [comment]
没事，那暂时先关了。。。
