### ISSUE TITLE
微信付款了还不是会员

### ISSUE THREAD

**Issue by charpty** [ghosert/cmd-editor#901]
跳转支付宝付款的时候，要让我输入支付宝账号和密码，这我哪敢输入？
于是我使用了微信付款，付了款之后没反应啊

**Comment by ghosert** [comment]
加我下微信号 ghosert，用户名说下。

**Comment by ghosert** [comment]
跳转到支付宝付款的那个页面你看域名是支付宝的网站，支付实际是发生在支付宝那边，所以很安全，我们这里也没法记录你的支付宝帐号了。微信支付那边红字高亮写了支付以后加下 ghosert 这个微信号，会手动处理的。

**Comment by ghosert** [comment]
caibo2014 这个用户名已经开通高级会员了。可以回作业部落查看下，谢谢支持。

**Comment by charpty** [comment]
现在是的了，谢谢。

**Comment by ghosert** [comment]
zstu_cc 这个微博也是你吧？

**Comment by charpty** [comment]
嗯，是的，还发了一封邮件。

**Comment by ghosert** [comment]
那没事了。
