### ISSUE TITLE
bug: 当前页面锚点无法定位

### ISSUE THREAD

**Issue by huangjj27** [ghosert/cmd-editor#902]
文章地址: https://www.zybuluo.com/DingCao-HJJ/note/202158

跳转处方式为<a href="#subflow">连接</a> 或者[连接](#subflow)
锚点位置使用<div id="subflow" /> 或者<a id="subflow" /> 均无法跳转

点击后除了URL变了，没有其他变化。
怀疑是解析逻辑有误。

**Comment by DingCao** [comment]
将 <div id="subflow" />改成后 <div id="subflow"></div>问题得到解决，求解释原因。

**Comment by huangjj27** [comment]
将<div id="subflow" />修改成<div id="subflow"></div>可以跳转，求开发者检查。

**Comment by huangjj27** [comment]
此外，我想在流程图里面设立当前页面的跳转点 请问应该如何做到吗？

**Comment by ghosert** [comment]
对，已更正，确实需要写完整的标签。 

```
<div id="subflow"></div>
```

**Comment by ghosert** [comment]
<div id="subflow"></div>

**Comment by ghosert** [comment]
流程图里的链接都会打开一个新页面，目前不支持了。
