### ISSUE TITLE
能否支持剪贴板图片直接插入？

### ISSUE THREAD

**Issue by duangao** [ghosert/cmd-editor#904]
高级会员功能中目前可以拖拽或者选择本地图片进入，但日常使用中经常需要插入一些临时性的图片（截图或者网页上一些图片），先保存到本地再插入十分麻烦，不知可否增加直接从剪贴板插入图片？
感谢！

**Comment by ghosert** [comment]
https://www.zybuluo.com/ghosert/note/378553

**Comment by ghosert** [comment]
可以直接粘贴上传了。
