### ISSUE TITLE
表格如何合并单元格

### ISSUE THREAD

**Issue by linking123** [ghosert/cmd-editor#906]
| A | B | C |
| --- | --- | --- |
| 1 | 2 | 3 |
| 4 |  |  |

4怎么样独占一行呢？
求解

**Comment by ghosert** [comment]
可自行书写html table标签 发自网易邮箱大师 在2015年10月27日 20:51 ，金文林写道： A B C 1 2 3 4 4怎么样独占一行呢？ 求解 — Reply to this email directly or view it on GitHub.

**Comment by linking123** [comment]
嗯嗯。感谢回复。知道了

**Comment by zyl54586** [comment]
为什么我写了HTML不起作用呢？表格内容完全不显示，MACBOOK环境，Windows还没试过。

**Comment by ghosert** [comment]
https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#11-html-标签

参考一下这个，另外可以自行在网络上查询一下合并单元格的HTML语法。
