### ISSUE TITLE
为何不开放<ruby>标签呢？

### ISSUE THREAD

**Issue by satgo1546** [ghosert/cmd-editor#915]
``` html
<ruby>这<rt><rp>（</rp>zhè<rp>）</rp></rt></ruby><ruby>样<rt><rp>（</rp>yàng<rp>）</rp></rt></ruby>
和<ruby>这<rt>zhè</rt></ruby><ruby>样<rt>yàng</rt></ruby>
```

**Comment by ghosert** [comment]
不是标准html不开放了，安全考虑。 发自网易邮箱大师 在2015年11月02日 17:40 ，Satgo1546写道： <ruby>这<rt><rp>（</rp>zhè<rp>）</rp></rt></ruby><ruby>样<rt><rp>（</rp>yàng<rp>）</rp></rt></ruby>
和<ruby>这<rt>zhè</rt></ruby><ruby>样<rt>yàng</rt></ruby> — Reply to this email directly or view it on GitHub.
