### ISSUE TITLE
选中分词建议

### ISSUE THREAD

**Issue by lenville** [ghosert/cmd-editor#916]
Hi，@ghosert

我一直以来都有遇到一个问题
**中英文间无空格行文时**，双击英文会选中整句
浏览器自带的分词功能在其它网站的行为正常
我观察到Cmd现在支持同词提示，选中一个词会框选所有相同词
这是个非常棒的功能，只是不知这两个功能是否相关

期待更棒的Cmd

**Comment by ghosert** [comment]
噢，好像是的，但是案例可能比较少，一般都会加空格或者标点符号吧。^_^。

**Comment by lenville** [comment]
嗯嗯，以前我也加，但是目前合作的发布方都是不加空格的，所以有时很无奈。
http://blog.csdn.net/watkinsong/article/details/37696389
不知道这个会不会有些帮助哈 : )

**Comment by ghosert** [comment]
目前的算法应该也没那么复杂就是如果没有空格又有英文中文就算一个单词处理了。或许就不要双击了，直接划选下，另外可以用 ctrl + f 搜索英文关键字。
