### ISSUE TITLE
标签无法显示

### ISSUE THREAD

**Issue by cinla** [ghosert/cmd-editor#918]
![image](https://cloud.githubusercontent.com/assets/1662827/10904423/f18cd4fa-824d-11e5-9764-608ecd102fe7.png)

help文档中的标签显示不正确，实际操作发现根本无法正常显示，请查看是否是bug！

**Comment by ghosert** [comment]
首先这个 标签 或者 Tags 关键字要顶在行首写，其次，如果这个标签或者Tags 出现在多个地方，只按首次出现的位置来显示，我怀疑你在几个地方写了标签。

**Comment by cinla** [comment]
请问是一篇文章只能有一个标签吗？

在 2015-11-03 22:48:14，"Jay Zhang" notifications@github.com 写道：

首先这个 标签 或者 Tags 关键字要顶在行首写，其次，如果这个标签或者Tags 出现在多个地方，只按首次出现的位置来显示，我怀疑你在几个地方写了标签。

**Comment by ghosert** [comment]
可以有至多五个标签，但是标签所在的行只能有一行，有多个标签行除了第一行，其他标签行不会变成标签而是原样输出。
