### ISSUE TITLE
代码块的缩进问题

### ISSUE THREAD

**Issue by baronZhang** [ghosert/cmd-editor#92]
对于`代码块`，如何才能让它用类似:加4个空格的方式进行缩进。
我用了>，但行不通。

**Comment by ghosert** [comment]
能给个具体的例子吗？

目前类似代码块都要定格写，否则 Markdown 不知道这是一块代码。

```
def main():
    print 'hello word'
```

**Comment by baronZhang** [comment]
写文章的时候不都是有层次结构的吗？ 比如某小节的内容要相对章内容缩进4个空格，这时小节的内容中包含**代码块**，怎么让这个代码块**整体**缩进？

**Comment by ghosert** [comment]
这么说吧，其实西文里并没有缩进的说法，中文里才有，markdown 语法天然也没这么支持，代码块就更不行了，我倒觉得你不是用来做出版的话，可以暂时忍忍。

**Comment by baronZhang** [comment]
markdown语法是这样不错，西文没有缩进也不错，但中文有！不要说”才有“，因为本项目是markdown中文版的，所以符合中文排版，满足中文需求才是第一位的，希望不要本末倒置。
stackedit也是没有层次结构的，不管章内容还是小节内容，第1个字符都是在一个横坐标上，但我觉得你们可以做出来，至少每个段落开头缩进可以做出来。至于代码块的整体缩进，这也是可以考虑的，因为可以让整版的内容看上去层次分明，有条理。
功能暂时没有，这个没问题，但我希望你们在以后的版本中，可以加以考虑。

**Comment by ghosert** [comment]
你可以发个公开链接给我，看看这个问题多严重，尤其是代码块的缩进。目前这个项目并没有足够的人手和时间做所有的事情也没有收入。我的意思是这些问题可以在这里记录，但是并不能保证获得足够的资源去改，时间很宝贵，只能放在更重要的事情上，谅解一下。
2014-4-30 上午11:01于 "baronZhang" notifications@github.com写道：

**Comment by baronZhang** [comment]
[示例在这](https://www.zybuluo.com/7788999z/note/10006)。
首先，对于这个开源项目的工作人员付出的辛劳表示敬意！其次，这个问题倒不是多么严重，只是一个想让项目变得更加优秀的提议。

**Comment by ghosert** [comment]
我看了一下，即使在中文里，应该只说了段落的起始要空两格的位置，并没有要求段落一定要相对标题的位置做缩进，我觉得你可以改一下，这样的话，代码段落也没必要缩进了，这位网友的稿子你可以参考看看，牺牲一些小局部的执念，整体上看会更美观吧：[示例](https://www.zybuluo.com/amoszhou/note/10037)

**Comment by ghosert** [comment]
噢？咋么都关了？

**Comment by baronZhang** [comment]
问题都差不多了。
至于执念，我觉得留出让用户自己去选择如何处理的余地会更人性化一些。
整体来说， 作业部落还是不错的（不知道是否开源）。

**Comment by ghosert** [comment]
暂时没有开源，即便开源也需要花费时间整理代码，文档，易于安装的环境脚本，目前还是赶开发进度为主。

**Comment by baronZhang** [comment]
恩，了解了。 加油！
