### ISSUE TITLE
ubuntu14.04的系统，一点bug。

### ISSUE THREAD

**Issue by wenbobuaa** [ghosert/cmd-editor#925]
ubuntu14.04的系统，点击了发布之后弹出对话框跳转到网页。之后打开客户端便立即跳转到网页，只能强制关掉。
还不是高级会员。

**Comment by ghosert** [comment]
是的，下次发布的时候一起改掉 发自网易邮箱大师 在2015年11月10日 00:03 ，wenbo写道： ubuntu14.04的系统，点击了发布之后弹出对话框跳转到网页。之后打开客户端便立即跳转到网页，只能强制关掉。 还不是高级会员。 — Reply to this email directly or view it on GitHub.

**Comment by wenbobuaa** [comment]
时间太久了，没再关注了，先关了。
