### ISSUE TITLE
在VIM格式下按[ESC]并不能退回到norm模式？？

### ISSUE THREAD

**Issue by peachgo-** [ghosert/cmd-editor#929]
是我不会用吗？

**Comment by ghosert** [comment]
看看是不是用了其它浏览器的vi插件，禁用一下 发自网易邮箱大师 在2015年11月14日 06:48 ，peachgo-写道： 是我不会用吗？ — Reply to this email directly or view it on GitHub.

**Comment by peachgo-** [comment]
谢谢， 关了插件解决了。
