### ISSUE TITLE
关于加粗的一个bug

### ISSUE THREAD

**Issue by imbyron** [ghosert/cmd-editor#93]
如果冒号后有英文字母，加粗会失败，并显示为斜体
冒号后中文则正常。
例：
`**你好：**世界`，这样是正常的，会显示为：
**你好：**世界
`**你好：**world`，则会显示为：
`*斜体的你好：*world`

**Comment by ghosert** [comment]
目前已经修正为显示成：
`**你好：**world`
我看了一下主流做法都是这样做的，包括 github，最近会把这个更新推到网站上，到时在这里通知你。

**Comment by ghosert** [comment]
已经更新了。
