### ISSUE TITLE
在网页端使用的时候每变动一点就会弹出合并冲突的对话框

### ISSUE THREAD

**Issue by BrambleXu** [ghosert/cmd-editor#930]
没打几个字就弹出对话框，说和本地冲突了，之前没有这样的问题啊

**Comment by ghosert** [comment]
是因为网络不稳定造成的，看看有没有加代理？ 发自网易邮箱大师 在2015年11月14日 10:08 ，Bramble写道： 没打几个字就弹出对话框，说和本地冲突了，之前没有这样的问题啊 — Reply to this email directly or view it on GitHub.
