### ISSUE TITLE
Is there an auto-generated content?

### ISSUE THREAD

**Issue by voyager0003** [ghosert/cmd-editor#936]
I saw that markdown support an auto-generated content in other place, like this:
- This will become a table of contents (this text will be scraped).
  {:toc}

However, in cmd markdown, it doesn't work at all.

**Comment by ghosert** [comment]
check this: https://www.zybuluo.com/mdeditor?url=https%3A%2F%2Fwww.zybuluo.com%2Fstatic%2Feditor%2Fmd-help.markdown#1-内容目录
