### ISSUE TITLE
字体可不可以调小一点

### ISSUE THREAD

**Issue by jarvys** [ghosert/cmd-editor#94]
RT

**Comment by ghosert** [comment]
正文字体是 16px, 最大的标题是 30px 你觉得哪里的字体太大？正文还是标题，还是都大？

**Comment by jarvys** [comment]
正文字体14号字要好一些吧，现在很多网站正文字大小都是14号字，16号有点大

**Comment by ghosert** [comment]
大一点的字号比较容易读，出于保护用户的视力目的，强制十六号。

**Comment by jarvys** [comment]
可以设置一个选项来调整字体大小吗？

**Comment by ghosert** [comment]
实在需要可以ctrl + - 缩小网页字体
2014-5-5 下午1:12于 "Jarvis Young" notifications@github.com写道：
