### ISSUE TITLE
希望可以将斜体字的默认间距调整下

### ISSUE THREAD

**Issue by linkin1005** [ghosert/cmd-editor#943]
希望可以将斜体字的默认间距调整下，如下图：
![qq 20151123141928](https://cloud.githubusercontent.com/assets/8130943/11330850/41f5b2b4-91ed-11e5-82fe-d6dc03ff3b00.jpg)

**Comment by ghosert** [comment]
字体字号CSS样式都可以改了：https://www.zybuluo.com/ghosert/note/378553
