### ISSUE TITLE
经常性发布更新卡住

### ISSUE THREAD

**Issue by ilovintit** [ghosert/cmd-editor#955]
经常性发布更新卡住，而且很慢。

**Comment by ghosert** [comment]
注意网速。应该挺快的，不要有代理，人是不是在国外？ 发自网易邮箱大师 在2015年11月26日 17:36 ，古俊杰写道： 经常性发布更新卡住，而且很慢。 — Reply to this email directly or view it on GitHub.

**Comment by ilovintit** [comment]
百兆电信光纤，无人上传，无用代理。

**Comment by ghosert** [comment]
浏览器是 chrome 吗？ 发自网易邮箱大师

**Comment by ilovintit** [comment]
chrome浏览器和windows客户端都是，不是一直会这样子，是偶尔抽风，一抽风就好久不行。

**Comment by ilovintit** [comment]
会不会是我的文章比较长的原因，就算正常的时候发布都要几秒钟（两秒以上）。

**Comment by ghosert** [comment]
比较长的文章是会，图片公式多不多。 发自网易邮箱大师 在2015年11月27日 15:57 ，古俊杰写道： 会不会是我的文章比较长的原因，就算正常的时候发布都要几秒钟（两秒以上）。 — Reply to this email directly or view it on GitHub.
