### ISSUE TITLE
流程图在web阅读模式下溢出，导出PDF也会报drawing error，无法正常显示

### ISSUE THREAD

**Issue by unsleepy22** [ghosert/cmd-editor#957]
![image](https://cloud.githubusercontent.com/assets/631361/11426579/13a53508-9498-11e5-9c6a-089023ddc2d0.png)
流程图溢出

![image](https://cloud.githubusercontent.com/assets/631361/11426565/fe7f5eba-9497-11e5-832f-b075d65c9ed8.png)
表格也有一点点溢出的情况

**Comment by unsleepy22** [comment]
chrome 46.0, mac os x10.10.3, 15寸RMBP， 2880*1800

**Comment by ghosert** [comment]
测试环境已经修好了，下周二发。 发自网易邮箱大师 在2015年11月26日 21:20 ，unsleepy22写道： — Reply to this email directly or view it on GitHub.

**Comment by unsleepy22** [comment]
这个问题还是没有修复啊，已经是下下周二了啊

**Comment by ghosert** [comment]
pdf 好了呀。 发自网易邮箱大师 在2015年12月08日 12:41 ，Cody写道： 这个问题还是没有修复啊，已经是下下周二了啊 — Reply to this email directly or view it on GitHub.

**Comment by unsleepy22** [comment]
好吧，没有看pdf的，网页的还是溢出的。。。

**Comment by ghosert** [comment]
我修。。。。 发自网易邮箱大师

**Comment by ghosert** [comment]
单击流程图已经可以放大了，显示溢出部分。
