### ISSUE TITLE
为什么用户信息界面那么简单，连个头像都没有，too low, too ugly!

### ISSUE THREAD

**Issue by xgqfrms** [ghosert/cmd-editor#959]

**Comment by xgqfrms** [comment]
https://www.zybuluo.com/xgqfrms/note/229002

**Comment by hsshenxi** [comment]
Google 刚出时候也就一简单的logo加输入框。
@xgqfrms toolow! 如果你能做得更好，你可以任性说too low，否则，请闭嘴！
