### ISSUE TITLE
序号与代码块的混排问题

### ISSUE THREAD

**Issue by oopp1800** [ghosert/cmd-editor#965]
![image](https://cloud.githubusercontent.com/assets/12545349/11490903/04212e06-9818-11e5-8cd2-96d9d2fb8436.png)
具体在图里说明了，第一点不是很重要，但是第二点
好像使用这种形式的话一定会打破序号排列（包括无序列表或者引用里面，想使用这种代码块的方法的话好像都会出现格式的问题）？做笔记的时候还是有些不方便的，希望有好的解决办法~

**Comment by ghosert** [comment]
MARKDOWN 原生规范里 有序列表只是简单的列表项不支持复杂渲染。可以用 #### 1. xxxx #### 2. yyyy #### 3. zzzz

**Comment by HIKALU-Z** [comment]
原来这个问题是这样的啊，不过解决办法倒是一样的哈哈
