### ISSUE TITLE
markdown有个BUG，在编辑代码的地方输入#号会导致出现<div class="md-section-divider"></div> 这个标签

### ISSUE THREAD

**Issue by yekeqiang** [ghosert/cmd-editor#97]
markdown有个BUG，在编辑代码的地方输入#号，导致在预览的那边会出现<div class="md-section-divider"></div> 这个标签，这个对预览阅读有干扰，

**Comment by ghosert** [comment]
等一下。。。你是在预览区看到的，还是在源码里看到的？理论上不会在正常预览的时候看到

**Comment by ghosert** [comment]
微博私信上的截图已经收到，找时间本地重现一下。

**Comment by ghosert** [comment]
我试了一下自己的文稿，如果 

``` 一些测试文字 ``` 

没有分成几行而是写在一行就会出现这种问题，请检查一下自己的文档内容。看看又没有这种情况。应该写成这样：

```
一些测试文字
```

**Comment by parabolazz** [comment]
你好，我在使用

```
code
```

的时候也出现了这种问题，用tab缩进四格的方式就不会了，请问这是什么原因？

**Comment by ghosert** [comment]
markdown 原文发我看看，我给你改下 ghosert@gmail.com
