### ISSUE TITLE
[bug]无法上传本地图片

### ISSUE THREAD

**Issue by tq5124** [ghosert/cmd-editor#979]
今天更新了新版，但是上传图片后，进度条100%，对话框消失了，但是光标处没有出现以前有的图片url

平台：Mac osx
版本：v2.0

**Comment by BrambleXu** [comment]
我也出现了这样的问题，上传成功，但是图片的url并没有出现

Linux 网页版

**Comment by lovemiffy** [comment]
我今天上午刚刚更新，客户端和网页版均出现了此问题，上传本地图片不能显示，并且文档编辑视图的末尾也看不到图片链接

平台：Windows 10 64bit

**Comment by ghosert** [comment]
好，我看看！

**Comment by ghosert** [comment]
图片其实传上去了，好像是贴进编辑器有问题，我再看看。

**Comment by ghosert** [comment]
已修复。
