### ISSUE TITLE
导出/同步到印象笔记 出错

### ISSUE THREAD

**Issue by BrambleXu** [ghosert/cmd-editor#983]
一个笔记的错误信息是：

导出当前文稿出错，请重试或联系我们，错误详情：Element or attribute do not match QName production: QName::=(NCName':')?NCName.

另一个笔记的错误信息是：

导出当前文稿出错，请重试或联系我们，错误详情：fail to convert

**Comment by ghosert** [comment]
把Markdown 原文发到我信箱 ghosert@gmail.com 两个都要。

**Comment by BrambleXu** [comment]
发过去了

**Comment by ghosert** [comment]
收到了，我看下。

**Comment by ghosert** [comment]
![screenshot from 2015-12-07 20 04 31](https://cloud.githubusercontent.com/assets/236040/11626452/f1ff6c5a-9d1d-11e5-90d8-ef4f91937abf.png)

**Comment by ghosert** [comment]
这一篇是好的。另一篇是有问题，在看了。

**Comment by ghosert** [comment]
另一篇六万三千字，超过系统负载了，最好分成几份，每份两万字以内再导出。另外原文里有个乱码：

if 'http://udacity.com/cs101x/urank/index.html' in graph:
    print graph['http://udacity.com/cs101x/urank/index.html']
#>>> ['http://udacity.com/cs101x/urank/hummus.html',
#'http://udacity.com/cs101x/urank/arsenic.html',
#'http://udacity.com/cs101x/urank/kathleen.html',
#'http://udacity.com/cs101x/urank/nickel.html',
#'http://udacity.com/cs101x/urank/zinc.html']

这个片段的第二行 print g 之后有个特殊字符，删掉它。

**Comment by BrambleXu** [comment]
好的，我重新试试。Thanks
