### ISSUE TITLE
书写的时候经常出现莫名其妙的同步冲突

### ISSUE THREAD

**Issue by JoeFirmament** [ghosert/cmd-editor#985]
书写经常出现冲突。 是否改成keyboard event 一段时间空闲才提交同步。

**Comment by ghosert** [comment]
主要是因为网络不稳定，可以看看有没有代理，人是不是在国外，公司或者学校的网络环境是不是好。因为现在支持离线文稿，可以新建这种离线文稿，这样就完全在本地编辑，就不会有这种问题，最后再一次性贴到在线文稿里即可。虽然不是很方便但是为了应对网络环境的问题，也算一种方法。
