### ISSUE TITLE
[Bug] 编辑时卡顿

### ISSUE THREAD

**Issue by wafer-li** [ghosert/cmd-editor#986]
Win 10 x64 Pro.
Edition: 2015 / 12 / 06

编辑时卡顿，普通模式和 vim 模式都有此现象。 
Math Render 选择的是 HTML/CSS，字数为 31848
内存占用大概在 200 M 左右，本机内存绝对充足。

不过在20分钟内生成了 16 个历史版本，是否与此有关？

**Comment by ghosert** [comment]
浏览器是哪个？建议chrome 发自网易邮箱大师在2015年12月08日 14:05 ，Donglin Li写道：

**Comment by wafer-li** [comment]
:joy: 我用的客户端……不是浏览器的。。。。。

**Comment by ghosert** [comment]
网络状况如何？有无代理，是不是公司或者学校的内网？三万字确实很多，但是理论上只对你正在编辑的区域做渲染所以不会卡顿。试试 CHROME 浏览器是不是也有这个情况先吧。

**Comment by wafer-li** [comment]
:joy:  嗯……卡顿状况有所缓解，只有在长按退格键的时候才会出现卡顿情况。

**Comment by ghosert** [comment]
建议把这么大的文稿拆一下，放在一个标签底下。先关了哈。。。

**Comment by wafer-li** [comment]
嗯……估计是偶然情况，长按键的卡顿是可以理解的。先就这样吧。
