### ISSUE TITLE
关于离线文稿和图片上传的几点提议

### ISSUE THREAD

**Issue by oopp1800** [ghosert/cmd-editor#987]
之前邮件作者了~回复说发 github 上会尽量解决~嗯，这就发过来了
1. 不知道离线文稿具体存储在哪？重装软件/系统等会不会误删除...
   
   > 作者回复：存在浏览器的indexeddb里，重装系统肯定会丢，但是可以一键导出备份。
   > 
   > > 我：我是用离线客户端的，更希望能直接存储在客户端的目录下，不知道可否..希望作者能给出更好些的方案呢，毕竟如果使用离线文稿的话更多还是重要性较高的文件~
2. 离线文稿上传图片好像还是传至服务器，不知能否使用本地文件
   
   > 作者回复：图片存服务器倒也没什么。。。
   > 
   > > 我：噗...
3. 本地文件上传希望能直接拖拽上传，而不是拖拽后打开上传页面再拖拽一次
4. 希望增加剪贴板里的图像粘贴直接上传并生成 markdown 语句的功能（离线文稿则是生成本地文件后生成 markdown 语句）
   
   > 作者可是在第十二次更新的批注中有回复别人的哟，特此记录→ →
   > [戳这里戳这里](https://www.zybuluo.com/ghosert/note/102771#b8b6-ffymc1co32l9)

**Comment by ghosert** [comment]
离线文稿可以直接读写在本地文件了，拖拽文件也可以直接上传了，复制粘贴剪贴板也行了：https://www.zybuluo.com/ghosert/note/378553
