### ISSUE TITLE
文档导出PDF, 序列图的 箭头 没有了

### ISSUE THREAD

**Issue by sunvim** [ghosert/cmd-editor#988]
如题所述，而且文档清晰度下降很多, 模糊的很，请改进！

**Comment by ghosert** [comment]
你是哪个操作系统？ markdown 原文发我邮箱。放大会失真， 100% 就没问题，我还是会看下。

**Comment by sunvim** [comment]
centos 7 x64

**Comment by ghosert** [comment]
已回复你的邮件，貌似没有箭头丢失啊？

**Comment by ghosert** [comment]
又看了一下，清晰度的问题已经提升了一倍所以应该没问题了。箭头丢失应该是FIREFOX独有的问题，请在导出 PDF 的时候，暂时使用CHROME或者客户端就不会有这个问题了。
