### ISSUE TITLE
弱弱地问句，源代码在哪里

### ISSUE THREAD

**Issue by p2227** [ghosert/cmd-editor#99]
没有源代码的github？

**Comment by ghosert** [comment]
非开源项目，哈哈
2014-5-4 下午9:13于 "kuang" notifications@github.com写道：

**Comment by p2227** [comment]
神速。。。。源代码那一块可以增加拷贝及针对HTML的运行功能吗？http://www.blueidea.com/tech/web/2007/4563.asp
像这样的

**Comment by ghosert** [comment]
我考虑一下答复你
2014-5-4 下午9:27于 "kuang" notifications@github.com写道：

**Comment by junyiliu** [comment]
1.有没有F#代码块高量支持？
2.我写过的文章都到哪里去了，不知道怎么找出来？

**Comment by ghosert** [comment]
登录以后点工具栏右上角的列表按钮。
2014-5-5 下午8:00于 "junyiliu" notifications@github.com写道：

**Comment by ghosert** [comment]
本作暂时不提供题主所述之功能。
