### ISSUE TITLE
建议:图片问题

### ISSUE THREAD

**Issue by zengzheng138** [ghosert/cmd-editor#991]
1. 建议支持剪切板图片直接粘贴
2. 建议可创建模板(每次画表格,流程图好累)
   3.当内容中插入大图片,左右两栏的位置就无法一致了,会导致右栏的预览看不到
   4.markdown语法建议高亮

**Comment by ghosert** [comment]
已经可以直接粘贴剪贴板图片了，大图片没办法。模板可以考虑。
