### ISSUE TITLE
"$$ $$"公式符号在github上没有正确显示啊

### ISSUE THREAD

**Issue by Silocean** [ghosert/cmd-editor#993]
比如我在md文件中输入这个公式$$x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$$，cmdmarkdown中可以正确显示，readme.md里却没有正确显示，这个是什么问题，是与github提供的md格式不符吗？

**Comment by ghosert** [comment]
是我们支持了，GITHUB没支持。应该请GITHUB支持一下。
