### ISSUE TITLE
[Bug]同步印象笔记错误

### ISSUE THREAD

**Issue by qianlei90** [ghosert/cmd-editor#994]
重现步骤:
1. 新建网页版文稿,导出到印象笔记的Cmd Markdown笔记本下.
2. 移动笔记到其他笔记本
3. 点击笔记标题,重新返回网页版,修改笔记
4. 再次导出到印象笔记,提示"导出当前文稿出错，请重试或联系我们，错误详情：authenticationToken"

**Comment by ghosert** [comment]
印象笔记给CMD MARKDOWN 的权限不够，正在索取。

**Comment by ghosert** [comment]
已解决，对方已给了足够的权限，请先前往这里把印象笔记对 Cmd Markdown 的授权撤销，然后回到 Cmd Markdown 重新导出到印象笔记，这个时候会重新让你授权 Cmd Markdown 访问 印象笔记，此后就不再有此限制了。
