### ISSUE TITLE
【建议】本地客户端支持打开本地markdown文件

### ISSUE THREAD

**Issue by kingname** [ghosert/cmd-editor#995]
希望电脑客户端支持打开本地markdown文件，希望电脑客户端不要只是一个包含网页端的壳。

如果电脑端能打开本地markdown，我就买会员。

**Comment by ghosert** [comment]
客户端下次就支持。这个也不完全是壳。

**Comment by ghosert** [comment]
高级会员可以新建打开离线文稿了，支持读写本地文件：https://www.zybuluo.com/ghosert/note/378553
