### ISSUE TITLE
邮箱验证长时间链接没点失效，账号无法使用

### ISSUE THREAD

**Issue by nickfan** [ghosert/cmd-editor#996]
登录界面上没有重发验证邮件的链接
同事注册了邮箱，验证邮件忘了点，过了几天再登录系统，提示验证邮件已于xx时间发送，
查邮件，点链接提示验证成功。
退出应用，重新打开登录-提示邮件未验证过，账号无法登录。
这账号重置密码后还是无法登录-提示邮件未验证过，账号无法登录。

**Comment by ghosert** [comment]
因为过期了，请前往 用户设置 页面重新发验证邮件。

**Comment by nickfan** [comment]
账号都无法登录！！，怎么进【用户设置】？你们未登录的界面上哪边有【用户设置】的链接？

**Comment by ghosert** [comment]
用用户名登录，非邮箱。 发自网易邮箱大师 在2015年12月14日 10:26 ，nick写道： 账号都无法登录！！，怎么进【用户设置】？你们未登录的界面上哪边有【用户设置】的链接？ — Reply to this email directly or view it on GitHub.
