### ISSUE TITLE
【导出到印象笔记】移动导出的文件到印象笔记的其他笔记本目录，同步时报 authenticationToken 错误

### ISSUE THREAD

**Issue by nibocn** [ghosert/cmd-editor#998]
如果重新移动到cmd markdown自动创建的 Cmd Markdown 笔记本目录，再同步又能成功。

![image](https://cloud.githubusercontent.com/assets/10879287/11704976/4d5958ee-9f27-11e5-8a92-cf9f279ecb8c.png)

**Comment by ghosert** [comment]
印象笔记那边给这边访问笔记本的权限较小，多谢提醒，会去沟通下。

**Comment by ghosert** [comment]
已解决，对方已给了足够的权限，请先前往这里把印象笔记对 Cmd Markdown 的授权撤销，然后回到 Cmd Markdown 重新导出到印象笔记，这个时候会重新让你授权 Cmd Markdown 访问 印象笔记，此后就不再有此限制了。
