### ISSUE TITLE
【导出到印象笔记】同步到印象笔记的部分格式渲染效果不是很好，如：todo list

### ISSUE THREAD

**Issue by nibocn** [ghosert/cmd-editor#999]
cmd markdown渲染效果：

![image](https://cloud.githubusercontent.com/assets/10879287/11705089/4194fb48-9f28-11e5-84a6-b9832a1f9032.png)

印象笔记显示效果：

![image](https://cloud.githubusercontent.com/assets/10879287/11705099/571725c2-9f28-11e5-9c64-a649df6c7d34.png)

自己调整了下cmd里面markdown格式：

![image](https://cloud.githubusercontent.com/assets/10879287/11705128/a2e2b0ca-9f28-11e5-9f96-7b4eaf328b00.png)

印象笔记显示时能换行了，只是效果还是不太理想：

![image](https://cloud.githubusercontent.com/assets/10879287/11705139/bad93c44-9f28-11e5-9c38-e620f104b97f.png)

**Comment by ghosert** [comment]
我的样稿里没有这个问题啊？
https://www.evernote.com/shard/s229/sh/30372a7b-1d50-4b17-a4e5-3c92c19ce20f/230885fb8fdb70794ed19f8332f8a306
你是用CHROME浏览器或者我们的客户端吗？

**Comment by nibocn** [comment]
我是用的印象笔记的客户端，不是evernote国际版。在印象笔记的web版本用chrome打开的效果是这样的:
![image](https://cloud.githubusercontent.com/assets/10879287/11707833/ec561f1a-9f43-11e5-83f1-ddd3cb3e1c93.png)

**Comment by ghosert** [comment]
印象笔记里我也是有这个效果的，你MARKDOWN原文我看下?

**Comment by ghosert** [comment]
发我信箱 ghosert@gmail.com
